import json
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    data_file = os.path.join(project_root, 'jlpt-web', 'src', 'data', 'vocab.json')

    if not os.path.exists(data_file):
        return

    with open(data_file, 'r', encoding='utf-8') as f:
        vocab = json.load(f)

    enrichment = {
        "N5_402": {"example_sentence": "百円ショップで買いました。", "example_reading": "ひゃくえんショップでかいました。", "example_meaning_cn": "在百元店买的。", "example_meaning_en": "I bought it at a 100-yen shop."},
        "N5_403": {"example_sentence": "病院へ行きます。", "example_reading": "びょういんへいきます。", "example_meaning_cn": "去医院。", "example_meaning_en": "I'm going to the hospital."},
        "N5_404": {"example_sentence": "病気になりました。", "example_reading": "びょうきになりました。", "example_meaning_cn": "生病了。", "example_meaning_en": "I became ill."},
        "N5_405": {"example_sentence": "平仮名を覚えます。", "example_reading": "ひらがなをおぼえます。", "example_meaning_cn": "记平假名。", "example_meaning_en": "I'll memorize Hiragana."},
        "N5_406": {"example_sentence": "昼休みにお弁当を食べます。", "example_reading": "ひるやすみにおべんとうをたべます。", "example_meaning_cn": "午休时吃便当。", "example_meaning_en": "I eat lunch during the lunch break."},
        "N5_407": {"example_sentence": "昼ご飯を食べましょう。", "example_reading": "ひるごはんをたべましょう。", "example_meaning_cn": "吃午饭吧。", "example_meaning_en": "Let's eat lunch."},
        "N5_408": {"example_sentence": "この部屋は広いです。", "example_reading": "このへやはひろいです。", "example_meaning_cn": "这个房间很宽敞。", "example_meaning_en": "This room is spacious."},
        "N5_409": {"example_sentence": "封筒に住所を書きます。", "example_reading": "ふうとうにじゅうしょをかきます。", "example_meaning_cn": "在信封上写地址。", "example_meaning_en": "Write the address on the envelope."},
        "N5_410": {"example_sentence": "プールで泳ぎたいです。", "example_reading": "プールでおよぎたいです。", "example_meaning_cn": "想在泳池游泳。", "example_meaning_en": "I want to swim in the pool."},
        "N5_411": {"example_sentence": "フォークを用意してください。", "example_reading": "フォークをよういしてください。", "example_meaning_cn": "请准备叉子。", "example_meaning_en": "Please prepare a fork."},
        "N5_412": {"example_sentence": "吹いていますね。 ", "example_reading": "ふいていますね。", "example_meaning_cn": "在吹（风）呢。", "example_meaning_en": "It's blowing, isn't it?"},
        "N5_413": {"example_sentence": "服を脱ぎます。", "example_reading": "ふくをぬぎます。", "example_meaning_cn": "脱衣服。", "example_meaning_en": "I'll take off my clothes."},
        "N5_414": {"example_sentence": "二日に一回運動します。", "example_reading": "ふつかにいっかいうんどうします。", "example_meaning_cn": "两天运动一次。", "example_meaning_en": "I exercise once every two days."},
        "N5_415": {"example_sentence": "太いですね。 ", "example_reading": "ふといですね。", "example_meaning_cn": "挺粗（胖）的呢。", "example_meaning_en": "It's thick/fat, isn't it?"},
        "N5_416": {"example_sentence": "冬は雪が降ります。", "example_reading": "ふゆはゆきがふります。", "example_meaning_cn": "冬天会下雪。", "example_meaning_en": "It snows in winter."},
        "N5_417": {"example_sentence": "プレゼントをもらいました。", "example_reading": "プレゼントをもらいました。", "example_meaning_cn": "收到了礼物。", "example_meaning_en": "I received a present."},
        "N5_418": {"example_sentence": "お風呂は気持ちいいです。", "example_reading": "おふろはきもちいいです。", "example_meaning_cn": "泡澡很舒服。", "example_meaning_en": "Taking a bath feels good."},
        "N5_419": {"example_sentence": "文章を読んでください。", "example_reading": "ぶんしょうをよんでください。", "example_meaning_cn": "请读文章。", "example_meaning_en": "Please read the text."},
        "N5_420": {"example_sentence": "ページをめくってください。", "example_reading": "ページをめくってください。", "example_meaning_cn": "请翻页。", "example_meaning_en": "Please turn the page."},
        "N5_421": {"example_sentence": "下手でも大丈夫です。", "example_reading": "へたでもだいじょうぶですよ。", "example_meaning_cn": "即使不擅长也没关系。", "example_meaning_en": "It's okay even if you are not good at it."},
        "N5_422": {"example_sentence": "ベッドで寝ます。", "example_reading": "ベッドでねます。", "example_meaning_cn": "在床上睡觉。", "example_meaning_en": "I sleep in a bed."},
        "N5_423": {"example_sentence": "ペットを飼っています。", "example_reading": "ペットをかっています。", "example_meaning_cn": "养着宠物。", "example_meaning_en": "I have a pet."},
        "N5_424": {"example_sentence": "部屋を片付けてください。", "example_reading": "へやをかたづけてください。", "example_meaning_cn": "请收拾房间。", "example_meaning_en": "Please tidy up the room."},
        "N5_425": {"example_sentence": "ペンを貸してください。", "example_reading": "ペンをかしてください。", "example_meaning_cn": "请借我笔。", "example_meaning_en": "Please lend me a pen."},
        "N5_426": {"example_sentence": "勉強は楽しいです。", "example_reading": "べんきょうはたのしいです。", "example_meaning_cn": "学习很有趣。", "example_meaning_en": "Studying is fun."},
        "N5_427": {"example_sentence": "便利ですね。 ", "example_reading": "べんりですね。", "example_meaning_cn": "很方便呢。", "example_meaning_en": "It's convenient, isn't it?"},
        "N5_428": {"example_sentence": "帽子を買いましょう。", "example_reading": "ぼうしをかいましょう。", "example_meaning_cn": "买帽子吧。", "example_meaning_en": "Let's buy a hat."},
        "N5_429": {"example_sentence": "ボールを投げます。", "example_reading": "ボールをなげます。", "example_meaning_cn": "扔球。", "example_meaning_en": "Throw a ball."},
        "N5_430": {"example_sentence": "ほかには何かありますか。", "example_reading": "ほかにはなにかありますか。", "example_meaning_cn": "还有别的吗？", "example_meaning_en": "Is there anything else?"},
        "N5_431": {"example_sentence": "ポケットにお金を入れます。", "example_reading": "ポケットにおかねをいれます。", "example_meaning_cn": "把钱放进口袋。", "example_meaning_en": "Put money in the pocket."},
        "N5_432": {"example_sentence": "欲しいものがあります。", "example_reading": "ほしいものがあります。", "example_meaning_cn": "有想要的东西。", "example_meaning_en": "I have something I want."},
        "N5_433": {"example_sentence": "細いですね。 ", "example_reading": "ほそいですね。", "example_meaning_cn": "挺细（瘦）的呢。", "example_meaning_en": "It's thin/slender, isn't it?"},
        "N5_434": {"example_sentence": "ボタンを押してください。", "example_reading": "ボタンをおしてください。", "example_meaning_cn": "请按按钮。", "example_meaning_en": "Please press the button."},
        "N5_435": {"example_sentence": "ホテルに泊まります。", "example_reading": "ホテルにとまります。", "example_meaning_cn": "住在饭店。", "example_meaning_en": "I'll stay at a hotel."},
        "N5_436": {"example_sentence": "本を読んでいます。", "example_reading": "ほんをよんでいます。", "example_meaning_cn": "正在看书。", "example_meaning_en": "I'm reading a book."},
        "N5_437": {"example_sentence": "棚に本棚があります。", "example_reading": "たなにほんだながあります。", "example_meaning_cn": "架子上有书架（或书架在架子上）。", "example_meaning_en": "There is a bookshelf in the rack."},
        "N5_438": {"example_sentence": "本当にいいですか。", "example_reading": "ほんとうにいいですか。", "example_meaning_cn": "真的可以吗？", "example_meaning_en": "Is it really okay?"},
        "N5_439": {"example_sentence": "毎朝、ジョギングをします。", "example_reading": "まいあさ、ジョギングをします。", "example_meaning_cn": "每天早晨慢跑。", "example_meaning_en": "I go jogging every morning."},
        "N5_440": {"example_sentence": "毎月、貯金しています。", "example_reading": "まいつき、ちょきんしています。", "example_meaning_cn": "每月都在存钱。", "example_meaning_en": "I save money every month."},
        "N5_441": {"example_sentence": "毎週、テニスをします。", "example_reading": "まいしゅう、テニスをします。", "example_meaning_cn": "每周都打网球。", "example_meaning_en": "I play tennis every week."},
        "N5_442": {"example_sentence": "毎日、日記を書きます。", "example_reading": "まいにち、にっきをかきます。", "example_meaning_cn": "每天写日记。", "example_meaning_en": "I write a diary every day."},
        "N5_443": {"example_sentence": "毎年、旅行へ行きます。", "example_reading": "まいとし、りょこうへいきます。", "example_meaning_cn": "每年去旅行。", "example_meaning_en": "I go on a trip every year."},
        "N5_444": {"example_sentence": "晩ご飯は何を食べますか。", "example_reading": "ばんごはんをなにをたべますか。", "example_meaning_cn": "晚饭吃什么？", "example_meaning_en": "What will you eat for dinner?"},
        "N5_445": {"example_sentence": "窓を閉めてください。", "example_reading": "まどをしめてください。", "example_meaning_cn": "请关窗户。", "example_meaning_en": "Please close the window."},
        "N5_446": {"example_sentence": "まっすぐ行ってください。", "example_reading": "まっすぐいってください。", "example_meaning_cn": "请直走。", "example_meaning_en": "Please go straight."},
        "N5_447": {"example_sentence": "マッチで火をつけます。", "example_reading": "マッチでひをつけます。", "example_meaning_cn": "用火柴点火。", "example_meaning_en": "Light a fire with a match."},
        "N5_448": {"example_sentence": "角を右に曲がります。", "example_reading": "かどをみぎにまがります。", "example_meaning_cn": "在拐角向右拐。", "example_meaning_en": "Turn right at the corner."},
        "N5_449": {"example_sentence": "また明日会いましょう。", "example_reading": "またあしたあいましょう。", "example_meaning_cn": "明天再见吧。", "example_meaning_en": "Let's meet again tomorrow."},
        "N5_450": {"example_sentence": "まだ食べていません。", "example_reading": "まだたべていません。", "example_meaning_cn": "还没吃。", "example_meaning_en": "I haven't eaten yet."},
        "N5_451": {"example_sentence": "町へ買い物に行きます。", "example_reading": "まちへかいものにいきます。", "example_meaning_cn": "去镇上买东西。", "example_meaning_en": "I'm going to town for shopping."},
        "N5_452": {"example_sentence": "友達を待ちます。", "example_reading": "ともだちをまちます。", "example_meaning_cn": "等朋友。", "example_meaning_en": "I'll wait for a friend."},
        "N5_453": {"example_sentence": "窓を開けてください。", "example_reading": "まどをあけてください。", "example_meaning_cn": "请开窗。", "example_meaning_en": "Please open the window."},
        "N5_454": {"example_sentence": "りんごを回してください。", "example_reading": "りんごをまわしてください。", "example_meaning_cn": "请把苹果传过来。 ", "example_meaning_en": "Please pass the apple."},
        "N5_455": {"example_sentence": "万単位で数えます。", "example_reading": "まんたんいでかぞえます。", "example_meaning_cn": "以万为单位计数。", "example_meaning_en": "Count in units of ten thousand."},
        "N5_456": {"example_sentence": "万年筆で書きます。", "example_reading": "まんねんひつでかきます。", "example_meaning_cn": "用钢笔写。", "example_meaning_en": "I'll write with a fountain pen."},
        "N5_457": {"example_sentence": "磨いてください。 ", "example_reading": "みがいてください。", "example_meaning_cn": "请磨（刷）。", "example_meaning_en": "Please polish/brush."},
        "N5_458": {"example_sentence": "右を見てください。", "example_reading": "みぎをみてください。", "example_meaning_cn": "请看右边。", "example_meaning_en": "Please look to the right."},
        "N5_459": {"example_sentence": "短いですね。 ", "example_reading": "みじかいですね。", "example_meaning_cn": "挺短的呢。", "example_meaning_en": "It's short, isn't it?"},
        "N5_460": {"example_sentence": "水が飲みたいです。", "example_reading": "みずがのみたいです。", "example_meaning_cn": "想喝水。", "example_meaning_en": "I want to drink water."},
        "N5_461": {"example_sentence": "店に行きましょう。", "example_reading": "みせにいきましょう。", "example_meaning_cn": "去店里吧。", "example_meaning_en": "Let's go to the store."},
        "N5_462": {"example_sentence": "見せてください。", "example_reading": "みせてください。", "example_meaning_cn": "请给我看看。", "example_meaning_en": "Please show me."},
        "N5_463": {"example_sentence": "道を聞きましょう。", "example_reading": "みちをききましょう。", "example_meaning_cn": "问路吧。", "example_meaning_en": "Let's ask for directions."},
        "N5_464": {"example_sentence": "三日間休みます。", "example_reading": "みっかかんやすみます。", "example_meaning_cn": "休息三天。", "example_meaning_en": "I'll take a three-day break."},
        "N5_465": {"example_sentence": "三つ買いました。", "example_reading": "みっつかいました。", "example_meaning_cn": "买了三个。", "example_meaning_en": "I bought three pieces."},
        "N5_466": {"example_sentence": "緑色が一番好きです。", "example_reading": "みどりいろがいちばんすきです。", "example_meaning_cn": "最喜欢绿色。", "example_meaning_en": "I like green the most."},
        "N5_467": {"example_sentence": "皆さん、聞いてください。", "example_reading": "みなさん、きいてください。", "example_meaning_cn": "大家，请听我说。", "example_meaning_en": "Everyone, please listen."},
        "N5_468": {"example_sentence": "南の方角はあちらです。", "example_reading": "みなみのほうがくはあちらです。", "example_meaning_cn": "南方在那边。", "example_meaning_en": "The south is that way."},
        "N5_469": {"example_sentence": "耳が痛いです。", "example_reading": "みみがいたいです。", "example_meaning_cn": "耳朵疼。", "example_meaning_en": "My ear hurts."},
        "N5_470": {"example_sentence": "映画を見ます。", "example_reading": "えいがをみます。", "example_meaning_cn": "看电影。", "example_meaning_en": "I watch a movie."},
        "N5_471": {"example_sentence": "みんなで歌いましょう。", "example_reading": "みんなでうたいましょう。", "example_meaning_cn": "大家一起唱吧。", "example_meaning_en": "Let's all sing together."},
        "N5_472": {"example_sentence": "六日に行きます。", "example_reading": "むいかにいきます。", "example_meaning_cn": "六号去。", "example_meaning_en": "I'll go on the sixth."},
        "N5_473": {"example_sentence": "向こうに見えるのが富士山です。", "example_reading": "むこうにみえるのがふじさんです。", "example_meaning_cn": "那边看到的是富士山。", "example_meaning_en": "What you see over there is Mt. Fuji."},
        "N5_474": {"example_sentence": "この本は難しいです。", "example_reading": "このほんはむずかしいです。", "example_meaning_cn": "这本书很难。", "example_meaning_en": "This book is difficult."},
        "N5_475": {"example_sentence": "六つ残っています。", "example_reading": "むっつのこっています。", "example_meaning_cn": "还剩六个。", "example_meaning_en": "There are six left."},
        "N5_476": {"example_sentence": "村に帰ります。", "example_reading": "むらにかえります。", "example_meaning_cn": "回村子。", "example_meaning_en": "Return to the village."},
        "N5_477": {"example_sentence": "目が痛いです。", "example_reading": "めがいたいです。", "example_meaning_cn": "眼睛疼。", "example_meaning_en": "My eyes hurt."},
        "N5_478": {"example_sentence": "メートルで測ります。", "example_reading": "メートルではかります。", "example_meaning_cn": "以米测量。", "example_meaning_en": "Measure in meters."},
        "N5_479": {"example_sentence": "眼鏡をかけます。", "example_reading": "めがねをかけます。", "example_meaning_cn": "戴眼镜。", "example_meaning_en": "I'll put on glasses."},
        "N5_480": {"example_sentence": "もう一度言ってください。", "example_reading": "もういちどいってください。", "example_meaning_cn": "请再说一遍。", "example_meaning_en": "Please say it once more."},
        "N5_481": {"example_sentence": "木曜日、暇ですか。", "example_reading": "もくようび、ひまですか。", "example_meaning_cn": "周四有空吗？", "example_meaning_en": "Are you free on Thursday?"},
        "N5_482": {"example_sentence": "もしもし。", "example_reading": "もしもし。", "example_meaning_cn": "喂（电话用语）。", "example_meaning_en": "Hello (on the phone)."},
        "N5_483": {"example_sentence": "カードを持っていますか。", "example_reading": "カードをもっていますか。", "example_meaning_cn": "有卡吗？", "example_meaning_en": "Do you have a card?"},
        "N5_484": {"example_sentence": "もっと欲ほしいです。", "example_reading": "もっとほしいです。", "example_meaning_cn": "更想要（还要更多）。", "example_meaning_en": "I want more."},
        "N5_485": {"example_sentence": "物が多いですね。", "example_reading": "ものがおおいですね。", "example_meaning_cn": "东西很多呢。", "example_meaning_en": "There are many things, aren't there?"},
        "N5_486": {"example_sentence": "門を開けてください。", "example_reading": "もんをあけてください。", "example_meaning_cn": "请开门。", "example_meaning_en": "Please open the gate."},
        "N5_487": {"example_sentence": "問題があります。", "example_reading": "もんだいがあります。", "example_meaning_cn": "有问题。", "example_meaning_en": "There is a problem."},
        "N5_488": {"example_sentence": "八屋でリンゴを買います。", "example_reading": "はちやでリンゴをかいます。", "example_meaning_cn": "在水果店（八百屋）买苹果。 ", "example_meaning_en": "I'll buy apples at the greengrocer."},
        "N5_489": {"example_sentence": "野菜をたくさん食べます。", "example_reading": "やさいをたくさんたべます。", "example_meaning_cn": "吃很多蔬菜。", "example_meaning_en": "I eat a lot of vegetables."},
        "N5_490": {"example_sentence": "このパソコンは安いです。", "example_reading": "このパソコンはやすいです。", "example_meaning_cn": "这台电脑很便宜。", "example_meaning_en": "This computer is cheap."},
        "N5_491": {"example_sentence": "休みの日、何をしますか。", "example_reading": "やすみのひ、なにをしますか。", "example_meaning_cn": "休息日做什么？", "example_meaning_en": "What do you do on your days off?"},
        "N5_492": {"example_sentence": "一分休みましょう。", "example_reading": "いっぷんやすみましょう。", "example_meaning_cn": "休息一分钟吧。", "example_meaning_en": "Let's rest for a minute."},
        "N5_493": {"example_sentence": "八つ置いてあります。", "example_reading": "やっつおいてあります。", "example_meaning_cn": "放着八个。", "example_meaning_en": "There are eight pieces placed."},
        "N5_494": {"example_sentence": "山に登りましょう。", "example_reading": "やまにのぼりましょう。", "example_meaning_cn": "去爬山吧。", "example_meaning_en": "Let's climb the mountain."},
        "N5_495": {"example_sentence": "八百屋で買い物をします。", "example_reading": "やおやでかいものをします。", "example_meaning_cn": "在蔬菜店买东西。", "example_meaning_en": "I shop at the greengrocer."},
        "N5_496": {"example_sentence": "ゆっくり言ってください。", "example_reading": "ゆっくりいってください。", "example_meaning_cn": "请慢慢说。", "example_meaning_en": "Please speak slowly."},
        "N5_497": {"example_sentence": "八日に行きます。", "example_reading": "ようかにいきます。", "example_meaning_cn": "八号去。", "example_meaning_en": "I'll go on the eighth."},
        "N5_498": {"example_sentence": "洋服を着ます。", "example_reading": "ようふくをきます。", "example_meaning_cn": "穿西服（洋服）。", "example_meaning_en": "I'll put on western clothes."},
        "N5_499": {"example_sentence": "よくできました。 ", "example_reading": "よくできました。", "example_meaning_cn": "做得很好。", "example_meaning_en": "Well done."},
        "N5_500": {"example_sentence": "横になってください。", "example_reading": "よこになってください。", "example_meaning_cn": "请躺下。", "example_meaning_en": "Please lie down."},
        "N5_501": {"example_sentence": "四日後に行きます。", "example_reading": "よっかごにいきます。", "example_meaning_cn": "四天后去。", "example_meaning_en": "I'll go in four days."},
        "N5_502": {"example_sentence": "四つ残っています。", "example_reading": "よっつのこっています。", "example_meaning_cn": "还剩四个。", "example_meaning_en": "There are four left."},
        "N5_503": {"example_sentence": "夜、勉強します。", "example_reading": "よる、べんきょうします。", "example_meaning_cn": "晚上学习。", "example_meaning_en": "I study at night."},
        "N5_504": {"example_sentence": "本を読んでください。", "example_reading": "ほんをよんでください。", "example_meaning_cn": "请读书。", "example_meaning_en": "Please read the book."},
        "N5_505": {"example_sentence": "来月、日本へ行きます。", "example_reading": "らいげつ、にほんへいきます。", "example_meaning_cn": "下个月去日本。", "example_meaning_en": "I'm going to Japan next month."},
        "N5_506": {"example_sentence": "来週、会いましょう。", "example_reading": "らいしゅう、あいましょう。", "example_meaning_cn": "下周见吧。", "example_meaning_en": "Let's meet next week."},
        "N5_507": {"example_sentence": "来年は二十歳になります。", "example_reading": "らいねんははたちになります。", "example_meaning_cn": "明年就二十岁了。", "example_meaning_en": "I'll turn twenty next year."},
        "N5_508": {"example_sentence": "ラジオを聞きます。", "example_reading": "ラジオをききます。", "example_meaning_cn": "听收音机。", "example_meaning_en": "I listen to the radio."},
        "N5_509": {"example_sentence": "留学生ですか。", "example_reading": "りゅうがくせいですか。", "example_meaning_cn": "是留学生吗？", "example_meaning_en": "Are you an international student?"},
        "N5_510": {"example_sentence": "両親は元気です。", "example_reading": "りょうしんはげんきです。", "example_meaning_cn": "父母身体很好。", "example_meaning_en": "My parents are well."},
        "N5_511": {"example_sentence": "日本料理が好きです。", "example_reading": "にほんりょうりがすきです。", "example_meaning_cn": "喜欢日本菜。", "example_meaning_en": "I like Japanese food."},
        "N5_512": {"example_sentence": "旅行へ行きたいです。", "example_reading": "りょこうへいきたいです。", "example_meaning_cn": "想去旅行。", "example_meaning_en": "I want to go on a trip."},
        "N5_513": {"example_sentence": "料理が上手です。 ", "example_reading": "りょうりがじょうずです。", "example_meaning_cn": "擅长做饭。", "example_meaning_en": "Good at cooking."},
        "N5_514": {"example_sentence": "リンゴを一袋買いました。", "example_reading": "リンゴをひとふくろかいました。", "example_meaning_cn": "买了一袋苹果。", "example_meaning_en": "I bought a bag of apples."},
        "N5_515": {"example_sentence": "冷蔵庫にビールがあります。", "example_reading": "れいぞうこにビールがあります。", "example_meaning_cn": "冰箱里有啤酒。", "example_meaning_en": "There is beer in the refrigerator."},
        "N5_516": {"example_sentence": "ゼロ和六です。", "example_reading": "ぜろわろくです。", "example_meaning_cn": "零和六。 ", "example_meaning_en": "Zero and six."},
        "N5_517": {"example_sentence": "練習してください。 ", "example_reading": "れんしゅうしてください。", "example_meaning_cn": "请练习。", "example_meaning_en": "Please practice."},
        "N5_518": {"example_sentence": "廊下で待ってください。", "example_reading": "ろうかでおまってください。", "example_meaning_cn": "请在走廊等候。", "example_meaning_en": "Please wait in the hallway."},
        "N5_519": {"example_sentence": "六本持っています。", "example_reading": "ろっぽんもっています。", "example_meaning_cn": "拿着六根（或六瓶）。", "example_meaning_en": "I'm holding six pieces."},
        "N5_520": {"example_sentence": "若いですね。 ", "example_reading": "わかいですね。", "example_meaning_cn": "很年轻呢。", "example_meaning_en": "You're young, aren't you?"},
        "N5_521": {"example_sentence": "わかりますか。 ", "example_reading": "わかりますか。", "example_meaning_cn": "懂了吗？", "example_meaning_en": "Do you understand?"},
        "N5_522": {"example_sentence": "忘れないでください。", "example_reading": "わすれないでください。", "example_meaning_cn": "请不要忘记。", "example_meaning_en": "Please don't forget."},
        "N5_523": {"example_sentence": "私、田中です。", "example_reading": "わたし、たなかです。", "example_meaning_cn": "我，田中。", "example_meaning_en": "I'm Tanaka."},
        "N5_524": {"example_sentence": "お箸を三ぜん渡してください。", "example_reading": "おはしをさんぜんわたしてください。", "example_meaning_cn": "请递给我三双筷子。", "example_meaning_en": "Please hand me three pairs of chopsticks."},
        "N5_525": {"example_sentence": "悪いことをしてはいけません。", "example_reading": "わるいことをしてはいけません。", "example_meaning_cn": "不能做坏事。", "example_meaning_en": "You must not do bad things."},
        "N5_526": {"example_sentence": "いいえ、まだです。 ", "example_reading": "いいえ、まだです。", "example_meaning_cn": "不，还没有。", "example_meaning_en": "No, not yet."},
        "N5_527": {"example_sentence": "お疲れ様でした。", "example_reading": "おつかれさまでした。", "example_meaning_cn": "辛苦了。", "example_meaning_en": "Thank you for your hard work."},
        "N5_528": {"example_sentence": "お手伝いしましょうか。", "example_reading": "おてつだいしましょうか。", "example_meaning_cn": "需要帮忙吗？", "example_meaning_en": "Shall I help you?"},
        "N5_529": {"example_sentence": "お久しぶりですね。", "example_reading": "おひさしぶりですね。", "example_meaning_cn": "好久不见呢。", "example_meaning_en": "Long time no see, isn't it?"},
        "N5_530": {"example_sentence": "お待ちください。", "example_reading": "おまちください。", "example_meaning_cn": "请稍候。", "example_meaning_en": "Please wait."},
        "N5_531": {"example_sentence": "お休みの日、何をしますか。", "example_reading": "おやすみのひ、なにをしますか。", "example_meaning_cn": "休息日做什么？", "example_meaning_en": "What do you do on your holidays?"},
        "N5_532": {"example_sentence": "失礼します。", "example_reading": "しつれいします。", "example_meaning_cn": "告辞了（打扰了）。", "example_meaning_en": "Excuse me (entering/leaving)."},
        "N5_533": {"example_sentence": "本当ですね。 ", "example_reading": "ほんとうですね。", "example_meaning_cn": "是真的呢。", "example_meaning_en": "It's true, isn't it?"},
        "N5_534": {"example_sentence": "また会いましょう。", "example_reading": "またあいましょう。", "example_meaning_cn": "再见吧。", "example_meaning_en": "Let's meet again."},
        "N5_535": {"example_sentence": "ゆっくり休んでください。", "example_reading": "ゆっくりやすんでください。", "example_meaning_cn": "请好好休息。", "example_meaning_en": "Please take a good rest."},
        "N5_536": {"example_sentence": "いってきます。", "example_reading": "いってきます。", "example_meaning_cn": "我走了（出门）。", "example_meaning_en": "I'm off."},
        "N5_537": {"example_sentence": "いってらっしゃい。", "example_reading": "いってらっしゃい。", "example_meaning_cn": "慢走。", "example_meaning_en": "Safe travels / See you later."},
        "N5_538": {"example_sentence": "お帰りなさい。", "example_reading": "おかえりなさい。", "example_meaning_cn": "欢迎回来。", "example_meaning_en": "Welcome home."},
        "N5_539": {"example_sentence": "いただきます。", "example_reading": "いただきます。", "example_meaning_cn": "我开动了。", "example_meaning_en": "Let's eat (grace)."},
        "N5_540": {"example_sentence": "お元気で。", "example_reading": "おげんきで。", "example_meaning_cn": "保重。", "example_meaning_en": "Take care."},
        "N5_541": {"example_sentence": "どちら様ですか。", "example_reading": "どちらさまですか。", "example_meaning_cn": "哪位？", "example_meaning_en": "Who is it (polite)?"},
        "N5_542": {"example_sentence": "どちらが早いですか。", "example_reading": "どちらがはやいですか。", "example_meaning_cn": "哪个更快？", "example_meaning_en": "Which one is faster?"},
        "N5_543": {"example_sentence": "こちらを見てください。", "example_reading": "こちらをみてください。", "example_meaning_cn": "请看这边。", "example_meaning_en": "Please look this way."},
        "N5_544": {"example_sentence": "あちらにあります。", "example_reading": "あちらにあります。", "example_meaning_cn": "在那边。", "example_meaning_en": "It's over there."},
        "N5_545": {"example_sentence": "そちらへどうぞ。", "example_reading": "そちらへどうぞ。", "example_meaning_cn": "请到那边去。", "example_meaning_en": "Please go that way."},
        "N5_546": {"example_sentence": "どこかにあります。", "example_reading": "どこかにあります。", "example_meaning_cn": "在某个地方。", "example_meaning_en": "It's somewhere."},
        "N5_547": {"example_sentence": "どこまで行きますか。", "example_reading": "どこまでいきますか。", "example_meaning_cn": "去到哪儿？", "example_meaning_en": "How far are you going?"},
        "N5_548": {"example_sentence": "いつか日本へ行きたいです。", "example_reading": "いつかにほんへいきたいです。", "example_meaning_cn": "什么时候想去日本。", "example_meaning_en": "I want to go to Japan someday."},
        "N5_549": {"example_sentence": "いつでもいいですよ。", "example_reading": "いつでもいいですよ。", "example_meaning_cn": "什么时候都可以哦。", "example_meaning_en": "Anytime is fine."},
        "N5_550": {"example_sentence": "とてもきれいです。", "example_reading": "とてもきれいです。", "example_meaning_cn": "非常漂亮。", "example_meaning_en": "It's very beautiful."}
    }

    for item in vocab:
        if item['id'] in enrichment:
            item.update(enrichment[item['id']])

    with open(data_file, 'w', encoding='utf-8') as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

    print(f"Updated items up to N5_550.")

if __name__ == "__main__":
    main()
