import json
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    data_file = os.path.join(project_root, 'jlpt-web', 'src', 'data', 'vocab.json')

    if not os.path.exists(data_file):
        return

    with open(data_file, 'r', encoding='utf-8') as f:
        vocab = json.load(f)

    enrichment = {
        "N3_601": {"example_sentence": "コンパス（こんぱす）で円を描きます。", "example_reading": "コンパスでえんをかきます。", "example_meaning_cn": "用圆规（或指南针）画圆。", "example_meaning_en": "I'll draw a circle with a compass."},
        "N3_602": {"example_sentence": "コンピューター（こんぴゅーたー）を使います。", "example_reading": "コンピューターをつかいます。", "example_meaning_cn": "使用电脑。", "example_meaning_en": "I use a computer."},
        "N3_603": {"example_sentence": "こん（今）夜（や）はパーティーです。", "example_reading": "こんやはぱーてぃーです。", "example_meaning_cn": "今晚有派对。", "example_meaning_en": "There's a party tonight."},
        "N3_604": {"example_sentence": "こ（婚）約（やく）しました！", "example_reading": "こんやくしました！", "example_meaning_cn": "订婚了！", "example_meaning_en": "I've gotten engaged!"},
        "N3_605": {"example_sentence": "こん（混乱）乱しています。", "example_reading": "こんらんしています。", "example_meaning_cn": "正混乱着呢。", "example_meaning_en": "It's in chaos/I'm confused."},
        "N3_606": {"example_sentence": "さ（差）があります。", "example_reading": "さがります。", "example_meaning_cn": "有差距。", "example_meaning_en": "There is a difference/gap."},
        "N3_607": {"example_sentence": "サービス（さーびす）してください。", "example_reading": "サービスしてください。", "example_meaning_cn": "请给点优惠（或提供服务）。", "example_meaning_en": "Please give me a discount/service."},
        "N3_608": {"example_sentence": "さい（最近）近はどうですか。", "example_reading": "さいきんはどうですか。", "example_meaning_cn": "最近怎么样？", "example_meaning_en": "How have you been lately?"},
        "N3_609": {"example_sentence": "さい（再）現（げん）してください。", "example_reading": "さいげんしてください。", "example_meaning_cn": "请再现（或还原）。", "example_meaning_en": "Please reproduce/recreate it."},
        "N3_610": {"example_sentence": "さい（最高）高ですね！", "example_reading": "さいこうですね！", "example_meaning_cn": "太棒了（最高）！", "example_meaning_en": "It's the best!"},
        "N3_611": {"example_sentence": "さい（最後）後まで頑張りましょう。", "example_reading": "さいごまでがんばりましょう。", "example_meaning_cn": "坚持到最后吧。", "example_meaning_en": "Let's do our best until the end."},
        "N3_612": {"example_sentence": "さい（最新）新の技術です。", "example_reading": "さいしんのぎじゅつです。", "example_meaning_cn": "是最新的技术。", "example_meaning_en": "It's the latest technology."},
        "N3_613": {"example_sentence": "さい（最小）小限に抑えてください。", "example_reading": "さいしょうげんにおさえてください。", "example_meaning_cn": "请压制在最小程度内。", "example_meaning_en": "Please keep it to a minimum."},
        "N3_614": {"example_sentence": "さい（再生）生してください。", "example_reading": "さいせいしてください。", "example_meaning_cn": "请播放（或再生）。", "example_meaning_en": "Please play/regenerate it."},
        "N3_615": {"example_sentence": "さい（採）用（よう）されました。", "example_reading": "さいようされました。", "example_meaning_cn": "被采用了（或录用了）。", "example_meaning_en": "I was hired/it was adopted."},
        "N3_616": {"example_sentence": "さい（材料）料（りょう）を揃えてください。", "example_reading": "ざいりょうをそろえてください。", "example_meaning_cn": "请准备齐材料。", "example_meaning_en": "Please gather the materials."},
        "N3_617": {"example_sentence": "さい（幸）いです。", "example_reading": "さいわいです。", "example_meaning_cn": "万分庆幸（或荣幸）。", "example_meaning_en": "I would be happy/fortunate."},
        "N3_618": {"example_sentence": "さか（境）を越えます。", "example_reading": "さかいをこえます。", "example_meaning_cn": "越过边界（境界）。", "example_meaning_en": "Cross the border."},
        "N3_619": {"example_sentence": "さか（逆）らいません。", "example_reading": "さからいません。", "example_meaning_cn": "不违抗（或不逆行）。", "example_meaning_en": "I won't go against it."},
        "N3_620": {"example_sentence": "さか（盛）んですね。 ", "example_reading": "さかんですね。", "example_meaning_cn": "很繁盛（兴旺）呢。", "example_meaning_en": "It's prosperous, isn't it?"},
        "N3_621": {"example_sentence": "さき（先）に行ってください。", "example_reading": "さきにいってください。", "example_meaning_cn": "请先走（去）。", "example_meaning_en": "Please go ahead."},
        "N3_622": {"example_sentence": "さぎ（詐欺）に気をつけてください。", "example_reading": "さぎにきをつけてください。", "example_meaning_cn": "请小心诈骗。", "example_meaning_en": "Please be careful of scams."},
        "N3_623": {"example_sentence": "さ（作）業（ぎょう）を始めてください。", "example_reading": "さぎょうをはじめてください。", "example_meaning_cn": "请开始作业。", "example_meaning_en": "Please start work."},
        "N3_624": {"example_sentence": "さく（昨）日（じつ）はありがとうございました。", "example_reading": "さくじつはありがとうございました。", "example_meaning_cn": "昨天谢谢了（正式）。", "example_meaning_en": "Thank you for yesterday (formal)."},
        "N3_625": {"example_sentence": "さく（作）品（ひん）を見てください。", "example_reading": "さくひんをみてください。", "example_meaning_cn": "请看作品。", "example_meaning_en": "Please look at the work/piece."},
        "N3_626": {"example_sentence": "さく（索）引（いん）で調べてください。", "example_reading": "さくいんでしらべてください。", "example_meaning_cn": "请在索引里查一下。", "example_meaning_en": "Please check the index."},
        "N3_627": {"example_sentence": "さく（削）除（じょ）してください。", "example_reading": "さくじょしてください。", "example_meaning_cn": "请删除。", "example_meaning_en": "Please delete it."},
        "N3_628": {"example_sentence": "さく（作成）成してください。", "example_reading": "さくせいしてください。", "example_meaning_cn": "请制作（或作成）。", "example_meaning_en": "Please create/make it."},
        "N3_629": {"example_sentence": "さぐ（探）ってください。", "example_reading": "さぐってください。", "example_meaning_cn": "请探索（或试探）。", "example_meaning_en": "Please search/probe for it."},
        "N3_630": {"example_sentence": "（避）けてください。", "example_reading": "さけてください。", "example_meaning_cn": "请避开。", "example_meaning_en": "Please avoid it."},
        "N3_631": {"example_sentence": "ささ（支）えてください。", "example_reading": "ささえてください。", "example_meaning_cn": "请支撑。", "example_meaning_en": "Please support me."},
        "N3_632": {"example_sentence": "さ（指）してください。", "example_reading": "さしてください。", "example_meaning_cn": "请指（向）。", "example_meaning_en": "Please point to it."},
        "N3_633": {"example_sentence": "（刺）されました！ ", "example_reading": "さされました！", "example_meaning_cn": "被刺（或叮）了！", "example_meaning_en": "I was stabbed/bitten!"},
        "N3_634": {"example_sentence": "（座）ってください。", "example_reading": "すわってください。", "example_meaning_cn": "请坐。", "example_meaning_en": "Please sit."},
        "N3_635": {"example_sentence": "さ（最）終（しゅう）回です。", "example_reading": "さいしゅうかいです。", "example_meaning_cn": "最终回（最后一集）。", "example_meaning_en": "It's the last episode."},
        "N3_636": {"example_sentence": "さ（差）い（し）入れ（いれ）です。", "example_reading": "さしいれです。", "example_meaning_cn": "这是慰劳品（或小礼）。", "example_meaning_en": "Here's a small treat/gift."},
        "N3_637": {"example_sentence": "さ（指）し（し）示（じ）してください。", "example_reading": "さしじしてください。", "example_meaning_cn": "请指示。", "example_meaning_en": "Please give instructions."},
        "N3_638": {"example_sentence": "さ（差）し（し）出し（だし）人（にん）は誰ですか。", "example_reading": "さしだしにんはだれですか。", "example_meaning_cn": "寄件人是谁？", "example_meaning_en": "Who is the sender?"},
        "N3_639": {"example_sentence": "さ（刺）し（し）身（み）を食べましょう。", "example_reading": "さしみをたべましょう。", "example_meaning_cn": "吃生鱼片吃吧。", "example_meaning_en": "Let's eat sashimi."},
        "N3_640": {"example_sentence": "さ（差）し（つ）支え（かえ）ありません。", "example_reading": "さしつかえありません。", "example_meaning_cn": "没有妨碍（不碍事）。", "example_meaning_en": "There's no problem/objection."},
        "N3_641": {"example_sentence": "さすが（流石）ですね！", "example_reading": "さすがですね！", "example_meaning_cn": "不愧是你（名不虚传）！", "example_meaning_en": "As expected of you!"},
        "N3_642": {"example_sentence": "さ（授）けてください。", "example_reading": "さずけてください。", "example_meaning_cn": "请授予（或教导）。", "example_meaning_en": "Please bestow/impart it."},
        "N3_643": {"example_sentence": "ささ（捧）げてください。", "example_reading": "ささげてください。", "example_meaning_cn": "请奉献。", "example_meaning_en": "Please dedicate/sacrifice it."},
        "N3_644": {"example_sentence": "（誘）ってください。", "example_reading": "さそってください。", "example_meaning_cn": "请邀请（我）。", "example_meaning_en": "Please invite me."},
        "N3_645": {"example_sentence": "さだ（定）めてください。", "example_reading": "さだめてください。", "example_meaning_cn": "请决定（或制定）。", "example_meaning_en": "Please determine/set it."},
        "N3_646": {"example_sentence": "さ（察）してください。", "example_reading": "さっしてください。", "example_meaning_cn": "请体察（或察觉）。", "example_meaning_en": "Please understand/perceive."},
        "N3_647": {"example_sentence": "さっき（さっき）会いました。", "example_reading": "さっきあいました。", "example_meaning_cn": "刚才见过了。", "example_meaning_en": "I met them just now."},
        "N3_648": {"example_sentence": "さっそく（早速）始めましょう。", "example_reading": "さっそくはじめましょう。", "example_meaning_cn": "赶紧开始吧。", "example_meaning_en": "Let's start immediately."},
        "N3_649": {"example_sentence": "ざっと（ざっと）説明してください。", "example_reading": "ざっとせつめいしてください。", "example_meaning_cn": "请粗略地说明一下。", "example_meaning_en": "Please explain briefly/roughly."},
        "N3_650": {"example_sentence": "ざ（雑）音（おん）がうるさいです。", "example_reading": "ざつおんがうるさいです。", "example_meaning_cn": "噪音太吵了。", "example_meaning_en": "The noise is annoying."},
        "N3_651": {"example_sentence": "さ（昨）夜（や）は寝られませんでした。", "example_reading": "さくやはねられませんでした。", "example_meaning_cn": "昨晚没睡着。", "example_meaning_en": "I couldn't sleep last night."},
        "N3_652": {"example_sentence": "さ（寂）びしいですね。", "example_reading": "さびしいですね。", "example_meaning_cn": "真寂寞呢。", "example_meaning_en": "It's lonely, isn't it?"},
        "N3_653": {"example_sentence": "さ（錆）びています。", "example_reading": "さびています。", "example_meaning_cn": "生锈了。", "example_meaning_en": "It's rusty."},
        "N3_654": {"example_sentence": "さま（様）々（ざま）な理由があります。", "example_reading": "さまざまなりゆうがあります。", "example_meaning_cn": "有各种理由。", "example_meaning_en": "There are various reasons."},
        "N3_655": {"example_sentence": "さ（冷）めてしまいました。", "example_reading": "さめてしまいました。", "example_meaning_cn": "凉了（或心冷了）。", "example_meaning_en": "It has cooled down/I've cooled down."},
        "N3_656": {"example_sentence": "（覚）めていましたか。", "example_reading": "さめていましたか。", "example_meaning_cn": "醒着的吗？", "example_meaning_en": "Were you awake?"},
        "N3_657": {"example_sentence": "さ（妨）げないでください。", "example_reading": "さまたげないでください。", "example_meaning_cn": "请不要妨碍。", "example_meaning_en": "Please don't disturb."},
        "N3_658": {"example_sentence": "さみ（冷）しいですね。", "example_reading": "さびしいですね。", "example_meaning_cn": "真冷清（或寂寞）呢。", "example_meaning_en": "It's lonely, isn't it?"},
        "N3_659": {"example_sentence": "さよなら（さよなら）。 ", "example_reading": "さよなら。", "example_meaning_cn": "再见。", "example_meaning_en": "Goodbye."},
        "N3_660": {"example_sentence": "さ（皿）を洗ってください。", "example_reading": "さらをあらってください。", "example_meaning_cn": "请洗碗。", "example_meaning_en": "Please wash the dishes."},
        "N3_661": {"example_sentence": "さら（致）に努力します。", "example_reading": "さらにどりょくします。", "example_meaning_cn": "进一步努力。", "example_meaning_en": "I'll work even harder."},
        "N3_662": {"example_sentence": "さら（致）してください。", "example_reading": "さらしてください。", "example_meaning_cn": "请曝光。", "example_meaning_en": "Please expose it."},
        "N3_663": {"example_sentence": "さり（去）ってください。", "example_reading": "さってください。", "example_meaning_cn": "请离去。", "example_meaning_en": "Please leave."},
        "N3_664": {"example_sentence": "さわ（爽）やかですね！", "example_reading": "さわやかですね！", "example_meaning_cn": "真清爽呢！", "example_meaning_en": "How refreshing!"},
        "N3_665": {"example_sentence": "さわ（騒）がないでください。", "example_reading": "さわがないでください。", "example_meaning_cn": "请不要大声吵闹。", "example_meaning_en": "Please don't make a noise."},
        "N3_666": {"example_sentence": "さわ（触）ってください。", "example_reading": "さわってください。", "example_meaning_cn": "请触摸。", "example_meaning_en": "Please touch it."},
        "N3_667": {"example_sentence": "さん（参）加（か）してください。", "example_reading": "さんかしてください。", "example_meaning_cn": "请参加。", "example_meaning_en": "Please participate."},
        "N3_668": {"example_sentence": "さん（参考）考にしてください。", "example_reading": "さんこうにしてください。", "example_meaning_cn": "请参考。", "example_meaning_en": "Please refer to it."},
        "N3_669": {"example_sentence": "さん（賛成）成です！", "example_reading": "さんせいです！", "example_meaning_cn": "赞成！", "example_meaning_en": "I agree!"},
        "N3_670": {"example_sentence": "さん（散歩）歩しましょう。", "example_reading": "さんぽしましょう。", "example_meaning_cn": "散步吧。", "example_meaning_en": "Let's take a walk."},
        "N3_671": {"example_sentence": "し（指）に（名）されました。", "example_reading": "しめいされました。", "example_meaning_cn": "被点了名（或指名）。", "example_meaning_en": "I was nominated/designated."},
        "N3_672": {"example_sentence": "し（氏）名（めい）を書いてください。", "example_reading": "しめいをかいてください。", "example_meaning_cn": "请写姓名。", "example_meaning_en": "Please write your name."},
        "N3_673": {"example_sentence": "し（四）か月（げつ）経ちました。", "example_reading": "よんかげつたちました。", "example_meaning_cn": "过了四个月了。", "example_meaning_en": "Four months have passed."},
        "N3_674": {"example_sentence": "しあ（試）合（あい）に勝ちました！", "example_reading": "しあいにかちました！", "example_meaning_cn": "比赛赢了！", "example_meaning_en": "We won the match!"},
        "N3_675": {"example_sentence": "しあわせ（幸せ）ですね！", "example_reading": "しあわせですね！", "example_meaning_cn": "真幸福呢！", "example_meaning_en": "How happy!"},
        "N3_676": {"example_sentence": "し（仕上げ）上げをしてください。", "example_reading": "しあげをしてください。", "example_meaning_cn": "请收尾（或精加工）。", "example_meaning_en": "Please finish it up."},
        "N3_677": {"example_sentence": "しい（強）いて言えばそうです。", "example_reading": "しいていえばそうです。", "example_meaning_cn": "硬要说的话就是那样。", "example_meaning_en": "If I had to say, that's right."},
        "N3_678": {"example_sentence": "しい（仕）入（れ）に行ってきます。", "example_reading": "しいれにいってきます。", "example_meaning_cn": "去进货。", "example_meaning_en": "I'm going to stock up/purchase."},
        "N3_679": {"example_sentence": "し（強）い（し）る（し）のは良くないです。", "example_reading": "しいるのはよくないです。", "example_meaning_cn": "强迫别人是不好的。", "example_meaning_en": "It's not good to force someone."},
        "N3_680": {"example_sentence": "しお（塩）をかけてください。", "example_reading": "しおをかけてください。", "example_meaning_cn": "请撒点盐。", "example_meaning_en": "Please sprinkle some salt."},
        "N3_681": {"example_sentence": "しか（司会）会（かい）をしてください。", "example_reading": "しかいをしてください。", "example_meaning_cn": "请担任主持。", "example_meaning_en": "Please act as the host/moderator."},
        "N3_682": {"example_sentence": "しか（視界）界が悪いです。", "example_reading": "しかいがわるいです。", "example_meaning_cn": "视线不好。", "example_meaning_en": "The visibility is poor."},
        "N3_683": {"example_sentence": "しか（時間）間がありません。", "example_reading": "じかんがありません。", "example_meaning_cn": "没时间。", "example_meaning_en": "I have no time."},
        "N3_684": {"example_sentence": "しかし（しかし）...", "example_reading": "しかし。", "example_meaning_cn": "但是...", "example_meaning_en": "But..."},
        "N3_685": {"example_sentence": "しかた（仕方）ありません。", "example_reading": "しかたありません。", "example_meaning_cn": "没办法。", "example_meaning_en": "It can't be helped."},
        "N3_686": {"example_sentence": "しき（指揮）を執ってください。", "example_reading": "しきをとってください。", "example_meaning_cn": "请指挥。", "example_meaning_en": "Please take command."},
        "N3_687": {"example_sentence": "しき（時期）期が早いです。", "example_reading": "じきがはやいです。", "example_meaning_cn": "时机太早。", "example_meaning_en": "It's too early/the timing is early."},
        "N3_688": {"example_sentence": "しき（四季）季の変化が好きです。", "example_reading": "しきのへんかがすきです。", "example_meaning_cn": "喜欢四季的变化。", "example_meaning_en": "I like the changes of the four seasons."},
        "N3_689": {"example_sentence": "しき（意識）識（しき）が高まっています。", "example_reading": "いしきがたかまっています。", "example_meaning_cn": "意识在提高。", "example_meaning_en": "The awareness is increasing."},
        "N3_690": {"example_sentence": "しき（至急）急（きゅう）連絡してください。", "example_reading": "しきゅうれんらくしてください。", "example_meaning_cn": "请火速联系。", "example_meaning_en": "Please contact urgently."},
        "N3_691": {"example_sentence": "しき（至極）極（ごく）当たり前です。", "example_reading": "しごくあたりまえです。", "example_meaning_cn": "理所当然（至极）。", "example_meaning_en": "It's perfectly natural."},
        "N3_692": {"example_sentence": "しき（支給）給してください。", "example_reading": "しきゅうしてください。", "example_meaning_cn": "请发放。", "example_meaning_en": "Please pay/issue it."},
        "N3_693": {"example_sentence": "しき（試験）験（けん）を頑張ってください。", "example_reading": "しけんをがんばってください。", "example_meaning_cn": "考试加油。", "example_meaning_en": "Do your best on the exam."},
        "N3_694": {"example_sentence": "しき（資源）源を大切にしましょう。", "example_reading": "しげんをたいせつにしましょう。", "example_meaning_cn": "珍惜资源吧。", "example_meaning_en": "Let's cherish our resources."},
        "N3_695": {"example_sentence": "じ（磁）石（しゃく）で遊びます。", "example_reading": "じしゃくであそびます。", "example_meaning_cn": "玩磁铁。", "example_meaning_en": "I'll play with magnets."},
        "N3_696": {"example_sentence": "し（自）信（しん）を持ってください。", "example_reading": "じしんをもってください。", "example_meaning_cn": "请有自信。", "example_meaning_en": "Please have confidence."},
        "N3_697": {"example_sentence": "し（事実）実（じつ）を話してください。", "example_reading": "じじつをはなしてください。", "example_meaning_cn": "请说事实。", "example_meaning_en": "Please tell the truth/fact."},
        "N3_698": {"example_sentence": "し（静）かにしてください。", "example_reading": "しずかにしてください。", "example_meaning_cn": "请安静。", "example_meaning_en": "Please be quiet."},
        "N3_699": {"example_sentence": "し（沈）んでいますね。 ", "example_reading": "しずんでいますね。", "example_meaning_cn": "正下沉（或沮丧）着呢。", "example_meaning_en": "It's sinking/I'm depressed."},
        "N3_700": {"example_sentence": "し（姿勢）勢（せい）を正してください。", "example_reading": "しせいをただしてください。", "example_meaning_cn": "请端正姿势。", "example_meaning_en": "Please correct your posture."},
        "N3_701": {"example_sentence": "し（自然）然を愛しています。", "example_reading": "しぜんをあいしています。", "example_meaning_cn": "热爱大自然。", "example_meaning_en": "I love nature."},
        "N3_702": {"example_sentence": "した（した）を見てください。", "example_reading": "したをみてください。", "example_meaning_cn": "请看下面。", "example_meaning_en": "Please look down."},
        "N3_703": {"example_sentence": "した（親）しい仲です。", "example_reading": "したしいなかです。", "example_meaning_cn": "亲密的关系。", "example_meaning_en": "We're on close terms."},
        "N3_704": {"example_sentence": "した（下）着を買いました。", "example_reading": "したぎをかいました。", "example_meaning_cn": "买了内衣。", "example_meaning_en": "I bought some underwear."},
        "N3_705": {"example_sentence": "した（致）します。", "example_reading": "いたします。", "example_meaning_cn": "我（会）做（谦词）。", "example_meaning_en": "I will do (humble)."},
        "N3_706": {"example_sentence": "し（質）問（もん）はありますか。", "example_reading": "しつもんはありますか。", "example_meaning_cn": "有问题吗？", "example_meaning_en": "Are there any questions?"},
        "N3_707": {"example_sentence": "し（失）礼（れい）します。", "example_reading": "しつれいします。", "example_meaning_cn": "失陪了（或打扰了）。", "example_meaning_en": "Excuse me."},
        "N3_708": {"example_sentence": "し（死）ぬかと思いました！ ", "example_reading": "しぬかとおもいました！", "example_meaning_cn": "还以为要死了呢！", "example_meaning_en": "I thought I was going to die!"},
        "N3_709": {"example_sentence": "しば（芝）生（ふ）を歩きます。", "example_reading": "しばふをあるきます。", "example_meaning_cn": "走在草坪上。", "example_meaning_en": "I'll walk on the lawn."},
        "N3_710": {"example_sentence": "し（（縛）ば）ってください。", "example_reading": "しばってください。", "example_meaning_cn": "请捆绑。", "example_meaning_en": "Please bind/tie it."},
        "N3_711": {"example_sentence": "しは（支払）払（はら）ってください。", "example_reading": "しはらってください。", "example_meaning_cn": "请支付。", "example_meaning_en": "Please pay."},
        "N3_712": {"example_sentence": "しぼ（搾）ってください。", "example_reading": "しぼってください。", "example_meaning_cn": "请拧（或榨）。", "example_meaning_en": "Please squeeze/wring it."},
        "N3_713": {"example_sentence": "しぼ（絞）ってください。", "example_reading": "しぼってください。", "example_meaning_cn": "请限制（或压缩）。", "example_meaning_en": "Please narrow down/constrict it."},
        "N3_714": {"example_sentence": "し（島）へ行きます。", "example_reading": "しまへいきます。", "example_meaning_cn": "去岛上。", "example_meaning_en": "I'm going to the island."},
        "N3_715": {"example_sentence": "し（市民）民会館へ行きます。", "example_reading": "しみんかいかんへいきます。", "example_meaning_cn": "去市民会馆。", "example_meaning_en": "I'm going to the civic center."},
        "N3_716": {"example_sentence": "し（辞）め（め）てください。", "example_reading": "やめてください。", "example_meaning_cn": "请停止（或辞职）。", "example_meaning_en": "Please stop/quit."},
        "N3_717": {"example_sentence": "し（締）めてください。", "example_reading": "しめてください。", "example_meaning_cn": "请系紧（或关上）。", "example_meaning_en": "Please tighten/shut it."},
        "N3_718": {"example_sentence": "じ（事務）務（む）所で働いています。", "example_reading": "じむしょではたらいています。", "example_meaning_cn": "在办公室工作。", "example_meaning_en": "I work in an office."},
        "N3_719": {"example_sentence": "じ（示）め（め）してください。", "example_reading": "しめしてください。", "example_meaning_cn": "请指示（或出示）。", "example_meaning_en": "Please show/indicate."},
        "N3_720": {"example_sentence": "し（地）面（めん）を見てください。", "example_reading": "じめんをみてください。", "example_meaning_cn": "请看地面。", "example_meaning_en": "Please look at the ground."},
        "N3_721": {"example_sentence": "しめ（湿）っていますね。 ", "example_reading": "しめっていますね。", "example_meaning_cn": "潮乎乎的呢。", "example_meaning_en": "It's damp, isn't it?"},
        "N3_722": {"example_sentence": "じゃあ（じゃあ）会いましょう。", "example_reading": "じゃああいましょう。", "example_meaning_cn": "那就见个面吧。", "example_meaning_en": "Well then, let's meet."},
        "N3_723": {"example_sentence": "し（社会）会（かい）に貢献します。", "example_reading": "しゃかいにこうけんします。", "example_meaning_cn": "向社会做贡献。", "example_meaning_en": "I'll contribute to society."},
        "N3_724": {"example_sentence": "し（借金）金（きん）を返します。", "example_reading": "しゃっきんをかえします。", "example_meaning_cn": "还债。", "example_meaning_en": "I'll repay the debt."},
        "N3_725": {"example_sentence": "し（社長）長に会いました。", "example_reading": "しゃちょうにあいました。", "example_meaning_cn": "见到了社长。", "example_meaning_en": "I met the president."},
        "N3_726": {"example_sentence": "し（邪魔）魔（ま）しないでください。", "example_reading": "じゃましないでください。", "example_meaning_cn": "请不要打扰。", "example_meaning_en": "Please don't disturb me."},
        "N3_727": {"example_sentence": "し（写）真（しん）を撮ります。", "example_reading": "しゃしんをとります。", "example_meaning_cn": "拍照片。", "example_meaning_en": "I'll take a photo."},
        "N3_728": {"example_sentence": "し（車庫）庫（こ）へ入れます。", "example_reading": "しゃこにいれます。", "example_meaning_cn": "进车库。", "example_meaning_en": "I'll put it in the garage."},
        "N3_729": {"example_sentence": "しょ（修正）正してください。", "example_reading": "しゅうせいてください。", "example_meaning_cn": "请修正（或改）。", "example_meaning_en": "Please correct/modify it."},
        "N3_730": {"example_sentence": "しゅう（周囲）囲を見てください。", "example_reading": "しゅういをみてください。", "example_meaning_cn": "请看周围。", "example_meaning_en": "Please look around you."},
        "N3_731": {"example_sentence": "しゅう（収穫）穫（かく）を祝います。", "example_reading": "しゅうかくをいわいます。", "example_meaning_cn": "庆祝丰收。", "example_meaning_en": "I'll celebrate the harvest."},
        "N3_732": {"example_sentence": "しゅう（習慣）慣（かん）を身につけます。", "example_reading": "しゅうかんをみにつけます。", "example_meaning_cn": "养成习惯。", "example_meaning_en": "I'll acquire the habit."},
        "N3_733": {"example_sentence": "じゅう（宗教）教（きょう）を信じますか。", "example_reading": "しゅうきょうをしんじますか。", "example_meaning_cn": "信教吗？", "example_meaning_en": "Do you believe in a religion?"},
        "N3_734": {"example_sentence": "しゅう（収集）集（しゅう）してください。", "example_reading": "しゅうしゅうしてください。", "example_meaning_cn": "请收集。", "example_meaning_en": "Please collect it."},
        "N3_735": {"example_sentence": "しゅう（収入）入（にゅう）はいくらですか。", "example_reading": "しゅうにゅうはいくらですか。", "example_meaning_cn": "收入是多少？", "example_meaning_en": "What is the income?"},
        "N3_736": {"example_sentence": "しゅう（就職）職（しょく）しました！", "example_reading": "しゅうしょくしました！", "example_meaning_cn": "就业了！", "example_meaning_en": "I got a job!"},
        "N3_737": {"example_sentence": "しゅう（集中）中してください。", "example_reading": "しゅうちゅうしてください。", "example_meaning_cn": "请集中（精务）。", "example_meaning_en": "Please concentrate."},
        "N3_738": {"example_sentence": "じゅう（重点）点（てん）を教えてください。", "example_reading": "じゅうてんをおしえてください。", "example_meaning_cn": "请告诉重点。", "example_meaning_en": "Please tell me the key points."},
        "N3_739": {"example_sentence": "しゅう（修）理（り）してください。", "example_reading": "しゅうりしてください。", "example_meaning_cn": "请修理。", "example_meaning_en": "Please repair it."},
        "N3_740": {"example_sentence": "しゅう（終了）了しました。", "example_reading": "しゅうりょうしました。", "example_meaning_cn": "结束（完了）了。", "example_meaning_en": "It's finished/over."},
        "N3_741": {"example_sentence": "しゅぎ（主義）を持っています。", "example_reading": "しゅぎをもっています。", "example_meaning_cn": "持有某种主义（或原则）。", "example_meaning_en": "I have a principle/ism."},
        "N3_742": {"example_sentence": "しゅく（祝）日（じつ）は休みです。", "example_reading": "しゅくじつはやすみです。", "example_meaning_cn": "节假日（祝日）休息。", "example_meaning_en": "National holidays are off."},
        "N3_743": {"example_sentence": "しゅく（宿題）題（だい）をしてください。", "example_reading": "しゅくだいをしてください。", "example_meaning_cn": "请做作业。", "example_meaning_en": "Please do your homework."},
        "N3_744": {"example_sentence": "しゅく（宿泊）泊してください。", "example_reading": "しゅくはくしてください。", "example_meaning_cn": "请住宿。", "example_meaning_en": "Please stay overnight."},
        "N3_745": {"example_sentence": "じゅ（手術）術（じゅつ）を受けます。", "example_reading": "しゅじゅつをうけます。", "example_meaning_cn": "受手术。", "example_meaning_en": "I'll undergo surgery."},
        "N3_746": {"example_sentence": "しゅ（主流）流（りゅう）になっています。", "example_reading": "しゅりゅうになっています。", "example_meaning_cn": "已成为主流。", "example_meaning_en": "It has become the mainstream."},
        "N3_747": {"example_sentence": "しゅ（種類）類（るい）が多いですね。", "example_reading": "しゅるいがおおいですね。", "example_meaning_cn": "种类很多呢。", "example_meaning_en": "There are many kinds, aren't there?"},
        "N3_748": {"example_sentence": "しゅ（順）番（ばん）を守ってください。", "example_reading": "じゅんばんをまもってください。", "example_meaning_cn": "请遵守顺序（排队）。", "example_meaning_en": "Please follow the order/wait your turn."},
        "N3_749": {"example_sentence": "しゅん（準備）備（び）をしてください。", "example_reading": "じゅんびをしてください。", "example_meaning_cn": "请做准备。", "example_meaning_en": "Please get ready."},
        "N3_750": {"example_sentence": "じゅん（順調）調（ちょう）ですね！", "example_reading": "じゅんちょうですね！", "example_meaning_cn": "一切顺利呢！", "example_meaning_en": "Everything is going smoothly!"}
    }

    for item in vocab:
        if item['id'] in enrichment:
            item.update(enrichment[item['id']])

    with open(data_file, 'w', encoding='utf-8') as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

    print(f"Updated items up to N3_750.")

if __name__ == "__main__":
    main()
