import json
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    data_file = os.path.join(project_root, 'jlpt-web', 'src', 'data', 'vocab.json')

    if not os.path.exists(data_file):
        return

    with open(data_file, 'r', encoding='utf-8') as f:
        vocab = json.load(f)

    enrichment = {
        "N2_0": {"example_sentence": "（合）い（（図）ず）をしてください。", "example_reading": "あいずをしてください。", "example_meaning_cn": "请打信号。", "example_meaning_en": "Please give a signal."},
        "N2_1": {"example_sentence": "（（相）あい）か（（変）か）わらず元気です。", "example_reading": "あいかわらずげんきです。", "example_meaning_cn": "一如既往地精神。", "example_meaning_en": "I'm doing well as always."},
        "N2_2": {"example_sentence": "（（愛）あい）き（（嬌）きょう）がありますね。", "example_reading": "あいきょうがありますね。", "example_meaning_cn": "真讨人喜欢（有魅力）呢。", "example_meaning_en": "They are charming, aren't they?"},
        "N2_3": {"example_sentence": "（（愛）あい）じょう（（情）じょう）を注いでください。", "example_reading": "あいじょうをそそいでください。", "example_meaning_cn": "请倾注爱意。", "example_meaning_en": "Please pour your affection into it."},
        "N2_4": {"example_sentence": "（（合）あい）ず（（図）ず）を送ります。", "example_reading": "あいずをおくります。", "example_meaning_cn": "发生信号。", "example_meaning_en": "I'll send a signal."},
        "N2_5": {"example_sentence": "アイス（あいす）を食べましょう。", "example_reading": "アイスをたべましょう。", "example_meaning_cn": "吃冰淇淋吧。", "example_meaning_en": "Let's eat ice cream."},
        "N2_6": {"example_sentence": "（（愛）あい）する（する）人を守ります。", "example_reading": "あいするひとをまもります。", "example_meaning_cn": "保护所爱的人。", "example_meaning_en": "I'll protect the one I love."},
        "N2_7": {"example_sentence": "（（相）あい）だ（（手）て）に伝えてください。", "example_reading": "あいてにつたえてください。", "example_meaning_cn": "请转告对方。", "example_meaning_en": "Please tell the other party."},
        "N2_8": {"example_sentence": "（（空）あ）いて（て）いますか。", "example_reading": "あいていますか。", "example_meaning_cn": "有空吗？", "example_meaning_en": "Is it free/available?"},
        "N2_9": {"example_sentence": "あいにく（あいにく）不在です。", "example_reading": "あいにくふざいです。", "example_meaning_cn": "不凑巧不在家。", "example_meaning_en": "Unfortunately, they are out."},
        "N2_10": {"example_sentence": "（（明）あ）かり（（灯）とう）を消してください。", "example_reading": "あかりをけしてください。", "example_meaning_cn": "请熄灯。", "example_meaning_en": "Please turn off the light."},
        "N2_11": {"example_sentence": "（（明）あ）き（（空）あ）き（（明）あ）きし（きし）ました。", "example_reading": "あきあきしました。", "example_meaning_cn": "已经腻透了（厌烦）。", "example_meaning_en": "I'm sick and tired of it."},
        "N2_12": {"example_sentence": "（（明）あ）らか（（確）らか）に（に）違います。", "example_reading": "あきらかにちがいます。", "example_meaning_cn": "显而易见地不同。", "example_meaning_en": "It's clearly different."},
        "N2_13": {"example_sentence": "（（諦）あきら）め（め）ないでください！ ", "example_reading": "あきらめないでください！", "example_meaning_cn": "请不要放弃！", "example_meaning_en": "Please don't give up!"},
        "N2_14": {"example_sentence": "（（飽）あ）き（き）て（て）しまいました。", "example_reading": "あきてしまいました。", "example_meaning_cn": "已经厌烦了。", "example_meaning_en": "I've gotten tired of it."},
        "N2_15": {"example_sentence": "（（握）あく）しゅ（しゅ）しましょう。", "example_reading": "あくしゅしましょう。", "example_meaning_cn": "握手吧。", "example_meaning_en": "Let's shake hands."},
        "N2_16": {"example_sentence": "ア（あ）ク（く）セ（せ）サ（さ）リ（り）ー（ー）を買いました。", "example_reading": "アクセサリーをかいました。", "example_meaning_cn": "买了首饰（配件）。", "example_meaning_en": "I bought some accessories."},
        "N2_17": {"example_sentence": "アクセル（あくせる）を踏んでください。", "example_reading": "アクセルをふんでください。", "example_meaning_cn": "请踩油门。", "example_meaning_en": "Please step on the accelerator."},
        "N2_18": {"example_sentence": "（（明）あ）け（け）が（（方）がた）に（に）帰り（かえり）ます。", "example_reading": "あけがたにかえります。", "example_meaning_cn": "黎明时分回去。", "example_meaning_en": "I'll return at dawn."},
        "N2_19": {"example_sentence": "（（揚）あ）げ（（句）く）のは（は）て（て）に（に）怒り（いかり）ました。", "example_reading": "あげくのはてにおこりました。", "example_meaning_cn": "到头来（最终）还是生气了。", "example_meaning_en": "Finally/in the end, they got angry."},
        "N2_20": {"example_sentence": "（（憧）あこが）れ（れ）の（の）人（ひと）です。", "example_reading": "あこがれのひとです。", "example_meaning_cn": "向往的人。", "example_meaning_en": "They are the person I admire."},
        "N2_21": {"example_sentence": "（（足）あし）あ（（跡）あと）を（を）見（み）て（て）ください。", "example_reading": "あしあとをみてください。", "example_meaning_cn": "请看足迹。", "example_meaning_en": "Please look at the footprints."},
        "N2_22": {"example_sentence": "（（味わう）あじわう）楽しみがあります。", "example_reading": "あじわうたのしみがあります。", "example_meaning_cn": "有品味的乐趣。", "example_meaning_en": "There is a pleasure in savoring it."},
        "N2_23": {"example_sentence": "（（預）あず）かって（て）ください。", "example_reading": "あずかってください。", "example_meaning_cn": "请替我保管。", "example_meaning_en": "Please keep it for me."},
        "N2_24": {"example_sentence": "（（預）あず）けて（て）ください。", "example_reading": "あずけてください。", "example_meaning_cn": "请寄放。", "example_meaning_en": "Please deposit/leave it with me."},
        "N2_25": {"example_sentence": "（（焦）あせ）らない（ない）で（で）ください。", "example_reading": "あせらないでください。", "example_meaning_cn": "请不要焦躁。", "example_meaning_en": "Please don't hurry/panic."},
        "N2_26": {"example_sentence": "あた（（当）た）り（（前）まえ）の（の）こと（こと）です。", "example_reading": "あたりまえのことです。", "example_meaning_cn": "那是理所当然的事情。", "example_meaning_en": "It's a natural/obvious thing."},
        "N2_27": {"example_sentence": "（（当）あ）た（（付）つ）か（か）ず（ず）離れ（はなれ）ず（ず）。", "example_reading": "あたつかずはなれず。", "example_meaning_cn": "不即不离。", "example_meaning_en": "Maintaining a proper distance."},
        "N2_28": {"example_sentence": "（（扱）あつか）って（て）ください。", "example_reading": "あつかってください。", "example_meaning_cn": "请对待（或处理）。", "example_meaning_en": "Please handle/treat it."},
        "N2_29": {"example_sentence": "（（集）あつ）って（て）ください。", "example_reading": "あつまってください。", "example_meaning_cn": "请集合。", "example_meaning_en": "Please gather."},
        "N2_30": {"example_sentence": "（（当）あ）て（（地）じ）ですよ。", "example_reading": "あてじですよ。", "example_meaning_cn": "那是借代字（借字）哦。", "example_meaning_en": "That's a phonetic equivalent (ateji)."},
        "N2_31": {"example_sentence": "（（当）あ）て（（嵌）は）めて（て）ください。", "example_reading": "あてはめてください。", "example_meaning_cn": "请套用（或应用）。", "example_meaning_en": "Please apply/fit it in."},
        "N2_32": {"example_sentence": "（（当）あ）て（（嵌）は）まる（る）例（れい）です。", "example_reading": "あてはまるれいです。", "example_meaning_cn": "适用的例子。", "example_meaning_en": "A case that applies."},
        "N2_33": {"example_sentence": "アドレス（あどれす）を教えてください。", "example_reading": "あどれすをおしえてください。", "example_meaning_cn": "请告诉地址。", "example_meaning_en": "Please tell me the address."},
        "N2_34": {"example_sentence": "（（暴）あば）れない（ない）で（で）ください！ ", "example_reading": "あばれないでください！", "example_meaning_cn": "请不要胡闹（或施暴）！", "example_meaning_en": "Please don't act violently/struggle!"},
        "N2_35": {"example_sentence": "（（脂）あぶら）っこい（こい）ですね。 ", "example_reading": "あぶらっこいですね。", "example_meaning_cn": "真油腻呢。", "example_meaning_en": "It's greasy, isn't it?"},
        "N2_36": {"example_sentence": "（（甘）あま）か（（噛）が）み（み）し（し）ます。", "example_reading": "あまがみします。", "example_meaning_cn": "（宠物等）撒娇似地咬。", "example_meaning_en": "Playful biting (nipping)."},
        "N2_37": {"example_sentence": "ア（あ）マ（ま）チ（ち）ュ（ゅ）ア（あ）です。", "example_reading": "あまちゅあです。", "example_meaning_cn": "是业余爱好者。", "example_meaning_en": "I'm an amateur."},
        "N2_38": {"example_sentence": "（（雨）あま）ど（（具）ぐ）を（を）持（も）って（て）ください。", "example_reading": "あまぐをもってください。", "example_meaning_cn": "请带好雨具。", "example_meaning_en": "Please bring rain gear."},
        "N2_39": {"example_sentence": "（（編）あ）んで（て）ください。", "example_reading": "あんでください。", "example_meaning_cn": "请编织。", "example_meaning_en": "Please knit/braid it."},
        "N2_40": {"example_sentence": "（（危）あやう）い（い）ところ（ところ）でした。", "example_reading": "あやういところでした。", "example_meaning_cn": "刚才太危险了（千钧一发）。", "example_meaning_en": "That was a close call."},
        "N2_41": {"example_sentence": "（（怪）あや）しい（しい）人（ひと）です。", "example_reading": "あやしいひとです。", "example_meaning_cn": "是个可疑的人。", "example_meaning_en": "They are a suspicious person."},
        "N2_42": {"example_sentence": "（（荒）あら）い（い）ですね。 ", "example_reading": "あらいですね。", "example_meaning_cn": "很粗鲁（或波涛汹涌）呢。", "example_meaning_en": "It's rough, isn't it?"},
        "N2_43": {"example_sentence": "（（粗）あら）い（い）ですね。 ", "example_reading": "あらいですね。", "example_meaning_cn": "真粗糙（或颗粒大）呢。", "example_meaning_en": "It's coarse, isn't it?"},
        "N2_44": {"example_sentence": "あら（（嵐）あらし）が来ました。", "example_reading": "あらしがきました。", "example_meaning_cn": "暴风雨来了。", "example_meaning_en": "A storm has come."},
        "N2_45": {"example_sentence": "あら（（粗）あら）す（す）じ（じ）を（を）読（よ）んで（て）ください。", "example_reading": "あらすじをよんでください。", "example_meaning_cn": "请看梗概（情节大意）。", "example_meaning_en": "Please read the summary/plot."},
        "N2_46": {"example_sentence": "あら（（争）あらそ）い（い）を（を）止め（とめ）て（て）ください。", "example_reading": "あらそいをとめてください。", "example_meaning_cn": "请停止争斗。", "example_meaning_en": "Please stop the conflict."},
        "N2_47": {"example_sentence": "（（新）あら）た（（新）た）に（に）始め（はじめ）ましょう。", "example_reading": "あらたにはじめましょう。", "example_meaning_cn": "重新开始吧。", "example_meaning_en": "Let's start anew."},
        "N2_48": {"example_sentence": "（（改）あらた）めて（て）会い（あい）ましょう。", "example_reading": "あらためてあいましょう。", "example_meaning_cn": "改天（或再次）见吧。", "example_meaning_en": "Let's meet again/another time."},
        "N2_49": {"example_sentence": "（（改）あらた）める（る）点（てん）が（が）あります。", "example_reading": "あらためるてんがあります。", "example_meaning_cn": "有需要改进的地方。", "example_meaning_en": "There are points to be improved."},
        "N2_50": {"example_sentence": "（（著）あらわ）して（て）います。", "example_reading": "あらわしています。", "example_meaning_cn": "著作（或表现）着。", "example_meaning_en": "It expresses/is written by."},
        "N2_51": {"example_sentence": "（（有）あ）り（（難）がた）い（い）です。", "example_reading": "ありがたいです。", "example_meaning_cn": "感激不尽。", "example_meaning_en": "I'm grateful/thankful."},
        "N2_52": {"example_sentence": "（（在）あ）り（（得）う）る（る）話（はなし）です。", "example_reading": "ありうるはなしです。", "example_meaning_cn": "是有可能发生（存在）的话题。", "example_meaning_en": "It's a possible story."},
        "N2_53": {"example_sentence": "アルカリ（あるかり）性（せい）です。", "example_reading": "あるかりせいです。", "example_meaning_cn": "是碱性的。", "example_meaning_en": "It's alkaline."},
        "N2_54": {"example_sentence": "アルコール（あるこーる）はありますか。", "example_reading": "あるこーるはありますか。", "example_meaning_cn": "有酒精（或酒）吗？", "example_meaning_en": "Is there any alcohol?"},
        "N2_55": {"example_sentence": "ア（あ）ル（る）バ（ば）ム（む）を見（み）て（て）ください。", "example_reading": "アルバムをみてください。", "example_meaning_cn": "请看相册（或专辑）。", "example_meaning_en": "Please look at the album."},
        "N2_56": {"example_sentence": "ア（あ）ル（る）ミ（み）で作られ（つくられ）て（て）います。", "example_reading": "アルミでつくられています。", "example_meaning_cn": "由铝制造。", "example_meaning_en": "It is made of aluminum."},
        "N2_57": {"example_sentence": "（（泡）あわ）を（を）立て（たて）て（て）ください。", "example_reading": "あわをたててください。", "example_meaning_cn": "请起泡。", "example_meaning_en": "Please lather it up."},
        "N2_58": {"example_sentence": "（（合）あ）わせ（せ）て（て）ください。", "example_reading": "あわせてください。", "example_meaning_cn": "请配合（或合计）。", "example_meaning_en": "Please combine/align them."},
        "N2_59": {"example_sentence": "（（慌）あわ）て（て）ない（ない）で（で）ください。", "example_reading": "あわてないでください。", "example_meaning_cn": "请不要慌张。", "example_meaning_en": "Please don't panic."},
        "N2_60": {"example_sentence": "（（哀）あわ）れ（れ）ですね。 ", "example_reading": "あわれですね。", "example_meaning_cn": "真可怜（或哀愁）呢。", "example_meaning_en": "How pitiful."},
        "N2_61": {"example_sentence": "（（案）あん）を（を）出し（だし）て（て）ください。", "example_reading": "あんをだしてください。", "example_meaning_cn": "请提出方案。", "example_meaning_en": "Please propose a plan."},
        "N2_62": {"example_sentence": "（（暗）あん）き（き）し（し）て（て）ください。", "example_reading": "あんきしてください。", "example_meaning_cn": "请背诵（记在心里）。", "example_meaning_en": "Please memorize it."},
        "N2_63": {"example_sentence": "アンケート（あんけーと）に答え（こたえ）て（て）ください。", "example_reading": "アンケートにこたえてください。", "example_meaning_cn": "请回答问卷。", "example_meaning_en": "Please answer the questionnaire."},
        "N2_64": {"example_sentence": "アンテナ（あんてな）を立て（たて）て（て）ください。", "example_reading": "アンテナをたててください。", "example_meaning_cn": "请架起天线。", "example_meaning_en": "Please set up the antenna."},
        "N2_65": {"example_sentence": "（（暗）あん）に（に）示し（しめし）て（て）います。", "example_reading": "あんにしめしています。", "example_meaning_cn": "暗示着（或在暗处暗示）。", "example_meaning_en": "It's implying it implicitly."},
        "N2_66": {"example_sentence": "（（胃）い）が痛い（いたい）です。", "example_reading": "いがいたいです。", "example_meaning_cn": "胃疼。", "example_meaning_en": "My stomach hurts."},
        "N2_67": {"example_sentence": "いい（いい）考え（かんがえ）ですね！", "example_reading": "いいかんがえですね！", "example_meaning_cn": "好主意（好想法）呢！", "example_meaning_en": "That's a good idea!"},
        "N2_68": {"example_sentence": "（（言）い）い（い）訳（わけ）を（を）し（し）ないで（で）ください。", "example_reading": "いいわけをしないでください。", "example_meaning_cn": "请不要找借口。", "example_meaning_en": "Please don't make excuses."},
        "N2_69": {"example_sentence": "（（家）いえ）に（に）帰り（かえり）ましょう。", "example_reading": "いえにかえりましょう。", "example_meaning_cn": "回家吧。", "example_meaning_en": "Let's go home."},
        "N2_70": {"example_sentence": "（（委）い）いん（いん）会（かい）に（に）出席（しゅっせき）し（し）ます。", "example_reading": "いいんかいにしゅっせきします。", "example_meaning_cn": "出席委员会。", "example_meaning_en": "I'll attend the committee meeting."},
        "N2_71": {"example_sentence": "（（言）い）う（う）こと（こと）を（を）聞い（きい）て（て）ください。", "example_reading": "いうことをきいてください。", "example_meaning_cn": "请听话。", "example_meaning_en": "Please listen to what I say."},
        "N2_72": {"example_sentence": "（（言）い）わ（わ）ば（ば）...", "example_reading": "いわば。", "example_meaning_cn": "说起来（比如）...", "example_meaning_en": "So to speak..."},
        "N2_73": {"example_sentence": "（（医）い）が（（学）がく）を（を）志し（こころざし）ます。", "example_reading": "いがくをこころざします。", "example_meaning_cn": "立志从医（医学）。", "example_meaning_en": "I aspire to study medicine."},
        "N2_74": {"example_sentence": "（（生）い）き（き）がい（がい）が（が）あり（あり）ます。", "example_reading": "いきがいがあります。", "example_meaning_cn": "有生存的价值（人生的意义）。", "example_meaning_en": "Life is worth living."},
        "N2_75": {"example_sentence": "いき（（息）いき）を（を）止め（とめ）て（て）ください！ ", "example_reading": "いきをとめてください！", "example_meaning_cn": "请屏住呼吸！", "example_meaning_en": "Please hold your breath!"},
        "N2_76": {"example_sentence": "いき（（意）い）き（き）し（し）て（て）いますね！", "example_reading": "いきいきしていますね！", "example_meaning_cn": "真有活力呢！", "example_meaning_en": "How lively/vibrant!"},
        "N2_77": {"example_sentence": "いき（（勢）いき）おい（おい）が（が）あり（あり）ます。", "example_reading": "いきおいがあります。", "example_meaning_cn": "有气势。", "example_meaning_en": "It has momentum/power."},
        "N2_78": {"example_sentence": "いき（（行）い）き（き）帰り（かえり）ます。", "example_reading": "いきかえります。", "example_meaning_cn": "往返。", "example_meaning_en": "Going to and fro."},
        "N2_79": {"example_sentence": "（（幾）いく）つ（つ）か（か）あり（あり）ます。", "example_reading": "いくつかあります。", "example_meaning_cn": "有几个。", "example_meaning_en": "There are several."},
        "N2_80": {"example_sentence": "（（育）いく）じ（じ）に（に）奮闘（ふんとう）中（ちゅう）です。", "example_reading": "いくじにふんとうちゅうです。", "example_meaning_cn": "正在奋斗育儿。", "example_meaning_en": "I'm struggling with childcare now."},
        "N2_81": {"example_sentence": "（（幾）いく）ぶん（ぶん）か（か）良（よ）くなり（なり）まし（し）た。", "example_reading": "いくぶんかよくなりました。", "example_meaning_cn": "好转了一些。", "example_meaning_en": "It has improved somewhat."},
        "N2_82": {"example_sentence": "（（生）い）け（け）ば（ば）な（な）を（を）習い（ならい）ます。", "example_reading": "いけばなをならいます。", "example_meaning_cn": "学习插花（生花）。", "example_meaning_en": "I study flower arrangement."},
        "N2_83": {"example_sentence": "（（意）い）じ（じ）を（を）張ら（はら）ないで（で）ください。", "example_reading": "いじをはらないでください。", "example_meaning_cn": "不要倔强（或固执）。", "example_meaning_en": "Don't be stubborn."},
        "N2_84": {"example_sentence": "（（意）い）し（じ）を（を）継い（つい）で（て）ください。", "example_reading": "いじをついでください。", "example_meaning_cn": "请继志。", "example_meaning_en": "Please carry on the legacy/will."},
        "N2_85": {"example_sentence": "（（意）い）識（しき）が（が）はっきり（はっきり）し（し）ます。", "example_reading": "いしきがはっきりします。", "example_meaning_cn": "意识清醒。", "example_meaning_en": "I'm conscious/clear-headed."},
        "N2_86": {"example_sentence": "（（衣）い）食（しょく）に（に）不（ふ）自由（じゆう）あり（あり）ません。", "example_reading": "いしょくにふじゆうありません。", "example_meaning_cn": "衣食无忧。", "example_meaning_en": "I have no lack of food and clothing."},
        "N2_87": {"example_sentence": "（（意）い）じ（じ）り（り）ます。", "example_reading": "いじります。", "example_meaning_cn": "摆弄（或戏弄）。", "example_meaning_en": "I'll fiddle with/tease it."},
        "N2_88": {"example_sentence": "（（意）い）ず（ず）れ（れ）会い（あい）ましょう。", "example_reading": "いずれあいましょう。", "example_meaning_cn": "总有一天（或迟早）见个面吧。", "example_meaning_en": "Let's meet eventually/some day."},
        "N2_89": {"example_sentence": "（（意）い）せい（せい）が（が）いい（いい）ですね。", "example_reading": "いせいがいいですね。", "example_meaning_cn": "真有精神呢（威势）。", "example_meaning_en": "You're full of spirit, aren't you?"},
        "N2_90": {"example_sentence": "（（意）い）ぜん（ぜん）として（て）変わり（かわり）ません。", "example_reading": "いぜんとしてかわりません。", "example_meaning_cn": "依然如故。", "example_meaning_en": "It remains unchanged as before."},
        "N2_91": {"example_sentence": "（（意）い）ぞん（ぞん）し（し）ないで（で）ください。", "example_reading": "いぞんしないでください。", "example_meaning_cn": "请不要依赖（或依存）。", "example_meaning_en": "Please don't depend on it."},
        "N2_92": {"example_sentence": "（（板）いた）を（を）切っ（きっ）て（て）ください。", "example_reading": "いたをきってください。", "example_meaning_cn": "请切开木板。", "example_meaning_en": "Please cut the board."},
        "N2_93": {"example_sentence": "（（偉）い）だい（だい）な（な）人（ひと）です。", "example_reading": "いだいなひとです。", "example_meaning_cn": "伟大的人。", "example_meaning_en": "A great person."},
        "N2_94": {"example_sentence": "（（抱）いた）い（い）て（て）ください。", "example_reading": "いだいてください。", "example_meaning_cn": "请抱着（或怀有）。", "example_meaning_en": "Please embrace it/hold a feeling."},
        "N2_95": {"example_sentence": "いたずら（いたずら）し（し）ないで（で）ください。", "example_reading": "いたずらしないでください。", "example_meaning_cn": "请不要恶作剧（或调皮）。", "example_meaning_en": "Please don't play pranks."},
        "N2_96": {"example_sentence": "いた（（頂）いた）き（き）ます。", "example_reading": "いただきます。", "example_meaning_cn": "我开动了（谦语）。", "example_meaning_en": "I'll eat/receive it (humble)."},
        "N2_97": {"example_sentence": "（（至）いた）る（る）場所（ばしょ）に（に）あり（あり）ます。", "example_reading": "いたるばしょにあります。", "example_meaning_cn": "到处（无所不在）都有。", "example_meaning_en": "It's everywhere."},
        "N2_98": {"example_sentence": "（（市）いち）ば（ば）へ（へ）行き（いき）ましょう。", "example_reading": "いちばへいきましょう。", "example_meaning_cn": "去市场吧。", "example_meaning_en": "Let's go to the market."},
        "N2_99": {"example_sentence": "（（一）いち）おう（おう）報告（ほうこく）し（し）ます。", "example_reading": "いちおうほうこくします。", "example_meaning_cn": "姑且报告一下。", "example_meaning_en": "I'll report just in case/for now."},
        "N2_100": {"example_sentence": "（（一）いち）じ（じ）に（に）始め（はじめ）ましょう。", "example_reading": "いちじにはじめましょう。", "example_meaning_cn": "一点钟开始吧。", "example_meaning_en": "Let's start at one o'clock."},
        "N2_101": {"example_sentence": "（（一）いち）だんと（と）寒く（さむく）なり（なり）まし（し）た。", "example_reading": "いちだんとさむくなりました。", "example_meaning_cn": "更加冷了（更进一层）。", "example_meaning_en": "It has become even colder."},
        "N2_102": {"example_sentence": "（（一）いち）ち（ち）に（に）三（さん）歩（ぽ）。 ", "example_reading": "いちににさんぽ。", "example_meaning_cn": "第一是三步（喻指踏实）。", "example_meaning_en": "One, two, three steps."},
        "N2_103": {"example_sentence": "（（一）いち）ど（ど）に（に）来（き）ないで（で）ください。", "example_reading": "いちどにこないでください。", "example_meaning_cn": "请不要一下子全过来。", "example_meaning_en": "Please don't all come at once."},
        "N2_104": {"example_sentence": "（（一）いち）ば（ば）ん（ん）好き（すき）です。", "example_reading": "いちばんすきです。", "example_meaning_cn": "最喜欢了。", "example_meaning_en": "I like it the most."},
        "N2_105": {"example_sentence": "（（一）いつ）か（か）会い（あい）ましょう。", "example_reading": "いつかあいましょう。", "example_meaning_cn": "总有一天见个面吧。", "example_meaning_en": "Let's meet some day."},
        "N2_106": {"example_sentence": "（（一）いっ）か（か）に（に）一台（いちだい）。 ", "example_reading": "いっかにいちだい。", "example_meaning_cn": "一户一台（喻普及）。", "example_meaning_en": "One per household."},
        "N2_107": {"example_sentence": "いっ（（一）いっ）せいに（に）始め（はじめ）て（て）ください。", "example_reading": "いっせいにはじめてください。", "example_meaning_cn": "请齐声开始。", "example_meaning_en": "Please start all at once."},
        "N2_108": {"example_sentence": "いっ（（一）いっ）そう（そう）努力（どりょく）し（し）ます。", "example_reading": "いっそうどりょくします。", "example_meaning_cn": "越发（更加）努力。", "example_meaning_en": "I'll work even harder."},
        "N2_109": {"example_sentence": "（（一）いっ）たい（たい）何（なに）です（す）か。", "example_reading": "いったいなんですか。", "example_meaning_cn": "到底是什么？", "example_meaning_en": "What on earth is it?"},
        "N2_110": {"example_sentence": "（（一）いっ）ち（ち）し（し）て（て）いますね。", "example_reading": "いっちしていますね。", "example_meaning_cn": "心往一处使（一致）呢。", "example_meaning_en": "They are in agreement/unanimous."},
        "N2_111": {"example_sentence": "いっ（（一）いっ）て（て）み（み）れば（ば）...", "example_reading": "いってみれば。", "example_meaning_cn": "说起来（比如）...", "example_meaning_en": "If I were to say/so to speak..."},
        "N2_112": {"example_sentence": "いっ（（一）いっ）ぱい（ぱい）食べ（たべ）て（て）ください。", "example_reading": "いっぱいたべてください。", "example_meaning_cn": "请尽情吃（吃撑）。", "example_meaning_en": "Please eat your fill/a lot."},
        "N2_113": {"example_sentence": "いっ（（一）いっ）ぺんに（に）片（かた）付け（づけ）まし（し）た。", "example_reading": "いっぺんにかたづけました。", "example_meaning_cn": "一下子收拾好了。", "example_meaning_en": "I cleaned it all up at once."},
        "N2_114": {"example_sentence": "いと（（糸）いと）を（を）引い（ひい）て（て）ください。", "example_reading": "いとをひいてください。", "example_meaning_cn": "请拉线（或藕断丝连）。", "example_meaning_en": "Please pull the thread."},
        "N2_115": {"example_sentence": "（（意）い）と（と）を（を）説明（せつめい）し（し）て（て）ください。", "example_reading": "いとをせつめいしてください。", "example_meaning_cn": "请说明意图。", "example_meaning_en": "Please explain your intention."},
        "N2_116": {"example_sentence": "（（暇）いとま）が（が）ありません。", "example_reading": "いとまがありません。", "example_meaning_cn": "没有闲暇（或没时间）。", "example_meaning_en": "I have no leisure time/no time."},
        "N2_117": {"example_sentence": "いとな（（営）いとな）み（み）が（が）あり（あり）ます。", "example_reading": "いとなみがあります。", "example_meaning_cn": "有业务（或生活忙碌）。", "example_meaning_en": "There is a business/activity."},
        "N2_118": {"example_sentence": "（（居）い）ない（ない）で（で）ください。", "example_reading": "いないでください。", "example_meaning_cn": "请不要在里头（不在）。", "example_meaning_en": "Please don't be there/stay out."},
        "N2_119": {"example_sentence": "（（田）い）な（なか）へ（へ）帰り（かえり）ます。", "example_reading": "いなかへかえります。", "example_meaning_cn": "回乡下（农村）。", "example_meaning_en": "I'm going back to the countryside."},
        "N2_120": {"example_sentence": "（（稲）いね）を（を）刈り（かり）ます。", "example_reading": "いねをかります。", "example_meaning_cn": "割稻子。", "example_meaning_en": "I harvest the rice."},
        "N2_121": {"example_sentence": "（（居）い）ね（ね）むり（むり）し（し）ないで（で）ください。", "example_reading": "いねむりしないでください。", "example_meaning_cn": "请不要打瞌睡。", "example_meaning_en": "Please don't doze off."},
        "N2_122": {"example_sentence": "（（命）いのち）を（を）大切（たいせつ）に（に）し（し）ましょう。", "example_reading": "いのちをたいせつにしましょう。", "example_meaning_cn": "珍惜生命吧。", "example_meaning_en": "Let's cherish life."},
        "N2_123": {"example_sentence": "（（祈）いの）って（て）ください。", "example_reading": "いのってください。", "example_meaning_cn": "请祈祷。", "example_meaning_en": "Please pray."},
        "N2_124": {"example_sentence": "いば（（威）いば）ら（ら）ないで（で）ください。", "example_reading": "いばらないでください。", "example_meaning_cn": "请不要自大（或摆架子）。", "example_meaning_en": "Please don't be arrogant/bossy."},
        "N2_125": {"example_sentence": "（（嫌）いや）な（な）ことは（は）し（し）ません。", "example_reading": "いやなことはしません。", "example_meaning_cn": "不做讨厌的事情。", "example_meaning_en": "I won't do what I dislike."},
        "N2_126": {"example_sentence": "（（嫌）いや）いや（いや）やって（て）います。", "example_reading": "いやいややっています。", "example_meaning_cn": "勉勉强强（极不情愿）地做着。", "example_meaning_en": "I'm doing it reluctantly."},
        "N2_127": {"example_sentence": "（（癒）い）や（や）し（し）を（を）求め（もとめ）て（て）います。", "example_reading": "いやしをもとめています。", "example_meaning_cn": "正在寻求治愈。", "example_meaning_en": "I'm seeking healing."},
        "N2_128": {"example_sentence": "いらん（いらん）お（お）世話（せわ）です。", "example_reading": "いらんおせわです。", "example_meaning_cn": "狗咬吕洞宾（多管闲事）。", "example_meaning_en": "It's none of your business."},
        "N2_129": {"example_sentence": "（（煎）い）っ（っ）て（て）ください。", "example_reading": "いってください。", "example_meaning_cn": "请炒（或煎）。", "example_meaning_en": "Please roast/pan-fry it."},
        "N2_130": {"example_sentence": "（（衣）い）類（るい）を（を）整理（せいり）し（し）ます。", "example_reading": "いるいをせいりします。", "example_meaning_cn": "整理衣类。", "example_meaning_en": "I'll organize the clothing."},
        "N2_131": {"example_sentence": "（（色）いろ）々（いろ）（（有）あ）り（（難）がた）う（う）。 ", "example_reading": "いろいろありがとう。", "example_meaning_cn": "多谢了。", "example_meaning_en": "Thanks for everything."},
        "N2_132": {"example_sentence": "（（岩）いわ）に（に）登り（のぼり）ます。", "example_reading": "いわにのぼります。", "example_meaning_cn": "攀岩。", "example_meaning_en": "I climb the rock."},
        "N2_133": {"example_sentence": "（（祝）いわ）い（い）を（を）し（し）ましょう。", "example_reading": "いわいをしましょう。", "example_meaning_cn": "庆祝一下吧。", "example_meaning_en": "Let's celebrate."},
        "N2_134": {"example_sentence": "（（言）い）わ（わ）ず（ず）も（も）が（が）な（な）。 ", "example_reading": "いわずもがな。", "example_meaning_cn": "不言而喻（多此一语）。", "example_meaning_en": "Needless to say/better left unsaid."},
        "N2_135": {"example_sentence": "（（祝）いわ）って（て）ください。", "example_reading": "いわってください。", "example_meaning_cn": "请庆祝（或祝贺）。", "example_meaning_en": "Please celebrate."},
        "N2_136": {"example_sentence": "イン（いん）ク（く）が（が）出（で）ません。", "example_reading": "インクがでません。", "example_meaning_cn": "不出墨水。", "example_meaning_en": "The ink won't come out."},
        "N2_137": {"example_sentence": "（（印）いん）さ（さ）つ（つ）し（し）て（て）ください。", "example_reading": "いんさつしてください。", "example_meaning_cn": "请打印。", "example_meaning_en": "Please print it."},
        "N2_138": {"example_sentence": "イ（い）ン（ん）シ（し）ュ（ゅ）リ（り）ン（ん）を（を）打ち（うち）ます。", "example_reading": "インシュリンをうちます。", "example_meaning_cn": "打胰岛素。", "example_meaning_en": "Administering insulin."},
        "N2_139": {"example_sentence": "イ（い）ン（ん）フ（ふ）レ（れ）が（が）進ん（すすん）で（て）います。", "example_reading": "インフレがすすんでいます。", "example_meaning_cn": "通货膨胀正在加剧。", "example_meaning_en": "Inflation is progressing."},
        "N2_140": {"example_sentence": "（（引）いん）た（た）い（い）を（を）表明（ひょうめい）し（し）まし（し）た。", "example_reading": "いんたいをひょうめいしました。", "example_meaning_cn": "表明引退（退役）。", "example_meaning_en": "Announced retirement."},
        "N2_141": {"example_sentence": "（（陰）いん）に（に）陽（よう）に（に）助け（たすけ）て（て）ください。", "example_reading": "いんによにたすけてください。", "example_meaning_cn": "请在明里暗里都帮帮我。", "example_meaning_en": "Please help me in every possible way."},
        "N2_142": {"example_sentence": "（（引）いん）用（よう）し（し）て（て）ください。", "example_reading": "いんようしてください。", "example_meaning_cn": "请引用。", "example_meaning_en": "Please quote/cite it."},
        "N2_143": {"example_sentence": "（（引）いん）力（りょく）が（が）働い（はたらい）て（て）います。", "example_reading": "いんりょくがはたらいています。", "example_meaning_cn": "引力正在起作用。", "example_meaning_en": "Gravity is at work."},
        "N2_144": {"example_sentence": "（（上）うえ）を（を）見（み）て（て）ください。", "example_reading": "うえをみてください。", "example_meaning_cn": "请看上面。", "example_meaning_en": "Please look up."},
        "N2_145": {"example_sentence": "（（植）う）えて（て）ください。", "example_reading": "うえてください。", "example_meaning_cn": "请种植。", "example_meaning_en": "Please plant it."},
        "N2_146": {"example_sentence": "（（飢）う）えて（て）います。", "example_reading": "うえています。", "example_meaning_cn": "正饥渴（或饥饿）着呢。", "example_meaning_en": "I'm starving/hungry for it."},
        "N2_147": {"example_sentence": "（（魚）うお）を（を）釣り（つり）ます。", "example_reading": "うおをつります。", "example_meaning_cn": "钓鱼（鱼类）。", "example_meaning_en": "I'll catch a fish."},
        "N2_148": {"example_sentence": "う（（伺）うか）い（い）まし（し）た。", "example_reading": "うかがいました。", "example_meaning_cn": "打听到了（或拜访了）。", "example_meaning_en": "I've heard/visited (humble)."},
        "N2_149": {"example_sentence": "う（（浮）う）か（か）べて（て）ください。", "example_reading": "うかべてください。", "example_meaning_cn": "请让它浮起来（或想起）。", "example_meaning_en": "Please float it/call to mind."},
        "N2_150": {"example_sentence": "う（（承）うけたまわ）り（り）まし（し）た。", "example_reading": "うけたまわりました。", "example_meaning_cn": "谨领（领教了）。", "example_meaning_en": "I have received your request (humble)."}
    }

    for item in vocab:
        if item['id'] in enrichment:
            item.update(enrichment[item['id']])

    with open(data_file, 'w', encoding='utf-8') as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

    print(f"Updated items up to N2_150.")

if __name__ == "__main__":
    main()
