import json
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    data_file = os.path.join(project_root, 'jlpt-web', 'src', 'data', 'vocab.json')

    if not os.path.exists(data_file):
        return

    with open(data_file, 'r', encoding='utf-8') as f:
        vocab = json.load(f)

    enrichment = {
        "N3_751": {"example_sentence": "じょ（女）性（せい）の方はあちらです。", "example_reading": "じょせいのほうはあちらです。", "example_meaning_cn": "女士在这边。", "example_meaning_en": "Women are over there."},
        "N3_752": {"example_sentence": "じょ（徐）々（じょ）に良くなります。", "example_reading": "じょじょによくなります。", "example_meaning_cn": "会渐渐好起来的。", "example_meaning_en": "It will gradually get better."},
        "N3_753": {"example_sentence": "（知）ってください。", "example_reading": "しってください。", "example_meaning_cn": "请了解（或知道）。", "example_meaning_en": "Please know/be aware of it."},
        "N3_754": {"example_sentence": "し（（退）ぞ）いてください。", "example_reading": "しりぞいてください。", "example_meaning_cn": "请退后（或引退）。", "example_meaning_en": "Please step back/withdraw."},
        "N3_755": {"example_sentence": "（知）り合いに会いました。", "example_reading": "しりあいにあいました。", "example_meaning_cn": "见到了熟人。", "example_meaning_en": "I met an acquaintance."},
        "N3_756": {"example_sentence": "し（資料）料（りょう）を読んでください。", "example_reading": "しりょうをよんでください。", "example_meaning_cn": "请看资料。", "example_meaning_en": "Please read the documents."},
        "N3_757": {"example_sentence": "しる（汁）を飲んでください。", "example_reading": "しるをのんでください。", "example_meaning_cn": "请喝汤（或汁）。", "example_meaning_en": "Please drink the soup/juice."},
        "N3_758": {"example_sentence": "し（白）い服が好きです。", "example_reading": "しろいふくがすきです。", "example_meaning_cn": "喜欢白色衣服。", "example_meaning_en": "I like white clothes."},
        "N3_759": {"example_sentence": "（城）へ行きます。", "example_reading": "しろへいきます。", "example_meaning_cn": "去城堡。", "example_meaning_en": "I'm going to the castle."},
        "N3_760": {"example_sentence": "じ（素）人（ろうと）ではありません。", "example_reading": "しろうとではありません。", "example_meaning_cn": "不是外行（非专业人士）。", "example_meaning_en": "I'm not an amateur."},
        "N3_761": {"example_sentence": "（皺）を伸ばしてください。", "example_reading": "しわをのばしてください。", "example_meaning_cn": "请抚平皱纹。", "example_meaning_en": "Please smooth out the wrinkles."},
        "N3_762": {"example_sentence": "しん（新）しい服を買いました。", "example_reading": "あたらしいふくをかいました。", "example_meaning_cn": "买了新衣服。", "example_meaning_en": "I bought new clothes."},
        "N3_763": {"example_sentence": "しん（心）理（り）学（がく）を勉強します。", "example_reading": "しんりがくをべんきょうします。", "example_meaning_cn": "学习心理学。", "example_meaning_en": "I study psychology."},
        "N3_764": {"example_sentence": "しん（親）切（せつ）にしてください。", "example_reading": "しんせつにしてください。", "example_meaning_cn": "请亲切待人。", "example_meaning_en": "Please be kind."},
        "N3_765": {"example_sentence": "しん（真）実（じつ）を話してください。", "example_reading": "しんじつをはなしてください。", "example_meaning_cn": "请说出真相。", "example_meaning_en": "Please tell the truth."},
        "N3_766": {"example_sentence": "しん（信）じています。", "example_reading": "しんじています。", "example_meaning_cn": "相信着。", "example_meaning_en": "I believe you."},
        "N3_767": {"example_sentence": "じん（人）生（せい）を楽しみましょう。", "example_reading": "じんせいをたのしみましょう。", "example_meaning_cn": "享受人生吧。", "example_meaning_en": "Let's enjoy life."},
        "N3_768": {"example_sentence": "しん（心）配（ぱい）しないでください。", "example_reading": "しんぱいしないでください。", "example_meaning_cn": "请不要担心。", "example_meaning_en": "Please don't worry."},
        "N3_769": {"example_sentence": "しん（親）友（ゆう）に会いました。", "example_reading": "しんゆうにあいました。", "example_meaning_cn": "见到了好朋友（亲友）。", "example_meaning_en": "I met my best friend."},
        "N3_770": {"example_sentence": "しん（審）査（さ）してください。", "example_reading": "しんさしてください。", "example_meaning_cn": "请审查。", "example_meaning_en": "Please audit/examine it."},
        "N3_771": {"example_sentence": "しん（新）幹線に乗ります。", "example_reading": "しんかんせんにのります。", "example_meaning_cn": "坐新干线。", "example_meaning_en": "I'll take the Shinkansen."},
        "N3_772": {"example_sentence": "しん（深刻）刻（こく）ですね。 ", "example_reading": "しんこくですね。", "example_meaning_cn": "真深刻（严重）呢。", "example_meaning_en": "It's serious, isn't it?"},
        "N3_773": {"example_sentence": "しん（信号）号（ごう）を守りましょう。", "example_reading": "しんごうをまもりましょう。", "example_meaning_cn": "遵守红绿灯吧。", "example_meaning_en": "Let's obey the traffic light."},
        "N3_774": {"example_sentence": "しん（診）察（さつ）を受けてください。", "example_reading": "しんさつをうけてください。", "example_meaning_cn": "请接受诊察。", "example_meaning_en": "Please have a medical examination."},
        "N3_775": {"example_sentence": "じん（迅速）速（そく）に対応します。", "example_reading": "じんそくにたいおうします。", "example_meaning_cn": "迅速应对。", "example_meaning_en": "I'll respond quickly."},
        "N3_776": {"example_sentence": "しん（慎重）重（ちょう）にしてください。", "example_reading": "しんちょうにしてください。", "example_meaning_cn": "请慎重。", "example_meaning_en": "Please be cautious."},
        "N3_777": {"example_sentence": "しん（進入）入（にゅう）禁止です。", "example_reading": "しんにゅうきんしです。", "example_meaning_cn": "禁止进入。", "example_meaning_en": "Entry is prohibited."},
        "N3_778": {"example_sentence": "しん（信頼）頼（らい）しています。", "example_reading": "しんらいしています。", "example_meaning_cn": "信任着。", "example_meaning_en": "I trust you."},
        "N3_779": {"example_sentence": "しん（森林）林を歩きます。", "example_reading": "しんりんをあるきます。", "example_meaning_cn": "在森林里走走。", "example_meaning_en": "I'll walk in the forest."},
        "N3_780": {"example_sentence": "しん（親睦）睦（ぼく）を深めましょう。", "example_reading": "しんぼくをふかめましょう。", "example_meaning_cn": "加深友谊吧。", "example_meaning_en": "Let's deepen our friendship."},
        "N3_781": {"example_sentence": "しん（進歩）歩（ぽ）しましたね！", "example_reading": "しんぽしましたね！", "example_meaning_cn": "进步了呢！", "example_meaning_en": "You've progressed, haven't you!"},
        "N3_782": {"example_sentence": "しん（心房）房（ぼう）が震えています。", "example_reading": "しんぼうがふるえています。", "example_meaning_cn": "心房在震颤。", "example_meaning_en": "The atrium is vibrating."},
        "N3_783": {"example_sentence": "す（酢）をかけてください。", "example_reading": "すをかけてください。", "example_meaning_cn": "请加点醋。", "example_meaning_en": "Please add some vinegar."},
        "N3_784": {"example_sentence": "（吸）ってください。", "example_reading": "すってください。", "example_meaning_cn": "请吸（或抽烟）。", "example_meaning_en": "Please inhale/smoke."},
        "N3_785": {"example_sentence": "（図）に描いてください。", "example_reading": "ずにかいてください。", "example_meaning_cn": "请画在图上。", "example_meaning_en": "Please draw it on the diagram."},
        "N3_786": {"example_sentence": "すい（推薦）薦（せん）状を書いてください。", "example_reading": "すいせんじょうをかいてください。", "example_meaning_cn": "请写推荐信。", "example_meaning_en": "Please write a recommendation letter."},
        "N3_787": {"example_sentence": "すい（水曜）曜日（び）は休みです。", "example_reading": "すいようびはやすみです。", "example_meaning_cn": "周三休息。", "example_meaning_en": "Wednesday is a holiday."},
        "N3_788": {"example_sentence": "すい（睡眠）眠を摂ってください。", "example_reading": "すいみんをとってください。", "example_meaning_cn": "请保持睡眠。", "example_meaning_en": "Please get some sleep."},
        "N3_789": {"example_sentence": "すい（垂直）直に立ててください。", "example_reading": "すいちょくにたててください。", "example_meaning_cn": "请垂直立起来。", "example_meaning_en": "Please stand it vertically."},
        "N3_790": {"example_sentence": "すい（推定）定（てい）してください。", "example_reading": "すいていしてください。", "example_meaning_cn": "请推定（或估算）。", "example_meaning_en": "Please estimate it."},
        "N3_791": {"example_sentence": "すい（（透）す）いていますね。", "example_reading": "すいていますね。", "example_meaning_cn": "（肚子）空了（或路人少）呢。", "example_meaning_en": "It's empty/less crowded, isn't it?"},
        "N3_792": {"example_sentence": "（過）ぎてしまいました。", "example_reading": "すぎてしまいました。", "example_meaning_cn": "已经过了。", "example_meaning_en": "It's already past."},
        "N3_793": {"example_sentence": "（好）きなものを食べてください。", "example_reading": "すきなものをたべてください。", "example_meaning_cn": "请吃喜欢的东西。", "example_meaning_en": "Please eat what you like."},
        "N3_794": {"example_sentence": "（空）いていますか。", "example_reading": "すいていますか。", "example_meaning_cn": "有空吗？", "example_meaning_en": "Is it vacant/Are you free?"},
        "N3_795": {"example_sentence": "（掬）ってください。", "example_reading": "すくってください。", "example_meaning_cn": "请舀（或捧）。", "example_meaning_en": "Please scoop/ladle it."},
        "N3_796": {"example_sentence": "（救）ってください！ ", "example_reading": "たすけてください！", "example_meaning_cn": "请救救我！", "example_meaning_en": "Please save me!"},
        "N3_797": {"example_sentence": "す（優）れている点があります。", "example_reading": "すぐれているてんがあります。", "example_meaning_cn": "有优秀的点。", "example_meaning_en": "There are some excellent points."},
        "N3_798": {"example_sentence": "すぐ（直ぐ）に行きます。", "example_reading": "すぐにいきます。", "example_meaning_cn": "马上就去。", "example_meaning_en": "I'll go right away."},
        "N3_799": {"example_sentence": "すこ（少）し待ってください。", "example_reading": "すこしまってください。", "example_meaning_cn": "请等一会儿。", "example_meaning_en": "Please wait a bit."},
        "N3_800": {"example_sentence": "すご（凄）いですね！", "example_reading": "すごいいですね！", "example_meaning_cn": "太厉害了呢！", "example_meaning_en": "That's amazing!"},
        "N3_801": {"example_sentence": "（過）ごしてください。", "example_reading": "すごしてください。", "example_meaning_cn": "请度过（时间）。", "example_meaning_en": "Please spend (your time)."},
        "N3_802": {"example_sentence": "すこ（健）やかですね。 ", "example_reading": "すこやかですね。", "example_meaning_cn": "真健康端庄呢。", "example_meaning_en": "You're healthy/wholesome, aren't you?"},
        "N3_803": {"example_sentence": "（勧）めてください。", "example_reading": "すすめてください。", "example_meaning_cn": "请推荐（或劝诱）。", "example_meaning_en": "Please recommend/suggest it."},
        "N3_804": {"example_sentence": "（進）めてください。", "example_reading": "すすめてください。", "example_meaning_cn": "请推进。", "example_meaning_en": "Please advance it."},
        "N3_805": {"example_sentence": "すそ（裾）が濡れました。", "example_reading": "すそがぬれました。", "example_meaning_cn": "裤脚（裙撑）湿了。", "example_meaning_en": "The hem got wet."},
        "N3_806": {"example_sentence": "すた（廃）れてしまいました。", "example_reading": "すたれてしまいました。", "example_meaning_cn": "废弃（或过时）了。", "example_meaning_en": "It has become obsolete."},
        "N3_807": {"example_sentence": "スタイル（すたいる）がいいですね。", "example_reading": "スタイルがいいですね。", "example_meaning_cn": "身材（风格）真好呢。", "example_meaning_en": "You have a great figure/style, don't you?"},
        "N3_808": {"example_sentence": "ずつ（頭）痛がします。", "example_reading": "ずつうがします。", "example_meaning_cn": "头疼。", "example_meaning_en": "I have a headache."},
        "N3_809": {"example_sentence": "す（酸）っぱいですね。 ", "example_reading": "すっぱいですね。", "example_meaning_cn": "真酸呢。", "example_meaning_en": "It's sour, isn't it?"},
        "N3_810": {"example_sentence": "すて（捨）ててください。", "example_reading": "すててください。", "example_meaning_cn": "请扔掉。", "example_meaning_en": "Please throw it away."},
        "N3_811": {"example_sentence": "ステキ（素敵）ですね！", "example_reading": "すてきですね！", "example_meaning_cn": "真棒呢（极好）！", "example_meaning_en": "How wonderful!"},
        "N3_812": {"example_sentence": "ストップ（すとっぷ）してください。", "example_reading": "ストップしてください。", "example_meaning_cn": "请停止。", "example_meaning_en": "Please stop."},
        "N3_813": {"example_sentence": "（砂）で遊んでいます。", "example_reading": "すなであそんでいます。", "example_meaning_cn": "正在玩沙子。", "example_meaning_en": "I'm playing in the sand."},
        "N3_814": {"example_sentence": "すなお（素直）ですね。", "example_reading": "すなおですね。", "example_meaning_cn": "真诚实（纯朴）呢。", "example_meaning_en": "You're honest/docile, aren't you?"},
        "N3_815": {"example_sentence": "す（済）ませてください。", "example_reading": "すませてください。", "example_meaning_cn": "请办完（或了结）。", "example_meaning_en": "Please get it over with."},
        "N3_816": {"example_sentence": "す（済）みました。", "example_reading": "すみました。", "example_meaning_cn": "办完了（或结束了）。", "example_meaning_en": "It's done/finished."},
        "N3_817": {"example_sentence": "（住）んでいます。", "example_reading": "すんでいます。", "example_meaning_cn": "住着。", "example_meaning_en": "I live there."},
        "N3_818": {"example_sentence": "（澄）んでいますね。 ", "example_reading": "すんでいますね。", "example_meaning_cn": "（水或空气）很清澈呢。", "example_meaning_en": "It's clear/transparent, isn't it?"},
        "N3_819": {"example_sentence": "すみ（隅）を見てください。", "example_reading": "すみをみてください。", "example_meaning_cn": "请看角落。", "example_meaning_en": "Please look at the corner."},
        "N3_820": {"example_sentence": "（刷）ってください。", "example_reading": "すってください。", "example_meaning_cn": "请印刷（或刷）。", "example_meaning_en": "Please print/brush it."},
        "N3_821": {"example_sentence": "（磨）ってください。", "example_reading": "すってください。", "example_meaning_cn": "请磨（或磨平）。", "example_meaning_en": "Please grind/rub it."},
        "N3_822": {"example_sentence": "する（掏）られました！ ", "example_reading": "すられました！", "example_meaning_cn": "被偷了（扒手）！", "example_meaning_en": "I was pickpocketed!"},
        "N3_823": {"example_sentence": "する（鋭）いですね。 ", "example_reading": "するいですね。", "example_meaning_cn": "真敏锐（或锋利）呢。", "example_meaning_en": "It's sharp/keen, isn't it?"},
        "N3_824": {"example_sentence": "す（座）ってください。", "example_reading": "すわってください。", "example_meaning_cn": "请坐。", "example_meaning_en": "Please sit."},
        "N3_825": {"example_sentence": "ず（寸）断（だん）されました。", "example_reading": "すんだんされました。", "example_meaning_cn": "被寸断（切断）了。", "example_meaning_en": "It was cut into small pieces."},
        "N3_826": {"example_sentence": "せ（背）が高いですね。", "example_reading": "せがたかいですね。", "example_meaning_cn": "个子很高呢。", "example_meaning_en": "You're tall, aren't you?"},
        "N3_827": {"example_sentence": "せい（正解）解です！", "example_reading": "せいかいです！", "example_meaning_cn": "正确！", "example_meaning_en": "That's correct!"},
        "N3_828": {"example_sentence": "せい（性格）格が良いですね。", "example_reading": "せいかくがいいですね。", "example_meaning_cn": "性格很好呢。", "example_meaning_en": "You have a good personality, don't you?"},
        "N3_829": {"example_sentence": "せい（正確）確に答えてください。", "example_reading": "せいかくにこたえてください。", "example_meaning_cn": "请准确回答。", "example_meaning_en": "Please answer accurately."},
        "N3_830": {"example_sentence": "せい（生活）活を楽しんでください。", "example_reading": "せいかつをたのしんでください。", "example_meaning_cn": "请享受生活。", "example_meaning_en": "Please enjoy your life."},
        "N3_831": {"example_sentence": "せい（政治）治に興味があります。", "example_reading": "せいじにきょうみがあります。", "example_meaning_cn": "对政治感兴趣。", "example_meaning_en": "I'm interested in politics."},
        "N3_832": {"example_sentence": "せい（清潔）潔にしてください。", "example_reading": "せいけつにしてください。", "example_meaning_cn": "请保持清洁。", "example_meaning_en": "Please keep it clean."},
        "N3_833": {"example_sentence": "せい（制作）作してください。", "example_reading": "せいさくしてください。", "example_meaning_cn": "请制作。", "example_meaning_en": "Please produce/create it."},
        "N3_834": {"example_sentence": "せい（製作）作を始めます。", "example_reading": "せいさくをはじめます。", "example_meaning_cn": "开始制作（产品）。", "example_meaning_en": "I'll begin production."},
        "N3_835": {"example_sentence": "せい（性質）質を調べてください。", "example_reading": "せいしつをしらべてください。", "example_meaning_cn": "请检查性质。", "example_meaning_en": "Please investigate the nature/property."},
        "N3_836": {"example_sentence": "せい（成績）績が上がりましたね！", "example_reading": "せいせきがあがりましたね！", "example_meaning_cn": "成绩提高了呢！", "example_meaning_en": "Your grades have improved, haven't they!"},
        "N3_837": {"example_sentence": "せい（製造）造してください。", "example_reading": "せいぞうしてください。", "example_meaning_cn": "请制造。", "example_meaning_en": "Please manufacture it."},
        "N3_838": {"example_sentence": "せい（生存）存者はいませんか。", "example_reading": "せいぞんしゃはいませんか。", "example_meaning_cn": "有幸存者吗？", "example_meaning_en": "Are there any survivors?"},
        "N3_839": {"example_sentence": "せい（贅沢）沢ですね！", "example_reading": "ぜいたくですね！", "example_meaning_cn": "真奢侈呢！", "example_meaning_en": "How luxurious!"},
        "N3_840": {"example_sentence": "せい（（成長）ちょう）しましたね！", "example_reading": "せいちょうしましたね！", "example_meaning_cn": "长大了（成长）呢！", "example_meaning_en": "You've grown up, haven't you!"},
        "N3_841": {"example_sentence": "ぜい（税金）金を払います。", "example_reading": "ぜいきんをはらいます。", "example_meaning_cn": "纳税。", "example_meaning_en": "I'll pay taxes."},
        "N3_842": {"example_sentence": "せい（制限）限されています。", "example_reading": "せいげんされています。", "example_meaning_cn": "被限制了。", "example_meaning_en": "It's restricted."},
        "N3_843": {"example_sentence": "せい（整理）理してください。", "example_reading": "せいりしてください。", "example_meaning_cn": "请整理。", "example_meaning_en": "Please organize it."},
        "N3_844": {"example_sentence": "せい（精神）神的に疲れました。", "example_reading": "せいしんてきにつかれました。", "example_meaning_cn": "精神上累了。", "example_meaning_en": "I'm mentally exhausted."},
        "N3_845": {"example_sentence": "せい（（西洋）よう）へ行きたいです。", "example_reading": "せいようへいきたいです。", "example_meaning_cn": "想去西方。", "example_meaning_en": "I want to go to the West."},
        "N3_846": {"example_sentence": "せ（成立）立しました！", "example_reading": "せいりつしました！", "example_meaning_cn": "成立了！", "example_meaning_en": "It's established/reached a deal!"},
        "N3_847": {"example_sentence": "せ（責任）任を持ってください。", "example_reading": "せきにんをもってください。", "example_meaning_cn": "请负起责任。", "example_meaning_en": "Please take responsibility."},
        "N3_848": {"example_sentence": "せき（石油）油が高いです。", "example_reading": "せきゆがたかいです。", "example_meaning_cn": "石油很贵。", "example_meaning_en": "Oil is expensive."},
        "N3_849": {"example_sentence": "せき（席）に座ってください。", "example_reading": "せきにすわってください。", "example_meaning_cn": "请坐在位子上。", "example_meaning_en": "Please sit in your seat."},
        "N3_850": {"example_sentence": "せっ（世）間（けん）は狭いですね。", "example_reading": "せけんわせまいですね。", "example_meaning_cn": "这世道（世界）真窄呢（人生何处不相逢）。", "example_meaning_en": "It's a small world, isn't it?"},
        "N3_851": {"example_sentence": "せっ（清潔）潔に保ってください。", "example_reading": "せいけつにたもってください。", "example_meaning_cn": "请保持清洁。", "example_meaning_en": "Please keep it clean."},
        "N3_852": {"example_sentence": "せっ（接続）続されていますか。", "example_reading": "せつぞくされていますか。", "example_meaning_cn": "连接上了吗？", "example_meaning_en": "Is it connected?"},
        "N3_853": {"example_sentence": "せっ（絶対）対に来てください。", "example_reading": "ぜったいにきてください。", "example_meaning_cn": "一定要来。", "example_meaning_en": "You must come."},
        "N3_854": {"example_sentence": "せっ（（説）とく）得してください。", "example_reading": "せっとくしてください。", "example_meaning_cn": "请说服。", "example_meaning_en": "Please persuade them."},
        "N3_855": {"example_sentence": "せっ（設備）備が整っています。", "example_reading": "せつびがととのっています。", "example_meaning_cn": "设备齐全。", "example_meaning_en": "The facilities are well-equipped."},
         "N3_856": {"example_sentence": "せつめい（説明）してください。", "example_reading": "せつめいしてください。", "example_meaning_cn": "请说明。", "example_meaning_en": "Please explain."},
        "N3_857": {"example_sentence": "せ（背）中（なか）が痛いです。", "example_reading": "せなかがいたいです。", "example_meaning_cn": "背疼。", "example_meaning_en": "My back hurts."},
        "N3_858": {"example_sentence": "せま（狭）いですね。 ", "example_reading": "せまいですね。", "example_meaning_cn": "真窄（或小）呢。", "example_meaning_en": "It's narrow/small, isn't it?"},
        "N3_859": {"example_sentence": "ぜ（全員）員いますか。", "example_reading": "ぜんいんいますか。", "example_meaning_cn": "全员都在吗？", "example_meaning_en": "Is everyone here?"},
        "N3_860": {"example_sentence": "せん（専攻）攻は何ですか。", "example_reading": "せんこうはなんですか。", "example_meaning_cn": "专业是什么？", "example_meaning_en": "What is your major?"},
        "N3_861": {"example_sentence": "せん（先日）日はありがとうございました。", "example_reading": "せんじつはありがとうございました。", "example_meaning_cn": "前几天谢谢了。", "example_meaning_en": "Thank you for the other day."},
        "N3_862": {"example_sentence": "ぜん（（前）じつ）日から準備します。", "example_reading": "ぜんじつからじゅんびします。", "example_meaning_cn": "从前一天开始准备。", "example_meaning_en": "I'll prepare from the day before."},
        "N3_863": {"example_sentence": "せん（選手）手になりたいです。", "example_reading": "せんしゅになりたいです。", "example_meaning_cn": "想成为选手。", "example_meaning_en": "I want to be a player/athlete."},
        "N3_864": {"example_sentence": "せん（洗濯）濯をします。", "example_reading": "せんたくをします。", "example_meaning_cn": "洗衣服。", "example_meaning_en": "I'll do the laundry."},
        "N3_865": {"example_sentence": "せん（先生）生に聞きます。", "example_reading": "せんせいにききます。", "example_meaning_cn": "去问老师。", "example_meaning_en": "I'll ask the teacher."},
        "N3_866": {"example_sentence": "ぜん（全然）然わかりません。", "example_reading": "ぜんぜんわかりません。", "example_meaning_cn": "完全不明白。", "example_meaning_en": "I don't understand at all."},
        "N3_867": {"example_sentence": "せん（（戦争）そう）は良くないです。", "example_reading": "せんそうはよくないです。", "example_meaning_cn": "战争是不好的。", "example_meaning_en": "War is not good."},
        "N3_868": {"example_sentence": "せん（先頭）頭に立ってください。", "example_reading": "せんとうにたってください。", "example_meaning_cn": "请站在最前头。", "example_meaning_en": "Please lead the way/stand at the front."},
        "N3_869": {"example_sentence": "ぜん（（全部）ぶ）食べてください。", "example_reading": "ぜんぶたべてください。", "example_meaning_cn": "请全部吃掉。", "example_meaning_en": "Please eat it all."},
        "N3_870": {"example_sentence": "せん（（線）せん）を引いてください。", "example_reading": "せんをひいてください。", "example_meaning_cn": "请划线。", "example_meaning_en": "Please draw a line."},
        "N3_871": {"example_sentence": "ぜん（（前方）ぽう）に注意してください。", "example_reading": "ぜんぽうにちゅういしてください。", "example_meaning_cn": "请注意前方。", "example_meaning_en": "Please watch the road ahead."},
        "N3_872": {"example_sentence": "せん（専門）問（もん）は何ですか。", "example_reading": "せんもんわなんですか。", "example_meaning_cn": "专门（特长）是什么？", "example_meaning_en": "What is your specialty?"},
        "N3_873": {"example_sentence": "せん（（占）りょう）領されました。", "example_reading": "せんりょうされました。", "example_meaning_cn": "被占领了。", "example_meaning_en": "It was occupied."},
        "N3_874": {"example_sentence": "せん（線路）路を歩かないでください。", "example_reading": "せんろをあるかないでください。", "example_meaning_cn": "请不要在铁轨上走。", "example_meaning_en": "Please don't walk on the railway tracks."},
        "N3_875": {"example_sentence": "そ（（外）そと）へ行きましょう。", "example_reading": "そとへいきましょう。", "example_meaning_cn": "去外面吧。", "example_meaning_en": "Let's go outside."},
        "N3_876": {"example_sentence": "し（（添）そ）えてください。", "example_reading": "そえてください。", "example_meaning_cn": "请附上（或伴随）。", "example_meaning_en": "Please attach/add it."},
        "N3_877": {"example_sentence": "そう（掃除）除してください。", "example_reading": "そうじしてください。", "example_meaning_cn": "请打扫。", "example_meaning_en": "Please clean it."},
        "N3_878": {"example_sentence": "そう（相談）談してください。", "example_reading": "そうだんしてください。", "example_meaning_cn": "请商量。", "example_meaning_en": "Please consult/talk to me."},
        "N3_879": {"example_sentence": "ぞう（象）は大きいです。", "example_reading": "ぞうわおおきいです。", "example_meaning_cn": "大象很大。", "example_meaning_en": "The elephant is big."},
        "N3_880": {"example_sentence": "そう（想像）像してください。", "example_reading": "そうぞうしてください。", "example_meaning_cn": "请想象一下。", "example_meaning_en": "Please imagine it."},
        "N3_881": {"example_sentence": "そう（操作）作してください。", "example_reading": "そうさしてください。", "example_meaning_cn": "请操作。", "example_meaning_en": "Please operate it."},
        "N3_882": {"example_sentence": "そう（葬式）式に行きます。", "example_reading": "そうしきにいきます。", "example_meaning_cn": "去参加葬礼。", "example_meaning_en": "I'm going to a funeral."},
        "N3_883": {"example_sentence": "ぞう（増強）強してください。", "example_reading": "ぞうきょうしてください。", "example_meaning_cn": "请增强。", "example_meaning_en": "Please reinforce it."},
        "N3_884": {"example_sentence": "ぞう（送金）金してください。", "example_reading": "そうきんしてください。", "example_meaning_cn": "请汇款（或送金）。", "example_meaning_en": "Please remit/send money."},
        "N3_885": {"example_sentence": "ぞう（相互）互（ご）に助け合いましょう。", "example_reading": "そうごにたすけあいましょう。", "example_meaning_cn": "互相帮助吧。", "example_meaning_en": "Let's help each other out."},
        "N3_886": {"example_sentence": "ぞう（増産）産してください。", "example_reading": "ぞうさんしてください。", "example_meaning_cn": "请增产。", "example_meaning_en": "Please increase production."},
        "N3_887": {"example_sentence": "ぞう（装置）置を付けてください。", "example_reading": "そうちをつけてください。", "example_meaning_cn": "请装上装置。", "example_meaning_en": "Please attach the device."},
        "N3_888": {"example_sentence": "ぞう（相当）当（とう）努力しました。", "example_reading": "そうとうどりょくしました。", "example_meaning_cn": "相当努力了。", "example_meaning_en": "I worked quite hard."},
        "N3_889": {"example_sentence": "そく（（即）そく）座（ざ）に対応します。", "example_reading": "そくざにたいおうします。", "example_meaning_cn": "当即应对。", "example_meaning_en": "I'll respond immediately."},
        "N3_890": {"example_sentence": "そく（（速）そく）報（ほう）を見てください。", "example_reading": "そくほうをみてください。", "example_meaning_cn": "请看速报（快讯）。", "example_meaning_en": "Please look at the breaking news."},
        "N3_891": {"example_sentence": "そこ（そこ）に置いてください。", "example_reading": "そこにおいてください。", "example_meaning_cn": "请放在那里。", "example_meaning_en": "Please put it there."},
        "N3_892": {"example_sentence": "（底）を見てください。", "example_reading": "そこをみてください。", "example_meaning_cn": "请看底部。", "example_meaning_en": "Please look at the bottom."},
        "N3_893": {"example_sentence": "（（損）そこ）なわないでください。", "example_reading": "そこなわないでください。", "example_meaning_cn": "请不要损害（或损坏）。", "example_meaning_en": "Please don't damage it."},
        "N3_894": {"example_sentence": "そし（（組織）そしき）を作ります。", "example_reading": "そしきをつくります。", "example_meaning_cn": "建立组织。", "example_meaning_en": "I'll form an organization."},
        "N3_895": {"example_sentence": "そ（（育）そだ）ててください。", "example_reading": "そだててください。", "example_meaning_cn": "请培育（或养育）。", "example_meaning_en": "Please raise/nurture it."},
        "N3_896": {"example_sentence": "そっ（（即）そっ）決して（けっして）ください。", "example_reading": "そっけつしてください。", "example_meaning_cn": "请速决（当即决定）。", "example_meaning_en": "Please decide immediately."},
        "N3_897": {"example_sentence": "そっ（（外）そと）を見てください。", "example_reading": "そとをみてください。", "example_meaning_cn": "请看外面。", "example_meaning_en": "Please look outside."},
        "N3_898": {"example_sentence": "そ（（備）そな）えてください。", "example_reading": "そなえてください。", "example_meaning_cn": "请备齐（或防备）。", "example_meaning_en": "Please prepare/equip it."},
        "N3_899": {"example_sentence": "そ（（具）そな）わっています。", "example_reading": "そなわっています。", "example_meaning_cn": "已具备（或拥有）。", "example_meaning_en": "It's equipped/endowed with."},
        "N3_900": {"example_sentence": "（其）れから会いましょう。", "example_reading": "それからあいましょう。", "example_meaning_cn": "在那之后见个面吧。", "example_meaning_en": "Let's meet after that."}
    }

    for item in vocab:
        if item['id'] in enrichment:
            item.update(enrichment[item['id']])

    with open(data_file, 'w', encoding='utf-8') as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

    print(f"Updated items up to N3_900.")

if __name__ == "__main__":
    main()
