import json
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    data_file = os.path.join(project_root, 'jlpt-web', 'src', 'data', 'vocab.json')

    if not os.path.exists(data_file):
        return

    with open(data_file, 'r', encoding='utf-8') as f:
        vocab = json.load(f)

    enrichment = {
        "N5_551": {"example_sentence": "少し休みたいです。", "example_reading": "すこしやすみたいです。", "example_meaning_cn": "想稍微休息一下。", "example_meaning_en": "I want to rest a little."},
        "N5_552": {"example_sentence": "お名前を教えてください。", "example_reading": "おなまえをおしえてください。", "example_meaning_cn": "请告诉我你的名字。", "example_meaning_en": "Please tell me your name."},
        "N5_553": {"example_sentence": "これは私のです。", "example_reading": "これはわたしのです。", "example_meaning_cn": "这是我的。", "example_meaning_en": "This is mine."},
        "N5_554": {"example_sentence": "それは本です。", "example_reading": "それはほんです。", "example_meaning_cn": "那是书。", "example_meaning_en": "That is a book."},
        "N5_555": {"example_sentence": "あれは何ですか。", "example_reading": "あれはなんですか。", "example_meaning_cn": "那个是什么？", "example_meaning_en": "What is that?"},
        "N5_556": {"example_sentence": "どれが好きですか。", "example_reading": "どれがすきですか。", "example_meaning_cn": "喜欢哪个？", "example_meaning_en": "Which one do you like?"},
        "N5_557": {"example_sentence": "この本は面白いです。", "example_reading": "このほんはおもしろいです。", "example_meaning_cn": "这本书很有趣。", "example_meaning_en": "This book is interesting."},
        "N5_558": {"example_sentence": "そのペンを貸してください。", "example_reading": "そのペンをかしてください。", "example_meaning_cn": "请把那支笔借给我。", "example_meaning_en": "Please lend me that pen."},
        "N5_559": {"example_sentence": "あの人は誰ですか。", "example_reading": "あのひとはだれですか。", "example_meaning_cn": "那个人是谁？", "example_meaning_en": "Who is that person over there?"},
        "N5_560": {"example_sentence": "どのカバンがあなたのですか。", "example_reading": "どのかばんがあなたのですか。", "example_meaning_cn": "哪个包是你的？", "example_meaning_en": "Which bag is yours?"},
        "N5_561": {"example_sentence": "ここがいいです。", "example_reading": "ここがいいです。", "example_meaning_cn": "这里很好。", "example_meaning_en": "Here is good."},
        "N5_562": {"example_sentence": "そこを右に曲がってください。", "example_reading": "そこをみぎにまがってください。", "example_meaning_cn": "请在那里右转。", "example_meaning_en": "Please turn right there."},
        "N5_563": {"example_sentence": "あそこにありますよ。", "example_reading": "あそこにありますよ。", "example_meaning_cn": "在那边有哦。", "example_meaning_en": "It's over there."},
        "N5_564": {"example_sentence": "どこで行きますか。 ", "example_reading": "どこでいきますか。", "example_meaning_cn": "去哪儿？", "example_meaning_en": "Where are you going?"},
        "N5_565": {"example_sentence": "こちらへどうぞ。", "example_reading": "こちらへどうぞ。", "example_meaning_cn": "请往这边。", "example_meaning_en": "This way, please."},
        "N5_566": {"example_sentence": "そちらは田中さんです。", "example_reading": "そちらはたなかさんです。", "example_meaning_cn": "那位是田中先生。", "example_meaning_en": "That person is Mr. Tanaka."},
        "N5_567": {"example_sentence": "あちらを見てください。", "example_reading": "あちらをみてください。", "example_meaning_cn": "请看那边。", "example_meaning_en": "Please look over there."},
        "N5_568": {"example_sentence": "どちらが早いですか。", "example_reading": "どちらがはやいですか。", "example_meaning_cn": "哪个更快？", "example_meaning_en": "Which one is faster?"},
        "N5_569": {"example_sentence": "どんな料理が好きですか。", "example_reading": "どんなりょうりがすきですか。", "example_meaning_cn": "喜欢什么样的菜？", "example_meaning_en": "What kind of food do you like?"},
        "N5_570": {"example_sentence": "どうして遅れたのですか。", "example_reading": "どうしておくれたのですか。", "example_meaning_cn": "为什么迟到了？", "example_meaning_en": "Why were you late?"},
        "N5_571": {"example_sentence": "いかがでしたか。", "example_reading": "いかがでしたか。", "example_meaning_cn": "觉得怎么样？", "example_meaning_en": "How was it?"},
        "N5_572": {"example_sentence": "いつ日本へ来ましたか。", "example_reading": "いつにほんへきましたか。", "example_meaning_cn": "什么时候来日本的？", "example_meaning_en": "When did you come to Japan?"},
        "N5_573": {"example_sentence": "いくつありますか。", "example_reading": "いくつありますか。", "example_meaning_cn": "有几个？", "example_meaning_en": "How many are there?"},
        "N5_574": {"example_sentence": "いくらですか。", "example_reading": "いくらですか。", "example_meaning_cn": "多少钱？", "example_meaning_en": "How much?"},
        "N5_575": {"example_sentence": "どうやって行きますか。", "example_reading": "どうやっていきますか。", "example_meaning_cn": "怎么去？", "example_meaning_en": "How do you go?"},
        "N5_576": {"example_sentence": "だれといっしょにいきますか。", "example_reading": "だれといっしょにいきますか。", "example_meaning_cn": "和谁一起去？", "example_meaning_en": "Who are you going with?"},
        "N5_577": {"example_sentence": "何時に起きますか。", "example_reading": "なんじにおきますか。", "example_meaning_cn": "几点起床？", "example_meaning_en": "What time do you wake up?"},
        "N5_578": {"example_sentence": "どこかにあります。 ", "example_reading": "どこかにあります。", "example_meaning_cn": "在某个地方。", "example_meaning_en": "It's somewhere."},
        "N5_579": {"example_sentence": "だれかいますか。 ", "example_reading": "だれかいますか。", "example_meaning_cn": "有人吗？", "example_meaning_en": "Is someone there?"},
        "N5_580": {"example_sentence": "なにか飲みませんか。", "example_reading": "なにかのみませんか。", "example_meaning_cn": "不喝点什么吗？", "example_meaning_en": "Would you like something to drink?"},
        "N5_581": {"example_sentence": "いつか会いましょう。", "example_reading": "いつかあいましょう。", "example_meaning_cn": "什么时候见一面吧。", "example_meaning_en": "Let's meet sometime."},
        "N5_582": {"example_sentence": "どこも行きません。", "example_reading": "どこもいきません。", "example_meaning_cn": "哪儿也不去。", "example_meaning_en": "I'm not going anywhere."},
        "N5_583": {"example_sentence": "だれもいません。", "example_reading": "だれもいません。", "example_meaning_cn": "谁也不在。", "example_meaning_en": "Nobody is there."},
        "N5_584": {"example_sentence": "なにもありません。", "example_reading": "なにもありません。", "example_meaning_cn": "什么也没有。", "example_meaning_en": "There is nothing."},
        "N5_585": {"example_sentence": "一回（いちかい）休みます。", "example_reading": "いっかいやすみます。", "example_meaning_cn": "休息一次。", "example_meaning_en": "I take a break once."},
        "N5_586": {"example_sentence": "二階（にかい）にあります。", "example_reading": "にかいにあります。", "example_meaning_cn": "在二楼。", "example_meaning_en": "It's on the second floor."},
        "N5_587": {"example_sentence": "一ヶ月（いっかげつ）勉強しました。", "example_reading": "いっかげつべんきょうしました。", "example_meaning_cn": "学了一个月。", "example_meaning_en": "I studied for one month."},
        "N5_588": {"example_sentence": "五個（ごこ）買いました。", "example_reading": "ごこかいました。", "example_meaning_cn": "买了五个。", "example_meaning_en": "I bought five pieces."},
        "N5_589": {"example_sentence": "三冊（さんさつ）持っています。", "example_reading": "さんさつもっています。", "example_meaning_cn": "拿了三本（书）。", "example_meaning_en": "I have three books."},
        "N5_590": {"example_sentence": "二分（にふん）待ってください。", "example_reading": "にふんまってください。", "example_meaning_cn": "请等两分钟。", "example_meaning_en": "Please wait for two minutes."},
        "N5_591": {"example_sentence": "一週間（いっしゅうかん）休みます。", "example_reading": "いっしゅうかんやすみます。", "example_meaning_cn": "休息一周。", "example_meaning_en": "I'll take a week off."},
        "N5_592": {"example_sentence": "三本（さんぼん）あります。", "example_reading": "さんぼんあります。", "example_meaning_cn": "有三根（长条物）。", "example_meaning_en": "There are three pieces."},
        "N5_593": {"example_sentence": "三枚（さんまい）書いてください。", "example_reading": "さんまいかいてください。", "example_meaning_cn": "请写三张（纸）。", "example_meaning_en": "Please write on three sheets."},
        "N5_594": {"example_sentence": "五人（ごにん）で食べます。", "example_reading": "ごにんでたべます。", "example_meaning_cn": "五个人一起吃。", "example_meaning_en": "Five people eat together."},
        "N5_595": {"example_sentence": "二つ（ふたつ）あります。", "example_reading": "ふたつあります。", "example_meaning_cn": "有两个。", "example_meaning_en": "There are two."},
        "N5_596": {"example_sentence": "三つ（みっつ）ください。", "example_reading": "みっつください。", "example_meaning_cn": "请给我三个。", "example_meaning_en": "Give me three pieces, please."},
        "N5_597": {"example_sentence": "四つ（よっつ）持っています。", "example_reading": "よっつもっています。", "example_meaning_cn": "拿了四个。", "example_meaning_en": "I have four pieces."},
        "N5_598": {"example_sentence": "五つ（いつつ）残っています。", "example_reading": "いつつのこっています。", "example_meaning_cn": "还剩五个。", "example_meaning_en": "There are five pieces left."},
        "N5_599": {"example_sentence": "六つ（むっつ）あります。", "example_reading": "むっつあります。", "example_meaning_cn": "有六个。", "example_meaning_en": "There are six pieces."},
        "N5_600": {"example_sentence": "七つ（ななつ）です。", "example_reading": "ななつです。", "example_meaning_cn": "七个。", "example_meaning_en": "Seven pieces."},
        "N5_601": {"example_sentence": "八つ（やっつ）買いました。", "example_reading": "やっつかいました。", "example_meaning_cn": "买了八个。", "example_meaning_en": "I bought eight pieces."},
        "N5_602": {"example_sentence": "九つ（ここのつ）です。", "example_reading": "ここのつです。", "example_meaning_cn": "九个。", "example_meaning_en": "Nine pieces."},
        "N5_603": {"example_sentence": "十（とお）あります。", "example_reading": "とおあります。", "example_meaning_cn": "有十个。", "example_meaning_en": "There are ten."},
        "N5_604": {"example_sentence": "月曜日（げつようび）に行きます。", "example_reading": "げつようびにいきます。", "example_meaning_cn": "周一去。", "example_meaning_en": "I'll go on Monday."},
        "N5_605": {"example_sentence": "火曜日（かようび）は暇です。", "example_reading": "かようびはひまです。", "example_meaning_cn": "周二有空。", "example_meaning_en": "I'm free on Tuesday."},
        "N5_606": {"example_sentence": "水曜日（すいようび）に会いましょう。", "example_reading": "すいようびにあいましょう。", "example_meaning_cn": "周三见吧。", "example_meaning_en": "Let's meet on Wednesday."},
        "N5_607": {"example_sentence": "木曜日（もくようび）に勉強します。", "example_reading": "もくようびにべんきょうします。", "example_meaning_cn": "周四学习。", "example_meaning_en": "I'll study on Thursday."},
        "N5_608": {"example_sentence": "金曜日（きんようび）に帰ります。", "example_reading": "きんようびにかえります。", "example_meaning_cn": "周五回来。", "example_meaning_en": "I'll return on Friday."},
        "N5_609": {"example_sentence": "土曜日（どようび）に映画を見ます。", "example_reading": "どようびにえいがをみます。", "example_meaning_cn": "周六看电影。", "example_meaning_en": "I'll watch a movie on Saturday."},
        "N5_610": {"example_sentence": "日曜日（にちようび）は休みです。", "example_reading": "にちようびはやすみです。", "example_meaning_cn": "周日休假。", "example_meaning_en": "Sunday is a holiday."},
        "N5_611": {"example_sentence": "一日（ついたち）に始まります。", "example_reading": "ついたちにはじまります。", "example_meaning_cn": "一号开始。", "example_meaning_en": "It starts on the 1st."},
        "N5_612": {"example_sentence": "二日（ふつか）に行きます。", "example_reading": "ふつかにいきます。", "example_meaning_cn": "二号去。", "example_meaning_en": "I'll go on the 2nd."},
        "N5_613": {"example_sentence": "三日（みっか）間（かん）休みます。", "example_reading": "みっかかんやすみます。", "example_meaning_cn": "休息三天。 ", "example_meaning_en": "I'll take a 3-day break."},
        "N5_614": {"example_sentence": "四日（よっか）後（ご）に会いましょう。", "example_reading": "よっかごにあいましょう。", "example_meaning_cn": "四天后见吧。", "example_meaning_en": "Let's meet in 4 days."},
        "N5_615": {"example_sentence": "五日（いつか）まで待ちます。", "example_reading": "いつかまでまちます。", "example_meaning_cn": "等到五号。", "example_meaning_en": "I'll wait until the 5th."},
        "N5_616": {"example_sentence": "六日（むいか）に帰ります。", "example_reading": "むいかにかえります。", "example_meaning_cn": "六号回来。", "example_meaning_en": "I'll return on the 6th."},
        "N5_617": {"example_sentence": "七日（なのか）に旅行へ行きます。", "example_reading": "なのかにりょこうへいきます。", "example_meaning_cn": "七号去旅行。", "example_meaning_en": "I'm going on a trip on the 7th."},
        "N5_618": {"example_sentence": "八日（ようか）に行きます。", "example_reading": "ようかにいきます。", "example_meaning_cn": "八号去。", "example_meaning_en": "I'll go on the 8th."},
        "N5_619": {"example_sentence": "九日（ここのか）まで勉強します。", "example_reading": "ここのかまでべんきょうします。", "example_meaning_cn": "学到九号。", "example_meaning_en": "I'll study until the 9th."},
        "N5_620": {"example_sentence": "十日（とおか）に始まります。", "example_reading": "とおかにはじまります。", "example_meaning_cn": "十号开始。", "example_meaning_en": "It starts on the 10th."},
        "N5_621": {"example_sentence": "二十日（はつか）までに書いてください。", "example_reading": "はつかまでにかいてください。", "example_meaning_cn": "请在二十号之前写好。", "example_meaning_en": "Please write it by the 20th."},
        "N5_622": {"example_sentence": "一月（いちがつ）はとても寒いです。", "example_reading": "いちがつはとてもさむいです。", "example_meaning_cn": "一月非常冷。", "example_meaning_en": "January is very cold."},
        "N5_623": {"example_sentence": "二月（にがつ）に雪が降りました。", "example_reading": "にがつにゆきがふりました。", "example_meaning_cn": "二月下了雪。", "example_meaning_en": "It snowed in February."},
        "N5_624": {"example_sentence": "三月（さんがつ）は卒業の季節です。", "example_reading": "さんがつはそつぎょうのきせつです。", "example_meaning_cn": "三月是毕业季。", "example_meaning_en": "March is the graduation season."},
        "N5_625": {"example_sentence": "四月（しがつ）に学校が始まります。", "example_reading": "しがつにがっこうがはじまります。", "example_meaning_cn": "四月开学。", "example_meaning_en": "School starts in April."},
        "N5_626": {"example_sentence": "五月（ごがつ）に日本へ行きます。", "example_reading": "ごがつににほんへいきます。", "example_meaning_cn": "五月去日本。", "example_meaning_en": "I'll go to Japan in May."},
        "N5_627": {"example_sentence": "六月（ろくがつ）は雨が多いです。", "example_reading": "ろくがつはあめがおおいです。", "example_meaning_cn": "六月雨水多。", "example_meaning_en": "There is a lot of rain in June."},
        "N5_628": {"example_sentence": "七月（しちがつ）に海へ行きます。", "example_reading": "しちがつにうみへいきます。", "example_meaning_cn": "七月去海边。", "example_meaning_en": "I'll go to the sea in July."},
        "N5_629": {"example_sentence": "八月（はちがつ）はとても暑いです。", "example_reading": "はちがつはとてもあついです。", "example_meaning_cn": "八月非常热。", "example_meaning_en": "August is very hot."},
        "N5_630": {"example_sentence": "九月（くがつ）に旅行しました。", "example_reading": "くがつにりょこうしました。", "example_meaning_cn": "九月旅行了。", "example_meaning_en": "I traveled in September."},
        "N5_631": {"example_sentence": "十月（じゅうがつ）に会いました。", "example_reading": "じゅうがつにあいました。", "example_meaning_cn": "十月见面了。", "example_meaning_en": "We met in October."},
        "N5_632": {"example_sentence": "十一月（じゅういちがつ）は涼しいです。", "example_reading": "じゅういちがつはすずしいです。", "example_meaning_cn": "十一月很凉爽。", "example_meaning_en": "November is cool."},
        "N5_633": {"example_sentence": "十二月（じゅうにがつ）に帰ります。", "example_reading": "じゅうにがつにかえります。", "example_meaning_cn": "十二月回来。", "example_meaning_en": "I'll return in December."},
        "N5_634": {"example_sentence": "一度（いちど）だけ見ました。", "example_reading": "いちどだけみました。", "example_meaning_cn": "只看了一次。", "example_meaning_en": "I only saw it once."},
        "N5_635": {"example_sentence": "一つ（ひとつ）ください。", "example_reading": "ひとつください。", "example_meaning_cn": "请给我一个。", "example_meaning_en": "One piece, please."},
        "N5_636": {"example_sentence": "右（みぎ）を見てください。", "example_reading": "みぎをみてください。", "example_meaning_cn": "请看右边。", "example_meaning_en": "Please look right."},
        "N5_637": {"example_sentence": "左（ひだり）へ曲がります。", "example_reading": "ひだりへまがります。", "example_meaning_cn": "向左转。", "example_meaning_en": "Turn to the left."},
        "N5_638": {"example_sentence": "上（うえ）に本があります。", "example_reading": "うえにほんがあります。", "example_meaning_cn": "上面有书。", "example_meaning_en": "There is a book on top."},
        "N5_639": {"example_sentence": "下（した）にありますよ。", "example_reading": "したにありますよ。", "example_meaning_cn": "在下面哦。", "example_meaning_en": "It's below."},
        "N5_640": {"example_sentence": "前（まえ）に先生がいます。", "example_reading": "まえにせんせいがいます。", "example_meaning_cn": "前面有老师。", "example_meaning_en": "There is a teacher in front."},
        "N5_641": {"example_sentence": "後ろ（うしろ）にカバンがあります。", "example_reading": "うしろにカバンがあります。", "example_meaning_cn": "后面有个包。", "example_meaning_en": "There is a bag behind."},
        "N5_642": {"example_sentence": "中（なか）に入りましょう。", "example_reading": "なかにはいりましょう。", "example_meaning_cn": "进到里面吧。", "example_meaning_en": "Let's go inside."},
        "N5_643": {"example_sentence": "外（そと）は寒いです。", "example_reading": "そとはさむいです。", "example_meaning_cn": "外面很冷。", "example_meaning_en": "It's cold outside."},
        "N5_644": {"example_sentence": "隣（となり）に住んでいます。", "example_reading": "となりにすんでいます。", "example_meaning_cn": "住在隔壁。", "example_meaning_en": "Lives next door."},
        "N5_645": {"example_sentence": "近く（ちかく）に公園があります。", "example_reading": "ちかくにこうえんがあります。", "example_meaning_cn": "附近有公园。", "example_meaning_en": "There is a park nearby."},
        "N5_646": {"example_sentence": "遠く（とおく）へ行きたいです。", "example_reading": "とおくへいきたいです。", "example_meaning_cn": "想去远方。", "example_meaning_en": "I want to go far away."},
        "N5_647": {"example_sentence": "横（よこ）に置いてください。", "example_reading": "よこにおいてください。", "example_meaning_cn": "请放在旁边。", "example_meaning_en": "Please place it on the side."},
        "N5_648": {"example_sentence": "向こう（むこう）のビルです。", "example_reading": "むこうのビルです。", "example_meaning_cn": "是那边那栋楼。", "example_meaning_en": "It's that building over there."},
        "N5_649": {"example_sentence": "東（ひがし）から太陽が昇ります。", "example_reading": "ひがしからたいようがのぼります。", "example_meaning_cn": "太阳从东边升起。", "example_meaning_en": "The sun rises from the east."},
        "N5_650": {"example_sentence": "西（にし）へ沈みます。", "example_reading": "にしへしずみます。", "example_meaning_cn": "向西落。", "example_meaning_en": "It sets to the west."},
        "N5_651": {"example_sentence": "南（みなみ）は暖かいです。", "example_reading": "みなみはあたたかいです。", "example_meaning_cn": "南方很温暖。", "example_meaning_en": "The south is warm."},
        "N5_652": {"example_sentence": "北（きた）は雪が多いです。", "example_reading": "きたはゆきがおおいです。", "example_meaning_cn": "北方雪很多。", "example_meaning_en": "There is a lot of snow in the north."},
        "N5_653": {"example_sentence": "午前（ごぜん）は忙しいです。", "example_reading": "ごぜんはいそがしいです。", "example_meaning_cn": "上午很忙。", "example_meaning_en": "The morning is busy."},
        "N5_654": {"example_sentence": "午後（ごご）から遊びます。", "example_reading": "ごごからあそびます。", "example_meaning_cn": "从下午开始玩。", "example_meaning_en": "I'll play from the afternoon."},
        "N5_655": {"example_sentence": "昨日（きのう）は何をしましたか。", "example_reading": "きのうはなにをしましたか。", "example_meaning_cn": "昨天做了什么？", "example_meaning_en": "What did you do yesterday?"},
        "N5_656": {"example_sentence": "今日（きょう）はいい天気です。", "example_reading": "きょうはいいてんきです。", "example_meaning_cn": "今天天气很好。", "example_meaning_en": "The weather is good today."},
        "N5_657": {"example_sentence": "明日（あした）会いましょう。", "example_reading": "あしたあいましょう。", "example_meaning_cn": "明天见面吧。", "example_meaning_en": "Let's meet tomorrow."},
        "N5_658": {"example_sentence": "あさって勉強します。", "example_reading": "あさってべんきょうします。", "example_meaning_cn": "后天学习。", "example_meaning_en": "I'll study the day after tomorrow."},
        "N5_659": {"example_sentence": "昨夜（ゆうべ）はよく寝ました。", "example_reading": "ゆうべはよくねました。", "example_meaning_cn": "昨晚睡得很好。", "example_meaning_en": "I slept well last night."},
        "N5_660": {"example_sentence": "今朝（けさ）早く起きました。", "example_reading": "けさはやくおきました。", "example_meaning_cn": "今天早上起得很早。", "example_meaning_en": "I woke up early this morning."},
        "N5_661": {"example_sentence": "今晩（こんばん）電話します。", "example_reading": "こんばんでんわします。", "example_meaning_cn": "今晚打电话。", "example_meaning_en": "I'll call tonight."},
        "N5_662": {"example_sentence": "去年（きょねん）日本へ来ました。", "example_reading": "きょねんにほんへきました。", "example_meaning_cn": "去年来日本的。", "example_meaning_en": "I came to Japan last year."},
        "N5_663": {"example_sentence": "今年（ことし）卒業します。", "example_reading": "ことしそつぎょうします。", "example_meaning_cn": "今年毕业。", "example_meaning_en": "I'll graduate this year."},
        "N5_664": {"example_sentence": "来年（らいねん）また会いましょう。", "example_reading": "らいねんまたあいましょう。", "example_meaning_cn": "明年再见吧。", "example_meaning_en": "Let's meet again next year."},
        "N5_665": {"example_sentence": "今（いま）から始めます。", "example_reading": "いまからはじめます。", "example_meaning_cn": "现在开始。", "example_meaning_en": "I'll start now."},
        "N5_666": {"example_sentence": "まだ食べていません。", "example_reading": "まだたべていません。", "example_meaning_cn": "还没吃。", "example_meaning_en": "I haven't eaten yet."},
        "N5_667": {"example_sentence": "もう読みましたか。", "example_reading": "もうよみましたか。", "example_meaning_cn": "已经读了吗？", "example_meaning_en": "Have you read it already?"},
        "N5_668": {"example_sentence": "とても（とても）寒いです。", "example_reading": "とてもさむいです。", "example_meaning_cn": "非常冷。", "example_meaning_en": "It's very cold."},
        "N5_669": {"example_sentence": "少し（すこし）疲れました。", "example_reading": "すこしつかれました。", "example_meaning_cn": "稍微有点累了。", "example_meaning_en": "I'm a little tired."},
        "N5_670": {"example_sentence": "あまり（あまり）飲みません。", "example_reading": "あまりのみません。", "example_meaning_cn": "不怎么喝。", "example_meaning_en": "I don't drink much."},
        "N5_671": {"example_sentence": "全然（ぜんぜん）わかりません。", "example_reading": "ぜんぜんわかりません。", "example_meaning_cn": "完全不懂。", "example_meaning_en": "I don't understand at all."},
        "N5_672": {"example_sentence": "いつも（いつも）遅いです。", "example_reading": "いつもおそいです。", "example_meaning_cn": "总是很迟。", "example_meaning_en": "Always late."},
        "N5_673": {"example_sentence": "時々（ときどき）買い物へ行きます。", "example_reading": "ときどきかいものへいきます。", "example_meaning_cn": "有时去买东西。", "example_meaning_en": "I sometimes go shopping."},
        "N5_674": {"example_sentence": "ゆっくり（ゆっくり）話してください。", "example_reading": "ゆっくりはなしてください。", "example_meaning_cn": "请慢慢说。", "example_meaning_en": "Please speak slowly."},
        "N5_675": {"example_sentence": "すぐ（すぐ）行きます。", "example_reading": "すぐいきます。", "example_meaning_cn": "马上就去。", "example_meaning_en": "I'll go immediately."},
        "N5_676": {"example_sentence": "だんだん（だんだん）暖かくなります。", "example_reading": "だんだんあたたかくなります。", "example_meaning_cn": "渐渐变暖和了。", "example_meaning_en": "It gradually gets warmer."},
        "N5_677": {"example_sentence": "ちょうど（ちょうど）三時です。", "example_reading": "ちょうどさんじです。", "example_meaning_cn": "正好三点。", "example_meaning_en": "It's exactly three o'clock."},
        "N5_678": {"example_sentence": "もっと（もっと）欲ほしいです。", "example_reading": "もっとほしいです。", "example_meaning_cn": "还要更多。", "example_meaning_en": "I want more."},
        "N5_679": {"example_sentence": "一番（いちばん）好きです。", "example_reading": "いちばんすきです。", "example_meaning_cn": "最喜欢。", "example_meaning_en": "I like it the most."},
        "N5_680": {"example_sentence": "一緒（いっしょ）に行きましょう。", "example_reading": "いっしょにいきましょう。", "example_meaning_cn": "一起去吧。", "example_meaning_en": "Let's go together."},
        "N5_681": {"example_sentence": "一人（ひとり）で勉強します。", "example_reading": "ひとりでべんきょうします。", "example_meaning_cn": "一个人学习。", "example_meaning_en": "I study alone."},
        "N5_682": {"example_sentence": "全部（ぜんぶ）でいくらですか。", "example_reading": "ぜんぶでいくらですか。", "example_meaning_cn": "总共多少钱？", "example_meaning_en": "How much in total?"},
        "N5_683": {"example_sentence": "たくさん（たくさん）食べました。", "example_reading": "たくさんたべました。", "example_meaning_cn": "吃了很多。", "example_meaning_en": "I ate a lot."},
        "N5_684": {"example_sentence": "おおぜい（おおぜい）いますね。", "example_reading": "おおぜいいますね。", "example_meaning_cn": "人很多呢。", "example_meaning_en": "There are many people, aren't there?"},
        "N5_685": {"example_sentence": "本当（ほんとう）ですか。", "example_reading": "ほんとうですか。", "example_meaning_cn": "是真的吗？", "example_meaning_en": "Is it true?"},
        "N5_686": {"example_sentence": "大変（たいへん）ですね。", "example_reading": "たいへんですね。", "example_meaning_cn": "太辛苦了呢。", "example_meaning_en": "It's hard, isn't it?"},
        "N5_687": {"example_sentence": "大丈夫（だいじょうぶ）ですよ。", "example_reading": "だいじょうぶですよ。", "example_meaning_cn": "没关系哦。", "example_meaning_en": "It's okay."},
        "N5_688": {"example_sentence": "色々（いろいろ）あります。", "example_reading": "いろいろあります。", "example_meaning_cn": "有各种各样的。", "example_meaning_en": "There are various types."},
        "N5_689": {"example_sentence": "皆（みんな）で行きましょう。", "example_reading": "みんなでいきましょう。", "example_meaning_cn": "大家一起去吧。", "example_meaning_en": "Let's all go."},
        "N5_690": {"example_sentence": "赤（あか）が一番好きです。", "example_reading": "あかがいちばんすきです。", "example_meaning_cn": "最喜欢红色。", "example_meaning_en": "I like red the most."},
        "N5_691": {"example_sentence": "青（あお）い空ですね。", "example_reading": "あおいそらですね。", "example_meaning_cn": "蓝天呢。", "example_meaning_en": "It's a blue sky, isn't it?"},
        "N5_692": {"example_sentence": "白（しろ）い服を着ています。", "example_reading": "しろいふくをきています。", "example_meaning_cn": "穿着白色的衣服。", "example_meaning_en": "I'm wearing white clothes."},
        "N5_693": {"example_sentence": "黒（くろ）いペンを貸してください。", "example_reading": "くろいペンをかしてください。", "example_meaning_cn": "请借我黑色的笔。", "example_meaning_en": "Please lend me a black pen."},
        "N5_694": {"example_sentence": "黄色（きいろ）い帽子を被っています。", "example_reading": "きいろいぼうしをかぶっています。", "example_meaning_cn": "戴着黄色的帽子。", "example_meaning_en": "Wearing a yellow hat."},
        "N5_695": {"example_sentence": "茶色（ちゃいろ）いカバンですね。", "example_reading": "ちゃいろいカバンですね。", "example_meaning_cn": "是棕色的包呢。", "example_meaning_en": "It's a brown bag, isn't it?"},
        "N5_696": {"example_sentence": "ゼロ（ぜろ）から始めます。", "example_reading": "ぜろからはじめます。", "example_meaning_cn": "从零开始。", "example_meaning_en": "Start from zero."},
        "N5_697": {"example_sentence": "レストラン（れすとらん）で食べます。", "example_reading": "レストランでたべます。", "example_meaning_cn": "在餐厅吃。", "example_meaning_en": "Eat at a restaurant."},
        "N5_698": {"example_sentence": "コーヒー（こーひー）をください。", "example_reading": "コーヒーをください。", "example_meaning_cn": "请给我咖啡。", "example_meaning_en": "Coffee, please."},
        "N5_699": {"example_sentence": "テレビ（てれび）を見ます。", "example_reading": "テレビをみます。", "example_meaning_cn": "看电视。", "example_meaning_en": "I watch TV."}
    }

    for item in vocab:
        if item['id'] in enrichment:
            item.update(enrichment[item['id']])

    with open(data_file, 'w', encoding='utf-8') as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

    print(f"N5 enrichment COMPLETE (699 items).")

if __name__ == "__main__":
    main()
