import json
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    data_file = os.path.join(project_root, 'jlpt-web', 'src', 'data', 'vocab.json')

    if not os.path.exists(data_file):
        return

    with open(data_file, 'r', encoding='utf-8') as f:
        vocab = json.load(f)

    enrichment = {
        "N4_151": {"example_sentence": "お（茶）を入れましょうか。", "example_reading": "おちゃをいれましょうか。", "example_meaning_cn": "要不要给您沏杯茶？", "example_meaning_en": "Shall I make some tea?"},
        "N4_152": {"example_sentence": "おつ（釣）りはありません。", "example_reading": "おつりはありません。", "example_meaning_cn": "没有找零。", "example_meaning_en": "There is no change."},
        "N4_153": {"example_sentence": "おと（音）が聞こえます。", "example_reading": "おとがきこえます。", "example_meaning_cn": "听到声音了。", "example_meaning_en": "I hear a sound."},
        "N4_154": {"example_sentence": "おと（落）とし物ですよ。", "example_reading": "おとしものですよ。", "example_meaning_cn": "这是你掉的东西哦。", "example_meaning_en": "This is something you dropped."},
        "N4_155": {"example_sentence": "おどり（踊り）が上手ですね。", "example_reading": "おどりがじょうずですね。", "example_meaning_cn": "舞跳得真棒呢。", "example_meaning_en": "You're a good dancer, aren't you?"},
        "N4_156": {"example_sentence": "おどろ（驚）かさないでください。", "example_reading": "おどろかさないでください。", "example_meaning_cn": "请别吓唬我。", "example_meaning_en": "Please don't surprise me."},
        "N4_157": {"example_sentence": "おな（同）じものを持っています。", "example_reading": "おなじものをもっています。", "example_meaning_cn": "我也有一样的东西。", "example_meaning_en": "I have the same thing."},
        "N4_158": {"example_sentence": "おに（兄）は銀行員です。", "example_reading": "おにいさんはぎんこういんです。", "example_meaning_cn": "我哥哥是银行职员。", "example_meaning_en": "My brother is a bank clerk."},
        "N4_159": {"example_sentence": "おね（姉）は看護師です。", "example_reading": "おねえさんはかんごしです。", "example_meaning_cn": "我姐姐是护士。", "example_meaning_en": "My sister is a nurse."},
        "N4_160": {"example_sentence": "おば（伯母）さんに会いました。", "example_reading": "おばさんにあいました。", "example_meaning_cn": "见到伯母了。", "example_meaning_en": "I met my aunt."},
        "N4_161": {"example_sentence": "おま（待）たせしました。", "example_reading": "お待たせしました。", "example_meaning_cn": "让您久等了。", "example_meaning_en": "Sorry to have kept you waiting."},
        "N4_162": {"example_sentence": "おまつ（祭）りに行きましょう。", "example_reading": "おまつりにいきましょう。", "example_meaning_cn": "去参加祭典吧。", "example_meaning_en": "Let's go to the festival."},
        "N4_163": {"example_sentence": "おみ（見）舞いに行きます。", "example_reading": "おみまいにいきます。", "example_meaning_cn": "去探病。", "example_meaning_en": "I'm going to visit the sick."},
        "N4_164": {"example_sentence": "おみ（見）上げを買いました。", "example_reading": "おみやげをかいました。", "example_meaning_cn": "买了特产（伴手礼）。", "example_meaning_en": "I bought some souvenirs."},
        "N4_165": {"example_sentence": "おも（思）い出しました。", "example_reading": "おもいだしました。", "example_meaning_cn": "想起来了。", "example_meaning_en": "I remembered."},
        "N4_166": {"example_sentence": "おもちゃで遊びます。", "example_reading": "おもちゃであそびます。", "example_meaning_cn": "玩玩具。", "example_meaning_en": "I'll play with toys."},
        "N4_167": {"example_sentence": "おも（表）に出てください。", "example_reading": "おもにでてください。", "example_meaning_cn": "请到外面去。", "example_meaning_en": "Please step outside."},
        "N4_168": {"example_sentence": "おや（親）を大切にしましょう。", "example_reading": "おやをたいせつにしましょう。", "example_meaning_cn": "要孝敬父母（珍视双亲）。", "example_meaning_en": "Let's take good care of our parents."},
        "N4_169": {"example_sentence": "おり（下）てください。", "example_reading": "おりてください。", "example_meaning_cn": "请下来（或下车）。", "example_meaning_en": "Please get off (the bus/train)."},
        "N4_170": {"example_sentence": "お（折）れましたね。", "example_reading": "おれましたね。", "example_meaning_cn": "折断了呢。", "example_meaning_en": "It broke, didn't it?"},
        "N4_171": {"example_sentence": "お（終）わりです。", "example_reading": "おわりです。", "example_meaning_cn": "结束了。", "example_meaning_en": "It's the end."},
        "N4_172": {"example_sentence": "おん（音）楽が好き（すき）ですか。", "example_reading": "おんがくがすきですか。", "example_meaning_cn": "喜欢音乐吗？", "example_meaning_en": "Do you like music?"},
        "N4_173": {"example_sentence": "か（火）事です！逃げて！", "example_reading": "かじです！にげて！", "example_meaning_cn": "着火了！快逃！", "example_meaning_en": "It's a fire! Run!"},
        "N4_174": {"example_sentence": "かい（海）外へ行きたいです。", "example_reading": "かいがいへいきたいです。", "example_meaning_cn": "想去国外。", "example_meaning_en": "I want to go abroad."},
        "N4_175": {"example_sentence": "かい（会）議に出席します。", "example_reading": "かいぎにしゅっせきします。", "example_meaning_cn": "出席会议。", "example_meaning_en": "I'll attend the meeting."},
        "N4_176": {"example_sentence": "かい（海）岸を歩きます。", "example_reading": "かいがんをあるきます。", "example_meaning_cn": "在海岸边行走。", "example_meaning_en": "I'll walk along the coast."},
        "N4_177": {"example_sentence": "かい（会）場はこちらです。", "example_reading": "かいじょうはこちらです。", "example_meaning_cn": "会场在这边。", "example_meaning_en": "The venue is this way."},
        "N4_178": {"example_sentence": "かい（会）話の練習をします。", "example_reading": "かいわのれんしゅうをします。", "example_meaning_cn": "练习会话。", "example_meaning_en": "I'll practice conversation."},
        "N4_179": {"example_sentence": "かえ（帰）りましょう。", "example_reading": "かえりましょう。", "example_meaning_cn": "回去吧。", "example_meaning_en": "Let's go back."},
        "N4_180": {"example_sentence": "か（変）えてください。", "example_reading": "かえてください。", "example_meaning_cn": "请换一下。", "example_meaning_en": "Please change it."},
        "N4_181": {"example_sentence": "かえ（替）えてください。", "example_reading": "かえてください。", "example_meaning_cn": "请替换（或兑换）。", "example_meaning_en": "Please replace it."},
        "N4_182": {"example_sentence": "かがみ（鏡）を見てください。", "example_reading": "かがみをみてください。", "example_meaning_cn": "请照镜子。", "example_meaning_en": "Please look in the mirror."},
        "N4_183": {"example_sentence": "か（掛）けてください。", "example_reading": "かけてください。", "example_meaning_cn": "请挂上（或戴上眼镜）。", "example_meaning_en": "Please hang it (or put on glasses)."},
        "N4_184": {"example_sentence": "かざ（飾）ってください。", "example_reading": "かざってください。", "example_meaning_cn": "请装饰一下。", "example_meaning_en": "Please decorate it."},
        "N4_185": {"example_sentence": "か（火）山が噴火しました。", "example_reading": "かざんがふんかしました。", "example_meaning_cn": "火山喷发了。", "example_meaning_en": "The volcano erupted."},
        "N4_186": {"example_sentence": "かし（貸）してください。", "example_reading": "かしてください。", "example_meaning_cn": "请借给我。", "example_meaning_en": "Please lend it to me."},
        "N4_187": {"example_sentence": "かす（貸）してください。 ", "example_reading": "かしてください。", "example_meaning_cn": "请借（出）给我。 ", "example_meaning_en": "Please lend it to me."},
        "N4_188": {"example_sentence": "かぜ（風）が吹いています。", "example_reading": "かぜがふいています。", "example_meaning_cn": "正在刮风。", "example_meaning_en": "The wind is blowing."},
        "N4_189": {"example_sentence": "かぜ（感冒）を引きました。", "example_reading": "かぜをひきました。", "example_meaning_cn": "感冒了。", "example_meaning_en": "I caught a cold."},
        "N4_190": {"example_sentence": "かぞ（飾）るのが楽しみです。", "example_reading": "かざるのがたのしみです。", "example_meaning_cn": "很期待装饰。", "example_meaning_en": "I'm looking forward to decorating."},
        "N4_191": {"example_sentence": "ガソリン（がそりん）を入れます。", "example_reading": "ガソリンをいれます。", "example_meaning_cn": "加汽油。", "example_meaning_en": "I'll put in gas."},
        "N4_192": {"example_sentence": "かた（形）がいいですね。", "example_reading": "かたがいいですね。", "example_meaning_cn": "形状（或款式）很好呢。", "example_meaning_en": "The shape/model is good, isn't it?"},
        "N4_193": {"example_sentence": "かた（片）づけてください。", "example_reading": "かたづけてください。", "example_meaning_cn": "请收拾一下。", "example_meaning_en": "Please tidy up."},
        "N4_194": {"example_sentence": "か（勝）ちました！", "example_reading": "かちました！", "example_meaning_cn": "赢了！", "example_meaning_en": "We won!"},
        "N4_195": {"example_sentence": "かっこう（格好）がいいですね。", "example_reading": "かっこうがいいですね。", "example_meaning_cn": "真够帅（有型）的呢。", "example_meaning_en": "You look cool, don't you?"},
        "N4_196": {"example_sentence": "かない（家内）は主婦です。", "example_reading": "かないはしゅふです。", "example_meaning_cn": "我爱人（内人）是家庭主妇。", "example_meaning_en": "My wife is a housewife."},
        "N4_197": {"example_sentence": "かな（悲）しいですね。", "example_reading": "かなしいですね。", "example_meaning_cn": "真够悲伤的呢。", "example_meaning_en": "It's sad, isn't it?"},
        "N4_198": {"example_sentence": "かなら（必）ず来てください。", "example_reading": "かならずきてください。", "example_meaning_cn": "请一定要来。", "example_meaning_en": "Please be sure to come."},
        "N4_199": {"example_sentence": "かね（金）を持ちます。", "example_reading": "かねをもちます。", "example_meaning_cn": "我有钱（拿着钱）。", "example_meaning_en": "I have money."},
        "N4_200": {"example_sentence": "かね（金）持ちになりたいです。", "example_reading": "かねもちになりたいです。", "example_meaning_cn": "想成为有钱人。", "example_meaning_en": "I want to be rich."},
        "N4_201": {"example_sentence": "かのじょ（彼女）はきれいです。", "example_reading": "かのじょはきれいです。", "example_meaning_cn": "她很漂亮。", "example_meaning_en": "She is beautiful."},
        "N4_202": {"example_sentence": "かべ（壁）に写真を貼ります。", "example_reading": "かべにしゃしんをはります。", "example_meaning_cn": "在墙上贴照片。", "example_meaning_en": "I'll put a photo on the wall."},
        "N4_203": {"example_sentence": "かま（構）いませんよ。", "example_reading": "かまいませんよ。", "example_meaning_cn": "没关系哦。", "example_meaning_en": "I don't mind."},
        "N4_204": {"example_sentence": "かみ（髪）を切りたいです。", "example_reading": "かみをきりたいです。", "example_meaning_cn": "想剪头发。", "example_meaning_en": "I want to cut my hair."},
        "N4_205": {"example_sentence": "かみ（紙）をください。", "example_reading": "かみをください。", "example_meaning_cn": "请给我纸。", "example_meaning_en": "Please give me some paper."},
        "N4_206": {"example_sentence": "か（噛）んでください。", "example_reading": "かんでください。", "example_meaning_cn": "请咀嚼。", "example_meaning_en": "Please chew."},
        "N4_207": {"example_sentence": "かよう（火曜）日は忙しいです。", "example_reading": "かようびはいそがしいです。", "example_meaning_cn": "周二我很忙。", "example_meaning_en": "I'm busy on Tuesday."},
        "N4_208": {"example_sentence": "かよ（通）っています。", "example_reading": "かよっています。", "example_meaning_cn": "正在往返（通勤/通学）。", "example_meaning_en": "I'm commuting/attending."},
        "N4_209": {"example_sentence": "から（空）っぽです。", "example_reading": "からっぽです。", "example_meaning_cn": "空的。", "example_meaning_en": "It's empty."},
        "N4_210": {"example_sentence": "から（体）を大事にしてください。", "example_reading": "からだをだいじにしてください。", "example_meaning_cn": "请保重身体。", "example_meaning_en": "Please take care of your body."},
        "N4_211": {"example_sentence": "から（借）りてください。", "example_reading": "かりてください。", "example_meaning_cn": "请借（入）走吧。", "example_meaning_en": "Please borrow it."},
        "N4_212": {"example_sentence": "かる（軽）いカバンですね。", "example_reading": "かるいかばんですね。", "example_meaning_cn": "真是个轻巧的包呢。", "example_meaning_en": "It's a light bag, isn't it?"},
        "N4_213": {"example_sentence": "カレンダー（かれんだー）を見てください。", "example_reading": "カレンダーをみてください。", "example_meaning_cn": "请看日历。", "example_meaning_en": "Please look at the calendar."},
        "N4_214": {"example_sentence": "かわ（川）で泳ぎましょう。", "example_reading": "かわでおよぎましょう。", "example_meaning_cn": "在河里游泳吧。", "example_meaning_en": "Let's swim in the river."},
        "N4_215": {"example_sentence": "かわ（代）わってください。", "example_reading": "かわってください。", "example_meaning_cn": "请替换（或代理）。", "example_meaning_en": "Please take over/swap."},
        "N4_216": {"example_sentence": "かわ（乾）きましたか。", "example_reading": "かわきましたか。", "example_meaning_cn": "干了吗？", "example_meaning_en": "Is it dry?"},
        "N4_217": {"example_sentence": "かわ（変）わりましたね。", "example_reading": "かわりましたね。", "example_meaning_cn": "变了呢。", "example_meaning_en": "It has changed, hasn't it?"},
        "N4_218": {"example_sentence": "かわ（可愛）いですね。", "example_reading": "かわいいですね。", "example_meaning_cn": "真可爱呢。", "example_meaning_en": "It's cute, isn't it?"},
        "N4_219": {"example_sentence": "がん（考）えてください。", "example_reading": "かんがえてください。", "example_meaning_cn": "请考虑一下。", "example_meaning_en": "Please think about it."},
        "N4_220": {"example_sentence": "かん（完）成しました！", "example_reading": "かんせいしました！", "example_meaning_cn": "完成了！", "example_meaning_en": "It's finished!"},
        "N4_221": {"example_sentence": "かん（関）係ありません。", "example_reading": "かんけいありません。", "example_meaning_cn": "没有关系。", "example_meaning_en": "It's unrelated."},
        "N4_222": {"example_sentence": "かん（看）護師さんは忙しいです。", "example_reading": "かんごしさんはいそがしいです。", "example_meaning_cn": "护士们很忙。", "example_meaning_en": "Nurses are busy."},
        "N4_223": {"example_sentence": "き（木）が揺れています。", "example_reading": "きがゆれています。", "example_meaning_cn": "树正在摇晃。", "example_meaning_en": "The tree is swaying."},
        "N4_224": {"example_sentence": "き（気）をつけてください。", "example_reading": "きをつけてください。", "example_meaning_cn": "请小心。", "example_meaning_en": "Please be careful."},
        "N4_225": {"example_sentence": "き（機）会があります。", "example_reading": "きかいがあります。", "example_meaning_cn": "会有机会的。", "example_meaning_en": "There will be an opportunity."},
        "N4_226": {"example_sentence": "き（危）険ですから離れて！", "example_reading": "きけんですからはなれて！", "example_meaning_cn": "很危险，快离开！", "example_meaning_en": "It's dangerous, so move away!"},
        "N4_227": {"example_sentence": "き（聞）いてください。", "example_reading": "きいてください。", "example_meaning_cn": "请听（或请问）。", "example_meaning_en": "Please listen (or ask)."},
        "N4_228": {"example_sentence": "き（帰）ってください。", "example_reading": "きってください。", "example_meaning_cn": "请回吧（或请切开）。", "example_meaning_en": "Please return (or cut)."},
        "N4_229": {"example_sentence": "き（着）てください。", "example_reading": "きてください。", "example_meaning_cn": "请穿上。", "example_meaning_en": "Please put it on/wear it."},
        "N4_230": {"example_sentence": "き（来）てください。", "example_reading": "きてください。", "example_meaning_cn": "请过来。", "example_meaning_en": "Please come."},
        "N4_231": {"example_sentence": "き（決）まりましたね。", "example_reading": "きまりましたね。", "example_meaning_cn": "决定了呢。", "example_meaning_en": "It's decided, isn't it?"},
        "N4_232": {"example_sentence": "き（君）は誰ですか。", "example_reading": "きみはだれですか。", "example_meaning_cn": "你是谁？", "example_meaning_en": "Who are you?"},
        "N4_233": {"example_sentence": "きもち（気持ち）がいいです。", "example_reading": "きもちがいいです。", "example_meaning_cn": "心情（或感觉）很好。", "example_meaning_en": "It feels good."},
        "N4_234": {"example_sentence": "き（着）物を持っています。", "example_reading": "きものをもっています。", "example_meaning_cn": "我有和服。", "example_meaning_en": "I have a kimono."},
        "N4_235": {"example_sentence": "きゃく（客）さんが来ました。", "example_reading": "きゃくさんがきました。", "example_meaning_cn": "客人来了。", "example_meaning_en": "A guest has come."},
        "N4_236": {"example_sentence": "きゅう（急）な坂道です。", "example_reading": "きゅうなさかみちです。", "example_meaning_cn": "陡峭的山路。", "example_meaning_en": "It's a steep slope."},
        "N4_237": {"example_sentence": "きゅう（急）に雨が降りました。", "example_reading": "きゅうにあめがふりました。", "example_meaning_cn": "突然下雨了。", "example_meaning_en": "It suddenly rained."},
        "N4_238": {"example_sentence": "きゅう（九）円足りません。", "example_reading": "きゅうえんたりません。", "example_meaning_cn": "差九日元。", "example_meaning_en": "It's nine yen short."},
        "N4_239": {"example_sentence": "きゅう（休）行ですね。", "example_reading": "きゅうこうですね。", "example_meaning_cn": "停航（或停开）呢。", "example_meaning_en": "It's cancelled/not running, isn't it?"},
        "N4_240": {"example_sentence": "きゅう（急）行電車に乗ります。", "example_reading": "きゅうこうでんしゃにのります。", "example_meaning_cn": "坐快车（急行）。", "example_meaning_en": "I'll take the express train."},
        "N4_241": {"example_sentence": "きゅう（教育）が大切です。", "example_reading": "きょういくがたいせつです。", "example_meaning_cn": "教育很重要。", "example_meaning_en": "Education is important."},
        "N4_242": {"example_sentence": "きょう（教）会へ行きます。", "example_reading": "きょうかいへいきます。", "example_meaning_cn": "去教堂。", "example_meaning_en": "I'm going to the church."},
        "N4_243": {"example_sentence": "きょう（興）味があります。", "example_reading": "きょうみがあります。", "example_meaning_cn": "有兴趣。", "example_meaning_en": "I'm interested."},
        "N4_244": {"example_sentence": "きょう（競）走しましょう。", "example_reading": "きょうそうしましょう。", "example_meaning_cn": "赛跑吧。", "example_meaning_en": "Let's race."},
        "N4_245": {"example_sentence": "きょ（去）年（ねん）卒業しました。", "example_reading": "きょねんそつぎょうしました。", "example_meaning_cn": "去年毕业了。", "example_meaning_en": "I graduated last year."},
        "N4_246": {"example_sentence": "き（切）ってください。", "example_reading": "きってください。", "example_meaning_cn": "请切（断）。", "example_meaning_en": "Please cut it."},
        "N4_247": {"example_sentence": "き（切）手（て）を貼ります。", "example_reading": "きってをはります。", "example_meaning_cn": "贴邮票。", "example_meaning_en": "I'll stick on the stamp."},
        "N4_248": {"example_sentence": "きっぷ（切符）を買いましたか。", "example_reading": "きっぷをかいましたか。", "example_meaning_cn": "买票了吗？", "example_meaning_en": "Did you buy the ticket?"},
        "N4_249": {"example_sentence": "き（嫌）いですか。 ", "example_reading": "きらいですか。", "example_meaning_cn": "讨厌吗？", "example_meaning_en": "Do you hate it?"},
        "N4_250": {"example_sentence": "き（清）潔な服を着ます。", "example_reading": "せいけつなふくをきます。", "example_meaning_cn": "穿干净整洁的衣服。", "example_meaning_en": "I wear clean clothes."},
        "N4_251": {"example_sentence": "き（着）るのが楽しみです。", "example_reading": "きるのがたのしみです。", "example_meaning_cn": "很期待穿（那一身）。", "example_meaning_en": "I'm looking forward to wearing it."},
        "N4_252": {"example_sentence": "き（奇）れいな景色ですね。", "example_reading": "きれいなけしきですね。", "example_meaning_cn": "真棒的景色呢。", "example_meaning_en": "It's a beautiful scenery, isn't it?"},
        "N4_253": {"example_sentence": "ぎん（銀）色のカバンです。", "example_reading": "ぎんいろのかばんです。", "example_meaning_cn": "银色的包。", "example_meaning_en": "It's a silver bag."},
        "N4_254": {"example_sentence": "ぎん（銀）行でお金を下ろします。", "example_reading": "ぎんこうでおかねをおろします。", "example_meaning_cn": "去银行取钱。", "example_meaning_en": "I'll withdraw money at the bank."},
        "N4_255": {"example_sentence": "きん（近）所の人に挨拶します。", "example_reading": "きんじょのひとにあいさつします。", "example_meaning_cn": "和邻居打招呼。", "example_meaning_en": "I greet the neighbors."},
        "N4_256": {"example_sentence": "きん（金）曜（よう）日は休みです。", "example_reading": "きんようびはやすみです。", "example_meaning_cn": "周五休假。", "example_meaning_en": "Friday is a holiday."},
        "N4_257": {"example_sentence": "く（九）時に寝ます。", "example_reading": "くじにねます。", "example_meaning_cn": "九点睡觉。", "example_meaning_en": "I go to sleep at nine."},
        "N4_258": {"example_sentence": "く（空気）が美味しいです。", "example_reading": "くうきがおいしいです。", "example_meaning_cn": "空气很清爽（好吃）。", "example_meaning_en": "The air is fresh."},
        "N4_259": {"example_sentence": "くう（空）港へ迎えに行きます。", "example_reading": "くうこうへむかえにいきます。", "example_meaning_cn": "去机场接人。", "example_meaning_en": "I'm going to the airport to pick someone up."},
        "N4_260": {"example_sentence": "くさ（草）を抜きます。", "example_reading": "くさをぬきます。", "example_meaning_cn": "拔草。", "example_meaning_en": "I'll pull out the weeds."},
        "N4_261": {"example_sentence": "くす（薬）を飲んでください。", "example_reading": "くすりをのんでください。", "example_meaning_cn": "请吃药。", "example_meaning_en": "Please take the medicine."},
        "N4_262": {"example_sentence": "ください（ください）。 ", "example_reading": "ください。", "example_meaning_cn": "请给我。 ", "example_meaning_en": "Please give me."},
        "N4_263": {"example_sentence": "くだ（下）ってください。", "example_reading": "くだってください。", "example_meaning_cn": "请下去。", "example_meaning_en": "Please go down."},
        "N4_264": {"example_sentence": "くだ（果物）が食べたいです。", "example_reading": "くだものがたべたいです。", "example_meaning_cn": "想吃水果。", "example_meaning_en": "I want to eat fruit."},
        "N4_265": {"example_sentence": "くち（口）を閉じてください。", "example_reading": "くちをしめてください。", "example_meaning_cn": "请闭嘴。", "example_meaning_en": "Please close your mouth."},
        "N4_266": {"example_sentence": "くつ（靴）を履きます。", "example_reading": "くつをはきます。", "example_meaning_cn": "穿鞋。", "example_meaning_en": "I'll put on shoes."},
        "N4_267": {"example_sentence": "くつ（靴）下を履いてください。", "example_reading": "くつしたをはいてください。", "example_meaning_cn": "请穿上袜子。", "example_meaning_en": "Please put on socks."},
        "N4_268": {"example_sentence": "くに（国）へ帰りたいです。", "example_reading": "くにへかえりたいです。", "example_meaning_cn": "想回老家（或回国）。", "example_meaning_en": "I want to go back to my country."},
        "N4_269": {"example_sentence": "くび（首）が痛いです。", "example_reading": "くびがいたいです。", "example_meaning_cn": "脖子疼。", "example_meaning_en": "My neck hurts."},
        "N4_270": {"example_sentence": "くも（雲）が出てきました。", "example_reading": "くもがでてきました。", "example_meaning_cn": "云出来了。", "example_meaning_en": "Clouds have appeared."},
        "N4_271": {"example_sentence": "くら（暗）いですね。 ", "example_reading": "くらいですね。", "example_meaning_cn": "挺暗的呢。", "example_meaning_en": "It's dark, isn't it?"},
        "N4_272": {"example_sentence": "クラス（くらす）で一番です。", "example_reading": "クラスでいちばんです。", "example_meaning_cn": "在班级里是第一名。", "example_meaning_en": "I am number one in the class."},
        "N4_273": {"example_sentence": "くら（比）べてください。", "example_reading": "くらべてください。", "example_meaning_cn": "请对比一下。", "example_meaning_en": "Please compare them."},
        "N4_274": {"example_sentence": "くる（来）るのが遅いですね。", "example_reading": "くるのがおそいですね。", "example_meaning_cn": "来得真慢呢。", "example_meaning_en": "Coming slow, aren't you?"},
        "N4_275": {"example_sentence": "くる（車）を買いたいです。", "example_reading": "くるまをかいたいです。", "example_meaning_cn": "想买车。", "example_meaning_en": "I want to buy a car."},
        "N4_276": {"example_sentence": "くろ（黒）い服を着ています。", "example_reading": "くろいふくをきています。", "example_meaning_cn": "穿着黑衣服。", "example_meaning_en": "I'm wearing black clothes."},
        "N4_277": {"example_sentence": "くん（君）の名前は？", "example_reading": "くんのなまえは？", "example_meaning_cn": "你的名字是？", "example_meaning_en": "What's your name?"},
        "N4_278": {"example_sentence": "け（毛）が落ちています。", "example_reading": "けがおちています。", "example_meaning_cn": "掉头发（或毛）了。", "example_meaning_en": "Hair is falling out."},
        "N4_279": {"example_sentence": "けい（計画）を立てましょう。", "example_reading": "けいかくをたてましょう。", "example_meaning_cn": "制定计划吧。", "example_meaning_en": "Let's make a plan."},
        "N4_280": {"example_sentence": "けい（経）験が豊富です。", "example_reading": "けいけんがほうふです。", "example_meaning_cn": "经验丰富。", "example_meaning_en": "I have extensive experience."},
        "N4_281": {"example_sentence": "けい（警察）官です。", "example_reading": "けいさつかんです。", "example_meaning_cn": "是位警官。", "example_meaning_en": "He is a police officer."},
        "N4_282": {"example_sentence": "けが（怪我）をしましたか。", "example_reading": "けがをしましたか。", "example_meaning_cn": "受伤了吗？", "example_meaning_en": "Did you get injured?"},
        "N4_283": {"example_sentence": "けし（景）色がいいですね。", "example_reading": "けしきがいいですね。", "example_meaning_cn": "景色挺不错的呢。", "example_meaning_en": "The scenery is nice, isn't it?"},
        "N4_284": {"example_sentence": "け（消）してください。", "example_reading": "けしてください。", "example_meaning_cn": "请关掉（或擦掉）。", "example_meaning_en": "Please turn it off (or erase it)."},
        "N4_285": {"example_sentence": "けしゴム（けしごむ）を貸して。", "example_reading": "けしゴムをかして。", "example_meaning_cn": "借我橡皮。", "example_meaning_en": "Lend me your eraser."},
        "N4_286": {"example_sentence": "け（下）宿に住んでいます。", "example_reading": "げしゅくにすんでいます。", "example_meaning_cn": "住在旅宿。", "example_meaning_en": "I live in a boarding house."},
        "N4_287": {"example_sentence": "けっ（決して）して忘れません。", "example_reading": "けっしてわすれません。", "example_meaning_cn": "绝不会忘记。", "example_meaning_en": "I will never forget."},
        "N4_288": {"example_sentence": "けっ（結婚）婚しましたか。", "example_reading": "けっこんしましたか。", "example_meaning_cn": "结婚了吗？", "example_meaning_en": "Are you married?"},
        "N4_289": {"example_sentence": "けつ（月曜）日は忙しいです。", "example_reading": "げつようびはいそがしいです。", "example_meaning_cn": "周一我很忙。", "example_meaning_en": "I'm busy on Monday."},
        "N4_290": {"example_sentence": "けつ（結果）を出してください。", "example_reading": "けっかしてください。", "example_meaning_cn": "请出结果。", "example_meaning_en": "Please produce results."},
        "N4_291": {"example_sentence": "けっ（欠席）席しますか。", "example_reading": "けっせきしますか。", "example_meaning_cn": "要缺席吗？", "example_meaning_en": "Are you going to be absent?"},
        "N4_292": {"example_sentence": "け（決）定しました。", "example_reading": "けっていしました。", "example_meaning_cn": "决定了。", "example_meaning_en": "Decided."},
        "N4_293": {"example_sentence": "げん（原因）がわかりません。", "example_reading": "げんいんがわかりません。", "example_meaning_cn": "原因不明。", "example_meaning_en": "The cause is unknown."},
        "N4_294": {"example_sentence": "けん（見）学に行きましょう。", "example_reading": "けんがくにいきましょう。", "example_meaning_cn": "去观摩（或见学）吧。", "example_meaning_en": "Let's go for a study visit."},
        "N4_295": {"example_sentence": "けん（研究）究に励みます。", "example_reading": "けんきゅうにはげみます。", "example_meaning_cn": "致力于研究。", "example_meaning_en": "I'll strive for research."},
        "N4_296": {"example_sentence": "けん（見物）物に行きました。", "example_reading": "けんぶつにいきました。", "example_meaning_cn": "去游览（或观看）了。", "example_meaning_en": "I went sightseeing."},
        "N4_297": {"example_sentence": "けん（憲法）法を守りましょう。", "example_reading": "けんぽうをまもりましょう。", "example_meaning_cn": "遵守宪法吧。", "example_meaning_en": "Let's follow the constitution."},
        "N4_298": {"example_sentence": "げん（元気）気ですか。", "example_reading": "げんきですか。", "example_meaning_cn": "身体好吗？", "example_meaning_en": "Are you well?"},
        "N4_299": {"example_sentence": "げん（現在）在は二時です。", "example_reading": "げんざいはにじです。", "example_meaning_cn": "现在是两点。", "example_meaning_en": "It is currently two o'clock."},
        "N4_300": {"example_sentence": "けん（見当）当がつきません。", "example_reading": "けんとうがつきません。", "example_meaning_cn": "毫无头绪。", "example_meaning_en": "I have no idea/clue."}
    }

    for item in vocab:
        if item['id'] in enrichment:
            item.update(enrichment[item['id']])

    with open(data_file, 'w', encoding='utf-8') as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

    print(f"Updated items up to N4_300.")

if __name__ == "__main__":
    main()
