import json
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    data_file = os.path.join(project_root, 'jlpt-web', 'src', 'data', 'vocab.json')

    if not os.path.exists(data_file):
        return

    with open(data_file, 'r', encoding='utf-8') as f:
        vocab = json.load(f)

    enrichment = {
        "N2_151": {"example_sentence": "う（（受）う）け（（取）と）ってください。", "example_reading": "うけとってください。", "example_meaning_cn": "请收下（或领取）。", "example_meaning_en": "Please receive/accept it."},
        "N2_152": {"example_sentence": "う（（受）う）け（（持）も）っています。", "example_reading": "うけもっています。", "example_meaning_cn": "正担任（或负责）着。", "example_meaning_en": "I'm in charge of it."},
        "N2_153": {"example_sentence": "（（動）うご）か（（作）く）ってください。", "example_reading": "うごかしてください。", "example_meaning_cn": "请移动（或开动）。", "example_meaning_en": "Please move/operate it."},
        "N2_154": {"example_sentence": "（（潮）うしお）が満ちて（みちて）います。", "example_reading": "うしおがみちています。", "example_meaning_cn": "潮涨了。", "example_meaning_en": "The tide is high."},
        "N2_155": {"example_sentence": "（（失）うしな）いたくないです。", "example_reading": "うしないたくないです。", "example_meaning_cn": "不想失去。", "example_meaning_en": "I don't want to lose it."},
        "N2_156": {"example_sentence": "（（薄）うす）いですね。 ", "example_reading": "うすいですね。", "example_meaning_cn": "真薄（或淡）呢。", "example_meaning_en": "It's thin/faint, isn't it?"},
        "N2_157": {"example_sentence": "うず（（渦）うず）に（に）巻き込まれ（まきこまれ）まし（し）た。", "example_reading": "うずにまきこまれました。", "example_meaning_cn": "卷入了旋涡。", "example_meaning_en": "I was swallowed into the vortex/whirlpool."},
        "N2_158": {"example_sentence": "（（疑）うたが）わないで（で）ください。", "example_reading": "うたがわないでください。", "example_meaning_cn": "请不要怀疑。", "example_meaning_en": "Please don't doubt/suspect it."},
        "N2_159": {"example_sentence": "（（内）うち）へ（へ）入り（はいり）ましょう。", "example_reading": "うちへはいりましょう。", "example_meaning_cn": "进屋吧。", "example_meaning_en": "Let's go inside."},
        "N2_160": {"example_sentence": "（（打）う）ち（（消）け）して（て）ください。", "example_reading": "うちけしてください。", "example_meaning_cn": "请取消（或否定）。", "example_meaning_en": "Please negate/deny it."},
        "N2_161": {"example_sentence": "（（打）う）ち（（明）あ）けて（て）ください。", "example_reading": "うちあけてください。", "example_meaning_cn": "请坦白（或倾诉）。", "example_meaning_en": "Please confide/be open about it."},
        "N2_162": {"example_sentence": "（（打）う）ち（（合）あ）わせ（せ）を（を）し（し）ます。", "example_reading": "うちあわせをします。", "example_meaning_cn": "进行碰头（洽谈）。", "example_meaning_en": "We'll have a preliminary meeting."},
        "N2_163": {"example_sentence": "（（宇宙）うちゅう）へ（へ）行き（いき）たい（たい）です。", "example_reading": "うちゅうへいきたいです。", "example_meaning_cn": "想去宇宙。", "example_meaning_en": "I want to go to space."},
        "N2_164": {"example_sentence": "（（器）うつわ）を（を）洗っ（あらっ）て（て）ください。", "example_reading": "うつわをあらってください。", "example_meaning_cn": "请洗碗（容器）。", "example_meaning_en": "Please wash the vessel/container."},
        "N2_165": {"example_sentence": "（（映）うつ）して（て）ください。", "example_reading": "うつしてください。", "example_meaning_cn": "请映照（或放映）。", "example_meaning_en": "Please reflect/project it."},
        "N2_166": {"example_sentence": "（（写）うつ）して（て）ください。", "example_reading": "うつしてください。", "example_meaning_cn": "请抄写（或照相）。", "example_meaning_en": "Please copy/photograph it."},
        "N2_167": {"example_sentence": "（（描）えが）いて（て）ください。", "example_reading": "えがいてください。", "example_meaning_cn": "请描绘。", "example_meaning_en": "Please depict/sketch it."},
        "N2_168": {"example_sentence": "（（歌）うた）って（て）ください。", "example_reading": "うたってください。", "example_meaning_cn": "请唱歌。", "example_meaning_en": "Please sing."},
        "N2_169": {"example_sentence": "（（訴）うった）え（え）て（て）ください。", "example_reading": "うったえてください。", "example_meaning_cn": "请诉讼（或投诉）。", "example_meaning_en": "Please appeal/sue."},
        "N2_170": {"example_sentence": "うっ（（鬱）うっ）とう（とう）しい（しい）ですね。 ", "example_reading": "うっとうしいですね。", "example_meaning_cn": "真郁闷（或阴沉）呢。", "example_meaning_en": "It's gloomy/annoying, isn't it?"},
        "N2_171": {"example_sentence": "（（写）うつ）って（て）いますか。", "example_reading": "うつっていますか。", "example_meaning_cn": "拍进去了吗？", "example_meaning_en": "Is it shown in the photo?"},
        "N2_172": {"example_sentence": "（（写）うつ）し（し）て（て）ください。", "example_reading": "うつしてください。", "example_meaning_cn": "请抄写（或复印）。", "example_meaning_en": "Please photocopy/duplicate it."},
        "N2_173": {"example_sentence": "うで（（腕）うで）を（を）組ん（くん）で（て）ください。", "example_reading": "うでをくんでください。", "example_meaning_cn": "请交叉双臂。", "example_meaning_en": "Please cross your arms."},
        "N2_174": {"example_sentence": "うど（（饂飩）うどん）を（を）食べ（たべ）ましょう。", "example_reading": "うどんをたべましょう。", "example_meaning_cn": "吃乌冬面吧。", "example_meaning_en": "Let's eat udon."},
        "N2_175": {"example_sentence": "（（促）うなが）して（て）ください。", "example_reading": "うながしてください。", "example_meaning_cn": "请促使（或催促）。", "example_meaning_en": "Please urge/encourage it."},
        "N2_176": {"example_sentence": "（（唸）うな）鳴（な）って（て）います。", "example_reading": "うなっています。", "example_meaning_cn": "正在呻吟（或咆哮）着呢。", "example_meaning_en": "It's moaning/groaning."},
        "N2_177": {"example_sentence": "うな（（頷）うな）ず（ず）いて（て）ください。", "example_reading": "うなずいてください。", "example_meaning_cn": "请点头（表示同意）。", "example_meaning_en": "Please nod."},
        "N2_178": {"example_sentence": "うな（（唸）うな）鳴（な）る（る）声（こえ）が（が）聞こえ（きこえ）ます。", "example_reading": "うなるこえがきこえます。", "example_meaning_cn": "听到了呻吟声。", "example_meaning_en": "I hear a groaning sound."},
        "N2_179": {"example_sentence": "（（自惚）うぬぼ）れ（れ）ないで（で）ください。", "example_reading": "うぬぼれないでください。", "example_meaning_cn": "请不要自负（自恋）。", "example_meaning_en": "Please don't be conceited."},
        "N2_180": {"example_sentence": "（（奪）うば）わないで（で）ください！ ", "example_reading": "うばわないでください！", "example_meaning_cn": "请不要抢走！", "example_meaning_en": "Please don't take it away!"},
        "N2_181": {"example_sentence": "（（馬）うま）に（に）乗っ（のっ）て（て）ください。", "example_reading": "うまにのってください。", "example_meaning_cn": "请骑马。", "example_meaning_en": "Please ride the horse."},
        "N2_182": {"example_sentence": "（（生）う）まれ（れ）て（て）きて（て）ありがとう。", "example_reading": "うまれてきてありがとう。", "example_meaning_cn": "谢谢你出生（到这个世界上）。", "example_meaning_en": "Thank you for being born."},
        "N2_183": {"example_sentence": "（（海）うみ）へ（へ）行き（いき）ましょう。", "example_reading": "うみへいきましょう。", "example_meaning_cn": "去海边吧。", "example_meaning_en": "Let's go to the sea."},
        "N2_184": {"example_sentence": "（（有無）うむ）を（を）言わ（いわ）せ（せ）ず（ず）。", "example_reading": "うむをいわせず。", "example_meaning_cn": "不容分说。", "example_meaning_en": "Whether you like it or not."},
        "N2_185": {"example_sentence": "（（埋）う）め（め）て（て）ください。", "example_reading": "うめてください。", "example_meaning_cn": "请埋掉（或填平）。", "example_meaning_en": "Please bury/fill it up."},
        "N2_186": {"example_sentence": "（（敬）うやま）って（て）ください。", "example_reading": "うやまってください。", "example_meaning_cn": "请尊敬。", "example_meaning_en": "Please respect/venerate them."},
        "N2_187": {"example_sentence": "うら（（裏）うら）を（を）見（み）て（て）ください。", "example_reading": "うらをみてください。", "example_meaning_cn": "请看背面。", "example_meaning_en": "Please look at the back."},
        "N2_188": {"example_sentence": "うら（（裏）うら）返（がえ）し（し）に（に）し（し）て（て）ください。", "example_reading": "うらがえしにしてください。", "example_meaning_cn": "请翻过来。", "example_meaning_en": "Please turn it inside out."},
        "N2_189": {"example_sentence": "（（占）うらな）って（て）ください。", "example_reading": "うらなってください。", "example_meaning_cn": "请算一卦（占卜）。", "example_meaning_en": "Please tell my fortune."},
        "N2_190": {"example_sentence": "（（恨）うら）ま（ま）ないで（で）ください。", "example_reading": "うらまないでください。", "example_meaning_cn": "请不要怨恨。", "example_meaning_en": "Please don't bear a grudge."},
        "N2_191": {"example_sentence": "（（羨）うらや）ましい（しい）ですね！", "example_reading": "うらやましいですね！", "example_meaning_cn": "真令人羡慕呢！", "example_meaning_en": "I'm so jealous!"},
        "N2_192": {"example_sentence": "う（（売）う）り（（切）き）れ（れ）まし（し）た。", "example_reading": "うりきれました。", "example_meaning_cn": "卖光了（售罄）。", "example_meaning_en": "It's sold out."},
        "N2_193": {"example_sentence": "う（（売）う）り（（出）だ）し（し）て（て）います。", "example_reading": "うりだしています。", "example_meaning_cn": "正在发售（或上市）。", "example_meaning_en": "It's on sale/launching."},
        "N2_194": {"example_sentence": "う（（売）う）る（る）さい（さい）ですよ！", "example_reading": "うるさいですよ！", "example_meaning_cn": "太吵了（烦人）！", "example_meaning_en": "You're being noisy/shut up!"},
        "N2_195": {"example_sentence": "（（潤）うるお）い（い）を（を）与え（あたえ）て（て）ください。", "example_reading": "うるおいをあたえてください。", "example_meaning_cn": "请给予滋润。", "example_meaning_en": "Please provide moisture/richness."},
        "N2_196": {"example_sentence": "うれ（（売）うれ）っ（っ）こ（こ）ですね。", "example_reading": "うれっこですね。", "example_meaning_cn": "是大红人（红极一时）呢。", "example_meaning_en": "They are popular/in demand, aren't they?"},
        "N2_197": {"example_sentence": "（（嬉）うれ）しい（しい）です！ ", "example_reading": "うれしいです！", "example_meaning_cn": "太开心了！", "example_meaning_en": "I'm so happy!"},
        "N2_198": {"example_sentence": "うわ（（噂）うわ）さ（さ）を（を）し（し）て（て）い（い）ました。", "example_reading": "うわさをしていました。", "example_meaning_cn": "正在议论（传谣言）。", "example_meaning_en": "We were just talking about the rumor."},
        "N2_199": {"example_sentence": "うわ（（上）うわ）手（て）に（に）出（で）て（て）ください。", "example_reading": "うわてにでてください。", "example_meaning_cn": "请棋高一着（占上风）。", "example_meaning_en": "Please get the upper hand."},
        "N2_200": {"example_sentence": "（（運）うん）が（が）いい（いい）ですね。", "example_reading": "うんがいいですね。", "example_meaning_cn": "运气真好呢。", "example_meaning_en": "You're lucky, aren't you?"},
        "N2_201": {"example_sentence": "（（運）うん）えい（えい）し（し）て（て）います。", "example_reading": "うんえいしています。", "example_meaning_cn": "正在经营（或运营）着。", "example_meaning_en": "It's being operated/managed."},
        "N2_202": {"example_sentence": "（（運）うん）が（が）に（に）沿っ（そっ）て（て）歩き（あるき）ます。", "example_reading": "うんがにそってあるきます。", "example_meaning_cn": "沿着运河走。", "example_meaning_en": "I'll walk along the canal."},
        "N2_203": {"example_sentence": "（（運）うん）ちん（ちん）を（を）払っ（はらっ）て（て）ください。", "example_reading": "うんちんをはらってください。", "example_meaning_cn": "请付运费（或车费）。", "example_meaning_en": "Please pay the fare/shipping fee."},
        "N2_204": {"example_sentence": "（（運）うん）てん（てん）し（し）て（て）ください。", "example_reading": "うんてんしてください。", "example_meaning_cn": "请驾驶。", "example_meaning_en": "Please drive."},
        "N2_205": {"example_sentence": "（（運）うん）ど（ど）う（う）し（し）ましょう。", "example_reading": "うんどうしましょう。", "example_meaning_cn": "运动一下吧。", "example_meaning_en": "Let's exercise."},
        "N2_206": {"example_sentence": "（（運）うん）ぱ（ぱ）ん（ん）し（し）て（て）ください。", "example_reading": "うんぱんしてください。", "example_meaning_cn": "请搬运（运输）。", "example_meaning_en": "Please transport it."},
        "N2_207": {"example_sentence": "（（運）うん）よ（よ）う（う）し（し）て（て）ください。", "example_reading": "うんようしてください。", "example_meaning_cn": "请运用（或使用）。", "example_meaning_en": "Please utilize/operate it."},
        "N2_208": {"example_sentence": "（（会）え）し（し）ゃ（ゃ）く（く）し（し）てください。", "example_reading": "えしゃくしてください。", "example_meaning_cn": "请点头（行礼）。", "example_meaning_en": "Please make a slight bow."},
        "N2_209": {"example_sentence": "（（柄）え）を（を）持っ（もっ）て（て）ください。", "example_reading": "えをもってください。", "example_meaning_cn": "请握住柄。", "example_meaning_en": "Please hold the handle."},
        "N2_210": {"example_sentence": "え（（永遠）えいえん）の（の）愛（あい）を（を）誓客（せいかく）し（し）ます。", "example_reading": "えいえんのあいをちかいます。", "example_meaning_cn": "誓言永恒之爱。", "example_meaning_en": "Vowing eternal love."},
        "N2_211": {"example_sentence": "えい（（影）えい）き（き）ょう（ょう）を（を）受け（うけ）ないで（で）ください。", "example_reading": "えいきょうをうけないでください。", "example_meaning_cn": "请不要受影响。", "example_meaning_en": "Please don't be influenced."},
        "N2_212": {"example_sentence": "えい（（営）えい）ぎょ（ぎょ）う（う）し（し）て（て）いますか。", "example_reading": "えいぎょうしていますか。", "example_meaning_cn": "营业中吗？", "example_meaning_en": "Are you open for business?"},
        "N2_213": {"example_sentence": "えい（（衛）えい）せ（せい）に（に）気（き）を（を）つけ（つけ）ましょう。", "example_reading": "えいせいにきをつけましょう。", "example_meaning_cn": "注意卫生吧。", "example_meaning_en": "Let's mind the hygiene."},
        "N2_214": {"example_sentence": "えい（（栄）えい）ぞ（ぞ）う（う）を（を）見（み）て（て）ください。", "example_reading": "えいぞうをみてください。", "example_meaning_cn": "请看影像（或画面）。", "example_meaning_en": "Please look at the video/image."},
        "N2_215": {"example_sentence": "えい（英雄）ゆう（ゆう）になり（なり）たい（たい）です。", "example_reading": "えいゆうになりたいです。", "example_meaning_cn": "想成为英雄。", "example_meaning_en": "I want to be a hero."},
        "N2_216": {"example_sentence": "え（（液）えき）を（を）入れ（いれ）て（て）ください。", "example_reading": "えきをいれてください。", "example_meaning_cn": "请注入液体。", "example_meaning_en": "Please pour the liquid in."},
        "N2_217": {"example_sentence": "えき（（液体）たい）を（を）混ぜ（まぜ）て（て）ください。", "example_reading": "えきたいをまぜてください。", "example_meaning_cn": "请混合液体。", "example_meaning_en": "Please mix the liquids."},
        "N2_218": {"example_sentence": "えき（（役）えき）を（を）演じ（えんじ）て（て）ください。", "example_reading": "えきをえんじてください。", "example_meaning_cn": "请演这个角色。", "example_meaning_en": "Please play the role."},
        "N2_219": {"example_sentence": "エ（え）コ（こ）ロ（ろ）ジ（じ）ー（ー）を（を）考え（かんがえ）ましょう。", "example_reading": "エコロジーをかんがえましょう。", "example_meaning_cn": "考虑一下生态平衡（环保）吧。", "example_meaning_en": "Let's think about ecology."},
        "N2_220": {"example_sentence": "え（（餌）えさ）を（を）与え（あたえ）て（て）ください。", "example_reading": "えさをあたえてください。", "example_meaning_cn": "请喂食（饵料）。", "example_meaning_en": "Please feed them."},
        "N2_221": {"example_sentence": "エ（え）ネ（ね）ル（る）ギ（ぎ）ー（ー）を（を）節約（せつやく）し（し）ましょう。", "example_reading": "エネルギーをせつやくしましょう。", "example_meaning_cn": "节约能源吧。", "example_meaning_en": "Let's save energy."},
        "N2_222": {"example_sentence": "え（（得）え）ら（ら）れ（れ）る（る）利（り）え（え）き（き）は？", "example_reading": "えられるりえきは？", "example_meaning_cn": "能获得的利益是？", "example_meaning_en": "What is the profit to be gained?"},
        "N2_223": {"example_sentence": "えら（（偉）えら）い（い）ですね！", "example_reading": "えらいですね！", "example_meaning_cn": "真了不起（或伟大）呢！", "example_meaning_en": "You're great/admirable!"},
        "N2_224": {"example_sentence": "え（（選）えら）んで（て）ください。", "example_reading": "えらんでください。", "example_meaning_cn": "请选择。", "example_meaning_en": "Please choose."},
        "N2_225": {"example_sentence": "エリ（えり）あ（あ）を（を）確認（かくにん）し（し）て（て）ください。", "example_reading": "エリアをかくにんしてください。", "example_meaning_cn": "请确认区域（范围）。", "example_meaning_en": "Please confirm the area."},
        "N2_226": {"example_sentence": "え（（縁）えん）が（が）あり（あり）ますね。", "example_reading": "えんがありますね。", "example_meaning_cn": "真有缘分呢。", "example_meaning_en": "We have a connection/fate, don't we?"},
        "N2_227": {"example_sentence": "えん（（園）えん）へ（へ）遊び（あそび）に（に）行き（いき）ましょう。", "example_reading": "えんへあそびにいきましょう。", "example_meaning_cn": "去园内玩吧。", "example_meaning_en": "Let's go play at the park/garden."},
        "N2_228": {"example_sentence": "えん（（演）えん）しゅ（しゅ）つ（つ）し（し）て（て）ください。", "example_reading": "えんしゅつしてください。", "example_meaning_cn": "请演出（或策划）。", "example_meaning_en": "Please direct/produce it."},
        "N2_229": {"example_sentence": "えん（（演）えん）じょ（じょ）し（し）て（て）ください。", "example_reading": "えんじょしてください。", "example_meaning_cn": "请援助。", "example_meaning_en": "Please assist/aid."},
        "N2_230": {"example_sentence": "えん（（演）えん）ぜ（ぜ）つ（つ）を（を）し（し）ます。", "example_reading": "えんぜつをします。", "example_meaning_cn": "进行演说。", "example_meaning_en": "I'll give a speech."},
        "N2_231": {"example_sentence": "えん（（演）えん）ぞ（ぞ）う（う）を（を）聴い（きい）て（て）ください。", "example_reading": "えんそうをきいてください。", "example_meaning_cn": "请听演奏。", "example_meaning_en": "Please listen to the performance."},
        "N2_232": {"example_sentence": "えん（（遠）えん）り（り）ょ（ょ）し（し）ないで（で）ください。", "example_reading": "えんりょしないでください。", "example_meaning_cn": "请不要客气。", "example_meaning_en": "Please don't hesitate."},
        "N2_233": {"example_sentence": "（（御）お）いで（で）ください。", "example_reading": "おいでください。", "example_meaning_cn": "请过来（或光临）。", "example_meaning_en": "Please come/visit."},
        "N2_234": {"example_sentence": "（（追）お）いこ（こ）し（し）て（て）ください。", "example_reading": "おいこしてください。", "example_meaning_cn": "请超越（超车）。", "example_meaning_en": "Please overtake it."},
        "N2_235": {"example_sentence": "（（追）お）い（い）だ（だ）し（し）て（て）ください。", "example_reading": "おいだしてください。", "example_meaning_cn": "请赶出去。", "example_meaning_en": "Please drive them out."},
        "N2_236": {"example_sentence": "おい（（於）お）い（い）に（に）やり（やり）ま（ま）しょう。", "example_reading": "おいにやりましょう。", "example_meaning_cn": "渐渐地做吧。", "example_meaning_en": "Let's do it gradually."},
        "N2_237": {"example_sentence": "（（追）お）い（い）つ（つ）い（い）て（て）ください。", "example_reading": "おいついてください。", "example_meaning_cn": "请追上（赶上）。", "example_meaning_en": "Please catch up."},
        "N2_238": {"example_sentence": "オ（お）ウ（う）ケ（け）ー（ー）です。", "example_reading": "オーケーです。", "example_meaning_cn": "没问题（OK）。", "example_meaning_en": "It's OK."},
        "N2_239": {"example_sentence": "（（王）おう）さま（さま）になり（なり）たい（たい）です。", "example_reading": "おうさまになりたいです。", "example_meaning_cn": "想当国王。", "example_meaning_en": "I want to become a king."},
        "N2_240": {"example_sentence": "（（黄）おう）ごん（ごん）の（の）時代（じだい）です。", "example_reading": "おうごんのじだいです。", "example_meaning_cn": "黄金时代。", "example_meaning_en": "The golden age."},
        "N2_241": {"example_sentence": "（（応）おう）じ（じ）て（て）ください。", "example_reading": "おうじてください。", "example_meaning_cn": "请响应（或对应）。", "example_meaning_en": "Please respond/comply."},
        "N2_242": {"example_sentence": "（（応）おう）せ（せ）つ（つ）ま（ま）で（で）待っ（まっ）て（て）ください。", "example_reading": "おうせつまてまってください。", "example_meaning_cn": "请在会客室等待。", "example_meaning_en": "Please wait in the reception room."},
        "N2_243": {"example_sentence": "（（応）おう）だん（だん）し（し）て（て）ください。", "example_reading": "おうだんしてください。", "example_meaning_cn": "请横过（横段）。", "example_meaning_en": "Please cross/traverse it."},
        "N2_244": {"example_sentence": "（（終）お）え（え）て（て）ください。", "example_reading": "おえてください。", "example_meaning_cn": "请完成（结束）。", "example_meaning_en": "Please finish it."},
        "N2_245": {"example_sentence": "（（覆）おお）っ（っ）て（て）ください。", "example_reading": "おおってください。", "example_meaning_cn": "请盖住。", "example_meaning_en": "Please cover it."},
        "N2_246": {"example_sentence": "（（大）おお）ど（（通）どお）り（り）を（を）歩き（あるき）ます。", "example_reading": "おおどおりをあるきます。", "example_meaning_cn": "在大道上走。", "example_meaning_en": "I'll walk on the main street."},
        "N2_247": {"example_sentence": "オートマチック（おーとまちっく）車（しゃ）です。", "example_reading": "オートマチックしゃです。", "example_meaning_cn": "是自动档车。", "example_meaning_en": "It's an automatic car."},
        "N2_248": {"example_sentence": "お（（大）おお）や（や）を（を）大切（たいせつ）に（に）し（し）ましょう。", "example_reading": "おやをたいせつにしましょう。", "example_meaning_cn": "孝敬父母（老板）吧。", "example_meaning_en": "Let's value our parents/landlord."},
        "N2_249": {"example_sentence": "お（（起）お）き（き）て（て）ください！ ", "example_reading": "おきてください！", "example_meaning_cn": "请起床！", "example_meaning_en": "Please wake up!"},
        "N2_250": {"example_sentence": "（（補）おぎな）って（て）ください。", "example_reading": "おぎなってください。", "example_meaning_cn": "请补充。", "example_meaning_en": "Please supplement/compensate for it."},
        "N2_251": {"example_sentence": "（（置）お）き（き）っぱなし（なし）に（に）し（し）ないで（で）ください。", "example_reading": "おきっぱなしにしないでください。", "example_meaning_cn": "请不要乱放（放着不理）。", "example_meaning_en": "Please don't leave it lying around."},
        "N2_252": {"example_sentence": "（（送）おく）り（り）ます。", "example_reading": "おくります。", "example_meaning_cn": "发送（或寄）。", "example_meaning_en": "I'll send it."},
        "N2_253": {"example_sentence": "（（贈）おく）り（り）ます。", "example_reading": "おくります。", "example_meaning_cn": "赠送（礼物）。", "example_meaning_en": "I'll present/gift it."},
        "N2_254": {"example_sentence": "（（慢）おく）れ（れ）ないで（で）ください。", "example_reading": "おれないでください。", "example_meaning_cn": "请不要迟到。", "example_meaning_en": "Please don't be late."},
        "N2_255": {"example_sentence": "（（起）お）こ（こ）し（し）て（て）ください。", "example_reading": "おこしてください。", "example_meaning_cn": "请叫醒我（或引起）。", "example_meaning_en": "Please wake me up/cause it."},
        "N2_256": {"example_sentence": "（（行）おこな）い（い）を（を）慎み（つつしみ）ましょう。", "example_reading": "おこないをつつしみましょう。", "example_meaning_cn": "约束行为吧。", "example_meaning_en": "Let's mind our behavior."},
        "N2_257": {"example_sentence": "（（行）おこな）い（い）を（を）正し（ただし）て（て）ください。", "example_reading": "おこないをただしてください。", "example_meaning_cn": "请端正行为。", "example_meaning_en": "Please correct your behavior."},
        "N2_258": {"example_sentence": "（（怒）おこ）らせ（せ）ないで（で）ください。", "example_reading": "おこらせないでください。", "example_meaning_cn": "请不要惹我生气。", "example_meaning_en": "Please don't make me angry."},
        "N2_259": {"example_sentence": "（（抑）おさ）え（え）て（て）ください。", "example_reading": "おさえてください。", "example_meaning_cn": "请按住（或压抑）。", "example_meaning_en": "Please suppress/hold it down."},
        "N2_260": {"example_sentence": "（（納）おさ）めて（て）ください。", "example_reading": "おさめてください。", "example_meaning_cn": "请交纳（或安放）。", "example_meaning_en": "Please pay/accept/store it."},
        "N2_261": {"example_sentence": "お（（教）おし）え（え）て（て）ください。", "example_reading": "おしえてください。", "example_meaning_cn": "请教我。", "example_meaning_en": "Please teach me."},
        "N2_262": {"example_sentence": "（（惜）お）し（し）い（い）ですね。 ", "example_reading": "おしいですね。", "example_meaning_cn": "真可惜（或遗憾）呢。", "example_meaning_en": "It's a pity/regrettable, isn't it?"},
        "N2_263": {"example_sentence": "お（（辞儀）じぎ）し（し）て（て）ください。", "example_reading": "おじぎしてください。", "example_meaning_cn": "请鞠躬行礼。", "example_meaning_en": "Please bow."},
        "N2_264": {"example_sentence": "（（押）お）し（し）つけ（つけ）ないで（で）ください。", "example_reading": "おしつけないでください。", "example_meaning_cn": "请不要强加（或推卸）。", "example_meaning_en": "Please don't force it upon me."},
        "N2_265": {"example_sentence": "お（（洒落）しゃれ）ですね！", "example_reading": "おしゃれですね！", "example_meaning_cn": "真时髦呢！", "example_meaning_en": "How fashionable!"},
        "N2_266": {"example_sentence": "（（押）お）し（し）入れ（いれ）に（に）しまい（しまい）ます。", "example_reading": "おしいれにしまいます。", "example_meaning_cn": "收进壁橱里。", "example_meaning_en": "I'll put it in the closet."},
        "N2_267": {"example_sentence": "（（教）おそ）わっ（わっ）き（き）て（て）ください。", "example_reading": "おそわってきてください。", "example_meaning_cn": "请去请教一下。", "example_meaning_en": "Please go and be taught."},
        "N2_268": {"example_sentence": "（（襲）おそ）われ（れ）ました！ ", "example_reading": "おそわれました！", "example_meaning_cn": "被袭击了！", "example_meaning_en": "I was attacked!"},
        "N2_269": {"example_sentence": "（（遅）おそ）い（い）ですね。 ", "example_reading": "おそいですね。", "example_meaning_cn": "真晚（或慢）呢。", "example_meaning_en": "It's late/slow, isn't it?"},
        "N2_270": {"example_sentence": "（（恐）おそ）ろしい（しい）ですね...", "example_reading": "おそろしいですね。", "example_meaning_cn": "真可怕（或恐怖）呢...", "example_meaning_en": "How terrifying."},
        "N2_271": {"example_sentence": "お（（互）たが）いに（に）助け合いましょう。", "example_reading": "おたがいにたすけあいましょう。", "example_meaning_cn": "互相帮助吧。", "example_meaning_en": "Let's help each other."},
        "N2_272": {"example_sentence": "お（（穏）おだ）やかな（な）日（ひ）です。", "example_reading": "おだやかなひです。", "example_meaning_cn": "和平安宁的一天。", "example_meaning_en": "It's a calm day."},
        "N2_273": {"example_sentence": "（（落）お）ち（ち）つき（つき）な（な）さい（さい）！ ", "example_reading": "おちつきなさい！", "example_meaning_cn": "给我冷静点！", "example_meaning_en": "Calm down!"},
        "N2_274": {"example_sentence": "おっ（（追）おっ）てください！ ", "example_reading": "おってください！", "example_meaning_cn": "请追赶！", "example_meaning_en": "Please chase them!"},
        "N2_275": {"example_sentence": "おっ（（夫）おっ）とは（は）誰（だれ）です（す）か。", "example_reading": "おっとわだれですか。", "example_meaning_cn": "丈夫是谁？", "example_meaning_en": "Who is the husband?"},
        "N2_276": {"example_sentence": "（（落）お）と（と）し（し）もの（もの）を（を）し（し）まし（し）た。", "example_reading": "おとしものをしました。", "example_meaning_cn": "丢东西了。", "example_meaning_en": "I lost something."},
        "N2_277": {"example_sentence": "お（（訪）おとず）れ（れ）て（て）ください。", "example_reading": "おとずれてください。", "example_meaning_cn": "请拜访。", "example_meaning_en": "Please visit."},
        "N2_278": {"example_sentence": "（（衰）おとろ）え（え）を（を）感じ（かんじ）ます。", "example_reading": "おとろえをかんじます。", "example_meaning_cn": "感到衰老。", "example_meaning_en": "I feel a decline."},
        "N2_279": {"example_sentence": "（（驚）おどろ）き（き）ました！ ", "example_reading": "おどろきました！", "example_meaning_cn": "大吃一惊！", "example_meaning_en": "I was surprised!"},
        "N2_280": {"example_sentence": "おな（（同）おな）じ（じ）です（す）か。", "example_reading": "おなじですか。", "example_meaning_cn": "一样吗？", "example_meaning_en": "Is it the same?"},
        "N2_281": {"example_sentence": "（（怯）おび）えない（ない）で（で）ください。", "example_reading": "おびえないでください。", "example_meaning_cn": "请不要害怕。", "example_meaning_en": "Please don't be frightened."},
        "N2_282": {"example_sentence": "お（（標）お）び（び）を（を）締め（しめ）て（て）ください。", "example_reading": "おびをしめてください。", "example_meaning_cn": "请系好带子。", "example_meaning_en": "Please tie the obi/belt."},
        "N2_283": {"example_sentence": "オ（お）ペ（ぺ）を（を）し（し）ます。", "example_reading": "オペをします。", "example_meaning_cn": "进行手术。", "example_meaning_en": "Performing surgery."},
        "N2_284": {"example_sentence": "お（（参）ま）り（り）し（し）て（て）ください。", "example_reading": "おまいりしてください。", "example_meaning_cn": "请参拜。", "example_meaning_en": "Please go and pray at the shrine."},
        "N2_285": {"example_sentence": "お（（負）ま）け（け）の（の）品（しな）です。", "example_reading": "おまけのしなです。", "example_meaning_cn": "赠品。", "example_meaning_en": "It's a free gift/extra."},
        "N2_286": {"example_sentence": "オ（お）マ（ま）ジ（じ）ュ（ゅ）を（を）捧げ（ささげ）ます。", "example_reading": "オマージュをささげます。", "example_meaning_cn": "致敬。", "example_meaning_en": "Pay homage to."},
        "N2_287": {"example_sentence": "お（（思）おも）い（い）き（き）っ（っ）て（て）ください。", "example_reading": "おもいきってください。", "example_meaning_cn": "请下定决心。", "example_meaning_en": "Please be decisive/take the plunge."},
        "N2_288": {"example_sentence": "お（（思）おも）い（い）こ（こ）み（み）が（が）激しい（はげしい）です。", "example_reading": "おもいこみがはげしいです。", "example_meaning_cn": "成见很深。", "example_meaning_en": "I'm very prone to preconceptions."},
        "N2_289": {"example_sentence": "お（（思）おも）い（い）だ（だ）し（し）（（笑）わら）い（い）し（し）ます。", "example_reading": "おもいだしわらいします。", "example_meaning_cn": "想起往事发笑。", "example_meaning_en": "Laughing at a memory."},
        "N2_290": {"example_sentence": "お（（思）おも）い（い）つ（つ）き（き）で（で）言い（いい）まし（し）た。", "example_reading": "おもいつきでいいました。", "example_meaning_cn": "一时兴起说出的。", "example_meaning_en": "I said it on an impulse/whim."},
        "N2_291": {"example_sentence": "お（（思）おも）い（い）やり（やり）を（を）持っ（もっ）て（て）ください。", "example_reading": "おもいやりをもってください。", "example_meaning_cn": "请怀有同情心（体谅）。", "example_meaning_en": "Please be considerate."},
        "N2_292": {"example_sentence": "お（（重）おも）い（い）き（き）り（り）泣い（ない）て（て）ください。", "example_reading": "おもいきりないてください。", "example_meaning_cn": "请尽情哭一场。", "example_meaning_en": "Please cry your heart out."},
        "N2_293": {"example_sentence": "お（（重）おも）じ（じ）ゃ（ゃ）を（を）運ん（はこん）で（て）ください。", "example_reading": "おもちゃをはこんでください。", "example_meaning_cn": "请搬运玩具。", "example_meaning_en": "Please carry the toys."},
        "N2_294": {"example_sentence": "おも（（表）おも）て（て）を（を）見（み）て（て）ください。", "example_reading": "おもてをみてください。", "example_meaning_cn": "请看表面（或外面/正脸）。", "example_meaning_en": "Please look at the surface/outside."},
        "N2_295": {"example_sentence": "お（（重）おも）な（な）理由（りゆう）を（を）教え（おしえ）て（て）ください。", "example_reading": "おなりゆうをおしえてください。", "example_meaning_cn": "请告诉主要理由。", "example_meaning_en": "Please tell me the main reason."},
        "N2_296": {"example_sentence": "お（（重）おも）に（に）これ（これ）を（を）使い（つかい）ます。", "example_reading": "おもにこれをつかいます。", "example_meaning_cn": "主要使用这个。", "example_meaning_en": "I mainly use this."},
        "N2_297": {"example_sentence": "お（（思）おも）わ（わ）ず（ず）笑い（わらい）まし（し）た。", "example_reading": "おもわずわらいました。", "example_meaning_cn": "情不自禁地笑了。", "example_meaning_en": "I laughed in spite of myself."},
        "N2_298": {"example_sentence": "（（及）およ）ば（ば）ない（ない）で（で）ください。", "example_reading": "およばないでください。", "example_meaning_cn": "请不要波及（或赶不上）。", "example_meaning_en": "Please don't reach/extend to it."},
        "N2_299": {"example_sentence": "（（及）およ）ぼ（ぼ）して（て）います。", "example_reading": "およぼしています。", "example_meaning_cn": "正在产生影响（波及）。", "example_meaning_en": "It's exerting an influence."},
        "N2_300": {"example_sentence": "オ（お）リ（り）ジ（じ）ナ（な）ル（る）を（を）作っ（つくっ）て（て）ください。", "example_reading": "オリジナルをつくってください。", "example_meaning_cn": "请制作原创作品。", "example_meaning_en": "Please create something original."}
    }

    for item in vocab:
        if item['id'] in enrichment:
            item.update(enrichment[item['id']])

    with open(data_file, 'w', encoding='utf-8') as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

    print(f"Updated items up to N2_300.")

if __name__ == "__main__":
    main()
