import json
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    data_file = os.path.join(project_root, 'jlpt-web', 'src', 'data', 'vocab.json')

    if not os.path.exists(data_file):
        return

    with open(data_file, 'r', encoding='utf-8') as f:
        vocab = json.load(f)

    enrichment = {
        "N3_451": {"example_sentence": "（下）ってください。", "example_reading": "くだってください。", "example_meaning_cn": "请下去（或走下）。", "example_meaning_en": "Please go down."},
        "N3_452": {"example_sentence": "くたび（草臥）れましたね。", "example_reading": "くたびれましたね。", "example_meaning_cn": "累（疲惫）了吧。", "example_meaning_en": "You're tired, aren't you?"},
        "N3_453": {"example_sentence": "くだらない（下らない）ですね。 ", "example_reading": "くだらないですね。", "example_meaning_cn": "真无聊呢。", "example_meaning_en": "It's trivial/useless, isn't it?"},
        "N3_454": {"example_sentence": "くだ（下）してください。", "example_reading": "くだしてください。", "example_meaning_cn": "请赐予（或下决定）。", "example_meaning_en": "Please bestow/decide/give it."},
        "N3_455": {"example_sentence": "くち（口）を閉じてください。", "example_reading": "くちをとじてください。", "example_meaning_cn": "请闭嘴。", "example_meaning_en": "Please close your mouth."},
        "N3_456": {"example_sentence": "くつ（靴）を履いてください。", "example_reading": "くつをはいてください。", "example_meaning_cn": "请穿鞋。", "example_meaning_en": "Please put on your shoes."},
        "N3_457": {"example_sentence": "くつ（靴）下（した）を履きます。", "example_reading": "くつしたをはきます。", "example_meaning_cn": "穿袜子。", "example_meaning_en": "I'll put on socks."},
        "N3_458": {"example_sentence": "くつろ（寛）いでください。", "example_reading": "くつろいでください。", "example_meaning_cn": "请随意（放松）。", "example_meaning_en": "Please relax/make yourself at home."},
        "N3_459": {"example_sentence": "（国）の外に出ます。", "example_reading": "くにのそとにでます。", "example_meaning_cn": "去国外。", "example_meaning_en": "I'm going out of the country."},
        "N3_460": {"example_sentence": "くば（配）ってください。", "example_reading": "くばってください。", "example_meaning_cn": "请分发。", "example_meaning_en": "Please distribute it."},
        "N3_461": {"example_sentence": "くび（首）が痛いです。", "example_reading": "くびがいたいです。", "example_meaning_cn": "脖子疼。", "example_meaning_en": "My neck hurts."},
        "N3_462": {"example_sentence": "く（工夫）ふうしてください。", "example_reading": "くふうしてください。", "example_meaning_cn": "请动动脑筋（下工夫）。", "example_meaning_en": "Please find a way/be creative."},
        "N3_463": {"example_sentence": "くぶん（区分）してください。", "example_reading": "くぶんしてください。", "example_meaning_cn": "请划分。", "example_meaning_en": "Please categorize it."},
        "N3_464": {"example_sentence": "く（組）み合わせてください。", "example_reading": "くみあわせてください。", "example_meaning_cn": "请组合。", "example_meaning_en": "Please combine them."},
        "N3_465": {"example_sentence": "くも（雲）が浮かんでいます。", "example_reading": "くもがうかんでいます。", "example_meaning_cn": "云在飘浮。", "example_meaning_en": "Clouds are floating."},
        "N3_466": {"example_sentence": "くも（曇）ってきました。", "example_reading": "くもってきました。", "example_meaning_cn": "天阴了。", "example_meaning_en": "It's getting cloudy."},
        "N3_467": {"example_sentence": "くら（暗）いですね。 ", "example_reading": "くらいですね。", "example_meaning_cn": "真黑（暗）呢。", "example_meaning_en": "It's dark, isn't it?"},
        "N3_468": {"example_sentence": "くら（暮）らしてください。", "example_reading": "くらしてください。", "example_meaning_cn": "请生活。", "example_meaning_en": "Please live/spend time."},
        "N3_469": {"example_sentence": "くら（比）べてください。", "example_reading": "くらべてください。", "example_meaning_cn": "请比较。", "example_meaning_en": "Please compare them."},
        "N3_470": {"example_sentence": "くる（来）るのが遅いです。", "example_reading": "くるのがおそいです。", "example_meaning_cn": "来得太慢了。", "example_meaning_en": "You're slow to come."},
        "N3_471": {"example_sentence": "くる（車）まで行きます。", "example_reading": "くるまでいきます。", "example_meaning_cn": "开车去。", "example_meaning_en": "I'll go by car."},
        "N3_472": {"example_sentence": "くる（苦）しいです。", "example_reading": "くるしいです。", "example_meaning_cn": "痛苦。", "example_meaning_en": "I'm in pain/suffering."},
        "N3_473": {"example_sentence": "くる（狂）っています！ ", "example_reading": "くるっています！", "example_meaning_cn": "疯了（出故障）了！", "example_meaning_en": "It's crazy/malfunctioning!"},
        "N3_474": {"example_sentence": "くる（包）んでください。", "example_reading": "くるんでください。", "example_meaning_cn": "请包起来。", "example_meaning_en": "Please wrap it up."},
        "N3_475": {"example_sentence": "くれ（暮）に会いましょう。", "example_reading": "くれにあいましょう。", "example_meaning_cn": "年底见吧。", "example_meaning_en": "Let's meet at the end of the year."},
        "N3_476": {"example_sentence": "くれ（呉）れるんですか。", "example_reading": "くれるんですか。", "example_meaning_cn": "是要给我吗？", "example_meaning_en": "Are you giving it to me?"},
        "N3_477": {"example_sentence": "く（黒）い服が好きです。", "example_reading": "くろいふくがすきです。", "example_meaning_cn": "喜欢黑色衣服。", "example_meaning_en": "I like black clothes."},
        "N3_478": {"example_sentence": "くろう（苦労）しましたね。", "example_reading": "くろうしましたね。", "example_meaning_cn": "受苦（辛苦）了呢。", "example_meaning_en": "You've been through a lot, haven't you?"},
        "N3_479": {"example_sentence": "くわ（加）えてください。", "example_reading": "くわえてください。", "example_meaning_cn": "请加上（或含在嘴里）。", "example_meaning_en": "Please add it/hold it in your mouth."},
        "N3_480": {"example_sentence": "くわ（詳）しいですね！", "example_reading": "くわしいですね！", "example_meaning_cn": "真详细呢（或很了解）！", "example_meaning_en": "How detailed/knowledgeable!"},
        "N3_481": {"example_sentence": "ぐん（軍）隊（たい）に入ります。", "example_reading": "ぐんたいにはいります。", "example_meaning_cn": "参军。", "example_meaning_en": "I'm joining the military."},
        "N3_482": {"example_sentence": "け（毛）が抜けます。", "example_reading": "けがぬけます。", "example_meaning_cn": "掉毛（或掉发）。", "example_meaning_en": "The hair is falling out."},
        "N3_483": {"example_sentence": "けい（計画）画（かく）を立てます。", "example_reading": "けいかくをたてます。", "example_meaning_cn": "制定计划。", "example_meaning_en": "I'll make a plan."},
        "N3_484": {"example_sentence": "けい（景）官（かん）に聞いてください。", "example_reading": "けいかんにきいてください。", "example_meaning_cn": "请咨询警官。", "example_meaning_en": "Please ask the police officer."},
        "N3_485": {"example_sentence": "けい（経験）験を積んでください。", "example_reading": "けいけんをつんでください。", "example_meaning_cn": "请积累经验。", "example_meaning_en": "Please gain experience."},
        "N3_486": {"example_sentence": "けい（敬語）語を使ってください。", "example_reading": "けいごをつかってください。", "example_meaning_cn": "请用敬语。", "example_meaning_en": "Please use polite language/honorifics."},
        "N3_487": {"example_sentence": "けい（経済）済が良くなりました。", "example_reading": "けいざいがよくないました。", "example_meaning_cn": "经济变好了。", "example_meaning_en": "The economy has improved."},
        "N3_488": {"example_sentence": "けい（掲示）示を見てください。", "example_reading": "けいじをみてください。", "example_meaning_cn": "请看告示。", "example_meaning_en": "Please look at the notice."},
        "N3_489": {"example_sentence": "けい（刑）事（じ）ドラマが好きです。", "example_reading": "けいじどらまがすきです。", "example_meaning_cn": "喜欢刑侦剧。", "example_meaning_en": "I like detective dramas."},
        "N3_490": {"example_sentence": "けい（継）続（ぞく）してください。", "example_reading": "けいぞくしてください。", "example_meaning_cn": "请继续（坚持）。", "example_meaning_en": "Please continue it."},
        "N3_491": {"example_sentence": "けい（競）馬（ば）で勝ちました。", "example_reading": "けいばでかちました。", "example_meaning_cn": "赛马赢了。", "example_meaning_en": "I won at the horse races."},
        "N3_492": {"example_sentence": "けい（警備）備が厳しいです。", "example_reading": "けいびがきびしいです。", "example_meaning_cn": "保安（戒备）很严。", "example_meaning_en": "Security is tight."},
        "N3_493": {"example_sentence": "けい（刑罰）罰を受けます。", "example_reading": "けいばつをうけます。", "example_meaning_cn": "受刑罚。", "example_meaning_en": "Punishment is received."},
        "N3_494": {"example_sentence": "けい（契約）約を交わします。", "example_reading": "けいやくをかわします。", "example_meaning_cn": "签合同。", "example_meaning_en": "I'll sign the contract."},
        "N3_495": {"example_sentence": "けい（経由）由してください。", "example_reading": "けいゆしてください。", "example_meaning_cn": "请经由（经过）。", "example_meaning_en": "Please go via/through it."},
        "N3_496": {"example_sentence": "け（怪）我（が）をしました。", "example_reading": "けがをしました。", "example_meaning_cn": "受伤了。", "example_meaning_en": "I got injured."},
        "N3_497": {"example_sentence": "け（劇）場へ行きます。", "example_reading": "げきじょうへいきます。", "example_meaning_cn": "去剧场。", "example_meaning_en": "I'm going to the theater."},
        "N3_498": {"example_sentence": "け（化粧）粧（しょう）をします。", "example_reading": "けしょうをします。", "example_meaning_cn": "化妆。", "example_meaning_en": "I'll put on makeup."},
        "N3_499": {"example_sentence": "け（消）してください。", "example_reading": "けしてください。", "example_meaning_cn": "请关掉（或擦掉）。", "example_meaning_en": "Please turn it off/erase it."},
        "N3_500": {"example_sentence": "け（削）ってください。", "example_reading": "けずってください。", "example_meaning_cn": "请削（或删减）。", "example_meaning_en": "Please shave/reduce it."},
        "N3_501": {"example_sentence": "け（桁）が違います。", "example_reading": "けたがちがいます。", "example_meaning_cn": "（数量级）差得太远了。", "example_meaning_en": "It's on a completely different scale."},
        "N3_502": {"example_sentence": "け（結）果（か）が出ました。", "example_reading": "けっかがでました。", "example_meaning_cn": "出结果了。", "example_meaning_en": "The results are out."},
        "N3_503": {"example_sentence": "けっ（欠）勤（きん）します。", "example_reading": "けっきんします。", "example_meaning_cn": "缺勤（旷工）。", "example_meaning_en": "I'll be absent from work."},
        "N3_504": {"example_sentence": "けっこう（結構）です。", "example_reading": "けっこうです。", "example_meaning_cn": "很好（或不用了）。", "example_meaning_en": "That's fine (or No thanks)."},
        "N3_505": {"example_sentence": "けっ（決）済（さい）してください。", "example_reading": "けっさいしてください。", "example_meaning_cn": "请支付（结算）。", "example_meaning_en": "Please settle/pay."},
        "N3_506": {"example_sentence": "けっ（欠）伸（しん）が出ます。", "example_reading": "けっしんがでます。", "example_meaning_cn": "打哈欠。", "example_meaning_en": "I'm yawning."},
        "N3_507": {"example_sentence": "けっ（決）心（しん）しました！", "example_reading": "けっしんしました！", "example_meaning_cn": "下决心了！", "example_meaning_en": "I've made up my mind!"},
        "N3_508": {"example_sentence": "けっ（欠）席（せき）します。", "example_reading": "けっせきします。", "example_meaning_cn": "缺席。", "example_meaning_en": "I'll be absent (from meeting/class)."},
        "N3_509": {"example_sentence": "けっ（決定）定しました！", "example_reading": "けっていしました！", "example_meaning_cn": "决定了！", "example_meaning_en": "It's decided!"},
        "N3_510": {"example_sentence": "けっ（欠）点（てん）を直してください。", "example_reading": "けってんなおしてください。", "example_meaning_cn": "请改掉缺点。", "example_meaning_en": "Please fix your flaws."},
        "N3_511": {"example_sentence": "けっ（結）論（ろん）を言ってください。", "example_reading": "けつろんをいってください。", "example_meaning_cn": "请说结论。", "example_meaning_en": "Please tell me the conclusion."},
        "N3_512": {"example_sentence": "けぶ（煙）いですね。 ", "example_reading": "けむいですね。", "example_meaning_cn": "真熏（呛）人呢。", "example_meaning_en": "It's smoky, isn't it?"},
        "N3_513": {"example_sentence": "け（券）を買ってください。", "example_reading": "けんをかってください。", "example_meaning_cn": "请买票。", "example_meaning_en": "Please buy a ticket."},
        "N3_514": {"example_sentence": "けん（県）庁へ行きます。", "example_reading": "けんちょうへいきます。", "example_meaning_cn": "去县政府。", "example_meaning_en": "I'm going to the prefectural office."},
        "N3_515": {"example_sentence": "げん（原因）因（いん）を調べてください。", "example_reading": "げんいんをしらべてください。", "example_meaning_cn": "请查明原因。", "example_meaning_en": "Please investigate the cause."},
        "N3_516": {"example_sentence": "げん（限界）界を超えます。", "example_reading": "げんかいをこえます。", "example_meaning_cn": "超越极限。", "example_meaning_en": "Cross the limit."},
        "N3_517": {"example_sentence": "げん（現）金（きん）で払います。", "example_reading": "げんきんではらいます。", "example_meaning_cn": "用现金支付。", "example_meaning_en": "I'll pay in cash."},
        "N3_518": {"example_sentence": "けん（健）康（こう）に気をつけてください。", "example_reading": "けんこうにきをつけてください。", "example_meaning_cn": "请注意健康。", "example_meaning_en": "Please take care of your health."},
        "N3_519": {"example_sentence": "げん（言語）語（ご）を学んでください。", "example_reading": "げんごをまなんだあでください。", "example_meaning_cn": "请学习语言。", "example_meaning_en": "Please learn the language."},
        "N3_520": {"example_sentence": "げん（現在）在（ざい）の場所はどこですか。", "example_reading": "げんざいのばしょはどこですか。", "example_meaning_cn": "现在的位置在哪儿？", "example_meaning_en": "Where is your current location?"},
        "N3_521": {"example_sentence": "けん（険）しい山道です。", "example_reading": "けわしいやまみちです。", "example_meaning_cn": "险峻的山路。", "example_meaning_en": "It's a steep mountain path."},
        "N3_522": {"example_sentence": "げん（現状）状（じょう）を報告してください。", "example_reading": "げんじょうをほうこくしてください。", "example_meaning_cn": "请汇报现状。", "example_meaning_en": "Please report the current situation."},
        "N3_523": {"example_sentence": "けん（謙）譲（じょう）語（ご）を使ってください。", "example_reading": "けんじょうごをつかってください。", "example_meaning_cn": "请用谦让语。", "example_meaning_en": "Please use humble language."},
        "N3_524": {"example_sentence": "げん（現象）象が起きました。", "example_reading": "げんしょうがおきました。", "example_meaning_cn": "现象发生了。", "example_meaning_en": "A phenomenon occurred."},
        "N3_525": {"example_sentence": "けん（検）索（さく）してください。", "example_reading": "けんさくしてください。", "example_meaning_cn": "请搜索。", "example_meaning_en": "Please search for it."},
        "N3_526": {"example_sentence": "けん（建設）設してください。", "example_reading": "けんせつしてください。", "example_meaning_cn": "请建设。", "example_meaning_en": "Please build/construct it."},
        "N3_527": {"example_sentence": "げん（限定）定品を買いました。", "example_reading": "げんていひんをかいました。", "example_meaning_cn": "买了限定品。", "example_meaning_en": "I bought a limited edition item."},
        "N3_528": {"example_sentence": "けん（検討）討してください。", "example_reading": "けんとうしてください。", "example_meaning_cn": "请探讨（或考虑）。", "example_meaning_en": "Please consider it."},
        "N3_529": {"example_sentence": "げんば（（現場）場へ行きます。", "example_reading": "げんばへいきます。", "example_meaning_cn": "去现场。", "example_meaning_en": "I'm going to the site."},
        "N3_530": {"example_sentence": "けん（憲法）法を守りましょう。", "example_reading": "けんぽうをまもりましょう。", "example_meaning_cn": "遵守宪法吧。", "example_meaning_en": "Let's obey the constitution."},
        "N3_531": {"example_sentence": "けん（権利）利を主張します。", "example_reading": "けんりをしゅちょうします。", "example_meaning_cn": "主张权利。", "example_meaning_en": "I'll assert my rights."},
        "N3_532": {"example_sentence": "ご（語）学を勉強します。", "example_reading": "ごがくをべんきょうします。", "example_meaning_cn": "学习语言（外语）。", "example_meaning_en": "I study linguistics/language."},
        "N3_533": {"example_sentence": "こ（小）屋（や）があります。", "example_reading": "こやがあります。", "example_meaning_cn": "有个小屋。", "example_meaning_en": "There is a hut."},
        "N3_534": {"example_sentence": "こ（幸）せですね！", "example_reading": "しあわせですね！", "example_meaning_cn": "真幸福呢！", "example_meaning_en": "How happy!"},
        "N3_535": {"example_sentence": "こ（声）を聞かせてください。", "example_reading": "こえをきかせてください。", "example_meaning_cn": "请让我听听你的声音。", "example_meaning_en": "Please let me hear your voice."},
        "N3_536": {"example_sentence": "こ（越）してください。", "example_reading": "こしてください。", "example_meaning_cn": "请超过（或搬家）。", "example_meaning_en": "Please pass/cross/move."},
        "N3_537": {"example_sentence": "こう（高）校へ行きます。", "example_reading": "こうこうへいきます。", "example_meaning_cn": "去高中。", "example_meaning_en": "I'm going to high school."},
        "N3_538": {"example_sentence": "こう（公園）園を歩きます。", "example_reading": "こうえんをあるきます。", "example_meaning_cn": "在公园走走。", "example_meaning_en": "I'll walk in the park."},
        "N3_539": {"example_sentence": "（講演）を聴きます。", "example_reading": "こうえんをききます。", "example_meaning_cn": "听讲座（演讲）。", "example_meaning_en": "I'll listen to the lecture."},
        "N3_540": {"example_sentence": "こう（効果）果があります。", "example_reading": "こうかがあります。", "example_meaning_cn": "见效（有效果）。", "example_meaning_en": "It's effective."},
        "N3_541": {"example_sentence": "こう（交換）換してください。", "example_reading": "こうかんしてください。", "example_meaning_cn": "请交换。", "example_meaning_en": "Please exchange it."},
        "N3_542": {"example_sentence": "こう（航空）急便で送ります。", "example_reading": "こうくうきゅうびんでおくります。", "example_meaning_cn": "空运快件发送。", "example_meaning_en": "I'll send it by air mail."},
        "N3_543": {"example_sentence": "こう（光景）景を思い出します。", "example_reading": "こうけいをおもいだします。", "example_meaning_cn": "想起那一幕（光景）。", "example_meaning_en": "I remember that scene."},
        "N3_544": {"example_sentence": "こう（合計）計してください。", "example_reading": "ごうけいしてください。", "example_meaning_cn": "请合计。", "example_meaning_en": "Please total it up."},
        "N3_545": {"example_sentence": "こう（攻撃）撃しないでください！", "example_reading": "こうげきしないでください！", "example_meaning_cn": "请不要攻击！", "example_meaning_en": "Please don't attack!"},
        "N3_546": {"example_sentence": "こう（広告）告を見てください。", "example_reading": "こうこくをみてください。", "example_meaning_cn": "请看广告。", "example_meaning_en": "Please look at the advertisement."},
        "N3_547": {"example_sentence": "こう（降参）参しました。", "example_reading": "こうさんしました。", "example_meaning_cn": "投降了。", "example_meaning_en": "I surrendered."},
        "N3_548": {"example_sentence": "こう（校舎）舎がきれいです。", "example_reading": "こうしゃがきれいです。", "example_meaning_cn": "校舍很漂亮。", "example_meaning_en": "The school building is beautiful."},
        "N3_549": {"example_sentence": "こう（更新）新してください。", "example_reading": "こうしんしてください。", "example_meaning_cn": "请更新。", "example_meaning_en": "Please update it."},
        "N3_550": {"example_sentence": "こう（（洪水）水に注意してください。", "example_reading": "こうずいにちゅういしてください。", "example_meaning_cn": "请注意洪水。", "example_meaning_en": "Please be careful of floods."},
        "N3_551": {"example_sentence": "こう（構造）造を調べてください。", "example_reading": "こうぞうをしらべてください。", "example_meaning_cn": "请检查构造。", "example_meaning_en": "Please investigate the structure."},
        "N3_552": {"example_sentence": "こう（交際）際してください！ ", "example_reading": "こうさいしてください！", "example_meaning_cn": "请和我交往！", "example_meaning_en": "Please go out with me!"},
        "N3_553": {"example_sentence": "こう（後悔）悔しています。", "example_reading": "こうかいしています。", "example_meaning_cn": "深感后悔。", "example_meaning_en": "I regret it."},
        "N3_554": {"example_sentence": "こう（交代）代してください。", "example_reading": "こうたいしてください。", "example_meaning_cn": "请接班（或轮班）。", "example_meaning_en": "Please switch/rotate."},
        "N3_555": {"example_sentence": "こう（交信）信してください。", "example_reading": "こうしんしてください。", "example_meaning_cn": "请通话（或通信）。", "example_meaning_en": "Please communicate."},
        "N3_556": {"example_sentence": "こう（工場）場で作ります。", "example_reading": "こうじょうでつくります。", "example_meaning_cn": "在工厂制造。", "example_meaning_en": "Produced in a factory."},
        "N3_557": {"example_sentence": "こう（公正）正な判断をしてください。", "example_reading": "こうせいなはんだんをしてください。", "example_meaning_cn": "请公正评断。", "example_meaning_en": "Please make a fair judgment."},
        "N3_558": {"example_sentence": "こう（候補）補者は誰ですか。", "example_reading": "こうほしゃはだれですか。", "example_meaning_cn": "候选人是谁？", "example_meaning_en": "Who is the candidate?"},
        "N3_559": {"example_sentence": "（降伏）しました。", "example_reading": "こうふくしました。", "example_meaning_cn": "投降了。", "example_meaning_en": "I yielded/surrendered."},
        "N3_560": {"example_sentence": "こう（幸福）福ですね！", "example_reading": "こうふくですね！", "example_meaning_cn": "真幸福呢！", "example_meaning_en": "How happy!"},
        "N3_561": {"example_sentence": "こう（光）栄です。", "example_reading": "こうえいです。", "example_meaning_cn": "是我的荣幸（光荣）。", "example_meaning_en": "I'm honored."},
        "N3_562": {"example_sentence": "こう（公務員）務員として働きます。", "example_reading": "こうむいんとしてはたらきます。", "example_meaning_cn": "作为公务员工作。", "example_meaning_en": "I work as a civil servant."},
        "N3_563": {"example_sentence": "こう（交通）通に気をつけてください。", "example_reading": "こうつうにきをつけてください。", "example_meaning_cn": "请注意交通安全。", "example_meaning_en": "Please be careful with traffic."},
        "N3_564": {"example_sentence": "こう（講）義（ぎ）を聴きます。", "example_reading": "こうぎをききます。", "example_meaning_cn": "听课。", "example_meaning_en": "I'll listen to the lecture."},
        "N3_565": {"example_sentence": "こう（向）上（じょう）させてください。", "example_reading": "こうじょうさせてください。", "example_meaning_cn": "请提高（或向上）。", "example_meaning_en": "Please improve/elevate it."},
        "N3_566": {"example_sentence": "こう（拘）留（りゅう）されました。", "example_reading": "こうりゅうされました。", "example_meaning_cn": "被拘留（或收容）了。", "example_meaning_en": "I was detained."},
        "N3_567": {"example_sentence": "（凍）りました。", "example_reading": "こおりました。", "example_meaning_cn": "冻住了（或冰冻）。", "example_meaning_en": "It's frozen."},
        "N3_568": {"example_sentence": "こ（小）包（づつみ）が届きました。", "example_reading": "こづつみがとどきました。", "example_meaning_cn": "小包（包裹）收到了。", "example_meaning_en": "The parcel arrived."},
        "N3_569": {"example_sentence": "こ（腰）が痛いです。", "example_reading": "こしがいたいです。", "example_meaning_cn": "腰疼。", "example_meaning_en": "My lower back hurts."},
        "N3_570": {"example_sentence": "こ（故障）障しました。", "example_reading": "こしょうしました。", "example_meaning_cn": "出故障（坏了）。", "example_meaning_en": "It's broken/out of order."},
        "N3_571": {"example_sentence": "こ（越）してください。", "example_reading": "こしてください。", "example_meaning_cn": "请超过（或超越）。", "example_meaning_en": "Please pass/cross."},
        "N3_572": {"example_sentence": "こ（誇）りに思っています。", "example_reading": "ほこりにおもっています。", "example_meaning_cn": "引以为豪。", "example_meaning_en": "I'm proud of it."},
        "N3_573": {"example_sentence": "こ（個人）人的な意見です。", "example_reading": "こじんてきないけんです。", "example_meaning_cn": "个人的意见。", "example_meaning_en": "Personal opinion."},
        "N3_574": {"example_sentence": "こ（超）えてください。", "example_reading": "こえてください。", "example_meaning_cn": "请跨越（或超越）。", "example_meaning_en": "Please cross/exceed it."},
        "N3_575": {"example_sentence": "こ（凍）えてしまいます。", "example_reading": "こごえてしまいます。", "example_meaning_cn": "要冻僵了。", "example_meaning_en": "I'm freezing."},
        "N3_576": {"example_sentence": "こ（心）から感謝します。", "example_reading": "こころからかんしゃします。", "example_meaning_cn": "由衷地感谢。", "example_meaning_en": "I thank you from my heart."},
        "N3_577": {"example_sentence": "（試）みてください。", "example_reading": "こころみてください。", "example_meaning_cn": "请尝试。", "example_meaning_en": "Please try/attempt it."},
        "N3_578": {"example_sentence": "（答）えてください。", "example_reading": "こたえてください。", "example_meaning_cn": "请回答（或应对）。", "example_meaning_en": "Please answer/respond."},
        "N3_579": {"example_sentence": "（拘）ってください。", "example_reading": "こだわってください。", "example_meaning_cn": "请讲究（或拘泥）。", "example_meaning_en": "Please be particular about it."},
        "N3_580": {"example_sentence": "こ（孤）独（どく）ですね。 ", "example_reading": "こどくですね。", "example_meaning_cn": "真孤独呢。", "example_meaning_en": "How lonely."},
        "N3_581": {"example_sentence": "この（この）本を読んでください。", "example_reading": "このほんをよんでください。", "example_meaning_cn": "请读这本书。", "example_meaning_en": "Please read this book."},
        "N3_582": {"example_sentence": "（好）んで食べています。", "example_reading": "このんでたべています。", "example_meaning_cn": "正爱吃着（喜欢吃）。", "example_meaning_en": "I eat it by choice/I like it."},
        "N3_583": {"example_sentence": "（零）れてしまいました。", "example_reading": "こぼれてしまいました。", "example_meaning_cn": "洒（溢）出来了。", "example_meaning_en": "It spilled/overflowed."},
        "N3_584": {"example_sentence": "（混）んでいますね。 ", "example_reading": "こんでいますね。", "example_meaning_cn": "挺拥挤（挤）的呢。", "example_meaning_en": "It's crowded, isn't it?"},
        "N3_585": {"example_sentence": "こま（困）っています。", "example_reading": "こまっています。", "example_meaning_cn": "正为难（困扰）着呢。", "example_meaning_en": "I'm in trouble/distressed."},
        "N3_586": {"example_sentence": "こまか（細）かいですね！", "example_reading": "こまかいですね！", "example_meaning_cn": "真细（或详细）呢！", "example_meaning_en": "How detailed/fine!"},
        "N3_587": {"example_sentence": "ごま（胡麻）をすりましょう。", "example_reading": "ごまをすりましょう。", "example_meaning_cn": "拍马屁（或磨芝麻）吧。", "example_meaning_en": "Let's grind sesame (or flatter them)."},
        "N3_588": {"example_sentence": "こ（込）めてください。", "example_reading": "こめてください。", "example_meaning_cn": "请注入（或包含）。", "example_meaning_en": "Please put your heart/effort into it."},
        "N3_589": {"example_sentence": "ご（御）免（めん）なさい。", "example_reading": "ごめんなさい。", "example_meaning_cn": "对不起。", "example_meaning_en": "I'm sorry."},
        "N3_590": {"example_sentence": "ここ（（心地）地）が良いです。", "example_reading": "ここちがいいです。", "example_meaning_cn": "心情舒适。", "example_meaning_en": "It feels pleasant."},
        "N3_591": {"example_sentence": "こ（殺）さないでください！ ", "example_reading": "ころさないでください！", "example_meaning_cn": "请不要杀掉（它）！", "example_meaning_en": "Please don't kill it!"},
        "N3_592": {"example_sentence": "こ（転）んでしまいました。", "example_reading": "ころんでしまいました。", "example_meaning_cn": "摔倒了。", "example_meaning_en": "I fell down."},
        "N3_593": {"example_sentence": "こん（怖）いですね。 ", "example_reading": "こわいですね。", "example_meaning_cn": "真可怕呢。", "example_meaning_en": "It's scary, isn't it?"},
        "N3_594": {"example_sentence": "こ（壊）してください。", "example_reading": "こわしてください。", "example_meaning_cn": "请弄坏（或拆除）。", "example_meaning_en": "Please break/destroy it."},
        "N3_595": {"example_sentence": "こわ（怖）がらないでください。", "example_reading": "こわがらないでください。", "example_meaning_cn": "请不要害怕。", "example_meaning_en": "Please don't be afraid."},
        "N3_596": {"example_sentence": "こん（今）回（かい）は勝ちます。", "example_reading": "こんかいはかちます。", "example_meaning_cn": "这次会赢。", "example_meaning_en": "I'll win this time."},
        "N3_597": {"example_sentence": "こん（今回）回は何ですか。", "example_reading": "こんかいはなんですか。", "example_meaning_cn": "这次是什么？", "example_meaning_en": "What is it this time?"},
        "N3_598": {"example_sentence": "こん（今後）後もよろしくお願いします。", "example_reading": "こんごもよろしくおねがいします。", "example_meaning_cn": "今后也请多多关照。", "example_meaning_en": "Please continue to be kind to me from now on."},
        "N3_599": {"example_sentence": "こん（混）雑（ざつ）しています。", "example_reading": "こんざつしています。", "example_meaning_cn": "很拥挤（或混杂）。", "example_meaning_en": "It's congested."},
        "N3_600": {"example_sentence": "こん（困難）難に立ち向かいます。", "example_reading": "こんなんにたちむかいます。", "example_meaning_cn": "直面困难。", "example_meaning_en": "Facing the difficulties."}
    }

    for item in vocab:
        if item['id'] in enrichment:
            item.update(enrichment[item['id']])

    with open(data_file, 'w', encoding='utf-8') as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

    print(f"Updated items up to N3_600.")

if __name__ == "__main__":
    main()
