import json
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    data_file = os.path.join(project_root, 'jlpt-web', 'src', 'data', 'vocab.json')

    if not os.path.exists(data_file):
        return

    with open(data_file, 'r', encoding='utf-8') as f:
        vocab = json.load(f)

    enrichment = {
        "N4_301": {"example_sentence": "こ（子）は宝（たから）です。", "example_reading": "こはたからです。", "example_meaning_cn": "孩子是宝物（财富）。", "example_meaning_en": "Children are treasures."},
        "N4_302": {"example_sentence": "こ（御）一（いっ）緒（しょ）にしますか。", "example_reading": "ごいっしょにしましょうか。", "example_meaning_cn": "要一起去吗？", "example_meaning_en": "Shall we go together?"},
        "N4_303": {"example_sentence": "こう（公）園で遊びましょう。", "example_reading": "こうえんであそびましょう。", "example_meaning_cn": "去公园玩吧。", "example_meaning_en": "Let's play in the park."},
        "N4_304": {"example_sentence": "こう（交）番へ行きましょう。", "example_reading": "こうばんへいきましょう。", "example_meaning_cn": "去派出所吧。", "example_meaning_en": "Let's go to the police box."},
        "N4_305": {"example_sentence": "こう（講）義を聞いています。", "example_reading": "こうぎをきいています。", "example_meaning_cn": "正在听讲座。", "example_meaning_en": "I'm listening to the lecture."},
        "N4_306": {"example_sentence": "こう（工）業が盛んです。", "example_reading": "こうぎょうがさかんです。", "example_meaning_cn": "工业很发达（盛行）。", "example_meaning_en": "Industry is flourishing."},
        "N4_307": {"example_sentence": "こう（高）校生になりました。", "example_reading": "こうこうせいになりました。", "example_meaning_cn": "成为高中生了。", "example_meaning_en": "I became a high school student."},
        "N4_308": {"example_sentence": "こう（工）場で見学します。", "example_reading": "こうじょうでけんがくします。", "example_meaning_cn": "在工厂进行参观（见学）。", "example_meaning_en": "I'll visit the factory for study."},
        "N4_309": {"example_sentence": "こう（校）長先生の話です。", "example_reading": "こうちょうせんせいのはなしです。", "example_meaning_cn": "校长的讲话。", "example_meaning_en": "The principal's speech."},
        "N4_310": {"example_sentence": "こう（交）通に気をつけて。", "example_reading": "こうつうにきをつけて。", "example_meaning_cn": "注意交通安全。", "example_meaning_en": "Be careful with the traffic."},
        "N4_311": {"example_sentence": "こう（講）堂で集まります。", "example_reading": "こうどうであつまります。", "example_meaning_cn": "在礼堂集合。", "example_meaning_en": "Collect at the auditorium."},
        "N4_312": {"example_sentence": "こう（公）務員になりたいです。", "example_reading": "こうむいんになりたいです。", "example_meaning_cn": "想当公务员。", "example_meaning_en": "I want to be a public official."},
        "N4_313": {"example_sentence": "こ（越）えてください。", "example_reading": "こえてください。", "example_meaning_cn": "请跨过（或越过）。", "example_meaning_en": "Please cross over/exceed."},
        "N4_314": {"example_sentence": "こ（声）が高いですね。", "example_reading": "こえがたかいですね。", "example_meaning_cn": "嗓门挺大呢。", "example_meaning_en": "You have a loud voice, don't you?"},
        "N4_315": {"example_sentence": "コー（こー）トを着てください。", "example_reading": "コートをきてください。", "example_meaning_cn": "请穿上大衣。", "example_meaning_en": "Please put on your coat."},
        "N4_316": {"example_sentence": "コーヒー（こーひー）を飲みます。", "example_reading": "コーヒーをのみます。", "example_meaning_cn": "喝咖啡。", "example_meaning_en": "I drink coffee."},
        "N4_317": {"example_sentence": "こ（越）してください。", "example_reading": "こしてください。", "example_meaning_cn": "请搬家（搬过来）。 ", "example_meaning_en": "Please move (here)."},
        "N4_318": {"example_sentence": "こころ（心）が温かいです。", "example_reading": "こころがあたたかいです。", "example_meaning_cn": "内心很温暖（心地善良）。", "example_meaning_en": "Warm-hearted."},
        "N4_319": {"example_sentence": "こ（答）えてください。", "example_reading": "こたえてください。", "example_meaning_cn": "请回答。", "example_meaning_en": "Please answer."},
        "N4_150+": "...", # Placeholder for counting logic if needed, but I will fulfill specifically.
        "N4_320": {"example_sentence": "こじ（個人）的な問題です。", "example_reading": "こじんてきなもんだいです。", "example_meaning_cn": "这是个人问题。", "example_meaning_en": "It's a personal problem."},
        "N4_321": {"example_sentence": "こす（越）してください。", "example_reading": "こしてください。", "example_meaning_cn": "请跨越（或传导）。", "example_meaning_en": "Please cross/transmit."},
        "N4_322": {"example_sentence": "ごぜん（午前）中に出かけます。", "example_reading": "ごぜんちゅうにでかけます。", "example_meaning_cn": "上午出门。", "example_meaning_en": "I'll go out in the morning."},
        "N4_323": {"example_sentence": "こた（答）えを書いてください。", "example_reading": "こたえをかいてください。", "example_meaning_cn": "请写下答案。", "example_meaning_en": "Please write the answer."},
        "N4_324": {"example_sentence": "ごち（御馳走）そう様でした。", "example_reading": "ごちそうさまでした。", "example_meaning_cn": "承蒙款待（吃好了）。", "example_meaning_en": "Thank you for the meal."},
        "N4_325": {"example_sentence": "こっ（国家）家のために働きます。", "example_reading": "こっかのためにはたらきます。", "example_meaning_cn": "为了国家而工作。", "example_meaning_en": "I work for the country."},
        "N4_326": {"example_sentence": "こっ（国会）会で話し合います。", "example_reading": "こっかいではなしあいます。", "example_meaning_cn": "在国会进行讨论。", "example_meaning_en": "Discussion in the parliament."},
        "N4_327": {"example_sentence": "こっ（小包）包が届きました。", "example_reading": "こづつみがとどきました。", "example_meaning_cn": "包裹寄到了。", "example_meaning_en": "A parcel has arrived."},
        "N4_328": {"example_sentence": "こと（事）を始めましょう。", "example_reading": "ことをはじめましょう。", "example_meaning_cn": "开始做事吧。", "example_meaning_en": "Let's start the matter/task."},
        "N4_329": {"example_sentence": "こと（言葉）に気をつけましょう。", "example_reading": "ことばにきをつけましょう。", "example_meaning_cn": "注意措辞（语言）。", "example_meaning_en": "Let's be careful with our words."},
        "N4_330": {"example_sentence": "こと（殊）にきれいです。", "example_reading": "ことにきれいです。", "example_meaning_cn": "格外的漂亮。", "example_meaning_en": "It's especially beautiful."},
        "N4_331": {"example_sentence": "こと（断）ってください。", "example_reading": "ことわってください。", "example_meaning_cn": "请拒绝。", "example_meaning_en": "Please refuse."},
        "N4_332": {"example_sentence": "こな（粉）をまいてください。", "example_reading": "こなをまいてください。", "example_meaning_cn": "请撒点粉末。", "example_meaning_en": "Please sprinkle the powder."},
        "N4_333": {"example_sentence": "この（この）ペンを貸して下さい。", "example_reading": "このペンをかしてください。", "example_meaning_cn": "请把这支笔借给我。", "example_meaning_en": "Please lend me this pen."},
        "N4_334": {"example_sentence": "ごま（胡麻）をすりましょう。", "example_reading": "ごまをすりましょう。", "example_meaning_cn": "磨芝麻吧（或拍马屁）。", "example_meaning_en": "Let's grind the sesame."},
        "N4_335": {"example_sentence": "こま（困）っていますね。", "example_reading": "こまっていますね。", "example_meaning_cn": "挺为难的呢。", "example_meaning_en": "You're in trouble, aren't you?"},
        "N4_336": {"example_sentence": "こ（込）んでいます。", "example_reading": "こんでいます。", "example_meaning_cn": "人很拥挤。", "example_meaning_en": "It is crowded."},
        "N4_337": {"example_sentence": "こ（米）が美味しいです。", "example_reading": "こめがおいしいです。", "example_meaning_cn": "米饭很好吃。", "example_meaning_en": "The rice is delicious."},
        "N4_338": {"example_sentence": "ごみ（塵）を捨てましょう。", "example_reading": "ごみをすてましょう。", "example_meaning_cn": "扔垃圾吧。", "example_meaning_en": "Let's throw away the trash."},
        "N4_339": {"example_sentence": "こむぎ（小麦）からパンを作ります。", "example_reading": "こむぎからパンをつくります。", "example_meaning_cn": "从小麦制作面包。", "example_meaning_en": "Make bread from wheat."},
        "N4_340": {"example_sentence": "こわ（壊）れてしまいました。", "example_reading": "こわれてしまいました。", "example_meaning_cn": "坏掉了。", "example_meaning_en": "It broke."},
        "N4_341": {"example_sentence": "こわ（怖）い夢を見ました。", "example_reading": "こわいゆめをみました。", "example_meaning_cn": "做了个可怕的梦。", "example_meaning_en": "I had a scary dream."},
        "N4_342": {"example_sentence": "こん（今）回は頑張りましょう。", "example_reading": "こんかいはがんばりましょう。", "example_meaning_cn": "这次加油吧。", "example_meaning_en": "Let's do our best this time."},
        "N4_343": {"example_sentence": "こん（今）月は忙しいです。", "example_reading": "こんげつはいそがしいです。", "example_meaning_cn": "这个月很忙。", "example_meaning_en": "I'm busy this month."},
        "N4_344": {"example_sentence": "こん（今）週会いましょう。", "example_reading": "こんしゅうあいましょう。", "example_meaning_cn": "这周见面吧。", "example_meaning_en": "Let's meet this week."},
        "N4_345": {"example_sentence": "こん（今）夜、電話します。", "example_reading": "こんや、でんわします。", "example_meaning_cn": "今晚打电话。", "example_meaning_en": "I'll call tonight."},
        "N4_346": {"example_sentence": "さ（左）に曲がってください。", "example_reading": "さにまがってください。", "example_meaning_cn": "请向左拐。", "example_meaning_en": "Please turn left."},
        "N4_347": {"example_sentence": "さい（最近）会っていません。", "example_reading": "さいきんあっていません。", "example_meaning_cn": "最近没见过面。", "example_meaning_en": "I haven't met them lately."},
        "N4_348": {"example_sentence": "さい（最後）までやりましょう。", "example_reading": "さいごまでやりましょう。", "example_meaning_cn": "坚持到底吧。", "example_meaning_en": "Let's do it until the end."},
        "N4_349": {"example_sentence": "さい（最初）は緊張しました。", "example_reading": "さいしょはきんちょうしました。", "example_meaning_cn": "起初很紧张。", "example_meaning_en": "I was nervous at first."},
        "N4_350": {"example_sentence": "さか（坂）を登ります。", "example_reading": "さかをのぼります。", "example_meaning_cn": "爬坡。", "example_meaning_en": "Climb up the slope."},
        "N4_351": {"example_sentence": "さが（探）してください。", "example_reading": "さがしてください。", "example_meaning_cn": "请寻找。", "example_meaning_en": "Please search for it."},
        "N4_352": {"example_sentence": "さか（逆）さまです。", "example_reading": "さかさまです。", "example_meaning_cn": "颠倒的。", "example_meaning_en": "It's upside down."},
        "N4_353": {"example_sentence": "さか（魚）を食べましょう。", "example_reading": "さかなをたべましょう。", "example_meaning_cn": "吃鱼吧。", "example_meaning_en": "Let's eat fish."},
        "N4_354": {"example_sentence": "さか（酒）を飲みに行きます。", "example_reading": "さけをのみにいきます。", "example_meaning_cn": "去喝酒。", "example_meaning_en": "I'm going out for a drink."},
        "N4_355": {"example_sentence": "さく（作）品を見てください。", "example_reading": "さくひんをみてください。", "example_meaning_cn": "请看作品。", "example_meaning_en": "Please look at the work."},
        "N4_356": {"example_sentence": "さくら（桜）がきれいです。", "example_reading": "さくらがきれいです。", "example_meaning_cn": "樱花很漂亮。", "example_meaning_en": "The cherry blossoms are beautiful."},
        "N4_357": {"example_sentence": "さ（下）げてください。", "example_reading": "さげてください。", "example_meaning_cn": "请放下（或降低）。", "example_meaning_en": "Please lower it."},
        "N4_358": {"example_sentence": "さ（刺）してください。 ", "example_reading": "さしてください。", "example_meaning_cn": "请刺（或指）。 ", "example_meaning_en": "Please stab/point."},
        "N4_359": {"example_sentence": "さ（差）してください。 ", "example_reading": "さしてください。", "example_meaning_cn": "请撑（伞）。 ", "example_meaning_en": "Please hold (an umbrella)."},
        "N4_360": {"example_sentence": "さ（誘）ってください。", "example_reading": "さそってください。", "example_meaning_cn": "请邀请我。", "example_meaning_en": "Please invite me."},
        "N4_361": {"example_sentence": "さび（寂）しいですね。", "example_reading": "さびしいですね。", "example_meaning_cn": "真够寂寞的呢。", "example_meaning_en": "It's lonely, isn't it?"},
        "N4_362": {"example_sentence": "さ（触）らないでください。", "example_reading": "さわらないでください。", "example_meaning_cn": "请不要触摸。", "example_meaning_en": "Please don't touch."},
        "N4_363": {"example_sentence": "さん（参）加しましょう。", "example_reading": "さんかしましょう。", "example_meaning_cn": "参加吧。", "example_meaning_en": "Let's participate."},
        "N4_364": {"example_sentence": "さん（散）歩に行きます。", "example_reading": "さんぽにいきます。", "example_meaning_cn": "去散步。", "example_meaning_en": "I'm going for a walk."},
        "N4_365": {"example_sentence": "し（市）内に住んでいます。", "example_reading": "しないにすんでいます。", "example_meaning_cn": "住在市内。", "example_meaning_en": "I live in the city."},
        "N4_366": {"example_sentence": "じ（字）を書いてください。", "example_reading": "じをかいてください。", "example_meaning_cn": "请写字。", "example_meaning_en": "Please write characters."},
        "N4_367": {"example_sentence": "し（試合）合が始まります。", "example_reading": "しあいがはじまります。", "example_meaning_cn": "比赛开始了。", "example_meaning_en": "The match begins."},
        "N4_368": {"example_sentence": "し（幸せ）あわせになりたいです。", "example_reading": "しあわせになりたいです。", "example_meaning_cn": "想变得幸福。", "example_meaning_en": "I want to be happy."},
        "N4_369": {"example_sentence": "じ（磁石）石を持ってますか。", "example_reading": "じしゃくをもっていますか。", "example_meaning_cn": "有磁铁吗？", "example_meaning_en": "Do you have a magnet?"},
        "N4_370": {"example_sentence": "し（静か）ずかですね。", "example_reading": "しずかですね。", "example_meaning_cn": "真够安静的呢。", "example_meaning_en": "It's quiet, isn't it?"},
        "N4_371": {"example_sentence": "し（下）着を買いました。", "example_reading": "したぎをかいました。", "example_meaning_cn": "买了贴身内衣。", "example_meaning_en": "I bought some underwear."},
        "N4_372": {"example_sentence": "し（支）度をしてください。", "example_reading": "したくをしてください。", "example_meaning_cn": "请准备一下。", "example_meaning_en": "Please prepare."},
        "N4_373": {"example_sentence": "し（親）しい友達です。", "example_reading": "したしいともだちです。", "example_meaning_cn": "关系亲密的朋友。", "example_meaning_en": "He is a close friend."},
        "N4_374": {"example_sentence": "しっかり（しっかり）してください。", "example_reading": "しっかりしてください。", "example_meaning_cn": "请振作（或好好干）。", "example_meaning_en": "Please get it together/do it properly."},
        "N4_375": {"example_sentence": "しっぱい（失敗）しました。", "example_reading": "しっぱいしました。", "example_meaning_cn": "失败了。", "example_meaning_en": "I failed."},
        "N4_376": {"example_sentence": "しつれい（失礼）します。", "example_reading": "しつれいします。", "example_meaning_cn": "告辞（或打扰了）。", "example_meaning_en": "Excuse me."},
        "N4_377": {"example_sentence": "しつもん（質問）がありますか。", "example_reading": "しつもんがありますか。", "example_meaning_cn": "有问题吗？", "example_meaning_en": "Do you have any questions?"},
        "N4_378": {"example_sentence": "じ（自）転車で来ました。", "example_reading": "じてんしゃできました。", "example_meaning_cn": "骑自行车回来的。", "example_meaning_en": "I came by bicycle."},
        "N4_379": {"example_sentence": "し（品）物が届きました。", "example_reading": "しなものがとどきました。", "example_meaning_cn": "货到了。", "example_meaning_en": "The goods have arrived."},
        "N4_380": {"example_sentence": "し（死）なないでください。", "example_reading": "しなないでください。", "example_meaning_cn": "请不要死。", "example_meaning_en": "Please don't die."},
        "N4_381": {"example_sentence": "し（島）へ行きたいです。", "example_reading": "しまへいきたいです。", "example_meaning_cn": "想去岛上。", "example_meaning_en": "I want to go to the island."},
        "N4_382": {"example_sentence": "し（閉）めてください。", "example_reading": "しめてください。", "example_meaning_cn": "请关闭（或系紧）。", "example_meaning_en": "Please close/tighten."},
        "N4_383": {"example_sentence": "じ（時）務所はこちらです。", "example_reading": "じむしょはこちらです。", "example_meaning_cn": "办公室在这边。", "example_meaning_en": "The office is this way."},
        "N4_384": {"example_sentence": "しゃ（社会）会の一員です。", "example_reading": "しゃかいのいちいんです。", "example_meaning_cn": "是社会的一员。", "example_meaning_en": "A member of society."},
        "N4_385": {"example_sentence": "しや（市役所）役所へ行きます。", "example_reading": "しやくしょへいきます。", "example_meaning_cn": "去市政府。", "example_meaning_en": "I'm going to the city hall."},
        "N4_386": {"example_sentence": "しゃ（写真）真を撮りましょう。", "example_reading": "しゃしんをとりましょう。", "example_meaning_cn": "拍照吧。", "example_meaning_en": "Let's take a photo."},
        "N4_387": {"example_sentence": "じゅう（十）円玉をください。", "example_reading": "じゅうえんだまをください。", "example_meaning_cn": "请给我10日元硬币。", "example_meaning_en": "Please give me a 10-yen coin."},
        "N4_388": {"example_sentence": "じゅう（住所）所を書いてください。", "example_reading": "じゅうしょをかいてください。", "example_meaning_cn": "请写下地址。", "example_meaning_en": "Please write your address."},
        "N4_389": {"example_sentence": "じゅう（自由）由になりたいです。", "example_reading": "じゆうになりたいです。", "example_meaning_cn": "想变得自由。", "example_meaning_en": "I want to be free."},
        "N4_390": {"example_sentence": "しゅう（習慣）慣は大切です。", "example_reading": "しゅうかんはたいせつです。", "example_meaning_cn": "习惯很重要。", "example_meaning_en": "Habits are important."},
        "N4_391": {"example_sentence": "しゅ（宿題）題をしましたか。", "example_reading": "しゅくだいをしましたか。", "example_meaning_cn": "写作业了吗？", "example_meaning_en": "Did you do your homework?"},
        "N4_392": {"example_sentence": "しゅ（主役）役を演じます。", "example_reading": "しゅやくをえんじます。", "example_meaning_cn": "扮演主角。", "example_meaning_en": "Playing the leading role."},
        "N4_393": {"example_sentence": "しゆ（出席）席します。", "example_reading": "しゅっせきします。", "example_meaning_cn": "我出席。", "example_meaning_en": "I will attend."},
        "N4_394": {"example_sentence": "しゅっ（出発）発しましょう。", "example_reading": "しゅっぱつしましょう。", "example_meaning_cn": "出发吧。", "example_meaning_en": "Let's depart."},
        "N4_395": {"example_sentence": "しゅ（趣味）味は何ですか。", "example_reading": "しゅみはなんですか。", "example_meaning_cn": "你的爱好是什么？", "example_meaning_en": "What is your hobby?"},
        "N4_396": {"example_sentence": "じゅん（準備）備をしてください。", "example_reading": "じゅんびをしてください。", "example_meaning_cn": "请做准备。", "example_meaning_en": "Please prepare."},
        "N4_397": {"example_sentence": "しよう（使用）してください。", "example_reading": "しようしてください。", "example_meaning_cn": "请使用。", "example_meaning_en": "Please use."},
        "N4_398": {"example_sentence": "しょう（小説）説を書いています。", "example_reading": "しょうせつをかいています。", "example_meaning_cn": "正在写小说。", "example_meaning_en": "I am writing a novel."},
        "N4_399": {"example_sentence": "じょう（招待）待されました。", "example_reading": "じょうたいされました。", "example_meaning_cn": "被招待（邀请）了。", "example_meaning_en": "I was invited."},
        "N4_400": {"example_sentence": "しょう（承知）知しました。", "example_reading": "しょうちしました。", "example_meaning_cn": "知道了（遵命）。", "example_meaning_en": "Understood."},
        "N4_401": {"example_sentence": "しょう（正月）月を祝います。", "example_reading": "しょうがつをいわいます。", "example_meaning_cn": "庆祝正月（新年）。", "example_meaning_en": "Celebrate the New Year."},
        "N4_402": {"example_sentence": "しょう（少々）々お待ちください。", "example_reading": "しょうしょうおまちください。", "example_meaning_cn": "请稍候。", "example_meaning_en": "Please wait a moment."},
        "N4_403": {"example_sentence": "じょう（状態）態が良いです。", "example_reading": "じょうたいがよいです。", "example_meaning_cn": "状态良好。", "example_meaning_en": "The condition is good."},
        "N4_404": {"example_sentence": "じょう（上品）品な人ですね。", "example_reading": "じょうひんなひとですね。", "example_meaning_cn": "是个高雅的人呢。", "example_meaning_en": "He is an elegant person, isn't he?"},
        "N4_405": {"example_sentence": "じょう（丈夫）夫なカバンです。", "example_reading": "じょうぶなかばんです。", "example_meaning_cn": "结实的包。", "example_meaning_en": "A sturdy bag."},
        "N4_406": {"example_sentence": "しょう（将来）来が楽しみです。", "example_reading": "しょうらいがたのしみです。", "example_meaning_cn": "将来值得期待。", "example_meaning_en": "The future is promising."},
        "N4_407": {"example_sentence": "しょ（食事）事に行きましょう。", "example_reading": "しょくじにいきましょう。", "example_meaning_cn": "去吃饭吧。", "example_meaning_en": "Let's go for a meal."},
        "N4_408": {"example_sentence": "しょく（食卓）卓を囲みます。", "example_reading": "しょくたくをかこみます。", "example_meaning_cn": "坐到餐桌旁（围着餐桌）。", "example_meaning_en": "Sit around the dining table."},
        "N4_409": {"example_sentence": "しょく（職業）業を教えて下さい。", "example_reading": "しょくぎょうをおしえてください。", "example_meaning_cn": "请告诉我的职业。", "example_meaning_en": "Please tell me your occupation."},
        "N4_410": {"example_sentence": "しょく（食堂）堂で食べます。", "example_reading": "しょくどうでたべます。", "example_meaning_cn": "在食堂吃。", "example_meaning_en": "I'll eat at the cafeteria."},
        "N4_411": {"example_sentence": "しょく（食料）料を買います。", "example_reading": "しょくりょうをかいます。", "example_meaning_cn": "买食粮（食品）。", "example_meaning_en": "I'll buy food/provisions."},
        "N4_412": {"example_sentence": "し（知）っていますか。", "example_reading": "しっていますか。", "example_meaning_cn": "你知道吗？", "example_meaning_en": "Do you know?"},
        "N4_413": {"example_sentence": "し（閉）めてください。", "example_reading": "しめてください。", "example_meaning_cn": "请关闭（或系紧）。 ", "example_meaning_en": "Please close/tighten."},
        "N4_414": {"example_sentence": "し（印）を付けてください。", "example_reading": "しるしをつけてください。", "example_meaning_cn": "请做上标记。", "example_meaning_en": "Please make a mark."},
        "N4_415": {"example_sentence": "し（白）色がきれいですね。", "example_reading": "しろいろがきれいですね。", "example_meaning_cn": "白色真漂亮呢。", "example_meaning_en": "The white color is beautiful, isn't it?"},
        "N4_416": {"example_sentence": "しん（新聞）聞を読んでいます。", "example_reading": "しんぶんをよんでいます。", "example_meaning_cn": "正在读报纸。", "example_meaning_en": "I'm reading a newspaper."},
        "N4_417": {"example_sentence": "しん（親切）切な人です。", "example_reading": "しんせつなひとです。", "example_meaning_cn": "是个亲切的人。", "example_meaning_en": "A kind person."},
        "N4_418": {"example_sentence": "しん（心配）ぱいしないでください。", "example_reading": "しんぱいしないでください。", "example_meaning_cn": "请不要担心。", "example_meaning_en": "Please don't worry."},
        "N4_419": {"example_sentence": "しん（信任）任を得ました。", "example_reading": "しんにんをえました。", "example_meaning_cn": "获得了信任。", "example_meaning_en": "Gained trust."},
        "N4_420": {"example_sentence": "す（吸）ってください。", "example_reading": "すってください。", "example_meaning_cn": "请吸食（或抽烟）。", "example_meaning_en": "Please smoke/suck."},
        "N4_421": {"example_sentence": "す（好）きですか。 ", "example_reading": "すきですか。", "example_meaning_cn": "喜欢吗？", "example_meaning_en": "Do you like it?"},
        "N4_422": {"example_sentence": "す（少）し待ってください。", "example_reading": "すこしまってください。", "example_meaning_cn": "请稍微等一下。", "example_meaning_en": "Please wait a little."},
        "N4_423": {"example_sentence": "す（涼）しいですね。", "example_reading": "すずしいですね。", "example_meaning_cn": "真够凉爽的呢。", "example_meaning_en": "It's cool, isn't it?"},
        "N4_424": {"example_sentence": "ずっと（ずっと）待っています。", "example_reading": "ずっとまっています。", "example_meaning_cn": "一直在等着。", "example_meaning_en": "I've been waiting all along."},
        "N4_425": {"example_sentence": "す（捨）ててください。", "example_reading": "すててください。", "example_meaning_cn": "请扔掉。", "example_meaning_en": "Please throw it away."},
        "N4_426": {"example_sentence": "すな（砂）で遊びます。", "example_reading": "すなであそびます。", "example_meaning_cn": "玩沙子。", "example_meaning_en": "I'll play with sand."},
        "N4_427": {"example_sentence": "すば（素晴）らしいですね。", "example_reading": "すばらしいですね。", "example_meaning_cn": "真棒呢。", "example_meaning_en": "It's wonderful, isn't it?"},
        "N4_428": {"example_sentence": "す（滑）りますね。 ", "example_reading": "すべりますね。", "example_meaning_cn": "很滑呢。", "example_meaning_en": "It's slippery, isn't it?"},
        "N4_429": {"example_sentence": "すべ（全て）て終わりました。", "example_reading": "すべておわりました。", "example_meaning_cn": "全部结束了。", "example_meaning_en": "Everything is finished."},
        "N4_430": {"example_sentence": "す（済）みましたか。", "example_reading": "すみましたか。", "example_meaning_cn": "办好了（或完事）了吗？", "example_meaning_en": "Is it settled/done?"},
        "N4_431": {"example_sentence": "す（住）んでいます。", "example_reading": "すんでいます。", "example_meaning_cn": "住着呢。", "example_meaning_en": "I am living (there)."},
        "N4_432": {"example_sentence": "す（座）ってください。", "example_reading": "すわってください。", "example_meaning_cn": "请坐。", "example_meaning_en": "Please sit."},
        "N4_433": {"example_sentence": "せい（背）が高いですね。", "example_reading": "せがたかいですね。", "example_meaning_cn": "个子挺高呢。", "example_meaning_en": "He is tall, isn't he?"},
        "N4_434": {"example_sentence": "ぜい（せい）のせいではありません。", "example_reading": "ぜいのせいではありません。", "example_meaning_cn": "不是因为那个（过错）。", "example_meaning_en": "It's not because of that."},
        "N4_435": {"example_sentence": "せい（正解）解です！", "example_reading": "せいかいです！", "example_meaning_cn": "正确答案！", "example_meaning_en": "That's correct!"},
        "N4_436": {"example_sentence": "せい（生活）生活に困っています。", "example_reading": "せいかつにこまっています。", "example_meaning_cn": "因生活琐事（或贫困）而苦恼。", "example_meaning_en": "Having trouble with daily life."},
        "N4_437": {"example_sentence": "せい（政治）治家になりたいです。", "example_reading": "せいじかになりたいです。", "example_meaning_cn": "想当政治家。", "example_meaning_en": "I want to be a politician."},
        "N4_438": {"example_sentence": "せい（西欧）欧へ行きます。", "example_reading": "せいおうへいきます。", "example_meaning_cn": "去西欧。", "example_meaning_en": "I'm going to Western Europe."},
        "N4_439": {"example_sentence": "せい（製造）造しています。", "example_reading": "せいぞうしています。", "example_meaning_cn": "生产（制造）中。", "example_meaning_en": "Under manufacture."},
        "N4_440": {"example_sentence": "せい（性格）格がいいですね。", "example_reading": "せいかくがいいですね。", "example_meaning_cn": "性格很好呢。", "example_meaning_en": "He has a good personality."},
        "N4_441": {"example_sentence": "せい（正確）確に答えてください。", "example_reading": "せいかくにこたえてください。", "example_meaning_cn": "请正确地回答。", "example_meaning_en": "Please answer accurately."},
        "N4_442": {"example_sentence": "せい（成功）功しました！", "example_reading": "せいこうしました！", "example_meaning_cn": "成功了！", "example_meaning_en": "Succeeded!"},
        "N4_443": {"example_sentence": "せい（生産）産が盛んです。", "example_reading": "せいさんがさかんです。", "example_meaning_cn": "生产很兴盛。", "example_meaning_en": "Production is high."},
        "N4_444": {"example_sentence": "せい（誠実）実な人です。", "example_reading": "せいじつなひとです。", "example_meaning_cn": "是个诚实的人。", "example_meaning_en": "A sincere person."},
        "N4_445": {"example_sentence": "せい（精神）神を鍛えます。", "example_reading": "せいしんをきたえます。", "example_meaning_cn": "锻炼精神。", "example_meaning_en": "Train the spirit."},
        "N4_446": {"example_sentence": "せい（成長）長しましたね。", "example_reading": "せいちょうしましたね。", "example_meaning_cn": "成长了呢。", "example_meaning_en": "Grown up, haven't you?"},
        "N4_447": {"example_sentence": "せい（政府）府に訴えます。", "example_reading": "せいふにうったえます。", "example_meaning_cn": "向政府申诉。", "example_meaning_en": "Appeal to the government."},
        "N4_448": {"example_sentence": "せい（静物）物画が好きです。", "example_reading": "せいぶつががすきです。", "example_meaning_cn": "喜欢静物画。", "example_meaning_en": "I like still life paintings."},
        "N4_449": {"example_sentence": "せい（生命）命を大切にしましょう。", "example_reading": "せいめいをたいせつにしましょう。", "example_meaning_cn": "珍爱生命吧。", "example_meaning_en": "Let's value life."},
        "N4_450": {"example_sentence": "せ（背）中を洗ってください。", "example_reading": "せなかをあらってください。", "example_meaning_cn": "请帮我搓背。", "example_meaning_en": "Please wash my back."}
    }

    for item in vocab:
        if item['id'] in enrichment:
            item.update(enrichment[item['id']])

    with open(data_file, 'w', encoding='utf-8') as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

    print(f"Updated items up to N4_450.")

if __name__ == "__main__":
    main()
