import json
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    data_file = os.path.join(project_root, 'jlpt-web', 'src', 'data', 'vocab.json')

    if not os.path.exists(data_file):
        return

    with open(data_file, 'r', encoding='utf-8') as f:
        vocab = json.load(f)

    enrichment = {
        "N3_151": {"example_sentence": "う（浮）かんでください。", "example_reading": "うかんでください。", "example_meaning_cn": "请浮上来。", "example_meaning_en": "Please float."},
        "N3_152": {"example_sentence": "う（受）けってください。", "example_reading": "うけてください。", "example_meaning_cn": "请接受（或参加考试）。", "example_meaning_en": "Please take it/accept it."},
        "N3_153": {"example_sentence": "うご（動）かないでください。", "example_reading": "うごかないでください。", "example_meaning_cn": "请不要动。", "example_meaning_en": "Please don't move."},
        "N3_154": {"example_sentence": "うさぎ（兎）が跳ねています。", "example_reading": "うさぎがはねています。", "example_meaning_cn": "兔子正在跳跃。", "example_meaning_en": "A rabbit is hopping."},
        "N3_155": {"example_sentence": "うし（牛）が鳴いています。", "example_reading": "うしがないています。", "example_meaning_cn": "牛在叫。", "example_meaning_en": "A cow is lowing/mooing."},
        "N3_156": {"example_sentence": "うしな（失）いました。", "example_reading": "うしないました。", "example_meaning_cn": "失去了。", "example_meaning_en": "I lost it."},
        "N3_157": {"example_sentence": "うしろ（後ろ）を見てください。", "example_reading": "うしろをみてください。", "example_meaning_cn": "请看后面。", "example_meaning_en": "Please look behind you."},
        "N3_158": {"example_sentence": "うそ（嘘）をつかないでください。", "example_reading": "うそをつかないでください。", "example_meaning_cn": "请不要撒谎。", "example_meaning_en": "Please don't tell a lie."},
        "N3_159": {"example_sentence": "うた（歌）を歌いましょう。", "example_reading": "うたをうたいましょう。", "example_meaning_cn": "唱歌吧。", "example_meaning_en": "Let's sing a song."},
        "N3_160": {"example_sentence": "うたが（疑）っています。", "example_reading": "うたがっています。", "example_meaning_cn": "正在怀疑。", "example_meaning_en": "I suspect it."},
        "N3_161": {"example_sentence": "うち（家）へ帰りましょう。", "example_reading": "うちへかえりましょう。", "example_meaning_cn": "回家吧。", "example_meaning_en": "Let's go home."},
        "N3_162": {"example_sentence": "う（打）ってください。", "example_reading": "うってください。", "example_meaning_cn": "请打（或击）。", "example_meaning_en": "Please hit/strike it."},
        "N3_163": {"example_sentence": "うつく（美）しいですね。 ", "example_reading": "うつくしいですね。", "example_meaning_cn": "好美呢（或漂亮）。", "example_meaning_en": "It's beautiful, isn't it?"},
        "N3_164": {"example_sentence": "うっ（写）してください。", "example_reading": "うつしてください。", "example_meaning_cn": "请抄写（或转映）。", "example_meaning_en": "Please copy/project it."},
        "N3_165": {"example_sentence": "う（移）してください。", "example_reading": "うつしてください。", "example_meaning_cn": "请移动（或移居）。", "example_meaning_en": "Please move/transfer it."},
        "N3_166": {"example_sentence": "う（訴）えてください。", "example_reading": "うったえてください。", "example_meaning_cn": "请起诉（或控诉）。", "example_meaning_en": "Please sue/appeal it."},
        "N3_167": {"example_sentence": "うつわ（器）に入れてください。", "example_reading": "うつわにいれてください。", "example_meaning_cn": "请放进器皿（容器）里。", "example_meaning_en": "Please put it in the vessel/container."},
        "N3_168": {"example_sentence": "うで（腕）が痛いです。", "example_reading": "うでがいたいです。", "example_meaning_cn": "胳膊疼。", "example_meaning_en": "My arm hurts."},
        "N3_169": {"example_sentence": "う（産）まれました！", "example_reading": "うまれました！", "example_meaning_cn": "出生了！", "example_meaning_en": "It's born!"},
        "N3_170": {"example_sentence": "うみ（海）に行きたいです。", "example_reading": "うみにいきたいです。", "example_meaning_cn": "想去大海。", "example_meaning_en": "I want to go to the sea."},
        "N3_171": {"example_sentence": "う（埋）めてください。", "example_reading": "うめてください。", "example_meaning_cn": "请埋掉。", "example_meaning_en": "Please bury it."},
        "N3_172": {"example_sentence": "うめ（梅）の花が咲きました。", "example_reading": "うめのはながさきました。", "example_meaning_cn": "梅花开了。", "example_meaning_en": "Plum blossoms have bloomed."},
        "N3_173": {"example_sentence": "うやま（敬）ってください。", "example_reading": "うやまってください。", "example_meaning_cn": "请尊敬（敬慕）。", "example_meaning_en": "Please respect/venerate it."},
        "N3_174": {"example_sentence": "うら（裏）を見てください。", "example_reading": "うらをみてください。", "example_meaning_cn": "请看背面。", "example_meaning_en": "Please look at the back."},
        "N3_175": {"example_sentence": "うらや（羨）ましいですね。", "example_reading": "うらやましいですね。", "example_meaning_cn": "好羡慕呀（真让人眼红）。", "example_meaning_en": "How enviable."},
        "N3_176": {"example_sentence": "う（売）ってください。", "example_reading": "うってください。", "example_meaning_cn": "请卖给我。", "example_meaning_en": "Please sell it to me."},
        "N3_177": {"example_sentence": "うれ（嬉）しいです！", "example_reading": "うれしいです！", "example_meaning_cn": "好高兴呀！", "example_meaning_en": "I'm happy!"},
        "N3_178": {"example_sentence": "うわ（噂）になっています。", "example_reading": "うわさになっています。", "example_meaning_cn": "正在传流（或传闻）。", "example_meaning_en": "It's a rumor."},
        "N3_179": {"example_sentence": "うん（運）がいいですね。", "example_reading": "うんがいいですね。", "example_meaning_cn": "运气真好呢。", "example_meaning_en": "You're lucky, aren't you?"},
        "N3_180": {"example_sentence": "うんえい（運営）してください。", "example_reading": "うんえいしてください。", "example_meaning_cn": "请运营。", "example_meaning_en": "Please operate it."},
        "N3_181": {"example_sentence": "うん（運転）転してください。", "example_reading": "うんてんしてください。", "example_meaning_cn": "请驾驶。", "example_meaning_en": "Please drive."},
        "N3_182": {"example_sentence": "うん（運動）どうしましょう。", "example_reading": "うんどうしましょう。", "example_meaning_cn": "运动吧。", "example_meaning_en": "Let's exercise."},
        "N3_183": {"example_sentence": "え（絵）を描いています。", "example_reading": "えをかいています。", "example_meaning_cn": "正在画画。", "example_meaning_en": "I'm drawing a picture."},
        "N3_184": {"example_sentence": "えい（映画）画を見ましょう。", "example_reading": "えいがをみましょう。", "example_meaning_cn": "看电影吧。", "example_meaning_en": "Let's watch a movie."},
        "N3_185": {"example_sentence": "えい（英語）語が話せますか。", "example_reading": "えいごがはなせますか。", "example_meaning_cn": "会说英语吗？", "example_meaning_en": "Can you speak English?"},
        "N3_186": {"example_sentence": "えい（衛）星（せい）が飛んでいます。", "example_reading": "えいせいがとんでいます。", "example_meaning_cn": "卫星正在飞行。", "example_meaning_en": "A satellite is flying."},
        "N3_187": {"example_sentence": "えい（影響）響が大きいです。", "example_reading": "えいきょうがおおきいです。", "example_meaning_cn": "影响很大。", "example_meaning_en": "The impact is big."},
        "N3_188": {"example_sentence": "えい（営業）業時間内です。", "example_reading": "えいぎょうじかんないです。", "example_meaning_cn": "在营业时间内。", "example_meaning_en": "We're within business hours."},
        "N3_189": {"example_sentence": "えい（栄）養（よう）を摂ってください。", "example_reading": "えいようをとってください。", "example_meaning_cn": "请摄取营养。", "example_meaning_en": "Please get some nutrition."},
        "N3_190": {"example_sentence": "え（笑）顔がいいですね。", "example_reading": "えがおがいいですね。", "example_meaning_cn": "笑容真好呢。", "example_meaning_en": "Your smile is great, isn't it?"},
        "N3_191": {"example_sentence": "えさ（餌）をあげてください。", "example_reading": "えさをあげてください。", "example_meaning_cn": "请给（动物）喂食。", "example_meaning_en": "Please feed them."},
        "N3_192": {"example_sentence": "え（駅）へ行きます。", "example_reading": "えきへいきます。", "example_meaning_cn": "去车站。", "example_meaning_en": "I'm going to the station."},
        "N3_193": {"example_sentence": "え（枝）が折れました。", "example_reading": "えだがおれました。", "example_meaning_cn": "树枝断了。", "example_meaning_en": "A branch broke."},
        "N3_194": {"example_sentence": "え（選）んでください。", "example_reading": "えらんでください。", "example_meaning_cn": "请选择。", "example_meaning_en": "Please choose."},
        "N3_195": {"example_sentence": "えら（偉）いですね！", "example_reading": "えらいですね！", "example_meaning_cn": "真了不起呢！", "example_meaning_en": "You're great!"},
        "N3_196": {"example_sentence": "えら（羨）んでいます。", "example_reading": "えらんでいます。", "example_meaning_cn": "正在筛选（或选拔）。", "example_meaning_en": "I'm selecting."},
        "N3_197": {"example_sentence": "エンスト（えんすと）しました。", "example_reading": "エンストしました。", "example_meaning_cn": "引擎熄火（死火）了。", "example_meaning_en": "The engine stalled."},
        "N3_198": {"example_sentence": "えん（円）安ですね。 ", "example_reading": "えんやすですね。", "example_meaning_cn": "日元贬值呢。", "example_meaning_en": "The yen is weak, isn't it?"},
        "N3_199": {"example_sentence": "えん（延長）長してください。", "example_reading": "えんちょうしてください。", "example_meaning_cn": "请延长。", "example_meaning_en": "Please extend it."},
        "N3_200": {"example_sentence": "えん（遠慮）慮しないでください。", "example_reading": "えんりょしないでください。", "example_meaning_cn": "请不要客气。", "example_meaning_en": "Please don't hesitate."},
        "N3_201": {"example_sentence": "お（御）使いに行きます。", "example_reading": "おつかいにいきます。", "example_meaning_cn": "去跑腿（办事）。", "example_meaning_en": "I'm going on an errand."},
        "N3_202": {"example_sentence": "おい（追）いかけてください。", "example_reading": "おいかけてください。", "example_meaning_cn": "请追赶。", "example_meaning_en": "Please chase/follow them."},
        "N3_203": {"example_sentence": "おい（甥）が生まれました。", "example_reading": "おいがうまれました。", "example_meaning_cn": "外甥（或侄子）出生了。", "example_meaning_en": "My nephew was born."},
        "N3_204": {"example_sentence": "おいしい（美味しい）ですね。", "example_reading": "おいしいですね。", "example_meaning_cn": "真好吃呢（或美味）。", "example_meaning_en": "It's delicious, isn't it?"},
        "N3_205": {"example_sentence": "お（多）いですね。 ", "example_reading": "おおいですね。", "example_meaning_cn": "很多呢。", "example_meaning_en": "There are a lot, aren't there?"},
        "N3_206": {"example_sentence": "おお（大）きな声で話してください。", "example_reading": "おおきなこえではなしてください。", "example_meaning_cn": "请大声说话。", "example_meaning_en": "Please speak in a loud voice."},
        "N3_207": {"example_sentence": "おか（丘）の上に家があります。", "example_reading": "おかのうえにいえがあります。", "example_meaning_cn": "山丘上有房子。", "example_meaning_en": "There is a house on the hill."},
        "N3_208": {"example_sentence": "おか（お陰）様で元気です。", "example_reading": "おかげさまでげんきです。", "example_meaning_cn": "托您的福，身体很好。", "example_meaning_en": "Thanks to you, I'm well."},
        "N3_209": {"example_sentence": "おか（可）笑（かし）いですね。", "example_reading": "おかしいですね。", "example_meaning_cn": "真奇怪（或好笑）呢。", "example_meaning_en": "It's funny/strange, isn't it?"},
        "N3_210": {"example_sentence": "おか（菓子）菓子を食べましょう。", "example_reading": "おかしをたべましょう。", "example_meaning_cn": "吃点心（糖果）吧。", "example_meaning_en": "Let's eat some sweets."},
        "N3_211": {"example_sentence": "おか（金）金がありません。", "example_reading": "おかねがありません。", "example_meaning_cn": "没钱。", "example_meaning_en": "I have no money."},
        "N3_212": {"example_sentence": "お（起）きるのは大変です。", "example_reading": "おきるのはたいへんです。", "example_meaning_cn": "起床很痛苦。", "example_meaning_en": "It's hard to wake up."},
        "N3_213": {"example_sentence": "お（置）いてください。", "example_reading": "おいてください。", "example_meaning_cn": "请放下。", "example_meaning_en": "Please put it down."},
        "N3_214": {"example_sentence": "お（奥）様はお元気ですか。", "example_reading": "おくさまはおげんきですか。", "example_meaning_cn": "夫人身体好吗？", "example_meaning_en": "Is your wife well?"},
        "N3_215": {"example_sentence": "おく（屋）上へ行きましょう。", "example_reading": "おくじょうへいきましょう。", "example_meaning_cn": "去屋顶（顶楼）吧。", "example_meaning_en": "Let's go to the rooftop."},
        "N3_216": {"example_sentence": "おく（奥）病ですね。 ", "example_reading": "おくびょうですね。", "example_meaning_cn": "真胆小呢。", "example_meaning_en": "You're a coward, aren't you?"},
        "N3_217": {"example_sentence": "おく（送）ってください。", "example_reading": "おくってください。", "example_meaning_cn": "请发送（或赠送）。", "example_meaning_en": "Please send it."},
        "N3_218": {"example_sentence": "おく（贈）ってください。", "example_reading": "おくってください。", "example_meaning_cn": "请赠送礼物。", "example_meaning_en": "Please give as a gift."},
        "N3_219": {"example_sentence": "おく（遅）れないでください。", "example_reading": "おくれないでください。", "example_meaning_cn": "请不要迟到。", "example_meaning_en": "Please don't be late."},
        "N3_220": {"example_sentence": "おこ（起）してください。", "example_reading": "おこしてください。", "example_meaning_cn": "请叫醒我。", "example_meaning_en": "Please wake me up."},
        "N3_221": {"example_sentence": "おこな（行）ってください。", "example_reading": "おこなってください。", "example_meaning_cn": "请举行（或进行）。", "example_meaning_en": "Please conduct/perform it."},
        "N3_222": {"example_sentence": "おこ（怒）らないでください。", "example_reading": "おこらないでください。", "example_meaning_cn": "请不要生气。", "example_meaning_en": "Please don't be angry."},
        "N3_223": {"example_sentence": "お（教）えてください。", "example_reading": "おしえてください。", "example_meaning_cn": "请教我。", "example_meaning_en": "Please teach me."},
        "N3_224": {"example_sentence": "お（押）してください。", "example_reading": "おしてください。", "example_meaning_cn": "请按（或推）。", "example_meaning_en": "Please push/press."},
        "N3_225": {"example_sentence": "お（惜）しいですね！", "example_reading": "おしいですね！", "example_meaning_cn": "好可惜呀（真遗憾）！", "example_meaning_en": "How close/unfortunate!"},
        "N3_226": {"example_sentence": "お（辞）儀（ぎ）をしてください。", "example_reading": "おじぎをしてください。", "example_meaning_cn": "请鞠躬。", "example_meaning_en": "Please bow."},
        "N3_227": {"example_sentence": "お（叔）父（じ）さんに会いました。", "example_reading": "おじさんにあいました。", "example_meaning_cn": "见到了叔父（伯父）。", "example_meaning_en": "I met my uncle."},
        "N3_228": {"example_sentence": "おしゃれ（お洒落）ですね。", "example_reading": "おしゃれですね。", "example_meaning_cn": "真时髦（爱打扮）呢。", "example_meaning_en": "You're fashionable, aren't you?"},
        "N3_229": {"example_sentence": "お（襲）われました！", "example_reading": "おそわれました！", "example_meaning_cn": "被袭击了！", "example_meaning_en": "I was attacked!"},
        "N3_230": {"example_sentence": "おそ（遅）くなりました。", "example_reading": "おそくなりました。", "example_meaning_cn": "我迟到了（或晚了）。", "example_meaning_en": "I'm late."},
        "N3_231": {"example_sentence": "おそ（恐）ろしいですね。 ", "example_reading": "おそろしいですね。", "example_meaning_cn": "真可怕呢（恐怖）。", "example_meaning_en": "It's terrifying, isn't it?"},
        "N3_232": {"example_sentence": "おだ（穏）やかですね。 ", "example_reading": "おだやかですね。", "example_meaning_cn": "真温和（平静）呢。", "example_meaning_en": "It's calm/gentle, isn't it?"},
        "N3_233": {"example_sentence": "お（落）ち着いてください。", "example_reading": "おちついてください。", "example_meaning_cn": "请冷静下来。", "example_meaning_en": "Please calm down."},
        "N3_234": {"example_sentence": "お（落）ちてください。", "example_reading": "おちてください。", "example_meaning_cn": "请掉下去（或落榜）。", "example_meaning_en": "Please fall/fail."},
        "N3_235": {"example_sentence": "おっしゃ（仰）ってください。", "example_reading": "おっしゃってください。", "example_meaning_cn": "请说（说，敬称）。", "example_meaning_en": "Please say it (polite)."},
        "N3_236": {"example_sentence": "おっと（夫）は会社員です。", "example_reading": "おっとはかいしゃいんです。", "example_meaning_cn": "我丈夫是公司职员。", "example_meaning_en": "My husband is an office worker."},
        "N3_237": {"example_sentence": "お（音）がうるさいです。", "example_reading": "おとがうるさいです。", "example_meaning_cn": "声音太吵了。", "example_meaning_en": "The sound is noisy."},
        "N3_238": {"example_sentence": "おとこ（男）の子です。", "example_reading": "おとこのこです。", "example_meaning_cn": "是个男孩。", "example_meaning_en": "It's a boy."},
        "N3_239": {"example_sentence": "おとと（一昨日）会いました。", "example_reading": "おとといあいました。", "example_meaning_cn": "前天见的面。", "example_meaning_en": "I met them the day before yesterday."},
        "N3_240": {"example_sentence": "おととし（一昨年）留学しました。", "example_reading": "おととしりゅうがくしました。", "example_meaning_cn": "前年留学了。", "example_meaning_en": "I studied abroad the year before last."},
        "N3_241": {"example_sentence": "お（大人）人になってください。", "example_reading": "おとなになってください。", "example_meaning_cn": "请成熟一点（成为大人）。", "example_meaning_en": "Please grow up."},
        "N3_242": {"example_sentence": "お（驚）きました！", "example_reading": "おどろきました！", "example_meaning_cn": "大吃一惊！", "example_meaning_en": "I was surprised!"},
        "N3_243": {"example_sentence": "お（同）じですね。 ", "example_reading": "おなじですね。", "example_meaning_cn": "一样呢。", "example_meaning_en": "It's the same, isn't it?"},
        "N3_244": {"example_sentence": "おねが（願）いします。", "example_reading": "おねがいします。", "example_meaning_cn": "拜托了。", "example_meaning_en": "Please."},
        "N3_245": {"example_sentence": "おば（叔母）さんは元気ですか。", "example_reading": "おばさんはげんきですか。", "example_meaning_cn": "叔母（伯母）身体好吗？", "example_meaning_en": "Is your aunt well?"},
        "N3_246": {"example_sentence": "おはよう（おはよう）！", "example_reading": "おはよう！", "example_meaning_cn": "早安（早上好）！", "example_meaning_en": "Good morning!"},
        "N3_247": {"example_sentence": "おか（多）いですね。 ", "example_reading": "おおいですね。", "example_meaning_cn": "很多呢。", "example_meaning_en": "There are many, aren't there?"},
        "N3_248": {"example_sentence": "お（起）きてください。", "example_reading": "おきてください。", "example_meaning_cn": "请起来。", "example_meaning_en": "Please get up."},
        "N3_249": {"example_sentence": "お（送）ってください。", "example_reading": "おくってください。", "example_meaning_cn": "请发送。", "example_meaning_en": "Please send it."},
        "N3_250": {"example_sentence": "おこ（怒）ってください。", "example_reading": "おこってください。", "example_meaning_cn": "请发火（或生气）。", "example_meaning_en": "Please get angry."},
        "N3_251": {"example_sentence": "おご（奢）ってください！", "example_reading": "おごってください！", "example_meaning_cn": "请请客！", "example_meaning_en": "Please treat me!"},
        "N3_252": {"example_sentence": "お（教）えてください。", "example_reading": "おしえてください。", "example_meaning_cn": "请教我（或告诉）。", "example_meaning_en": "Please teach/tell me."},
        "N3_253": {"example_sentence": "お（押）してください。", "example_reading": "おしてください。", "example_meaning_cn": "请按（或推）。", "example_meaning_en": "Please push/press."},
        "N3_254": {"example_sentence": "おそ（遅）いですね。 ", "example_reading": "おそいですね。", "example_meaning_cn": "太慢了呢（或太晚了）。", "example_meaning_en": "It's slow/late, isn't it?"},
        "N3_255": {"example_sentence": "おたが（互）いに頑張りましょう。", "example_reading": "おたがいにがんばりましょう。", "example_meaning_cn": "互相加油吧。", "example_meaning_en": "Let's both do our best."},
        "N3_256": {"example_sentence": "お（穏）やかな天気です。", "example_reading": "おだやかなてんきです。", "example_meaning_cn": "温和的天气。", "example_meaning_en": "The weather is calm."},
        "N3_257": {"example_sentence": "お（落）ちてください。", "example_reading": "おちてください。", "example_meaning_cn": "请掉下去（或落第）。", "example_meaning_en": "Please fall/fail."},
        "N3_258": {"example_sentence": "お（落）とし物です。", "example_reading": "おとしものです。", "example_meaning_cn": "遗失物（失物）。", "example_meaning_en": "A lost item."},
        "N3_259": {"example_sentence": "おと（音）がうるさいです。", "example_reading": "おとがうるさいです。", "example_meaning_cn": "声音太吵了。", "example_meaning_en": "The sound is loud."},
        "N3_260": {"example_sentence": "おとこ（男）の子です。", "example_reading": "おとこのこです。", "example_meaning_cn": "是个男孩。", "example_meaning_en": "It's a boy."},
        "N3_261": {"example_sentence": "おとと（一昨日）会いました。", "example_reading": "おとといあいました。", "example_meaning_cn": "前天交的面。", "example_meaning_en": "I met them the day before yesterday."},
        "N3_262": {"example_sentence": "おととし（一昨年）留学しました。", "example_reading": "おととしりゅうがくしました。", "example_meaning_cn": "前年留学了。", "example_meaning_en": "I studied abroad the year before last."},
        "N3_263": {"example_sentence": "お（大人）人らしくしてください。", "example_reading": "おとならしくしてください。", "example_meaning_cn": "请表现得成熟（像大人）点。", "example_meaning_en": "Please act like an adult."},
        "N3_264": {"example_sentence": "お（驚）きました！", "example_reading": "おどろきました！", "example_meaning_cn": "惊到了！", "example_meaning_en": "I was surprised!"},
        "N3_265": {"example_sentence": "お（同）じですね。 ", "example_reading": "おなじですね。", "example_meaning_cn": "是一样的呢。", "example_meaning_en": "It's the same, isn't it?"},
        "N3_266": {"example_sentence": "おねが（願）いします。", "example_reading": "おねがいします。", "example_meaning_cn": "拜托了。", "example_meaning_en": "Please."},
        "N3_267": {"example_sentence": "お（叔母）さんはお元気ですか。", "example_reading": "おばさんはげんきですか。", "example_meaning_cn": "叔母（伯母）身体好吗？", "example_meaning_en": "Is your aunt well?"},
        "N3_268": {"example_sentence": "お（午）昼を食べましょう。", "example_reading": "おひるをたべましょう。", "example_meaning_cn": "吃午饭吧。", "example_meaning_en": "Let's eat lunch."},
        "N3_269": {"example_sentence": "おぼ（覚）えてください。", "example_reading": "おぼえてください。", "example_meaning_cn": "请记住。", "example_meaning_en": "Please remember it."},
        "N3_270": {"example_sentence": "おま（御前）えには負けない！", "example_reading": "おまえにはまけない！", "example_meaning_cn": "不会输给你的！", "example_meaning_en": "I won't lose to you!"},
        "N3_271": {"example_sentence": "おも（重）いですね。 ", "example_reading": "おもいですね。", "example_meaning_cn": "挺重的呢。", "example_meaning_en": "It's heavy, isn't it?"},
        "N3_272": {"example_sentence": "おも（思）い出しました！", "example_reading": "おもいだしました！", "example_meaning_cn": "想起来了！", "example_meaning_en": "I remembered!"},
        "N3_273": {"example_sentence": "おも（想）いやりがあります。", "example_reading": "おもいやりがあります。", "example_meaning_cn": "体贴（关心别人）。", "example_meaning_en": "I am/He is considerate."},
        "N3_274": {"example_sentence": "おもしろ（面白い）いですね。", "example_reading": "おもしろいですね。", "example_meaning_cn": "真有趣呢。", "example_meaning_en": "It's interesting, isn't it?"},
        "N3_275": {"example_sentence": "おも（思）ってください。", "example_reading": "おもってください。", "example_meaning_cn": "请认为（或想象）。", "example_meaning_en": "Please think/imagine."},
        "N3_276": {"example_sentence": "おもちゃ（玩物）で遊びます。", "example_reading": "おもちゃであそびます。", "example_meaning_cn": "玩玩具。", "example_meaning_en": "I'll play with toys."},
        "N3_277": {"example_sentence": "お（祝）いしましょう。", "example_reading": "おいわいしましょう。", "example_meaning_cn": "庆祝一下吧。", "example_meaning_en": "Let's celebrate."},
        "N3_278": {"example_sentence": "お（泳）ぎましょう。", "example_reading": "およぎましょう。", "example_meaning_cn": "游泳吧。", "example_meaning_en": "Let's swim."},
        "N3_279": {"example_sentence": "お（降）りてください。", "example_reading": "おりてください。", "example_meaning_cn": "请下来（或下车）。", "example_meaning_en": "Please get off/down."},
        "N3_280": {"example_sentence": "お（織）ってください。", "example_reading": "おってください。", "example_meaning_cn": "请编织（或折叠）。", "example_meaning_en": "Please weave/fold it."},
        "N3_281": {"example_sentence": "おか（折）ってください。", "example_reading": "おってください。", "example_meaning_cn": "请折断（或折叠）。", "example_meaning_en": "Please break/fold it."},
        "N3_282": {"example_sentence": "おか（愚）かですね。 ", "example_reading": "おろかですね。", "example_meaning_cn": "真笨呢（愚蠢）。", "example_meaning_en": "How foolish."},
        "N3_283": {"example_sentence": "お（終）わりました。", "example_reading": "おわりました。", "example_meaning_cn": "结束了。", "example_meaning_en": "It's finished."},
        "N3_284": {"example_sentence": "お（音楽）が聞こえます。", "example_reading": "おんがくがきこえます。", "example_meaning_cn": "听到了音乐。", "example_meaning_en": "I can hear music."},
        "N3_285": {"example_sentence": "おん（温度）が高すぎます。", "example_reading": "おんどがたかすぎます。", "example_meaning_cn": "温度太高了。", "example_meaning_en": "The temperature is too high."},
        "N3_286": {"example_sentence": "おん（恩）を返したいです。", "example_reading": "おんをかえしたいです。", "example_meaning_cn": "想报恩。", "example_meaning_en": "I want to repay the favor."},
        "N3_287": {"example_sentence": "か（蚊）に刺されました。", "example_reading": "かにさされました。", "example_meaning_cn": "被蚊子叮了。", "example_meaning_en": "I was bitten by a mosquito."},
        "N3_288": {"example_sentence": "かい（会議）議は終わりましたか。", "example_reading": "かいぎはおわりましたか。", "example_meaning_cn": "会议结束了吗？", "example_meaning_en": "Is the meeting over?"},
        "N3_289": {"example_sentence": "がい（外国）国に行きたいです。", "example_reading": "がいこくにいきたいです。", "example_meaning_cn": "想去国外。", "example_meaning_en": "I want to go abroad."},
        "N3_290": {"example_sentence": "かい（開始）始してください。", "example_reading": "かいししてください。", "example_meaning_cn": "请开始。", "example_meaning_en": "Please start."},
        "N3_291": {"example_sentence": "がい（外出）出の準備をします。", "example_reading": "がいしゅつのじゅんびをします。", "example_meaning_cn": "准备外出。", "example_meaning_en": "I'll get ready to go out."},
        "N3_292": {"example_sentence": "かい（解決）決しました！", "example_reading": "かいけつしました！", "example_meaning_cn": "解决了！", "example_meaning_en": "Solved!"},
        "N3_293": {"example_sentence": "がい（海岸）岸を散歩します。", "example_reading": "かいがんをさんぽします。", "example_meaning_cn": "在海岸散步。", "example_meaning_en": "I'll take a walk along the coast."},
        "N3_294": {"example_sentence": "がい（改札）札を通ります。", "example_reading": "かいさつをとおります。", "example_meaning_cn": "通过检票口。", "example_meaning_en": "I'll pass through the ticket gate."},
        "N3_295": {"example_sentence": "かい（階段）段を上がります。", "example_reading": "かいだんをあがります。", "example_meaning_cn": "上楼梯。", "example_meaning_en": "I'll go up the stairs."},
        "N3_296": {"example_sentence": "か（買）ってください。", "example_reading": "かってください。", "example_meaning_cn": "请买（给我）。", "example_meaning_en": "Please buy it."},
        "N3_297": {"example_sentence": "か（飼）ってください。", "example_reading": "かってください。", "example_meaning_cn": "请饲养（它）。", "example_meaning_en": "Please keep it as a pet."},
        "N3_298": {"example_sentence": "かえ（返）してください。", "example_reading": "かえしてください。", "example_meaning_cn": "请还给我。", "example_meaning_en": "Please return it."},
        "N3_299": {"example_sentence": "かえ（帰）ってください。", "example_reading": "かえってください。", "example_meaning_cn": "请回去。", "example_meaning_en": "Please go back/home."},
        "N3_300": {"example_sentence": "か（変）えてください。", "example_reading": "かえてください。", "example_meaning_cn": "请更换（或改变）。", "example_meaning_en": "Please change it."}
    }

    for item in vocab:
        if item['id'] in enrichment:
            item.update(enrichment[item['id']])

    with open(data_file, 'w', encoding='utf-8') as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

    print(f"Updated items up to N3_300.")

if __name__ == "__main__":
    main()
