import json
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    data_file = os.path.join(project_root, 'jlpt-web', 'src', 'data', 'vocab.json')

    if not os.path.exists(data_file):
        return

    with open(data_file, 'r', encoding='utf-8') as f:
        vocab = json.load(f)

    enrichment = {
        "N3_901": {"example_sentence": "そのまま（そのまま）にしてください。", "example_reading": "そのままにしてください。", "example_meaning_cn": "请保持原样。", "example_meaning_en": "Please leave it as it is."},
        "N3_902": {"example_sentence": "（反）ってください。", "example_reading": "そってください。", "example_meaning_cn": "请挺胸（或弯曲）。", "example_meaning_en": "Please arch/bend."},
        "N3_903": {"example_sentence": "（沿）ってください。", "example_reading": "そってください。", "example_meaning_cn": "请沿着（路或海岸）走。", "example_meaning_en": "Please go along it."},
        "N3_904": {"example_sentence": "（逸）れないでください。", "example_reading": "そ得ないでください。", "example_meaning_cn": "请不要跑偏（或分心）。", "example_meaning_en": "Please don't stray."},
        "N3_905": {"example_sentence": "ぞん（存）じ（じ）上げ（あげ）て（て）おります。", "example_reading": "ぞんじあげております。", "example_meaning_cn": "我明白（谦词，知道）。", "example_meaning_en": "I know (humble)."},
        "N3_906": {"example_sentence": "ぞん（存）じ（じ）て（て）おります。", "example_reading": "ぞんじております。", "example_meaning_cn": "我知道（谦语）。", "example_meaning_en": "I know (humble)."},
        "N3_907": {"example_sentence": "ぞん（存）外（がい）ですね。 ", "example_reading": "ぞんがいですね。", "example_meaning_cn": "出乎意料（存外）呢。", "example_meaning_en": "It's unexpected, isn't it?"},
        "N3_908": {"example_sentence": "た（他）の方はいますか。", "example_reading": "ほかのかたわいますか。", "example_meaning_cn": "还有其他人在吗？", "example_meaning_en": "Is there anyone else?"},
        "N3_909": {"example_sentence": "だい（代表）表として話します。", "example_reading": "だいひょうとしてななします。", "example_meaning_cn": "作为代表发言。", "example_meaning_en": "I'll speak as a representative."},
        "N3_910": {"example_sentence": "たい（大）したことありません。", "example_reading": "たいしたことありません。", "example_meaning_cn": "没什么大不了的。", "example_meaning_en": "It's no big deal."},
        "N3_911": {"example_sentence": "たい（対）する意見を言ってください。", "example_reading": "たいするいけんをいってください。", "example_meaning_cn": "请发表针对性的意见。", "example_meaning_en": "Please give your opinion regarding it."},
        "N3_912": {"example_sentence": "たい（対）決（けつ）してください！ ", "example_reading": "たいけつしてください！", "example_meaning_cn": "请对决吧！", "example_meaning_en": "Please face off/confront!"},
        "N3_913": {"example_sentence": "たい（対）抗（こう）してください。", "example_reading": "たいこうしてください。", "example_meaning_cn": "请对抗。", "example_meaning_en": "Please counter/oppose it."},
        "N3_914": {"example_sentence": "たい（退）職（しょく）しました。", "example_reading": "たいしょくしました。", "example_meaning_cn": "退职（或离职）了。", "example_meaning_en": "I've resigned/retired."},
        "N3_915": {"example_sentence": "たい（（体）じゅう）重（じゅう）を量ります。", "example_reading": "たいじゅうをはかります。", "example_meaning_cn": "称体重。", "example_meaning_en": "I'll weigh myself."},
        "N3_916": {"example_sentence": "たい（（体）じゅう）重（じゅう）計（けい）に乗ります。", "example_reading": "たいじゅうけいにのります。", "example_meaning_cn": "上体重秤。", "example_meaning_en": "I'll step on the scale."},
        "N3_917": {"example_sentence": "たい（対処）処してください。", "example_reading": "たいしょしてください。", "example_meaning_cn": "请处理（应对）。", "example_meaning_en": "Please handle/deal with it."},
        "N3_918": {"example_sentence": "たい（対象）象者は誰ですか。", "example_reading": "たいしょうしゃはだれですか。", "example_meaning_cn": "对象（目标群体）是谁？", "example_meaning_en": "Who is the target?"},
        "N3_919": {"example_sentence": "たい（態度）度（ど）に気をつけてください。", "example_reading": "たいどにきをつけてください。", "example_meaning_cn": "请注意态度。", "example_meaning_en": "Please mind your attitude."},
        "N3_920": {"example_sentence": "たい（大）衆（しゅう）食堂へ行きます。", "example_reading": "たいしゅうしょくどうへいきます。", "example_meaning_cn": "去大众食堂。", "example_meaning_en": "I'm going to a public cafeteria."},
        "N3_921": {"example_sentence": "だい（（体）てい）体（てい）わかります。", "example_reading": "だいたいわかります。", "example_meaning_cn": "大概明白。", "example_meaning_en": "I mostly understand."},
        "N3_922": {"example_sentence": "たい（（体）どく）得（どく）してください。", "example_reading": "たいどくしてください。", "example_meaning_cn": "请领悟（或身教）。", "example_meaning_en": "Please master/realize it through experience."},
        "N3_923": {"example_sentence": "だい（台）所（どころ）で料理します。", "example_reading": "だいどころでりょうりします。", "example_meaning_cn": "在厨房做饭。", "example_meaning_en": "I'll cook in the kitchen."},
        "N3_924": {"example_sentence": "たい（対）等（とう）に接してください。", "example_reading": "たいとうにせっしてください。", "example_meaning_cn": "请对等对待。", "example_meaning_en": "Please treat them equally."},
        "N3_925": {"example_sentence": "たい（滞）納（のう）しないでください。", "example_reading": "たいのうしないでください。", "example_meaning_cn": "请不要欠费（滞纳）。", "example_meaning_en": "Please don't default on payment."},
        "N3_926": {"example_sentence": "（（耐）た）えてください。", "example_reading": "たえてください。", "example_meaning_cn": "请忍耐。", "example_meaning_en": "Please endure/bear it."},
        "N3_927": {"example_sentence": "（（絶）た）えてしまいました。", "example_reading": "たえてしまいました。", "example_meaning_cn": "绝迹（或断绝）了。", "example_meaning_en": "It has died out/become extinct."},
        "N3_928": {"example_sentence": "（（倒）たお）れてしまいました。", "example_reading": "たおれてしまいました。", "example_meaning_cn": "倒下了。", "example_meaning_en": "I fell down/it collapsed."},
        "N3_929": {"example_sentence": "た（他）の方に聞いてください。", "example_reading": "ほかのかたにきいてください。", "example_meaning_cn": "请问其他人。", "example_meaning_en": "Please ask someone else."},
        "N3_930": {"example_sentence": "たか（高）いですね！", "example_reading": "たかいですね！", "example_meaning_cn": "真贵（或高）呢！", "example_meaning_en": "How expensive/high!"},
        "N3_931": {"example_sentence": "たが（互）いに助け合いましょう。", "example_reading": "たがいにたすけあいましょう。", "example_meaning_cn": "互相帮助吧。", "example_meaning_en": "Let's help each other."},
        "N3_932": {"example_sentence": "たか（宝）物（もの）です。", "example_reading": "たからものです。", "example_meaning_cn": "是宝物（宝贝）。", "example_meaning_en": "It's a treasure."},
        "N3_933": {"example_sentence": "たき（焚）いてください。", "example_reading": "たいてください。", "example_meaning_cn": "请烧（或煮饭）。", "example_meaning_en": "Please burn/cook (rice)."},
        "N3_934": {"example_sentence": "たく（宅）配便が届きました。", "example_reading": "たくはいびんがとどきました。", "example_meaning_cn": "快递到了。", "example_meaning_en": "The courier arrived."},
        "N3_935": {"example_sentence": "たくま（逞）しいですね！", "example_reading": "たくましいですね！", "example_meaning_cn": "真强壮呢！", "example_meaning_en": "How robust/strong!"},
        "N3_936": {"example_sentence": "た（（確）たし）かめてください。", "example_reading": "たしかめてください。", "example_meaning_cn": "请确认。", "example_meaning_en": "Please confirm/verify it."},
        "N3_937": {"example_sentence": "たしょう（多少）はあります。", "example_reading": "たしょうわあります。", "example_meaning_cn": "多少还是有些的。", "example_meaning_en": "There is a little (somewhat)."},
        "N3_938": {"example_sentence": "たす（（助）たし）けてください！ ", "example_reading": "たすけてください！", "example_meaning_cn": "请救命（或帮助我）！", "example_meaning_en": "Please help/save me!"},
        "N3_939": {"example_sentence": "たた（畳）んでください。", "example_reading": "たたんでください。", "example_meaning_cn": "请叠好。", "example_meaning_en": "Please fold it."},
        "N3_940": {"example_sentence": "（（戦）たたか）ってください！ ", "example_reading": "たたかってください！", "example_meaning_cn": "战斗吧！", "example_meaning_en": "Please fight!"},
        "N3_941": {"example_sentence": "たた（叩）いてください。", "example_reading": "たたいてください。", "example_meaning_cn": "请拍打（或敲）。", "example_meaning_en": "Please strike/clap."},
        "N3_942": {"example_sentence": "ただ（（唯）ただ）の友達です。", "example_reading": "ただのともだちです。", "example_meaning_cn": "仅仅是朋友。", "example_meaning_en": "We're just friends."},
         "N3_943": {"example_sentence": "ただ（正しい）しい判断です。", "example_reading": "ただしいはんだんです。", "example_meaning_cn": "正确的判断。", "example_meaning_en": "It's a correct judgment."},
        "N3_944": {"example_sentence": "たた（（正）ただ）してください。", "example_reading": "ただしてください。", "example_meaning_cn": "请修正（或端正）。", "example_meaning_en": "Please correct/rectify it."},
        "N3_945": {"example_sentence": "たた（（漂）ただよ）っています。", "example_reading": "ただよっています。", "example_meaning_cn": "正飘荡（或弥漫）着。", "example_meaning_en": "It's drifting/wafting."},
        "N3_946": {"example_sentence": "ただち（直ち）に実行してください。", "example_reading": "ただちにじっこうしてください。", "example_meaning_cn": "请立即执行。", "example_meaning_en": "Please carry it out immediately."},
        "N3_947": {"example_sentence": "た（（立）た）ってください。", "example_reading": "たってください。", "example_meaning_cn": "请站起来。", "example_meaning_en": "Please stand up."},
        "N3_948": {"example_sentence": "た（（達）だっ）してください。", "example_reading": "たしてください。", "example_meaning_cn": "请达到（或通达）。", "example_meaning_en": "Please reach/achieve it."},
        "N3_949": {"example_sentence": "た（（断）た）ってください。", "example_reading": "たってください。", "example_meaning_cn": "请切断（或拒绝）。", "example_meaning_en": "Please cut off/refuse it."},
        "N3_950": {"example_sentence": "だ（（脱）だっ）してください。", "example_reading": "だっしてください。", "example_meaning_cn": "请脱离（或逃脱）。", "example_meaning_en": "Please escape/depart from it."},
        "N3_951": {"example_sentence": "たて（（建）たて）てください。", "example_reading": "たててください。", "example_meaning_cn": "请建造。", "example_meaning_en": "Please build it."},
        "N3_952": {"example_sentence": "たと（（例）たと）えば...", "example_reading": "たとえば。", "example_meaning_cn": "比如...", "example_meaning_en": "For example..."},
        "N3_953": {"example_sentence": "たな（棚）に置いてください。", "example_reading": "たなにおいてください。", "example_meaning_cn": "请放在搁板上。", "example_meaning_en": "Please put it on the shelf."},
        "N3_954": {"example_sentence": "たに（（谷）たに）に降ります。", "example_reading": "たににおります。", "example_meaning_cn": "下到山谷去。", "example_meaning_en": "I'll go down to the valley."},
        "N3_955": {"example_sentence": "た（（楽）たの）しんでください。", "example_reading": "たのしんでください。", "example_meaning_cn": "请享受。", "example_meaning_en": "Please enjoy."},
        "N3_956": {"example_sentence": "たの（頼）んでください。", "example_reading": "たのんでください。", "example_meaning_cn": "请恳求（或拜托）。", "example_meaning_en": "Please ask/request."},
        "N3_957": {"example_sentence": "たは（（束）たば）ねてください。", "example_reading": "たばねてください。", "example_meaning_cn": "请捆成捆。", "example_meaning_en": "Please tie them in a bundle."},
        "N3_958": {"example_sentence": "た（（度）たび）に思い出します。", "example_reading": "たびにおもいだします。", "example_meaning_cn": "每当那时就想起。", "example_meaning_en": "I remember it every time."},
        "N3_959": {"example_sentence": "たび（（旅）たび）に出ます。", "example_reading": "たびにでます。", "example_meaning_cn": "出发去旅行。", "example_meaning_en": "I'm going on a trip."},
        "N3_960": {"example_sentence": "だま（（騙）だま）されないでください。", "example_reading": "だまされないでください。", "example_meaning_cn": "请不要被骗。", "example_meaning_en": "Please don't be fooled."},
        "N3_961": {"example_sentence": "だま（黙）ってください。", "example_reading": "だまってください。", "example_meaning_cn": "请沉默（或收声）。", "example_meaning_en": "Please keep quiet."},
        "N3_962": {"example_sentence": "ため（溜）めてください。", "example_reading": "ためてください。", "example_meaning_cn": "请积攒（或堆积）。", "example_meaning_en": "Please accumulate/collect it."},
        "N3_963": {"example_sentence": "だめ（駄目）ですね。 ", "example_reading": "だめですね。", "example_meaning_cn": "不行（没用）呢。", "example_meaning_en": "It's no good/useless, isn't it?"},
        "N3_964": {"example_sentence": "た（（足）た）りないです。", "example_reading": "たりないです。", "example_meaning_cn": "不够。", "example_meaning_en": "It's not enough."},
        "N3_965": {"example_sentence": "たる（足）るところがありません。", "example_reading": "たるところがありません。", "example_meaning_cn": "没有什么可欠缺的（满足了）。", "example_meaning_en": "There is nothing lacking."},
        "N3_966": {"example_sentence": "た（（誰）だれ）かに聞いてください。", "example_reading": "だれかにきいてください。", "example_meaning_cn": "请去问问谁。", "example_meaning_en": "Please ask someone."},
        "N3_967": {"example_sentence": "たん（（単）たん）なミスです。", "example_reading": "たんなみすです。", "example_meaning_cn": "只是个单纯的失误。", "example_meaning_en": "It's just a simple mistake."},
        "N3_968": {"example_sentence": "たん（（短）たん）期（き）留学します。", "example_reading": "たんきりゅうがくします。", "example_meaning_cn": "短期留学。", "example_meaning_en": "I'll study abroad short-term."},
        "N3_969": {"example_sentence": "たん（単語）語を覚えてください。", "example_reading": "たんごをおぼえてください。", "example_meaning_cn": "请记单词。", "example_meaning_en": "Please memorize the words."},
        "N3_970": {"example_sentence": "たん（単位）位を落としました。", "example_reading": "たんいをおとしました。", "example_meaning_cn": "丢了学分（挂科）。", "example_meaning_en": "I failed to get the credits."},
        "N3_971": {"example_sentence": "たん（誕生日）生（じょう）日（び）おめでとう！", "example_reading": "たんじょうびおめでとう！", "example_meaning_cn": "生日快乐！", "example_meaning_en": "Happy birthday!"},
        "N3_972": {"example_sentence": "たん（（端）たん）末（まつ）を操作してください。", "example_reading": "たんまつをそうさしてください。", "example_meaning_cn": "请操作终端。", "example_meaning_en": "Please operate the terminal."},
        "N3_973": {"example_sentence": "たん（（担）たん）任（にん）は誰ですか。", "example_reading": "たんにんわだれですか。", "example_meaning_cn": "班主任是谁？", "example_meaning_en": "Who is the teacher in charge?"},
        "N3_974": {"example_sentence": "たん（（短）たん）所（しょ）を直してください。", "example_reading": "たんしょをなおしてください。", "example_meaning_cn": "请改掉缺点（短处）。", "example_meaning_en": "Please fix your shortcomings."},
        "N3_975": {"example_sentence": "だい（（題）だい）目（もく）を教えてください。", "example_reading": "だいもくをおしえてください。", "example_meaning_cn": "请告诉我题目（标题）。", "example_meaning_en": "Please tell me the subject/title."},
        "N3_976": {"example_sentence": "（（血）ち）が出ました。", "example_reading": "ちがでました。", "example_meaning_cn": "出血了。", "example_meaning_en": "It's bleeding."},
        "N3_977": {"example_sentence": "ち（（値）ち）を測ってください。", "example_reading": "ちをはかってください。", "example_meaning_cn": "请测量数值。", "example_meaning_en": "Please measure the value."},
        "N3_978": {"example_sentence": "ち（（知）ち）恵（え）を絞ってください。", "example_reading": "ちえをしぼってください。", "example_meaning_cn": "请动动脑筋（出主意）。", "example_meaning_en": "Please squeeze your brain/be creative."},
        "N3_979": {"example_sentence": "ち（（遅）ち）延（えん）しています。", "example_reading": "ちえんしています。", "example_meaning_cn": "正在延迟（或晚点）。", "example_meaning_en": "It's delayed."},
        "N3_980": {"example_sentence": "ち（（地）ち）下（か）へ行きます。", "example_reading": "ちかへいきます。", "example_meaning_cn": "去地下。", "example_meaning_en": "Go to the basement."},
        "N3_981": {"example_sentence": "（（違）ちが）います。", "example_reading": "ちがいます。", "example_meaning_cn": "不对（不同）。", "example_meaning_en": "That's wrong/different."},
        "N3_982": {"example_sentence": "（（近）ちか）づかないでください！ ", "example_reading": "ちかづかないでください！", "example_meaning_cn": "请不要靠近！", "example_meaning_en": "Please don't get close!"},
        "N3_983": {"example_sentence": "（（誓）ちか）ってください。", "example_reading": "ちかってください。", "example_meaning_cn": "请发誓。", "example_meaning_en": "Please swear/vow."},
        "N3_984": {"example_sentence": "ち（（地）ち）球（きゅう）を守りましょう。", "example_reading": "ちきゅうをまもりましょう。", "example_meaning_cn": "保护地球吧。", "example_meaning_en": "Let's save the earth."},
        "N3_985": {"example_sentence": "ち（（地区）く）を掃除します。", "example_reading": "ちくをそうじします。", "example_meaning_cn": "打扫地区（社区）。", "example_meaning_en": "I'll clean the district/area."},
        "N3_986": {"example_sentence": "ち（（畜）ちく）産（さん）をしています。", "example_reading": "ちくさんをしています。", "example_meaning_cn": "在搞畜牧业。", "example_meaning_en": "Doing livestock farming."},
        "N3_987": {"example_sentence": "ち（（蓄）ちく）積（せき）してください。", "example_reading": "ちくせきしてください。", "example_meaning_cn": "请积累（蓄积）。", "example_meaning_en": "Please accumulate it."},
        "N3_988": {"example_sentence": "ち（（恥）はじ）をかきました。", "example_reading": "はじをかきました。", "example_meaning_cn": "丢人了。", "example_meaning_en": "I was embarrassed/lost face."},
        "N3_989": {"example_sentence": "ち（（知）ち）識（しき）を深めてください。", "example_reading": "ちしきをふかめてください。", "example_meaning_cn": "请深造（加深知识）。", "example_meaning_en": "Please deepen your knowledge."},
        "N3_990": {"example_sentence": "（（縮）ちじ）めてください。", "example_reading": "ちぢめてください。", "example_meaning_cn": "请缩短（或压缩）。", "example_meaning_en": "Please shorten/compress it."},
        "N3_991": {"example_sentence": "（（縮）ちぢ）んでしまいました。", "example_reading": "ちぢんでしまいました。", "example_meaning_cn": "缩水了。", "example_meaning_en": "It has shrunk."},
        "N3_992": {"example_sentence": "ち（（知）ち）的（てき）な人ですね。", "example_reading": "ちてきなひとですね。", "example_meaning_cn": "真是个知性（聪明）的人呢。", "example_meaning_en": "They're an intellectual person, aren't they?"},
        "N3_993": {"example_sentence": "ち（（地点）てん）を教えてください。", "example_reading": "ちてんをおしえてください。", "example_meaning_cn": "请告诉地点。", "example_meaning_en": "Please tell me the location/point."},
        "N3_994": {"example_sentence": "ち（（茶）ちゃ）を飲みましょう。", "example_reading": "ちゃをのみましょう。", "example_meaning_cn": "喝茶吧。", "example_meaning_en": "Let's drink tea."},
        "N3_995": {"example_sentence": "ちゅう（（中）ちゅう）央（おう）に立ってください。", "example_reading": "ちゅうおうにたってください。", "example_meaning_cn": "请站在中央。", "example_meaning_en": "Please stand in the center."},
        "N3_996": {"example_sentence": "ちゅう（（中）ちゅう）学（がく）へ行きます。", "example_reading": "ちゅうがくへいきます。", "example_meaning_cn": "去中学。", "example_meaning_en": "I'm going to junior high school."},
        "N3_997": {"example_sentence": "ちゅう（（中）ちゅう）古（こ）の車を買いました。", "example_reading": "ちゅうこのくるまをかいました。", "example_meaning_cn": "买了二手车。", "example_meaning_en": "I bought a used car."},
        "N3_998": {"example_sentence": "ちゅう（中止）止してください。", "example_reading": "ちゅうししてください。", "example_meaning_cn": "请中止（取消）。", "example_meaning_en": "Please cancel/abort it."},
        "N3_999": {"example_sentence": "ちゅう（注意）意してください。", "example_reading": "ちゅういしてください。", "example_meaning_cn": "请注意。", "example_meaning_en": "Please be careful."},
        "N3_1000": {"example_sentence": "ちゅう（注文）文してください。", "example_reading": "ちゅうもんしてください。", "example_meaning_cn": "请下单（订购）。", "example_meaning_en": "Please order."},
        "N3_1001": {"example_sentence": "ちゅう（注）射（しゃ）が怖いです。", "example_reading": "ちゅうしゃがこわいです。", "example_meaning_cn": "怕打针。", "example_meaning_en": "I'm afraid of injections."},
        "N3_1002": {"example_sentence": "ちゅう（駐）車（しゃ）しないでください。", "example_reading": "ちゅうしゃしないでください。", "example_meaning_cn": "请不要停车。", "example_meaning_en": "Please don't park here."},
        "N3_1003": {"example_sentence": "ちゅう（（中）ちゅう）立（りつ）を守ってください。", "example_reading": "ちゅうりつをまもってください。", "example_meaning_cn": "请保持中立。", "example_meaning_en": "Please remain neutral."},
        "N3_1004": {"example_sentence": "ちょう（調査）査してください。", "example_reading": "ちょうさしてください。", "example_meaning_cn": "请调查。", "example_meaning_en": "Please investigate."},
        "N3_1005": {"example_sentence": "ちょう（頂）戴（だい）します。", "example_reading": "ちょうだいします。", "example_meaning_cn": "我领受了（礼貌地收下）。", "example_meaning_en": "I'll receive it (polite)."},
        "N3_1006": {"example_sentence": "ちょう（（調）ちょう）子（し）はどうですか。", "example_reading": "ちょうしはどうですか。", "example_meaning_cn": "情况怎么样？", "example_meaning_en": "How's your condition?"},
        "N3_1007": {"example_sentence": "ちょう（頂点）点（てん）に立ちます。", "example_reading": "ちょうてんにたちます。", "example_meaning_cn": "登上顶峰。", "example_meaning_en": "I'll stand at the summit."},
        "N3_1008": {"example_sentence": "ちょう（（長）ちょう）度（ど）良いです。", "example_reading": "ちょうどいいです。", "example_meaning_cn": "刚刚好。", "example_meaning_en": "It's just right."},
        "N3_1009": {"example_sentence": "ちょう（（調）ちょう）節（せつ）してください。", "example_reading": "ちょうせつしてください。", "example_meaning_cn": "请调节。", "example_meaning_en": "Please adjust it."},
        "N3_1010": {"example_sentence": "ちょう（（超）ちょう）過（か）しています。", "example_reading": "ちょうかしています。", "example_meaning_cn": "已经超出了（超过）。", "example_meaning_en": "It's exceeding the limit."},
        "N3_1011": {"example_sentence": "ちょう（挑战）戦してください！ ", "example_reading": "ちょうせんしてください！", "example_meaning_cn": "请挑战吧！", "example_meaning_en": "Please challenge yourself!"},
        "N3_1012": {"example_sentence": "ちょう（（調）ちょう）理（り）してください。", "example_reading": "ちょうりしてください。", "example_meaning_cn": "请烹饪（料理）。", "example_meaning_en": "Please cook it."},
        "N3_1013": {"example_sentence": "（（散）ち）ってください。", "example_reading": "ちってください。", "example_meaning_cn": "请凋谢（或散开）。", "example_meaning_en": "Please scatter/fall (flowers)."},
        "N3_1014": {"example_sentence": "（散）らかさないでください。", "example_reading": "ちらかさないでください。", "example_meaning_cn": "请不要弄乱。", "example_meaning_en": "Please don't make a mess."},
        "N3_1015": {"example_sentence": "つい（（通）つう）信（しん）が途絶えました。", "example_reading": "つうしんがとだえました。", "example_meaning_cn": "通信中断了。", "example_meaning_en": "Communication was cut off."},
        "N3_1016": {"example_sentence": "つい（（通）つう）知（ち）が来ました。", "example_reading": "つうちがきました。", "example_meaning_cn": "收到了通知。", "example_meaning_en": "A notification arrived."},
        "N3_1017": {"example_sentence": "つい（（通）つう）過（か）します。", "example_reading": "つうかします。", "example_meaning_cn": "通过。", "example_meaning_en": "It passes through."},
        "N3_1018": {"example_sentence": "つ（（使）つか）ってください。", "example_reading": "つかってください。", "example_meaning_cn": "请使用。", "example_meaning_en": "Please use it."},
        "N3_1019": {"example_sentence": "（（捕）つか）まえました！ ", "example_reading": "つかまえました！", "example_meaning_cn": "抓住了！", "example_meaning_en": "I caught it!"},
        "N3_1020": {"example_sentence": "つ（（疲）つか）れましたね。", "example_reading": "つかれましたね。", "example_meaning_cn": "累了吧。", "example_meaning_en": "You're tired, aren't you?"},
        "N3_1021": {"example_sentence": "（（漬）つ）けてください。", "example_reading": "つけてください。", "example_meaning_cn": "请浸泡（或腌制）。", "example_meaning_en": "Please soak/pickle it."},
        "N3_1022": {"example_sentence": "（（浸）つ）かってください。", "example_reading": "つかってください。", "example_meaning_cn": "请浸在里头（或泡澡）。", "example_meaning_en": "Please soak in it."},
        "N3_1023": {"example_sentence": "（（突）つ）いてください。", "example_reading": "ついてください。", "example_meaning_cn": "请冲撞（或刺）。", "example_meaning_en": "Please thrust/pke it."},
        "N3_1024": {"example_sentence": "（（付）つ）いてきてください。", "example_reading": "ついてきてください。", "example_meaning_cn": "请跟我来。", "example_meaning_en": "Please follow me."},
        "N3_1025": {"example_sentence": "つぎ（（次）つぎ）は何ですか。", "example_reading": "つぎわなんですか。", "example_meaning_cn": "下一个是什么？", "example_meaning_en": "What's next?"},
        "N3_1026": {"example_sentence": "（（告）つ）げてください。", "example_reading": "つげてください。", "example_meaning_cn": "请告知。", "example_meaning_en": "Please inform/notify."},
        "N3_1027": {"example_sentence": "（（作）つく）ってください。", "example_reading": "つくってください。", "example_meaning_cn": "请制作。", "example_meaning_en": "Please make it."},
        "N3_1028": {"example_sentence": "（（造）つく）られています。", "example_reading": "つくられています。", "example_meaning_cn": "正在制造着（产品）。", "example_meaning_en": "It is being manufactured."},
        "N3_1029": {"example_sentence": "（（点）つ）けてください。", "example_reading": "つけてください。", "example_meaning_cn": "请点亮（或打开）。", "example_meaning_en": "Please turn it on."},
        "N3_1030": {"example_sentence": "（（付）つ）けてください。", "example_reading": "つけてください。", "example_meaning_cn": "请附上（或贴上）。", "example_meaning_en": "Please attach/apply it."},
        "N3_1031": {"example_sentence": "（（着）つ）けてください。", "example_reading": "つけてください。", "example_meaning_cn": "请穿上（或佩戴）。", "example_meaning_en": "Please wear/put it on."},
        "N3_1032": {"example_sentence": "（（漬）つ）けてください。", "example_reading": "つけてください。", "example_meaning_cn": "请腌制（泡）。", "example_meaning_en": "Please pickle it."},
        "N3_1033": {"example_sentence": "（（伝）つた）えてください。", "example_reading": "つたえてください。", "example_meaning_cn": "请转告。", "example_meaning_en": "Please convey/pass it on."},
        "N3_1034": {"example_sentence": "（（伝）つた）わっています。", "example_reading": "つたわっています。", "example_meaning_cn": "传达到了。", "example_meaning_en": "It's being conveyed/transmitted."},
        "N3_1035": {"example_sentence": "（（突）つ）き（（合）あ）ってください！ ", "example_reading": "つきあってください！", "example_meaning_cn": "请和我交往（或陪陪我）！", "example_meaning_en": "Please go out with me/keep me company!"},
        "N3_1036": {"example_sentence": "つぎ（（継）つぎ）に繋げ（つなげ）てください。", "example_reading": "つぎにつなげてください。", "example_meaning_cn": "请连接到下一步（继承）。", "example_meaning_en": "Please pass it on to the next one."},
        "N3_1037": {"example_sentence": "（（点）つ）いています。", "example_reading": "ついています。", "example_meaning_cn": "已经开着（亮着）。", "example_meaning_en": "It's already on."},
        "N3_1038": {"example_sentence": "（（机）つくえ）の上に置いてください。", "example_reading": "つくえのうえにおいてください。", "example_meaning_cn": "请放在桌子上。", "example_meaning_en": "Please put it on the desk."},
        "N3_1039": {"example_sentence": "（（作）つく）ってください。", "example_reading": "つくってください。", "example_meaning_cn": "请制作。", "example_meaning_en": "Please create it."},
        "N3_1040": {"example_sentence": "つ（（疲）つか）れました...", "example_reading": "つかれました。", "example_meaning_cn": "累了...", "example_meaning_en": "I'm tired..."},
        "N3_1041": {"example_sentence": "（（包）つつ）んでください。", "example_reading": "つつんでください。", "example_meaning_cn": "请包起来。", "example_meaning_en": "Please wrap it."},
        "N3_1042": {"example_sentence": "（（勤）つと）めています。", "example_reading": "つとめています。", "example_meaning_cn": "正任职（或工作）着。", "example_meaning_en": "I'm employed there."},
        "N3_1043": {"example_sentence": "（（努）つと）めてください。", "example_reading": "つとめてください。", "example_meaning_cn": "请努力（尽力）。", "example_meaning_en": "Please strive/make an effort."},
        "N3_1044": {"example_sentence": "（（繋）つな）いでください。", "example_reading": "つないでください。", "example_meaning_cn": "请连接。", "example_meaning_en": "Please connect it."},
        "N3_1045": {"example_sentence": "（（抓）つね）らないでください！ ", "example_reading": "つねらないでください！", "example_meaning_cn": "请不要掐我！", "example_meaning_en": "Please don't pinch me!"},
        "N3_1046": {"example_sentence": "（（潰）つぶ）してしまいました。", "example_reading": "つぶしてしまいました。", "example_meaning_cn": "压坏（搞砸）了。", "example_meaning_en": "I crushed/wrecked it."},
        "N3_1047": {"example_sentence": "（（蕾）つぼみ）が膨らみました。", "example_reading": "つぼみがふくらみました。", "example_meaning_cn": "花蕾膨胀了。", "example_meaning_en": "The bud has swollen."},
        "N3_1048": {"example_sentence": "（（罪）つみ）を償って（つぐなって）ください。", "example_reading": "つみをつぐなってください。", "example_meaning_cn": "请赎罪。", "example_meaning_en": "Please atone for your sins."},
        "N3_1049": {"example_sentence": "（（詰）つ）めてください。", "example_reading": "つめてください。", "example_meaning_cn": "请塞进（或精简）。", "example_meaning_en": "Please stuff/pack/condense it."},
        "N3_1050": {"example_sentence": "（（冷）つめ）たいですね。 ", "example_reading": "つめたいですね。", "example_meaning_cn": "真冷（冰凉）呢。", "example_meaning_en": "It's cold/chilly, isn't it?"}
    }

    for item in vocab:
        if item['id'] in enrichment:
            item.update(enrichment[item['id']])

    with open(data_file, 'w', encoding='utf-8') as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

    print(f"Updated items up to N3_1050.")

if __name__ == "__main__":
    main()
