import json
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    data_file = os.path.join(project_root, 'jlpt-web', 'src', 'data', 'vocab.json')

    if not os.path.exists(data_file):
        return

    with open(data_file, 'r', encoding='utf-8') as f:
        vocab = json.load(f)

    enrichment = {
        "N4_0": {"example_sentence": "あ、危ない！気をつけて。", "example_reading": "あ、あぶない！きをつけて。", "example_meaning_cn": "啊，危险！小心点。", "example_meaning_en": "Ah, dangerous! Be careful."},
        "N4_1": {"example_sentence": "あ、雨が降り始めました。", "example_reading": "あ、あめがふりはじめました。", "example_meaning_cn": "啊，开始下雨了。", "example_meaning_en": "Ah, it started raining."},
        "N4_2": {"example_sentence": "あ、いいですね。そうしましょう。", "example_reading": "あ、いいですね。そうしましょう。", "example_meaning_cn": "啊，不错呢。就这么办吧。", "example_meaning_en": "Ah, that's good. Let's do that."},
        "N4_3": {"example_sentence": "ああいう人は苦手です。", "example_reading": "ああいうひとはにがてです。", "example_meaning_cn": "我不擅长对付那样的人。", "example_meaning_en": "I'm not good with people like that."},
        "N4_4": {"example_sentence": "間（あいだ）に入ってください。", "example_reading": "あいだにはいってください。", "example_meaning_cn": "请进到中间去。", "example_meaning_en": "Please get in between."},
        "N4_5": {"example_sentence": "相手（あいて）の目を見て話しましょう。", "example_reading": "あいてのめをみてはなしましょう。", "example_meaning_cn": "看着对方的眼睛说话吧。", "example_meaning_en": "Let's speak while looking at the other person's eyes."},
        "N4_6": {"example_sentence": "あう（合う）服がありません。", "example_reading": "あうふくがありません。", "example_meaning_cn": "没有合适的衣服。", "example_meaning_en": "I don't have any clothes that fit."},
        "N4_7": {"example_sentence": "あかちゃん（赤ちゃん）が泣いています。", "example_reading": "あかちゃんがないています。", "example_meaning_cn": "婴儿在哭。", "example_meaning_en": "The baby is crying."},
        "N4_8": {"example_sentence": "あがる（上がる）階段はあちらです。", "example_reading": "あがるかいだんはあちらです。", "example_meaning_cn": "上楼的楼梯在那边。", "example_meaning_en": "The stairs going up are over there."},
        "N4_9": {"example_sentence": "あかんぼう（赤ん坊）は寝ています。", "example_reading": "あかんぼうはねています。", "example_meaning_cn": "婴儿正在睡觉。", "example_meaning_en": "The baby is sleeping."},
        "N4_10": {"example_sentence": "あく（空く）席がありますか。", "example_reading": "あくせきがありますか。", "example_meaning_cn": "有空座吗？", "example_meaning_en": "Is there an empty seat?"},
        "N4_11": {"example_sentence": "アクセサリ（アクセサリー）を買いました。", "example_reading": "アクセサリーをかいました。", "example_meaning_cn": "买了首饰。", "example_meaning_en": "I bought some accessories."},
        "N4_12": {"example_sentence": "あげる（上げる）手を挙げてください。", "example_reading": "あげるてをあげてください。", "example_meaning_cn": "请举手。", "example_meaning_en": "Please raise your hand."},
        "N4_13": {"example_sentence": "あさねぼう（朝寝坊）してしまいました。", "example_reading": "あさねぼうしてしまいました。", "example_meaning_cn": "睡懒觉了（起晚了）。", "example_meaning_en": "I overslept."},
        "N4_14": {"example_sentence": "あじ（味）はどうですか。", "example_reading": "あじはどうですか。", "example_meaning_cn": "味道怎么样？", "example_meaning_en": "How is the taste?"},
        "N4_15": {"example_sentence": "あじあ（アジア）料理が好きです。", "example_reading": "アジアりょうりがすきです。", "example_meaning_cn": "我喜欢亚洲菜。", "example_meaning_en": "I like Asian food."},
        "N4_16": {"example_sentence": "あし（明日）は休みです。", "example_reading": "あしたはやすみです。", "example_meaning_cn": "明天休息。", "example_meaning_en": "Tomorrow is a holiday."},
        "N4_17": {"example_sentence": "あそび（遊び）に行きましょう。", "example_reading": "あそびにいきましょう。", "example_meaning_cn": "去玩吧。", "example_meaning_en": "Let's go play/out."},
        "N4_18": {"example_sentence": "あたたまる（温まる）スープを飲みます。", "example_reading": "あたたまるスープをのみます。", "example_meaning_cn": "喝暖身的汤。", "example_meaning_en": "I drink soup that warms me up."},
        "N4_19": {"example_sentence": "あたためる（温める）弁当を温めてください。", "example_reading": "あたためるべんとうをあたためてください。", "example_meaning_cn": "请加热下便当。", "example_meaning_en": "Please warm up the bento."},
        "N4_20": {"example_sentence": "あたま（頭）がいいですね。", "example_reading": "あたまがいいですね。", "example_meaning_cn": "真聪明呢。", "example_meaning_en": "You're smart, aren't you?"},
        "N4_21": {"example_sentence": "あたる（当たる）宝くじが当たりました。", "example_reading": "あたるたからくじがあたりました。", "example_meaning_cn": "中彩票了。", "example_meaning_en": "I won the lottery."},
        "N4_22": {"example_sentence": "あちらこちら（あっちこっち）探しました。", "example_reading": "あっちこっちさがしました。", "example_meaning_cn": "到处找过了。", "example_meaning_en": "I looked everywhere."},
        "N4_23": {"example_sentence": "あつい（厚い）本を読んでいます。", "example_reading": "あついほんをよんでいます。", "example_meaning_cn": "正在看厚书。", "example_meaning_en": "I'm reading a thick book."},
        "N4_24": {"example_sentence": "あつまる（集まる）人が集まっています。", "example_reading": "あつまるひとがあつまっています。", "example_meaning_cn": "人们正在聚集。", "example_meaning_en": "People are gathering."},
        "N4_25": {"example_sentence": "あつめる（集める）切手を集めています。", "example_reading": "あつめるきってをあつめています。", "example_meaning_cn": "正在集邮。", "example_meaning_en": "I am collecting stamps."},
        "N4_26": {"example_sentence": "あと（後）で行きます。", "example_reading": "あとでいきます。", "example_meaning_cn": "回头再去。", "example_meaning_en": "I'll go later."},
        "N4_27": {"example_sentence": "あな（穴）が開いています。", "example_reading": "あながあいています。", "example_meaning_cn": "有个洞。", "example_meaning_en": "There is a hole."},
        "N4_28": {"example_sentence": "あに（兄）は三人います。", "example_reading": "あにはさんにんいます。", "example_meaning_cn": "我有三个哥哥。", "example_meaning_en": "I have three older brothers."},
        "N4_29": {"example_sentence": "あね（姉）は結婚しています。", "example_reading": "あねはけっこんしています。", "example_meaning_cn": "姐姐已经结婚了。", "example_meaning_en": "My older sister is married."},
        "N4_30": {"example_sentence": "あのう（あのー）すみません。", "example_reading": "あのーすみません。", "example_meaning_cn": "那个...对不起（打扰一下）。", "example_meaning_en": "Um... excuse me."},
        "N4_31": {"example_sentence": "アパート（あぱーと）に住んでいます。", "example_reading": "アパートにすんでいます。", "example_meaning_cn": "住在公寓里。", "example_meaning_en": "I live in an apartment."},
        "N4_32": {"example_sentence": "あびる（浴びる）シャワーを浴びます。", "example_reading": "あびるシャワーをあびます。", "example_meaning_cn": "冲澡。", "example_meaning_en": "I'll take a shower."},
        "N4_33": {"example_sentence": "あぶない（危ない）から離れてください。", "example_reading": "あぶないからはなれてください。", "example_meaning_cn": "危险，请离开中心（或保持距离）。", "example_meaning_en": "It's dangerous, so please stay away."},
        "N4_34": {"example_sentence": "あまい（甘い）お菓子が好きです。", "example_reading": "あまいおかしがすきです。", "example_meaning_cn": "喜欢甜食。", "example_meaning_en": "I like sweet snacks."},
        "N4_35": {"example_sentence": "あまり（余り）ありません。", "example_reading": "あまりありません。", "example_meaning_cn": "没剩多少。", "example_meaning_en": "There isn't much left."},
        "N4_36": {"example_sentence": "あめ（雨）が止みました。", "example_reading": "あめがやみました。", "example_meaning_cn": "雨停了。", "example_meaning_en": "The rain has stopped."},
        "N4_37": {"example_sentence": "あめ（飴）をなめます。", "example_reading": "あめをなめます。", "example_meaning_cn": "吃糖（舔糖）。", "example_meaning_en": "I'll suck on a candy."},
        "N4_38": {"example_sentence": "アメリカ（あめりか）へ行きたいです。", "example_reading": "アメリカへいきたいです。", "example_meaning_cn": "想去美国。", "example_meaning_en": "I want to go to America."},
        "N4_39": {"example_sentence": "あやまる（謝る）ちゃんと謝ってください。", "example_reading": "あやまるちゃんとあやまってください。", "example_meaning_cn": "请好好道歉。", "example_meaning_en": "Please apologize properly."},
        "N4_40": {"example_sentence": "あら（洗）ってください。", "example_reading": "あらってください。", "example_meaning_cn": "请洗一下。", "example_meaning_en": "Please wash it."},
        "N4_41": {"example_sentence": "ある（有る）お金がありますか。", "example_reading": "あるおかねがありますか。", "example_meaning_cn": "有钱吗？", "example_meaning_en": "Do you have money?"},
        "N4_42": {"example_sentence": "ある（在る）花瓶が机にあります。", "example_reading": "あるかびんがつくえにあります。", "example_meaning_cn": "桌上有个花瓶。", "example_meaning_en": "There is a vase on the desk."},
        "N4_43": {"example_sentence": "ある（歩）いて行きましょう。", "example_reading": "あるいていきましょう。", "example_meaning_cn": "走着去吧。", "example_meaning_en": "Let's go on foot."},
        "N4_44": {"example_sentence": "アンケート（あんけーと）に答えてください。", "example_reading": "アンケートにこたえてください。", "example_meaning_cn": "请填写调查问卷。", "example_meaning_en": "Please answer the questionnaire."},
        "N4_45": {"example_sentence": "あんしん（安心）してください。", "example_reading": "あんしんしてください。", "example_meaning_cn": "请放心。", "example_meaning_en": "Please rest assured."},
        "N4_46": {"example_sentence": "あんぜん（安全）な場所へ逃げましょう。", "example_reading": "あんぜんなばしょへにげましょう。", "example_meaning_cn": "逃到安全的地方吧。", "example_meaning_en": "Let's escape to a safe place."},
        "N4_47": {"example_sentence": "あんな（あんな）ところに行きたくありません。", "example_reading": "あんなところにいきたくありません。", "example_meaning_cn": "不想去那种地方。", "example_meaning_en": "I don't want to go to a place like that."},
        "N4_48": {"example_sentence": "あんない（案内）しますね。", "example_reading": "あんないしますね。", "example_meaning_cn": "我来带路。 ", "example_meaning_en": "I'll guide you."},
        "N4_49": {"example_sentence": "あんまり（あんまり）食べたくありません。", "example_reading": "あんまりたべたくありません。", "example_meaning_cn": "不太想吃。", "example_meaning_en": "I don't really want to eat."},
        "N4_50": {"example_sentence": "い（胃）が痛いです。", "example_reading": "いがいたいです。", "example_meaning_cn": "胃疼。", "example_meaning_en": "My stomach hurts."},
        "N4_51": {"example_sentence": "いい（良い）天気ですね。", "example_reading": "いいてんきですね。", "example_meaning_cn": "好天气呢。", "example_meaning_en": "Nice weather, isn't it?"},
        "N4_52": {"example_sentence": "いいえ（いいえ）違います。", "example_reading": "いいえちがいます。", "example_meaning_cn": "不，不是。", "example_meaning_en": "No, that's not it."},
        "N4_53": {"example_sentence": "いう（云う）何と言いましたか。", "example_reading": "いうなんといいましたか。", "example_meaning_cn": "说了什么？", "example_meaning_en": "What did you say?"},
        "N4_54": {"example_sentence": "いえ（家）に帰ります。", "example_reading": "いえにかえります。", "example_meaning_cn": "回家。", "example_meaning_en": "I'm going home."},
        "N4_55": {"example_sentence": "いか（以下）の通りです。", "example_reading": "いかのとおりです。", "example_meaning_cn": "如下所示。", "example_meaning_en": "It is as follows."},
        "N4_56": {"example_sentence": "いがい（以外）に誰がきますか。", "example_reading": "いがいにだれがきますか。", "example_meaning_cn": "除了(他)还有谁来？", "example_meaning_en": "Who else is coming besides him?"},
        "N4_57": {"example_sentence": "いかが（如何）ですか。", "example_reading": "いかがですか。", "example_meaning_cn": "怎么样？", "example_meaning_en": "How is it?"},
        "N4_58": {"example_sentence": "いがつ（一月）は寒いです。", "example_reading": "いちがつはさむいです。", "example_meaning_cn": "一月很冷。", "example_meaning_en": "January is cold."},
        "N4_59": {"example_sentence": "いき（行）きましよう。", "example_reading": "いきましょう。", "example_meaning_cn": "走吧。", "example_meaning_en": "Let's go."},
        "N4_60": {"example_sentence": "いき（息）が苦しいです。", "example_reading": "いきがくるしいです。", "example_meaning_cn": "呼吸困难。", "example_meaning_en": "It's hard to breathe."},
        "N4_61": {"example_sentence": "いい（幾）つありますか。", "example_reading": "いくつありますか。", "example_meaning_cn": "有几个？", "example_meaning_en": "How many are there?"},
        "N4_62": {"example_sentence": "いくら（幾ら）ですか。", "example_reading": "いくらですか。", "example_meaning_cn": "多少钱？", "example_meaning_en": "How much?"},
        "N4_63": {"example_sentence": "い（生）きています。", "example_reading": "いきています。", "example_meaning_cn": "还活着。", "example_meaning_en": "It's alive."},
        "N4_64": {"example_sentence": "いけん（意見）を言ってください。", "example_reading": "いけんをいってください。", "example_meaning_cn": "请说出你的意见。", "example_meaning_en": "Please state your opinion."},
        "N4_65": {"example_sentence": "い（行）きましよう。", "example_reading": "いきましょう。", "example_meaning_cn": "出发吧。", "example_meaning_en": "Let's depart."},
        "N4_66": {"example_sentence": "いこ（以後）は気をつけます。", "example_reading": "いごはきをつけます。", "example_meaning_cn": "以后会小心的。", "example_meaning_en": "I'll be careful from now on."},
        "N4_67": {"example_sentence": "いぜん（以前）に会ったことがあります。", "example_reading": "いぜんにあったことがあります。", "example_meaning_cn": "以前见过面。", "example_meaning_en": "I've met you before."},
        "N4_68": {"example_sentence": "い（忙）しいですね。", "example_reading": "いそがしいですね。", "example_meaning_cn": "很忙呢。", "example_meaning_en": "You're busy, aren't you?"},
        "N4_69": {"example_sentence": "いそ（急）いでください。", "example_reading": "いそいでください。", "example_meaning_cn": "请快点。", "example_meaning_en": "Please hurry."},
        "N4_70": {"example_sentence": "いた（致）します。", "example_reading": "いたします。", "example_meaning_cn": "我做（谦指）。", "example_meaning_en": "I'll do it (humble)."},
        "N4_71": {"example_sentence": "いた（痛）いですか。", "example_reading": "いたいですか。", "example_meaning_cn": "疼吗？", "example_meaning_en": "Does it hurt?"},
        "N4_72": {"example_sentence": "いた（頂）きます。", "example_reading": "いただきます。", "example_meaning_cn": "我开动了。", "example_meaning_en": "Let's eat (grace)."},
        "N4_73": {"example_sentence": "いち（一）から始めます。", "example_reading": "いちからはじめます。", "example_meaning_cn": "从一开始。", "example_meaning_en": "Start from one."},
        "N4_74": {"example_sentence": "いち（位置）を確認してください。", "example_reading": "いちをかくにんしてください。", "example_meaning_cn": "请确认位置。", "example_meaning_en": "Please confirm the location."},
        "N4_75": {"example_sentence": "いちば（市場）で買い物をします。", "example_reading": "いちばでかいものをします。", "example_meaning_cn": "在市场买东西。", "example_meaning_en": "I shop at the market."},
        "N4_76": {"example_sentence": "いっとう（一等）賞を取りました。", "example_reading": "いっとうしょうをとりました。", "example_meaning_cn": "获得了一等奖。", "example_meaning_en": "I won first prize."},
        "N4_77": {"example_sentence": "い（行）きましょう。", "example_reading": "いきましょう。", "example_meaning_cn": "走吧（一同）。", "example_meaning_en": "Let's go together."},
        "N4_78": {"example_sentence": "いつ（何時）来ますか。", "example_reading": "いつきますか。", "example_meaning_cn": "什么时候来？", "example_meaning_en": "When are you coming?"},
        "N4_79": {"example_sentence": "いつか（五日）に会いましょう。", "example_reading": "いつかにあいましょう。", "example_meaning_cn": "五号见吧。", "example_meaning_en": "Let's meet on the 5th."},
        "N4_80": {"example_sentence": "いっ（一杯）杯飲んでください。", "example_reading": "いっぱいのんでください。", "example_meaning_cn": "请喝一杯。 ", "example_meaning_en": "Please drink a cup."},
        "N4_81": {"example_sentence": "いっ（今更）さら言えません。", "example_reading": "いまさらえません。", "example_meaning_cn": "事到如今没法说了。", "example_meaning_en": "I can't say it now after all this time."},
        "N4_82": {"example_sentence": "いっ（一生）しょうけんめい頑張ります。", "example_reading": "いっしょうけんめいがんばります。", "example_meaning_cn": "拼命加油。", "example_meaning_en": "I'll do my best with all my might."},
        "N4_83": {"example_sentence": "いだい（偉大）な人ですね。", "example_reading": "いだいないとですね。", "example_meaning_cn": "是个伟大的人呢。", "example_meaning_en": "He is a great person, isn't he?"},
        "N4_84": {"example_sentence": "いだ（抱）いています。", "example_reading": "いだいています。", "example_meaning_cn": "抱着（怀抱）。", "example_meaning_en": "I am holding it (in my arms)."},
        "N4_85": {"example_sentence": "いた（至）るところにあります。", "example_reading": "いたるところにあります。", "example_meaning_cn": "到处都有。", "example_meaning_en": "It's everywhere."},
        "N4_86": {"example_sentence": "いち（市）役所へ行きます。", "example_reading": "いちやくしょへいきます。", "example_meaning_cn": "去市政府。", "example_meaning_en": "I'm going to the city hall."},
        "N4_87": {"example_sentence": "いち（一日）中勉強しました。", "example_reading": "いちにちじゅうべんきょうしました。", "example_meaning_cn": "学了一整天。", "example_meaning_en": "I studied all day."},
        "N4_88": {"example_sentence": "いち（一度）に全部は無理です。", "example_reading": "いちどにぜんぶはむりです。", "example_meaning_cn": "一次性全部(做完)是不可能的。", "example_meaning_en": "It's impossible to do it all at once."},
        "N4_89": {"example_sentence": "いつ（何時）でもいいですよ。", "example_reading": "いつまでもいいですよ。", "example_meaning_cn": "什么时候都可以哦。", "example_meaning_en": "Anytime is fine."},
        "N4_90": {"example_sentence": "いっ（一般的）にそうです。", "example_reading": "いっぱんてきにそうです。", "example_meaning_cn": "一般来说确实如此。", "example_meaning_en": "It's generally so."},
        "N4_91": {"example_sentence": "いも（妹）がいます。", "example_reading": "いもうとがいます。", "example_meaning_cn": "有妹妹。", "example_meaning_en": "I have a younger sister."},
        "N4_92": {"example_sentence": "いや（嫌）ですか。 ", "example_reading": "いやですか。", "example_meaning_cn": "讨厌吗？", "example_meaning_en": "Do you dislike it?"},
        "N4_93": {"example_sentence": "いらっしゃい（いらっしゃい）ませ。 ", "example_reading": "いらっしゃいませ。", "example_meaning_cn": "欢迎光临。", "example_meaning_en": "Welcome."},
        "N4_94": {"example_sentence": "い（入）れてください。", "example_reading": "いれてください。", "example_meaning_cn": "请放进去。", "example_meaning_en": "Please put it in."},
        "N4_95": {"example_sentence": "いろ（色）がきれいですね。", "example_reading": "いろがきれいですね。", "example_meaning_cn": "颜色真漂亮呢。", "example_meaning_en": "The color is beautiful, isn't it?"},
        "N4_96": {"example_sentence": "いろ（彩）りを考えましょう。", "example_reading": "いろどりをかんがえましょう。", "example_meaning_cn": "考虑一下配色吧。", "example_meaning_en": "Let's think about the color arrangement."},
        "N4_97": {"example_sentence": "いわ（祝）ってください。", "example_reading": "いわってください。", "example_meaning_cn": "请祝贺我。", "example_meaning_en": "Please celebrate for me."},
        "N4_98": {"example_sentence": "いん（引）退します。", "example_reading": "いんたいします。", "example_meaning_cn": "退休（引退）。", "example_meaning_en": "I am retiring."},
        "N4_99": {"example_sentence": "う（植）えてください。", "example_reading": "うえてください。", "example_meaning_cn": "请种上（植物）。", "example_meaning_en": "Please plant it."},
        "N4_100": {"example_sentence": "う（伺）います。", "example_reading": "うかがいます。", "example_meaning_cn": "我去拜访（或请教）。", "example_meaning_en": "I'll visit (or ask)."},
        "N4_101": {"example_sentence": "う（受）けてください。", "example_reading": "うけてください。", "example_meaning_cn": "请接受（或参加考试）。", "example_meaning_en": "Please accept (or take a test)."},
        "N4_102": {"example_sentence": "うご（動）いてください。", "example_reading": "うごいてください。", "example_meaning_cn": "请动一下。", "example_meaning_en": "Please move."},
        "N4_103": {"example_sentence": "うそ（嘘）をついてはいけません。", "example_reading": "うそをついてはいけません。", "example_meaning_cn": "不可以撒谎。", "example_meaning_en": "You must not lie."},
        "N4_104": {"example_sentence": "うち（家）に帰ります。", "example_reading": "うちにかえります。", "example_meaning_cn": "回家（我家）。", "example_meaning_en": "I'm going to my house."},
        "N4_105": {"example_sentence": "う（打）ってください。", "example_reading": "うってください。", "example_meaning_cn": "请打（击）。", "example_meaning_en": "Please hit it."},
        "N4_106": {"example_sentence": "うつ（写）してください。", "example_reading": "うつしてください。", "example_meaning_cn": "请抄写。", "example_meaning_en": "Please copy it down."},
        "N4_107": {"example_sentence": "うつ（映）っています。", "example_reading": "うつっています。", "example_meaning_cn": "映在（屏幕/水中）。", "example_meaning_en": "It's being reflected/shown."},
        "N4_108": {"example_sentence": "うつ（移）ります。", "example_reading": "うつります。", "example_meaning_cn": "转移（或搬迁）。", "example_meaning_en": "I'll move (to another place)."},
        "N4_109": {"example_sentence": "うで（腕）が痛いです。", "example_reading": "うでがいたいです。", "example_meaning_cn": "胳膊疼。", "example_meaning_en": "My arm hurts."},
        "N4_110": {"example_sentence": "う（売）りましょう。", "example_reading": "うりましょう。", "example_meaning_cn": "卖掉吧。", "example_meaning_en": "Let's sell it."},
        "N4_111": {"example_sentence": "うわ（上）着を着てください。", "example_reading": "うわぎをきてください。", "example_meaning_cn": "请穿上外套。", "example_meaning_en": "Please put on a jacket."},
        "N4_112": {"example_sentence": "うん（運）がいいですね。", "example_reading": "うんがいいですね。", "example_meaning_cn": "运气真好呢。", "example_meaning_en": "You're lucky, aren't you?"},
        "N4_113": {"example_sentence": "うんてん（運転）できますか。", "example_reading": "うんてんできますか。", "example_meaning_cn": "会开车吗？", "example_meaning_en": "Can you drive?"},
        "N4_114": {"example_sentence": "うんどう（運動）しましょう。", "example_reading": "うんどうしましょう。", "example_meaning_cn": "运动吧。", "example_meaning_en": "Let's exercise."},
        "N4_115": {"example_sentence": "え（絵）を描きます。", "example_reading": "えをかきます。", "example_meaning_cn": "画画。", "example_meaning_en": "I'll draw a picture."},
        "N4_116": {"example_sentence": "え（枝）が折れました。", "example_reading": "えだがおれました。", "example_meaning_cn": "树枝折断了。", "example_meaning_en": "The branch broke."},
        "N4_117": {"example_sentence": "え（選）んでください。", "example_reading": "えらんでください。", "example_meaning_cn": "请选择。", "example_meaning_en": "Please choose."},
        "N4_118": {"example_sentence": "えんりょ（遠慮）しないでください。", "example_reading": "えんりょしないでください。", "example_meaning_cn": "请别客气。", "example_meaning_en": "Please don't hesitate."},
        "N4_119": {"example_sentence": "お（御）祝いをしましょう。", "example_reading": "おいわいをしましょう。", "example_meaning_cn": "祝贺一下吧。", "example_meaning_en": "Let's celebrate."},
        "N4_120": {"example_sentence": "お（起）きましたか。", "example_reading": "おきましたか。", "example_meaning_cn": "起床了吗？", "example_meaning_en": "Are you awake?"},
        "N4_121": {"example_sentence": "おく（置）いてください。", "example_reading": "おいてください。", "example_meaning_cn": "请放下。", "example_meaning_en": "Please place it down."},
        "N4_122": {"example_sentence": "おく（奥）さんによろしく。", "example_reading": "おくんさんによろしく。", "example_meaning_cn": "向您夫人问好。", "example_meaning_en": "Regards to your wife."},
        "N4_123": {"example_sentence": "おく（送）ってください。", "example_reading": "おくってください。", "example_meaning_cn": "请寄给我（或送我）。", "example_meaning_en": "Please send it (or give me a ride)."},
        "N4_124": {"example_sentence": "おく（遅）れないでください。", "example_reading": "おくれないでください。", "example_meaning_cn": "请不要迟到。", "example_meaning_en": "Please don't be late."},
        "N4_125": {"example_sentence": "お（起）こしてください。", "example_reading": "おこしてください。", "example_meaning_cn": "请喊醒我。", "example_meaning_en": "Please wake me up."},
        "N4_126": {"example_sentence": "おこな（行）います。", "example_reading": "おこないます。", "example_meaning_cn": "举行（或进行）。", "example_meaning_en": "We will hold (an event)."},
        "N4_127": {"example_sentence": "お（怒）らないでください。", "example_reading": "おこらないでください。", "example_meaning_cn": "请不要生气。", "example_meaning_en": "Please don't be angry."},
        "N4_128": {"example_sentence": "お（教）えてください。", "example_reading": "おしえてください。", "example_meaning_cn": "请告诉我。", "example_meaning_en": "Please teach me."},
        "N4_129": {"example_sentence": "お（押）してください。", "example_reading": "おしてください。", "example_meaning_cn": "请按。", "example_meaning_en": "Please press."},
        "N4_130": {"example_sentence": "お（遅）いですね。", "example_reading": "おそいですね。", "example_meaning_cn": "很慢（或很晚）呢。", "example_meaning_en": "It's late/slow, isn't it?"},
        "N4_131": {"example_sentence": "お（教）わりました。", "example_reading": "おそわりました。", "example_meaning_cn": "跟我学过了（被教过）。", "example_meaning_en": "I was taught."},
        "N4_132": {"example_sentence": "お（落）ちましたよ。", "example_reading": "おちましたよ。", "example_meaning_cn": "掉下去了哦。", "example_meaning_en": "It fell down."},
        "N4_133": {"example_sentence": "お（夫）さんは元気ですか。", "example_reading": "おっとさんはげんきですか。", "example_meaning_cn": "你丈夫身体好吗？", "example_meaning_en": "Is your husband well?"},
        "N4_134": {"example_sentence": "お（音）を小さくしてください。", "example_reading": "おとをちいさくしてください。", "example_meaning_cn": "请把声音调小点。", "example_meaning_en": "Please turn down the sound."},
        "N4_135": {"example_sentence": "お（落）としてしまいました。", "example_reading": "おとしてしまいました。", "example_meaning_cn": "弄掉了。", "example_meaning_en": "I dropped it."},
        "N4_136": {"example_sentence": "おど（踊）りましょう。", "example_reading": "おどりましょう。", "example_meaning_cn": "跳舞吧。", "example_meaning_en": "Let's dance."},
        "N4_137": {"example_sentence": "おどろ（驚）きました。", "example_reading": "おどろきました。", "example_meaning_cn": "大吃一惊。", "example_meaning_en": "I was surprised."},
        "N4_138": {"example_sentence": "お（同）じですね。", "example_reading": "おなじですね。", "example_meaning_cn": "一样呢。", "example_meaning_en": "It's the same, isn't it?"},
        "N4_139": {"example_sentence": "お（兄）さん、こんにちは。", "example_reading": "おにいさん、こんにちは。", "example_meaning_cn": "哥哥，你好。", "example_meaning_en": "Hello, big brother."},
        "N4_140": {"example_sentence": "お（姉）さん、きれいですね。", "example_reading": "おねえさん、きれいですね。", "example_meaning_cn": "姐姐，真漂亮呢。", "example_meaning_en": "Big sister is beautiful, isn't she?"},
        "N4_141": {"example_sentence": "おねがい（お願い）します。", "example_reading": "おねがいします。", "example_meaning_cn": "拜托了。", "example_meaning_en": "Please."},
        "N4_142": {"example_sentence": "お（伯）父さんは優しいです。", "example_reading": "おじさんはやさしいです。", "example_meaning_cn": "伯父很亲切。", "example_meaning_en": "The uncle is kind."},
        "N4_143": {"example_sentence": "お（伯）母さんも元気です。", "example_reading": "おばさんもげんきです。", "example_meaning_cn": "伯母也很有精神。", "example_meaning_en": "The aunt is also well."},
        "N4_144": {"example_sentence": "お、お（起）きましたか。", "example_reading": "お、おきましたか。", "example_meaning_cn": "哦，起床了吗？", "example_meaning_en": "Oh, are you awake?"},
        "N4_145": {"example_sentence": "お（送）りましょう。", "example_reading": "おくりましょう。", "example_meaning_cn": "由我来送吧。", "example_meaning_en": "I'll see you off."},
        "N4_146": {"example_sentence": "おこ（起）しましょうか。", "example_reading": "おこしましょうか。", "example_meaning_cn": "要我叫醒你吗？", "example_meaning_en": "Shall I wake you up?"},
        "N4_147": {"example_sentence": "おこな（行）われました。", "example_reading": "おこなわれました。", "example_meaning_cn": "已经举行了。", "example_meaning_en": "It was held."},
        "N4_148": {"example_sentence": "お（押）しましょう。", "example_reading": "おしましょう。", "example_meaning_cn": "推（按）一下吧。", "example_meaning_en": "Let's press it."},
        "N4_149": {"example_sentence": "お（教）えてもらいました。", "example_reading": "おしえてもらいました。", "example_meaning_cn": "请教过了。", "example_meaning_en": "I had someone teach me."},
        "N4_150": {"example_sentence": "お（落）ちないでください。", "example_reading": "おちないでください。", "example_meaning_cn": "请不要掉下去。", "example_meaning_en": "Please don't fall off."}
    }

    for item in vocab:
        if item['id'] in enrichment:
            item.update(enrichment[item['id']])

    with open(data_file, 'w', encoding='utf-8') as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

    print(f"Updated items up to N4_150.")

if __name__ == "__main__":
    main()
