import json
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    data_file = os.path.join(project_root, 'jlpt-web', 'src', 'data', 'vocab.json')

    if not os.path.exists(data_file):
        return

    with open(data_file, 'r', encoding='utf-8') as f:
        vocab = json.load(f)

    enrichment = {
        "N3_301": {"example_sentence": "か（描）いてください。", "example_reading": "かいてください。", "example_meaning_cn": "请画画。", "example_meaning_en": "Please draw it."},
        "N3_302": {"example_sentence": "か（書）いてください。", "example_reading": "かいてください。", "example_meaning_cn": "请写。", "example_meaning_en": "Please write it."},
        "N3_303": {"example_sentence": "か（嗅）いでください。", "example_reading": "かいでください。", "example_meaning_cn": "请闻一下。", "example_meaning_en": "Please smell it."},
        "N3_304": {"example_sentence": "がか（画家）になりたいです。", "example_reading": "がかになりたいです。", "example_meaning_cn": "想成为画家。", "example_meaning_en": "I want to be a painter."},
        "N3_305": {"example_sentence": "か（抱）かえてください。", "example_reading": "かかえてください。", "example_meaning_cn": "请抱住（或承担）。", "example_meaning_en": "Please hold/carry it."},
        "N3_306": {"example_sentence": "かか（価格）はいくらですか。", "example_reading": "かかくはいくらですか。", "example_meaning_cn": "价格是多少？", "example_meaning_en": "What is the price?"},
        "N3_307": {"example_sentence": "かから（係）員に聞いてください。", "example_reading": "かかりいんにきいてください。", "example_meaning_cn": "请询问工作人员。", "example_meaning_en": "Please ask the staff."},
        "N3_308": {"example_sentence": "かか（欠）かさず勉強します。", "example_reading": "かかさずべんきょうします。", "example_meaning_cn": "每天坚持学习。", "example_meaning_en": "I study without failing a single day."},
        "N3_309": {"example_sentence": "か（掛）けてください。", "example_reading": "かけてください。", "example_meaning_cn": "请挂上（或打电话）。", "example_meaning_en": "Please hang/call."},
        "N3_310": {"example_sentence": "か（欠）けていますね。 ", "example_reading": "かけていますね。", "example_meaning_cn": "缺了一块呢。", "example_meaning_en": "It's chipped/lacking, isn't it?"},
        "N3_311": {"example_sentence": "か（駆）けて行きましょう。", "example_reading": "かけていきましょう。", "example_meaning_cn": "跑着去吧。", "example_meaning_en": "Let's run there."},
        "N3_312": {"example_sentence": "かげ（影）が見えます。", "example_reading": "かげがみえます。", "example_meaning_cn": "看到了影子。", "example_meaning_en": "I can see a shadow."},
        "N3_313": {"example_sentence": "か（可）決（けつ）されました。", "example_reading": "かけつされました。", "example_meaning_cn": "被表决通过（可决）了。", "example_meaning_en": "It was passed/approved."},
        "N3_314": {"example_sentence": "かご（籠）に入れてください。", "example_reading": "かごにいれてください。", "example_meaning_cn": "请放进篮子里。", "example_meaning_en": "Please put it in the basket."},
        "N3_315": {"example_sentence": "かこ（過去）を忘れましょう。", "example_reading": "かこをわすれましょう。", "example_meaning_cn": "忘记过去吧。", "example_meaning_en": "Let's forget the past."},
        "N3_316": {"example_sentence": "か（囲）んでください。", "example_reading": "かこんでください。", "example_meaning_cn": "请围起来。", "example_meaning_en": "Please surround/encircle it."},
        "N3_317": {"example_sentence": "かさ（傘）を貸してください。", "example_reading": "かさをかしてください。", "example_meaning_cn": "请借给我雨伞。", "example_meaning_en": "Please lend me an umbrella."},
        "N3_318": {"example_sentence": "か（重）ねてください。", "example_reading": "かさねてください。", "example_meaning_cn": "请叠加（或重复）。", "example_meaning_en": "Please stack/overlap it."},
        "N3_319": {"example_sentence": "かざ（飾）ってください。", "example_reading": "かざってください。", "example_meaning_cn": "请装饰。", "example_meaning_en": "Please decorate it."},
        "N3_320": {"example_sentence": "かじ（火事）に気をつけてください。", "example_reading": "かじにきをつけてください。", "example_meaning_cn": "请小心火灾。", "example_meaning_en": "Please be careful of fire."},
        "N3_321": {"example_sentence": "かし（貸）してください。", "example_reading": "かしてください。", "example_meaning_cn": "请借（给我）。", "example_meaning_en": "Please lend it to me."},
        "N3_322": {"example_sentence": "かし（可）視（し）化してください。", "example_reading": "かしかしてください。", "example_meaning_cn": "请可视化。", "example_meaning_en": "Please visualize it."},
        "N3_323": {"example_sentence": "か（賢）いですね！", "example_reading": "かしこいですね！", "example_meaning_cn": "真聪明呢！", "example_meaning_en": "You're wise/clever!"},
        "N3_324": {"example_sentence": "かしゅ（歌手）に会いたいです。", "example_reading": "かしゅにあいたいです。", "example_meaning_cn": "想见歌手。", "example_meaning_en": "I want to meet the singer."},
        "N3_325": {"example_sentence": "かす（数）を数えてください。", "example_reading": "かずをかぞえてください。", "example_meaning_cn": "请数一下数量。", "example_meaning_en": "Please count the number."},
        "N3_326": {"example_sentence": "かせ（稼）いでください。", "example_reading": "かせいでください。", "example_meaning_cn": "请挣钱（或赚钱）。", "example_meaning_en": "Please earn money."},
        "N3_327": {"example_sentence": "かせ（風）邪を引きました。", "example_reading": "かぜをひきました。", "example_meaning_cn": "感冒了。", "example_meaning_en": "I caught a cold."},
        "N3_328": {"example_sentence": "かぜ（風）が吹いています。", "example_reading": "かぜがふいています。", "example_meaning_cn": "正在刮风。", "example_meaning_en": "The wind is blowing."},
        "N3_329": {"example_sentence": "かぞ（家族）族は元気ですか。", "example_reading": "かぞくはげんきですか。", "example_meaning_cn": "家里人身体好吗？", "example_meaning_en": "Is your family well?"},
        "N3_330": {"example_sentence": "かた（形）を整えてください。", "example_reading": "かたちをととのえてください。", "example_meaning_cn": "请整理形状。", "example_meaning_en": "Please tidy up the shape."},
        "N3_331": {"example_sentence": "かた（肩）を貸してください。", "example_reading": "かたをかしてください。", "example_meaning_cn": "请借给我肩膀（扶我一下）。", "example_meaning_en": "Please lend me a shoulder."},
        "N3_332": {"example_sentence": "かた（片）道（みち）だけですか。", "example_reading": "かたみちだけですか。", "example_meaning_cn": "只有单程吗？", "example_meaning_en": "Is it only one way?"},
        "N3_333": {"example_sentence": "かた（方）向を教えてください。", "example_reading": "ほうこうをおしえてください。", "example_meaning_cn": "请告诉方向。", "example_meaning_en": "Please tell me the direction."},
        "N3_334": {"example_sentence": "かた（固）いですね。 ", "example_reading": "かたいですね。", "example_meaning_cn": "挺硬的呢。", "example_meaning_en": "It's hard/solid, isn't it?"},
        "N3_335": {"example_sentence": "かた（語）ってください。", "example_reading": "かたってください。", "example_meaning_cn": "请讲述。", "example_meaning_en": "Please tell/relate."},
        "N3_336": {"example_sentence": "かたち（形）がきれいです。", "example_reading": "かたちがきれいです。", "example_meaning_cn": "形状很漂亮。", "example_meaning_en": "The shape is beautiful."},
        "N3_337": {"example_sentence": "かた（片）仮（かな）名で書いてください。", "example_reading": "かたかなでかいてください。", "example_meaning_cn": "请用片假名写。", "example_meaning_en": "Please write it in Katakana."},
        "N3_338": {"example_sentence": "かた（片）付（づ）けてください。", "example_reading": "かたづけてください。", "example_meaning_cn": "请收拾（或清理）。", "example_meaning_en": "Please tidy it up."},
        "N3_339": {"example_sentence": "かたっ（偏）ていますね。", "example_reading": "かたよっていますね。", "example_meaning_cn": "偏颇（或不平衡）了呢。", "example_meaning_en": "It's biased/unbalanced, isn't it?"},
        "N3_340": {"example_sentence": "かち（価値）があります。", "example_reading": "かちがあります。", "example_meaning_cn": "有价值。", "example_meaning_en": "It's valuable."},
        "N3_341": {"example_sentence": "（勝ち）ました！", "example_reading": "かちました！", "example_meaning_cn": "赢了！", "example_meaning_en": "I won!"},
        "N3_342": {"example_sentence": "がっ（活）気（き）がありますね。", "example_reading": "かっきがありますね。", "example_meaning_cn": "很有活力（生气）呢。", "example_meaning_en": "It's lively/full of energy, isn't it?"},
        "N3_343": {"example_sentence": "かっ（括）弧（こ）を付けてください。", "example_reading": "かっこをつけてください。", "example_meaning_cn": "请加上括号（或耍帅）。", "example_meaning_en": "Please add brackets/act cool."},
        "N3_344": {"example_sentence": "（勝手）にしないでください。", "example_reading": "かってにしないでください。", "example_meaning_cn": "请不要自作主张。", "example_meaning_en": "Please don't do as you please."},
        "N3_345": {"example_sentence": "かどう（稼働）させてください。", "example_reading": "かどうさせてください。", "example_meaning_cn": "请让其运转（或稼动）。", "example_meaning_en": "Please make it operate."},
        "N3_346": {"example_sentence": "かな（仮名）で書いてください。", "example_reading": "かなでかいてください。", "example_meaning_cn": "请用假名写。", "example_meaning_en": "Please write in Kana."},
        "N3_347": {"example_sentence": "かな（悲）しいです。", "example_reading": "かなしいです。", "example_meaning_cn": "好悲伤呀。", "example_meaning_en": "I'm sad."},
        "N3_348": {"example_sentence": "かなら（必ず）来てください。", "example_reading": "かならずきてください。", "example_meaning_cn": "请务必来。", "example_meaning_en": "Please be sure to come."},
        "N3_349": {"example_sentence": "かな（可）能（のう）性が高いです。", "example_reading": "かのうせいがたかいです。", "example_meaning_cn": "可能性很高。", "example_meaning_en": "The possibility is high."},
        "N3_350": {"example_sentence": "かのじょ（彼女）はきれいです。", "example_reading": "かのじょはきれいです。", "example_meaning_cn": "她是美丽的。", "example_meaning_en": "She is beautiful."},
        "N3_351": {"example_sentence": "がまん（我慢）してください。", "example_reading": "がまんしてください。", "example_meaning_cn": "请忍耐。", "example_meaning_en": "Please be patient."},
        "N3_352": {"example_sentence": "かみ（上）を見ないでください。", "example_reading": "かみをみないでください。", "example_meaning_cn": "请不要看上面（或上级）。", "example_meaning_en": "Please don't look up/at your superiors."},
        "N3_353": {"example_sentence": "かみ（神）様を信じます。", "example_reading": "かみさまをしんじます。", "example_meaning_cn": "相信神灵。", "example_meaning_en": "I believe in God."},
        "N3_354": {"example_sentence": "かみ（紙）をください。", "example_reading": "かみをください。", "example_meaning_cn": "请给我纸。", "example_meaning_en": "Please give me some paper."},
        "N3_355": {"example_sentence": "かみ（髪）を切りました。", "example_reading": "かみをきりました。", "example_meaning_cn": "剪头发了。", "example_meaning_en": "I cut my hair."},
        "N3_356": {"example_sentence": "（雷）が鳴っています。", "example_reading": "かみなりがなっています。", "example_meaning_cn": "雷在响（打雷）。", "example_meaning_en": "Thunder is rolling."},
        "N3_357": {"example_sentence": "か（噛）んでください。", "example_reading": "かんでください。", "example_meaning_cn": "请咀嚼（或咬）。", "example_meaning_en": "Please chew/bite."},
        "N3_358": {"example_sentence": "かも（科目）目を選んでください。", "example_reading": "かもくをえらんでください。", "example_meaning_cn": "请选择科目。", "example_meaning_en": "Please choose a subject."},
        "N3_359": {"example_sentence": "か（火曜）曜日は休みです。", "example_reading": "かようびはやすみです。", "example_meaning_cn": "周二休息。", "example_meaning_en": "Tuesday is a holiday."},
        "N3_360": {"example_sentence": "かよ（通）ってください。", "example_reading": "かよってください。", "example_meaning_cn": "请通勤（或往返）。", "example_meaning_en": "Please commute/attend."},
        "N3_361": {"example_sentence": "から（空）っぽですね。 ", "example_reading": "からっぽですね。", "example_meaning_cn": "空空的呢。", "example_meaning_en": "It's empty, isn't it?"},
        "N3_362": {"example_sentence": "から（辛）いですね。 ", "example_reading": "からいですね。", "example_meaning_cn": "挺辣的呢（或咸）。", "example_meaning_en": "It's spicy/salty, isn't it?"},
        "N3_363": {"example_sentence": "から（体）を大切にしてください。", "example_reading": "からだをだいじにしてください。", "example_meaning_cn": "请保重身体。", "example_meaning_en": "Please take care of your body."},
        "N3_364": {"example_sentence": "から（空）ですね。 ", "example_reading": "からですね。", "example_meaning_cn": "是空的呢。", "example_meaning_en": "It's empty, isn't it?"},
        "N3_365": {"example_sentence": "（借り）てください。", "example_reading": "かりてください。", "example_meaning_cn": "请借（入）。", "example_meaning_en": "Please borrow it."},
        "N3_366": {"example_sentence": "か（枯）れましたね。", "example_reading": "かれましたね。", "example_meaning_cn": "枯萎了呢。", "example_meaning_en": "It has withered, didn't it?"},
        "N3_367": {"example_sentence": "かれ（彼）は優しいです。", "example_reading": "かれはやさしいです。", "example_meaning_cn": "他很温柔。", "example_meaning_en": "He is kind."},
        "N3_368": {"example_sentence": "かわ（川）で泳ぎます。", "example_reading": "かわでおよぎます。", "example_meaning_cn": "在河里游泳。", "example_meaning_en": "I swim in the river."},
        "N3_369": {"example_sentence": "かわ（皮）を剥いてください。", "example_reading": "かわをむいてください。", "example_meaning_cn": "请削皮。", "example_meaning_en": "Please peel it."},
        "N3_370": {"example_sentence": "かわ（可愛）いですね！", "example_reading": "かわいいですね！", "example_meaning_cn": "真可爱呢！", "example_meaning_en": "How cute!"},
        "N3_371": {"example_sentence": "か（変）わりましたね。", "example_reading": "かわりましたね。", "example_meaning_cn": "变了呢。", "example_meaning_en": "You've changed, haven't you?"},
        "N3_372": {"example_sentence": "かわ（代）わってください。", "example_reading": "かわってください。", "example_meaning_cn": "请替我更换一下（或交换）。", "example_meaning_en": "Please take my place/switch with me."},
        "N3_373": {"example_sentence": "（乾）かしてください。", "example_reading": "かわかしてください。", "example_meaning_cn": "请晾干。", "example_meaning_en": "Please dry it."},
        "N3_374": {"example_sentence": "のか（漢）字を書いてください。", "example_reading": "かんじをかいてください。", "example_meaning_cn": "请写汉字。", "example_meaning_en": "Please write in Kanji."},
        "N3_375": {"example_sentence": "かん（感じ）が良いですね。", "example_reading": "かんじがいいですね。", "example_meaning_cn": "感觉真好呢。", "example_meaning_en": "The feeling/vibe is good, isn't it?"},
        "N3_376": {"example_sentence": "かん（感謝）謝しています。", "example_reading": "かんしゃしています。", "example_meaning_cn": "深表感谢。", "example_meaning_en": "I'm grateful."},
        "N3_377": {"example_sentence": "（患者）さんを診ます。", "example_reading": "かんじゃさんをみます。", "example_meaning_cn": "给患者看病。", "example_meaning_en": "I'll examine the patient."},
        "N3_378": {"example_sentence": "かん（勘）定（じょう）をお願いします。", "example_reading": "かんじょうをおねがいします。", "example_meaning_cn": "请结账。", "example_meaning_en": "Please give me the bill/check."},
        "N3_379": {"example_sentence": "かん（感情）情（じょう）を出さないでください。", "example_reading": "かんじょうをださないでください。", "example_meaning_cn": "请不要流露感情。", "example_meaning_en": "Please don't show your emotions."},
        "N3_380": {"example_sentence": "かん（完成）成しました！", "example_reading": "かんせいしました！", "example_meaning_cn": "完成了！", "example_meaning_en": "Completed!"},
        "N3_381": {"example_sentence": "かん（関）心（しん）がありますか。", "example_reading": "かんしんがありますか。", "example_meaning_cn": "有兴趣（关心）吗？", "example_meaning_en": "Are you interested?"},
        "N3_382": {"example_sentence": "かん（感動）動しました！", "example_reading": "かんどうしました！", "example_meaning_cn": "感动了！", "example_meaning_en": "I was moved!"},
        "N3_383": {"example_sentence": "かん（監督）督に会いました。", "example_reading": "かんとくにあいました。", "example_meaning_cn": "见到了导演（或监督）。", "example_meaning_en": "I met the director/supervisor."},
        "N3_384": {"example_sentence": "かんな（管理）理してください。", "example_reading": "かんりしてください。", "example_meaning_cn": "请管理。", "example_meaning_en": "Please manage it."},
        "N3_385": {"example_sentence": "かん（完了）了です。", "example_reading": "かんりょうです。", "example_meaning_cn": "已完成（完了）。", "example_meaning_en": "It's finished/complete."},
        "N3_386": {"example_sentence": "かん（関連）連がありません。", "example_reading": "かんれんがありません。", "example_meaning_cn": "没有关联。", "example_meaning_en": "There's no connection."},
        "N3_387": {"example_sentence": "き（木）が揺れています。", "example_reading": "きがゆれています。", "example_meaning_cn": "树在摇晃。", "example_meaning_en": "The tree is swaying."},
        "N3_388": {"example_sentence": "きい（黄色）いですね。 ", "example_reading": "きいろいですね。", "example_meaning_cn": "是黄色的呢。", "example_meaning_en": "It's yellow, isn't it?"},
        "N3_389": {"example_sentence": "きおん（気温）が高いです。", "example_reading": "きおんがたかいです。", "example_meaning_cn": "气温很高。", "example_meaning_en": "The temperature is high."},
        "N3_390": {"example_sentence": "き（機会）会（かい）をください。", "example_reading": "きかいをください。", "example_meaning_cn": "请给我机会。", "example_meaning_en": "Please give me a chance."},
        "N3_391": {"example_sentence": "き（機械）械（かい）を直してください。", "example_reading": "きかいをなおしてください。", "example_meaning_cn": "请修理机器。", "example_meaning_en": "Please fix the machine."},
        "N3_392": {"example_sentence": "きき（危機）機ですね。 ", "example_reading": "ききですね。", "example_meaning_cn": "是危机呢。", "example_meaning_en": "It's a crisis, isn't it?"},
        "N3_393": {"example_sentence": "き（聞）いてください。", "example_reading": "きいてください。", "example_meaning_cn": "请听（或问）。", "example_meaning_en": "Please listen/ask."},
        "N3_394": {"example_sentence": "き（効）いていますね。 ", "example_reading": "きいていますね。", "example_meaning_cn": "（药等）起作用了呢。", "example_meaning_en": "It's working, isn't it?"},
        "N3_395": {"example_sentence": "き（機）嫌（げん）が良いですね。", "example_reading": "きげんがいいですね。", "example_meaning_cn": "心情（或情绪）挺好呢。", "example_meaning_en": "You're in a good mood, aren't you?"},
        "N3_396": {"example_sentence": "き（危）険（けん）ですね。 ", "example_reading": "きけんですね。", "example_meaning_cn": "挺危险的呢。", "example_meaning_en": "It's dangerous, isn't it?"},
        "N3_397": {"example_sentence": "き（期限）限（げん）はいつですか。", "example_reading": "きげんはいつですか。", "example_meaning_cn": "期限是什么时候？", "example_meaning_en": "When is the deadline?"},
        "N3_398": {"example_sentence": "き（寄）付（ふ）してください。", "example_reading": "きふしてください。", "example_meaning_cn": "请捐款（或寄付）。", "example_meaning_en": "Please donate."},
        "N3_399": {"example_sentence": "きぼう（希望）があります。", "example_reading": "きぼうがあります。", "example_meaning_cn": "有希望。", "example_meaning_en": "There is hope."},
        "N3_400": {"example_sentence": "き（基本）本を学んでください。", "example_reading": "きほんをまなんあでください。", "example_meaning_cn": "请学习基础。", "example_meaning_en": "Please learn the basics."},
        "N3_401": {"example_sentence": "き（決）まってますね。", "example_reading": "きまっていますね。", "example_meaning_cn": "定下来了呢（或很帅）。", "example_meaning_en": "It's decided/looking sharp, isn't it?"},
        "N3_402": {"example_sentence": "きみ（君）が好きです。", "example_reading": "きみがすきです。", "example_meaning_cn": "喜欢你（君）。", "example_meaning_en": "I like you."},
        "N3_403": {"example_sentence": "き（決）めてください。", "example_reading": "きめてください。", "example_meaning_cn": "请决定。", "example_meaning_en": "Please decide."},
        "N3_404": {"example_sentence": "き（気）持（も）ちが良いです。", "example_reading": "きもちがいいです。", "example_meaning_cn": "感觉很舒服。", "example_meaning_en": "It feels good."},
        "N3_405": {"example_sentence": "き（着）てください。", "example_reading": "きてください。", "example_meaning_cn": "请穿上。", "example_meaning_en": "Please put it on."},
        "N3_406": {"example_sentence": "きゃく（客）様ですか。", "example_reading": "きゃくさまですか。", "example_meaning_cn": "是客人吗？", "example_meaning_en": "Are you a customer?"},
        "N3_407": {"example_sentence": "きゅう（急）に雨が降りました。", "example_reading": "きゅうにあめがふりました。", "example_meaning_cn": "突然下雨了。", "example_meaning_en": "It suddenly rained."},
        "N3_408": {"example_sentence": "きゅう（休暇）暇をとります。", "example_reading": "きゅうかをとります。", "example_meaning_cn": "请假（或休假）。", "example_meaning_en": "I'll take a vacation."},
        "N3_409": {"example_sentence": "きゅう（休憩）憩しましょう。", "example_reading": "きゅうけいしましょう。", "example_meaning_cn": "休息一下（休整）吧。", "example_meaning_en": "Let's take a break."},
        "N3_410": {"example_sentence": "きゅう（急）行（こう）に乗ります。", "example_reading": "きゅうこうにのります。", "example_meaning_cn": "坐快车（急行）。", "example_meaning_en": "I'll take the express train."},
        "N3_411": {"example_sentence": "きゅう（吸収）収が早いです。", "example_reading": "きゅうしゅうがはやいです。", "example_meaning_cn": "吸收很快。", "example_meaning_en": "It absorbs quickly."},
        "N3_412": {"example_sentence": "きゅう（救）助（じょ）してください！", "example_reading": "きゅうじょしてください！", "example_meaning_cn": "请救助（救援）！", "example_meaning_en": "Please rescue us!"},
        "N3_413": {"example_sentence": "きゅう（給）料（りょう）はいくらですか。", "example_reading": "きゅうりょうはいくらですか。", "example_meaning_cn": "工资是多少？", "example_meaning_en": "What is the salary?"},
        "N3_414": {"example_sentence": "きよ（起）用（よう）されました。", "example_reading": "きようされました。", "example_meaning_cn": "被启用了。", "example_meaning_en": "I was appointed."},
        "N3_415": {"example_sentence": "きょう（今日）は休みです。", "example_reading": "きょうはやすみです。", "example_meaning_cn": "今天休息。", "example_meaning_en": "Today is a holiday."},
        "N3_416": {"example_sentence": "きょう（教）育（いく）が大切です。", "example_reading": "きょういくがたいせつです。", "example_meaning_cn": "教育很重要。", "example_meaning_en": "Education is important."},
        "N3_417": {"example_sentence": "きょう（教会）会へ行きます。", "example_reading": "きょうかいへいきます。", "example_meaning_cn": "去教堂。", "example_meaning_en": "I'm going to church."},
        "N3_418": {"example_sentence": "きょう（境界）界を越えます。", "example_reading": "きょうかいをこえます。", "example_meaning_cn": "跨过境界（或边界）。", "example_meaning_en": "Cross the boundary."},
        "N3_419": {"example_sentence": "きょう（行）事（じ）があります。", "example_reading": "ぎょうじがあります。", "example_meaning_cn": "有活动。", "example_meaning_en": "There is an event."},
        "N3_420": {"example_sentence": "きょう（教授）授に相談します。", "example_reading": "きょうじゅにそうだんします。", "example_meaning_cn": "找教授商量。", "example_meaning_en": "I'll consult with the professor."},
        "N3_421": {"example_sentence": "きょう（強調）調してください。", "example_reading": "きょうちょうしてください。", "example_meaning_cn": "请强调。", "example_meaning_en": "Please emphasize it."},
        "N3_422": {"example_sentence": "きょう（今日）の日（ひ）を忘れません。", "example_reading": "きょうのひをわすれません。", "example_meaning_cn": "不会忘记今天的。", "example_meaning_en": "I won't forget today."},
        "N3_423": {"example_sentence": "きょう（興味）味深いですね。 ", "example_reading": "きょうみぶかいですね。", "example_meaning_cn": "饶有兴趣（引人入胜）呢。", "example_meaning_en": "It's very interesting, isn't it?"},
        "N3_424": {"example_sentence": "きょう（協力）力してください。", "example_reading": "きょうりょくしてください。", "example_meaning_cn": "请合作。", "example_meaning_en": "Please cooperate."},
        "N3_425": {"example_sentence": "きょく（曲）を聴いてください。", "example_reading": "きょくをきいてください。", "example_meaning_cn": "请听曲子（歌）。", "example_meaning_en": "Please listen to the song."},
        "N3_426": {"example_sentence": "きょ（許可）可をください。", "example_reading": "きょかをください。", "example_meaning_cn": "请准予许可。", "example_meaning_en": "Please give me permission."},
        "N3_427": {"example_sentence": "きらい（嫌い）ですか。 ", "example_reading": "きらいですか。", "example_meaning_cn": "讨厌吗？", "example_meaning_en": "Do you dislike it?"},
        "N3_428": {"example_sentence": "き（切）ってください。", "example_reading": "きってください。", "example_meaning_cn": "请剪（或切）。", "example_meaning_en": "Please cut it."},
        "N3_429": {"example_sentence": "き（霧）が出ています。", "example_reading": "きりがでています。", "example_meaning_cn": "起雾了。", "example_meaning_en": "It's foggy."},
        "N3_430": {"example_sentence": "き（切）り替えてください。", "example_reading": "きりかえてください。", "example_meaning_cn": "请切换（或转换心情）。", "example_meaning_en": "Please switch/change your mindset."},
        "N3_431": {"example_sentence": "き（奇）麗（れい）ですね！", "example_reading": "きれいですね！", "example_meaning_cn": "真漂亮呢！", "example_meaning_en": "It's beautiful!"},
        "N3_432": {"example_sentence": "きわ（際）どいですね。 ", "example_reading": "きわどいですね。", "example_meaning_cn": "真危险（或悬）呢。", "example_meaning_en": "It was close/dangerous, wasn't it?"},
        "N3_433": {"example_sentence": "きわ（極）めて重要です。", "example_reading": "きわめてじゅうようです。", "example_meaning_cn": "极其重要。", "example_meaning_en": "It's extremely important."},
        "N3_434": {"example_sentence": "きん（銀）メダルを獲りました。", "example_reading": "ぎんめだるを獲りました。", "example_meaning_cn": "获得了银牌。", "example_meaning_en": "I won a silver medal."},
        "N3_435": {"example_sentence": "きん（近）所（じょ）に住んでいます。", "example_reading": "きんじょにすんでいます。", "example_meaning_cn": "住在附近。", "example_meaning_en": "I live in the neighborhood."},
        "N3_436": {"example_sentence": "きん（緊張）張しています。", "example_reading": "きんちょうしています。", "example_meaning_cn": "有点紧张。", "example_meaning_en": "I'm nervous."},
        "N3_437": {"example_sentence": "きん（禁止）止されています。", "example_reading": "きんしされています。", "example_meaning_cn": "被禁止了。", "example_meaning_en": "It's prohibited."},
        "N3_438": {"example_sentence": "きん（勤）務（む）先はどこですか。", "example_reading": "きんむさきはどこですか。", "example_meaning_cn": "工作单位在哪儿？", "example_meaning_en": "Where do you work?"},
        "N3_439": {"example_sentence": "きん（金融）融機関で働いています。", "example_reading": "きんゆうきかんではたらいています。", "example_meaning_cn": "在金融机构工作。", "example_meaning_en": "I work for a financial institution."},
        "N3_440": {"example_sentence": "きん（金曜）曜日は休みです。", "example_reading": "きんようびはやすみです。", "example_meaning_cn": "周五休息。", "example_meaning_en": "Friday is a holiday."},
        "N3_441": {"example_sentence": "く（九）番目です。", "example_reading": "きゅうばんめです。", "example_meaning_cn": "第九个。", "example_meaning_en": "The ninth one."},
        "N3_442": {"example_sentence": "く（句）読（どく）点（てん）を付けてください。", "example_reading": "くどくてんをつけてください。", "example_meaning_cn": "请加标点符号。", "example_meaning_en": "Please add punctuation marks."},
        "N3_443": {"example_sentence": "く（食）ってください！ ", "example_reading": "くってください！", "example_meaning_cn": "吃吧（粗鲁点）！", "example_meaning_en": "Eat it! (rough)"},
        "N3_444": {"example_sentence": "くう（空港）港へ行きます。", "example_reading": "くうこうへいきます。", "example_meaning_cn": "去机场。", "example_meaning_en": "I'm going to the airport."},
        "N3_445": {"example_sentence": "くさ（草）を刈ります。", "example_reading": "くさをかります。", "example_meaning_cn": "割草。", "example_meaning_en": "I'll cut the grass."},
        "N3_446": {"example_sentence": "くすり（薬）を飲んでください。", "example_reading": "くすりをのんでください。", "example_meaning_cn": "请吃药。", "example_meaning_en": "Please take some medicine."},
        "N3_447": {"example_sentence": "く（崩）してください。", "example_reading": "くずしてください。", "example_meaning_cn": "请拆散（或找零钱）。", "example_meaning_en": "Please break/change it."},
        "N3_448": {"example_sentence": "くせ（癖）ですね。 ", "example_reading": "くせですね。", "example_meaning_cn": "是习惯呢（或癖好）。", "example_meaning_en": "It's a habit, isn't it?"},
        "N3_449": {"example_sentence": "くだ（管）を通してください。", "example_reading": "くだをとおしてください。", "example_meaning_cn": "请穿过管子。", "example_meaning_en": "Please pass the pipe/tube."},
        "N3_450": {"example_sentence": "くだ（果物）物を食べましょう。", "example_reading": "くだものをたべましょう。", "example_meaning_cn": "吃水果吧。", "example_meaning_en": "Let's eat some fruit."}
    }

    for item in vocab:
        if item['id'] in enrichment:
            item.update(enrichment[item['id']])

    with open(data_file, 'w', encoding='utf-8') as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

    print(f"Updated items up to N3_450.")

if __name__ == "__main__":
    main()
