import json
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    data_file = os.path.join(project_root, 'jlpt-web', 'src', 'data', 'vocab.json')

    if not os.path.exists(data_file):
        return

    with open(data_file, 'r', encoding='utf-8') as f:
        vocab = json.load(f)

    enrichment = {
        "N2_401": {"example_sentence": "（（活）かつ）よう（よう）し（し）て（て）ください。", "example_reading": "かつようしてください。", "example_meaning_cn": "请活用（或利用）。", "example_meaning_en": "Please utilize/make use of it."},
        "N2_402": {"example_sentence": "（（活）かつ）りょく（りょく）が（が）あり（あり）ますね。", "example_reading": "かつりょくがありますね。", "example_meaning_cn": "真有活力（生命力）呢。", "example_meaning_en": "You have a lot of vitality, don't you?"},
        "N2_403": {"example_sentence": "（（仮）か）てい（てい）し（し）て（て）み（み）ましょう。", "example_reading": "かていしてみましょう。", "example_meaning_cn": "假设（或假定）一下吧。", "example_meaning_en": "Let's assume/hypothesize."},
        "N2_404": {"example_sentence": "（（課）か）てい（てい）を（を）修了（しゅうりょう）し（し）まし（し）た。", "example_reading": "かていをしゅうりょうしました。", "example_meaning_cn": "完成了课程（课外）。", "example_meaning_en": "I've completed the course."},
        "N2_405": {"example_sentence": "（（過）か）てい（てい）を（を）教え（おしえ）て（て）ください。", "example_reading": "かていをおしえてください。", "example_meaning_cn": "请告诉我过程（经过）。", "example_meaning_en": "Please tell me the process."},
        "N2_406": {"example_sentence": "（（家）か）てい（てい）を（を）築き（きずき）ましょう。", "example_reading": "かていをきずきましょう。", "example_meaning_cn": "组建家庭吧。", "example_meaning_en": "Let's build a family."},
        "N2_407": {"example_sentence": "（（角）かど）を（を）曲がっ（まがっ）て（て）ください。", "example_reading": "かどをまがってください。", "example_meaning_cn": "请拐角。", "example_meaning_en": "Please turn the corner."},
        "N2_408": {"example_sentence": "（（叶）かな）え（え）て（て）ください。", "example_reading": "かなえてください。", "example_meaning_cn": "请实现（愿望）。", "example_meaning_en": "Please grant/fulfill it."},
        "N2_409": {"example_sentence": "（（悲）かな）し（し）ま（ま）ないで（で）ください。", "example_reading": "かなしまないでください。", "example_meaning_cn": "请不要悲伤。", "example_meaning_en": "Please don't be sad."},
        "N2_410": {"example_sentence": "（（金）かね）を（を）貯め（ため）て（て）ください。", "example_reading": "かねをためてください。", "example_meaning_cn": "请攒钱。", "example_meaning_en": "Please save money."},
        "N2_411": {"example_sentence": "（（可）か）能（のう）性（せい）は（は）あり（あり）ます。", "example_reading": "かのうせいわあります。", "example_meaning_cn": "是有可能发生的（可能性）。", "example_meaning_en": "There's a possibility."},
        "N2_412": {"example_sentence": "（（株）かぶ）を（を）買っ（かっ）て（て）み（み）ましょう。", "example_reading": "かぶをかってみましょう。", "example_meaning_cn": "买点股票试试吧。", "example_meaning_en": "Let's try buying some stocks."},
        "N2_413": {"example_sentence": "（（被）かぶ）って（て）ください。", "example_reading": "かぶってください。", "example_meaning_cn": "请戴上（或蒙上）。", "example_meaning_en": "Please wear/cover your head with it."},
        "N2_414": {"example_sentence": "（（花）か）び（び）ん（ん）に（に）花（はな）を（を）活け（いけ）ます。", "example_reading": "かびんにはなをいけます。", "example_meaning_cn": "在花瓶里插花。", "example_meaning_en": "I'll arrange flowers in the vase."},
        "N2_415": {"example_sentence": "（（壁）かべ）を（を）塗っ（ぬっ）て（て）ください。", "example_reading": "かべをぬってください。", "example_meaning_cn": "请粉刷墙壁。", "example_meaning_en": "Please paint the wall."},
        "N2_416": {"example_sentence": "（（釜）かま）で（で）炊い（たい）て（て）ください。", "example_reading": "かまでたいてください。", "example_meaning_cn": "请用釜（锅）煮。", "example_meaning_en": "Please cook it in the pot/kettle."},
        "N2_417": {"example_sentence": "（（構）かま）わ（わ）ない（ない）で（で）ください。", "example_reading": "かまわないでください。", "example_meaning_cn": "请不要管我（或不要介意）。", "example_meaning_en": "Please don't mind me/bother yourself."},
        "N2_418": {"example_sentence": "（（神）かみ）を（来（こ））ん（ん）じ（じ）て（て）ください。", "example_reading": "かみをしんじてください。", "example_meaning_cn": "请相信神。", "example_meaning_en": "Please believe in God."},
        "N2_419": {"example_sentence": "（（噛）か）んで（て）ください。", "example_reading": "かんでください。", "example_meaning_cn": "请咬（或咀嚼）。", "example_meaning_en": "Please bite/chew it."},
        "N2_420": {"example_sentence": "（（冠）かん）む（む）り（り）を（を）戴い（いただい）て（て）ください。", "example_reading": "かんむりをいただいてください。", "example_meaning_cn": "请戴上王冠。", "example_meaning_en": "Please wear the crown."},
        "N2_421": {"example_sentence": "（（通）かよ）わ（わ）せ（せ）て（て）ください。", "example_reading": "かよわせてください。", "example_meaning_cn": "请通过（或心意相通）。", "example_meaning_en": "Please let them communicate/pass through."},
         "N2_422": {"example_sentence": "（（通）かよ）っ（っ）て（て）います。", "example_reading": "かよっています。", "example_meaning_cn": "正通勤（或通往）着。", "example_meaning_en": "I'm commuting/it's leading there."},
        "N2_423": {"example_sentence": "（（殻）から）を（を）破っ（やぶっ）て（て）ください。", "example_reading": "からをやぶってください。", "example_meaning_cn": "请破茧成蝶（打破壳）。", "example_meaning_en": "Please break out of your shell."},
        "N2_424": {"example_sentence": "（（柄）がら）が（が）悪い（わるい）ですね。 ", "example_reading": "がらがわるいですね。", "example_meaning_cn": "人品（或花色）真差呢。", "example_meaning_en": "They have bad manners/it's a vulgar pattern."},
        "N2_425": {"example_sentence": "（（借）か）り（り）て（て）ください。", "example_reading": "かりてください。", "example_meaning_cn": "请借走。", "example_meaning_en": "Please borrow it."},
        "N2_426": {"example_sentence": "（（借）か）り（り）を（を）返し（かえし）て（て）ください。", "example_reading": "かりをかえしてください。", "example_meaning_cn": "请还债。", "example_meaning_en": "Please repay the debt."},
        "N2_427": {"example_sentence": "（（刈）か）っ（っ）て（て）ください。", "example_reading": "かってください。", "example_meaning_cn": "请收割（或修剪）。", "example_meaning_en": "Please mow/trim it."},
        "N2_428": {"example_sentence": "（（駆）か）る（る）声（こえ）を（を）出し（だし）て（て）ください。", "example_reading": "かるこえをだしてください。", "example_meaning_cn": "请大声喊叫。", "example_meaning_en": "Please raise a hunting cry/shout."},
        "N2_429": {"example_sentence": "（（軽）かる）い（い）ですね！", "example_reading": "かるいですね！", "example_meaning_cn": "真轻呢！", "example_meaning_en": "How light it is!"},
        "N2_430": {"example_sentence": "（（瓦）かわら）の（の）屋根（やね）です。", "example_reading": "かわらのやねです。", "example_meaning_cn": "瓦房顶。", "example_meaning_en": "It's a tiled roof."},
        "N2_431": {"example_sentence": "（（変）か）わり（り）は（は）ありませんか。", "example_reading": "かわりわありませんか。", "example_meaning_cn": "有什么变化（或别来无恙）吗？", "example_meaning_en": "Is there any change/how have you been?"},
        "N2_432": {"example_sentence": "（（代）か）わり（り）に（に）やっ（やっ）て（て）ください。", "example_reading": "かわりにやってください。", "example_meaning_cn": "请代替（我）做。", "example_meaning_en": "Please do it in my place."},
        "N2_433": {"example_sentence": "（（管）かん）を（を）通し（とおし）て（て）ください。", "example_reading": "かんをとおしてください。", "example_meaning_cn": "请通过管道。", "example_meaning_en": "Please pass it through the pipe."},
        "N2_434": {"example_sentence": "（（勘）かん）が（が）鋭い（ふるい）ですね。", "example_reading": "かんがふるいですね。", "example_meaning_cn": "直觉真灵敏（感）呢。", "example_meaning_en": "Your intuition is sharp, isn't it?"},
        "N2_435": {"example_sentence": "（（感）かん）が（が）あり（あり）ます。", "example_reading": "かんがあります。", "example_meaning_cn": "由于某种感觉。", "example_meaning_en": "There is a sense of it."},
        "N2_436": {"example_sentence": "（（簡）かん）いい（いい）答え（こたえ）です。", "example_reading": "かんいいこたえです。", "example_meaning_cn": "简易的回答。", "example_meaning_en": "A simple answer."},
        "N2_437": {"example_sentence": "（（汗）かん）を（を）流し（ながし）ましょう。", "example_reading": "かんをながしましょう。", "example_meaning_cn": "流点汗吧（或洗澡）。", "example_meaning_en": "Let's sweat/wash it off."},
        "N2_438": {"example_sentence": "かん（（官）かん）に（に）務め（つとめ）て（て）います。", "example_reading": "かんにつとめいています。", "example_meaning_cn": "在官（机关）任职。", "example_meaning_en": "I'm working for the government."},
        "N2_439": {"example_sentence": "かん（（観）かん）てん（てん）を変え（かえ）て（て）ください。", "example_reading": "かんてんをかえてください。", "example_meaning_cn": "请改变观点。", "example_meaning_en": "Please change your perspective."},
        "N2_440": {"example_sentence": "（（看）かん）ご（ご）し（し）になり（なり）たい（たい）です。", "example_reading": "かんごしになりたいです。", "example_meaning_cn": "想成为护士。", "example_meaning_en": "I want to become a nurse."},
        "N2_441": {"example_sentence": "かん（（間）かん）じ（じ）を（を）覚え（おぼえ）て（て）ください。", "example_reading": "かんじをおぼえてください。", "example_meaning_cn": "请记汉字。", "example_meaning_en": "Please memorize the Kanji."},
        "N2_442": {"example_sentence": "（（感）かん）じ（じ）て（て）ください。", "example_reading": "かんじてください。", "example_meaning_cn": "请感受。", "example_meaning_en": "Please feel it."},
        "N2_443": {"example_sentence": "（（感）かん）しゃ（しゃ）し（し）て（て）います。", "example_reading": "かんしゃしています。", "example_meaning_cn": "我心存感激（感谢）。", "example_meaning_en": "I'm grateful."},
        "N2_444": {"example_sentence": "（（感）かん）じょう（じょう）が（が）豊か（ゆたか）ですね。", "example_reading": "かんじょうがゆたかですね。", "example_meaning_cn": "情感真丰富呢。", "example_meaning_en": "You're very emotional/expressive, aren't you?"},
        "N2_445": {"example_sentence": "（（勘）かん）じょう（じょう）を（を）払っ（はらっ）て（て）ください。", "example_reading": "かんじょうをはらってください。", "example_meaning_cn": "请结账（结清勘定）。", "example_meaning_en": "Please pay the bill."},
        "N2_446": {"example_sentence": "（（感）かん）しん（しん）し（し）まし（し）た！ ", "example_reading": "かんしんしました！", "example_meaning_cn": "令人佩服（感叹）！", "example_meaning_en": "I was impressed/admired it."},
        "N2_447": {"example_sentence": "（（関）かん）しん（しん）は（は）あり（あり）ません。", "example_reading": "かんしんわありません。", "example_meaning_cn": "没有兴趣（关心）。", "example_meaning_en": "I have no interest/concern."},
        "N2_448": {"example_sentence": "（（管）かん）せ（せ）い（い）を（を）上げ（あげ）て（て）ください。", "example_reading": "かんせいをあげてください。", "example_meaning_cn": "请发出欢呼声。", "example_meaning_en": "Please raise a cheer."},
        "N2_449": {"example_sentence": "（（感）かん）せ（せ）い（い）を（を）磨い（みがい）て（て）ください。", "example_reading": "かんせいをみがいてください。", "example_meaning_cn": "请磨练感性。", "example_meaning_en": "Please refine your sensitivity/intuition."},
        "N2_450": {"example_sentence": "（（慣）かん）せい（せい）の（の）法則（ほうそく）です。", "example_reading": "かんせいのほうそくです。", "example_meaning_cn": "惯性定律。", "example_meaning_en": "It's the law of inertia."},
        "N2_451": {"example_sentence": "（（完）かん）せ（せ）い（い）し（し）まし（し）た！ ", "example_reading": "かんせいしました！", "example_meaning_cn": "完成了！", "example_meaning_en": "It's complete/finished!"},
        "N2_452": {"example_sentence": "（（間）かん）せ（せ）つ（つ）てき（てき）に（に）伝え（つたえ）て（て）ください。", "example_reading": "かんせつてきにつたえてください。", "example_meaning_cn": "请间接地转告。", "example_meaning_en": "Please tell them indirectly."},
        "N2_453": {"example_sentence": "（（完）かん）ぜ（ぜ）ん（ん）に（に）直り（なおり）まし（し）た。", "example_reading": "かんぜんになおりました。", "example_meaning_cn": "完全治好了。", "example_meaning_en": "It's completely fixed/healed."},
        "N2_454": {"example_sentence": "（（感）かん）ぜ（ぜ）ん（ん）な（な）答え（こたえ）です。", "example_reading": "かんぜんなこたえです。", "example_meaning_cn": "感性的答案。", "example_meaning_en": "A perfect/complete answer."},
        "N2_455": {"example_sentence": "（（乾）かん）そ（そ）う（う）し（し）て（て）います。", "example_reading": "かんそうしています。", "example_meaning_cn": "（气候）正干燥（干燥）着呢。", "example_meaning_en": "It's drying/getting dry."},
        "N2_456": {"example_sentence": "（（感）かん）そう（そう）を（を）聞か（きか）せ（せ）て（て）ください。", "example_reading": "かんそうをきかせてください。", "example_meaning_cn": "请让我听听感想。", "example_meaning_en": "Please let me hear your thoughts/impressions."},
        "N2_457": {"example_sentence": "（（観）かん）そ（そ）く（く）し（し）て（て）ください。", "example_reading": "かんそくしてください。", "example_meaning_cn": "请观测。", "example_meaning_en": "Please observe/forecast."},
        "N2_458": {"example_sentence": "（（簡）かん）た（た）ん（ん）な（な）仕事（しごと）です。", "example_reading": "かんたんなしごとです。", "example_meaning_cn": "是个简单的工作。", "example_meaning_en": "It's a simple task."},
        "N2_459": {"example_sentence": "（（官）かん）ちょう（ちょう）に（に）行き（いき）ます。", "example_reading": "かんちょうにいきます。", "example_meaning_cn": "去官厅（政府机关）。", "example_meaning_en": "I'm going to the government office."},
        "N2_460": {"example_sentence": "（（間）かん）ち（ち）が（が）い（い）し（し）ないで（で）ください。", "example_reading": "かんちがいしないでください。", "example_meaning_cn": "请不要误解（或搞错）。", "example_meaning_en": "Please don't misunderstand it."},
        "N2_461": {"example_sentence": "（（官）かん）て（て）い（い）に（に）行き（いき）ます。", "example_reading": "かんていにいきます。", "example_meaning_cn": "去官邸（首脑官邸）。", "example_meaning_en": "I'm going to the official residence."},
        "N2_462": {"example_sentence": "（（鑑）かん）て（て）い（い）し（し）て（て）ください。", "example_reading": "かんていしてください。", "example_meaning_cn": "请鉴定。", "example_meaning_en": "Please appraise/judge it."},
        "N2_463": {"example_sentence": "（（関）かん）て（て）ん（ん）が（が）あり（あり）ます。", "example_reading": "かんてんがあります。", "example_meaning_cn": "由于某种观点。", "example_meaning_en": "There is a connection/point of view."},
        "N2_464": {"example_sentence": "（（感）かん）ど（ど）が（が）いい（いい）ですね。", "example_reading": "かんどがいいですね。", "example_meaning_cn": "感度（灵敏度）真好呢。", "example_meaning_en": "The sensitivity is good, isn't it?"},
        "N2_465": {"example_sentence": "（（感）かん）ど（ど）う（う）し（し）まし（し）た！ ", "example_reading": "かんどうしました！", "example_meaning_cn": "感动了！", "example_meaning_en": "I was moved/touched!"},
        "N2_466": {"example_sentence": "（（観）かん）ど（ど）う（う）を（を）見（み）て（て）ください。", "example_reading": "かんどうをみてください。", "example_meaning_cn": "请看官道（大道）。", "example_meaning_en": "Please look at the main road."},
        "N2_467": {"example_sentence": "（（監）かん）と（と）く（く）に（に）従っ（したがっ）て（て）ください。", "example_reading": "かんとくにしたがってください。", "example_meaning_cn": "请服从监督（或导演）。", "example_meaning_en": "Please follow the supervisor/director."},
        "N2_468": {"example_sentence": "（（観）かん）ね（ね）ん（ん）を（を）捨て（すて）て（て）ください。", "example_reading": "かんねんをすててください。", "example_meaning_cn": "请抛弃观念（成见）。", "example_meaning_en": "Please discard your notions/preconceptions."},
        "N2_469": {"example_sentence": "（（干）かん）ぱ（ぱ）い（い）し（し）ましょう！ ", "example_reading": "かんぱいしましょう！", "example_meaning_cn": "干杯吧！", "example_meaning_en": "Let's toast/cheers!"},
        "N2_470": {"example_sentence": "（（看）かん）び（び）ょ（ょ）う（う）し（し）て（て）ください。", "example_reading": "かんびょうしてください。", "example_meaning_cn": "请看护（照顾病人）。", "example_meaning_en": "Please nurse/take care of them."},
        "N2_471": {"example_sentence": "（（管）かん）り（り）し（し）て（て）ください。", "example_reading": "かんりしてください。", "example_meaning_cn": "请管理。", "example_meaning_en": "Please manage it."},
         "N2_472": {"example_sentence": "（（完）かん）り（り）ょ（ょ）う（う）し（し）まし（し）た。", "example_reading": "かんりょうしました。", "example_meaning_cn": "完成了。", "example_meaning_en": "It's completed."},
        "N2_473": {"example_sentence": "（（関）かん）れ（れ）ん（ん）し（し）て（て）います。", "example_reading": "かんれんしています。", "example_meaning_cn": "有关联。", "example_meaning_en": "It's related/connected."},
        "N2_474": {"example_sentence": "（（緩）かん）わ（わ）し（し）て（て）ください。", "example_reading": "かんわしてください。", "example_meaning_cn": "请缓和（放松）。", "example_meaning_en": "Please relax/alleviate it."},
        "N2_475": {"example_sentence": "（（木）き）が（が）生え（はえ）て（て）います。", "example_reading": "きがはえています。", "example_meaning_cn": "长着树。", "example_meaning_en": "Trees are growing."},
        "N2_476": {"example_sentence": "き（（期）き）を（を）待っ（まっ）て（て）ください。", "example_reading": "きをまってください。", "example_meaning_cn": "请等待时机（或期限）。", "example_meaning_en": "Please wait for the opportunity/deadline."},
        "N2_477": {"example_sentence": "き（（気）き）を（を）つけ（つけ）て（て）ください。", "example_reading": "きをつけてください。", "example_meaning_cn": "请注意（小心）。", "example_meaning_en": "Please be careful."},
        "N2_478": {"example_sentence": "（（気）き）が（が）つき（つき）まし（し）た。", "example_reading": "きがつきました。", "example_meaning_cn": "意识到了（或发觉了）。", "example_meaning_en": "I noticed/realized it."},
        "N2_479": {"example_sentence": "（（気）き）が（が）進ま（すすま）ない（ない）です。", "example_reading": "きがすすまないです。", "example_meaning_cn": "提不起劲（不乐意）。", "example_meaning_en": "I'm not in the mood for it."},
        "N2_480": {"example_sentence": "（（気）き）が（が）済む（すむ）まで（で）やって（て）ください。", "example_reading": "きがすむまでやってください。", "example_meaning_cn": "请做到满意（心安）为止。", "example_meaning_en": "Please do it until you're satisfied."},
        "N2_481": {"example_sentence": "（（気）き）に（に）し（し）ないで（で）ください。", "example_reading": "きにしないでください。", "example_meaning_cn": "请不要在乎（或介意）。", "example_meaning_en": "Please don't worry about it."},
        "N2_482": {"example_sentence": "（（気）き）に（に）な（な）り（り）ますか。", "example_reading": "きになりますか。", "example_meaning_cn": "你在意吗？", "example_meaning_en": "Are you concerned about it?"},
        "N2_483": {"example_sentence": "（（気）き）に（に）入っ（はいっ）て（て）います。", "example_reading": "きにいっています。", "example_meaning_cn": "我挺喜欢的（中意）。", "example_meaning_en": "I like it/it's to my taste."},
        "N2_484": {"example_sentence": "（（気）き）に（に）障る（さわる）こと（こと）を（を）言い（いい）まし（し）たか。", "example_reading": "きにさわることをいいましたか。", "example_meaning_cn": "我说了让你不高兴的话吗？", "example_meaning_en": "Did I say something that offended you?"},
        "N2_485": {"example_sentence": "（（気）き）の（の）毒（どく）ですね。", "example_reading": "きのどくですね。", "example_meaning_cn": "真够可怜（够受）的呢。", "example_meaning_en": "What a pity/it's too bad for them."},
        "N2_486": {"example_sentence": "（（聞）き）き（き）と（と）れ（れ）ますか。", "example_reading": "ききとれますか。", "example_meaning_cn": "能听懂吗？", "example_meaning_en": "Can you hear/understand it?"},
        "N2_487": {"example_sentence": "（（効）き）き（き）め（め）が（が）あり（あり）ますね。", "example_reading": "ききめがありますね。", "example_meaning_cn": "真见效（药效好）呢。", "example_meaning_en": "It's effective, isn't it?"},
        "N2_488": {"example_sentence": "き（（木）き）く（く）ず（ず）を（を）捨て（すて）て（て）ください。", "example_reading": "きくずをすててください。", "example_meaning_cn": "请扔掉木屑。", "example_meaning_en": "Please throw away the wood chips."},
        "N2_489": {"example_sentence": "きぎ（（木々）きぎ）が（が）美しい（うつくしい）です。", "example_reading": "きぎがうつくしいです。", "example_meaning_cn": "树木郁郁葱葱，很美。", "example_meaning_en": "The trees are beautiful."},
        "N2_490": {"example_sentence": "き（（机）き）かい（かい）を（を）逃さ（のがさ）ないで（で）ください。", "example_reading": "きかいをのがさないでください。", "example_meaning_cn": "请不要错失良机。", "example_meaning_en": "Please don't miss the opportunity."},
        "N2_491": {"example_sentence": "き（（器）き）かい（かい）を（を）操作（そうさ）し（し）て（て）ください。", "example_reading": "きかいをそうさしてください。", "example_meaning_cn": "请操作机器。", "example_meaning_en": "Please operate the machine."},
        "N2_492": {"example_sentence": "き（（規）き）かく（かく）を（を）立て（たて）て（て）ください。", "example_reading": "きかくをたててください。", "example_meaning_cn": "请搞策划。", "example_meaning_en": "Please make a plan/project."},
        "N2_493": {"example_sentence": "き（（着）き）が（が）え（え）を（を）し（し）て（て）ください。", "example_reading": "きがえをしてください。", "example_meaning_cn": "请换衣服。", "example_meaning_en": "Please change your clothes."},
        "N2_494": {"example_sentence": "き（（期）き）かん（かん）内（ない）に（に）出し（だし）て（て）ください。", "example_reading": "きかんないにだしてください。", "example_meaning_cn": "请在期限内交出。", "example_meaning_en": "Please submit it within the period."},
        "N2_495": {"example_sentence": "き（（機）き）かん（かん）が（が）故障（こしょう）し（し）まし（し）た。", "example_reading": "きかんがこしょうしました。", "example_meaning_cn": "器官（或机关）故障了。", "example_meaning_en": "The mechanism/engine failed."},
        "N2_496": {"example_sentence": "き（（季）き）せ（せ）つ（つ）を（を）感じ（かんじ）ましょう。", "example_reading": "きせつをかんじましょう。", "example_meaning_cn": "感受季节吧。", "example_meaning_en": "Let's feel the season."},
        "N2_497": {"example_sentence": "き（（規）き）そ（そ）く（く）を（を）守り（まもり）ましょう。", "example_reading": "きそくをまもりましょう。", "example_meaning_cn": "遵守规则吧。", "example_meaning_en": "Let's follow the rules."},
        "N2_498": {"example_sentence": "き（（基）き）そ（そ）を（を）固め（かため）て（て）ください。", "example_reading": "きそをかためてください。", "example_meaning_cn": "请巩固基础。", "example_meaning_en": "Please solidify the foundation."},
        "N2_499": {"example_sentence": "き（（期）き）たい（たい）し（し）て（て）います！ ", "example_reading": "きたいしています！", "example_meaning_cn": "我非常期待（期待）！", "example_meaning_en": "I'm looking forward to it/expecting it!"},
        "N2_500": {"example_sentence": "き（（気）き）たい（たい）が（が）漏れ（もれ）て（て）います。", "example_reading": "きたいがもれています。", "example_meaning_cn": "气体泄漏了。", "example_meaning_en": "Gas is leaking."},
        "N2_501": {"example_sentence": "き（（北）きた）へ（へ）行き（いき）ます。", "example_reading": "きたへいきます。", "example_meaning_cn": "向北走。", "example_meaning_en": "I'm going north."},
        "N2_502": {"example_sentence": "（（来）き）て（て）ください。", "example_reading": "きてください。", "example_meaning_cn": "请过来。", "example_meaning_en": "Please come."},
        "N2_503": {"example_sentence": "き（（気）き）ど（ど）り（り）すぎ（すぎ）ですよ。", "example_reading": "きどりすぎですよ。", "example_meaning_cn": "你太装腔作势（自负）啦。", "example_meaning_en": "You're acting too posh/pretentious."},
        "N2_504": {"example_sentence": "き（（記）き）に（に）ゅう（ゅう）し（し）て（て）ください。", "example_reading": "きにゅうしてください。", "example_meaning_cn": "请填写。", "example_meaning_en": "Please fill it in."},
        "N2_505": {"example_sentence": "き（（記）き）ね（ね）ん（ん）に（に）撮り（とり）まし（し）た。", "example_reading": "きねんにとりました。", "example_meaning_cn": "作为纪念拍了张照。", "example_meaning_en": "I took it as a memento."},
        "N2_506": {"example_sentence": "き（（気）き）の（の）う（う）し（し）て（て）いますか。", "example_reading": "きのうしていますか。", "example_meaning_cn": "起作用（功能）吗？", "example_meaning_en": "Is it functional?"},
        "N2_507": {"example_sentence": "き（（基）き）ふ（ふ）し（し）て（て）ください。", "example_reading": "きふしてください。", "example_meaning_cn": "请捐赠。", "example_meaning_en": "Please donate."},
        "N2_508": {"example_sentence": "き（（基）き）ぼ（ぼ）を（を）教え（おしえ）て（て）ください。", "example_reading": "きぼをおしえてください。", "example_meaning_cn": "请告诉我规模。", "example_meaning_en": "Please tell me the scale."},
        "N2_509": {"example_sentence": "き（（希）き）ぼ（ぼ）う（う）を（を）持っ（もっ）て（て）ください。", "example_reading": "きぼうをもってください。", "example_meaning_cn": "请抱有希望。", "example_meaning_en": "Please have hope."},
        "N2_510": {"example_sentence": "き（（気）き）ま（ま）ま（ま）に（に）生き（いき）たい（たい）です。", "example_reading": "きままにいきたいです。", "example_meaning_cn": "想随心所欲地生活。", "example_meaning_en": "I want to live as I please."},
        "N2_511": {"example_sentence": "き（（決）き）まり（り）を（を）守り（まもり）ましょう。", "example_reading": "きまりをまもりましょう。", "example_meaning_cn": "遵守规定（决定）吧。", "example_meaning_en": "Let's follow the rules."},
        "N2_512": {"example_sentence": "（（決）き）め（め）て（て）ください。", "example_reading": "きめてください。", "example_meaning_cn": "请决定。", "example_meaning_en": "Please decide."},
        "N2_513": {"example_sentence": "き（（気）き）み（み）ど（ど）り（り）が（が）美しい（うつくしい）です。", "example_reading": "きみどりがうつくしいです。", "example_meaning_cn": "黄绿色很美。", "example_meaning_en": "The yellowish-green is beautiful."},
        "N2_514": {"example_sentence": "き（（気）き）む（む）ず（ず）か（か）しい（しい）人（ひと）ですね。", "example_reading": "きむずかしいひとですね。", "example_meaning_cn": "真是个难伺候（性情古怪）的人呢。", "example_meaning_en": "They are a difficult/cranky person, aren't they?"},
        "N2_515": {"example_sentence": "き（（客）き）も（も）ち（ち）を（を）伝え（つたえ）て（て）ください。", "example_reading": "きもちをつたえてください。", "example_meaning_cn": "请传达心意（感觉）。", "example_meaning_en": "Please convey your feelings."},
        "N2_516": {"example_sentence": "（（着）き）物（もの）を（を）着（き）ます。", "example_reading": "きものをきます。", "example_meaning_cn": "穿和服。", "example_meaning_en": "I wear a kimono."},
        "N2_517": {"example_sentence": "き（（客）き）ゃ（ゃ）く（く）を（を）招き（まねき）ます。", "example_reading": "きゃくをまねきます。", "example_meaning_cn": "招揽（或迎接）客人。", "example_meaning_en": "Inviting guests."},
        "N2_518": {"example_sentence": "き（（脚）きゃ）く（く）ほ（ほ）ん（ん）を（を）読ん（よん）で（て）ください。", "example_reading": "きゃくほんをよんでください。", "example_meaning_cn": "请读剧本。", "example_meaning_en": "Please read the script."},
        "N2_519": {"example_sentence": "き（（休）きゅう）か（か）を（を）楽しん（たのしん）で（て）ください。", "example_reading": "きゅうかをたのしんでください。", "example_meaning_cn": "请享受假期。", "example_meaning_en": "Please enjoy your vacation."},
        "N2_520": {"example_sentence": "きゅう（急）に（に）来（き）ないで（で）ください。", "example_reading": "きゅうにこないでください。", "example_meaning_cn": "请不要突然过来。", "example_meaning_en": "Please don't come suddenly."},
        "N2_521": {"example_sentence": "きゅう（（吸）きゅう）し（し）ゅう（ゅう）し（し）て（て）ください。", "example_reading": "きゅうしゅうしてください。", "example_meaning_cn": "请吸收。", "example_meaning_en": "Please absorb it."},
        "N2_522": {"example_sentence": "きゅう（（休）きゅう）け（け）い（い）し（し）ましょう。", "example_reading": "きゅうけいしましょう。", "example_meaning_cn": "休息一下吧。", "example_meaning_en": "Let's take a break."},
        "N2_523": {"example_sentence": "きゅう（（救）きゅう）し（し）ゅ（ゅ）つ（つ）し（し）て（て）ください！ ", "example_reading": "きゅうしゅつしてください！", "example_meaning_cn": "请营救（拯救）！", "example_meaning_en": "Please rescue me!"},
        "N2_524": {"example_sentence": "きゅう（（吸）きゅう）引（いん）し（し）て（て）ください。", "example_reading": "きゅういんしてください。", "example_meaning_cn": "请吸引（或抽吸）。", "example_meaning_en": "Please suck/inhale it."},
        "N2_525": {"example_sentence": "きゅう（（急）きゅう）げ（げ）き（き）に（に）変わり（かわり）まし（し）た。", "example_reading": "きゅうげきにかわりました。", "example_meaning_cn": "急剧地变化了。", "example_meaning_en": "It changed drastically."},
        "N2_526": {"example_sentence": "きゅう（（救）きゅう）さい（さい）し（し）て（て）ください。", "example_reading": "きゅうさいしてください。", "example_meaning_cn": "请救济。", "example_meaning_en": "Please provide relief/salvation."},
        "N2_527": {"example_sentence": "きゅう（（休）きゅう）止（し）し（し）て（て）います。", "example_reading": "きゅうししています。", "example_meaning_cn": "正在休止（暂停）。", "example_meaning_en": "It is paused/at a standstill."},
        "N2_528": {"example_sentence": "きゅう（（急）きゅう）し（し）ゅ（ゅ）ん（ん）な（な）崖（がけ）です。", "example_reading": "きゅうしゅんながけです。", "example_meaning_cn": "险峻的悬崖。", "example_meaning_en": "It's a steep cliff."},
        "N2_529": {"example_sentence": "きゅう（（休）きゅう）しょ（しょ）く（く）し（し）て（て）います。", "example_reading": "きゅうしょくしています。", "example_meaning_cn": "正在休职（停职）。", "example_meaning_en": "I'm on leave from work."},
        "N2_530": {"example_sentence": "きゅう（（求）きゅう）じ（じ）ん（ん）を（を）募集（ぼしゅう）し（し）て（て）います。", "example_reading": "きゅうじんをぼしゅうしています。", "example_meaning_cn": "正在招工。", "example_meaning_en": "We are recruiting/hiring."},
        "N2_531": {"example_sentence": "きゅう（（旧）きゅう）せ（せ）い（い）を（を）教えて（おしえて）ください。", "example_reading": "きゅうせいをおしえてください。", "example_meaning_cn": "请告诉我旧姓。", "example_meaning_en": "Please tell me your maiden/former name."},
        "N2_532": {"example_sentence": "きゅう（（急）きゅう）そ（そ）く（く）に（に）進ん（すすん）で（て）います。", "example_reading": "きゅうそくにすすんでいます。", "example_meaning_cn": "正在快速（急速）进行着。", "example_meaning_en": "It's progressing rapidly."},
         "N2_533": {"example_sentence": "きゅう（（休）きゅう）そ（そ）く（く）を（を）取っ（とっ）て（て）ください。", "example_reading": "きゅうそくをとってください。", "example_meaning_cn": "请休息一下。", "example_meaning_en": "Please take a rest."},
        "N2_534": {"example_sentence": "きゅう（（給）きゅう）よ（よ）を（を）上げ（あげ）て（て）ください。", "example_reading": "きゅうよをあげてください。", "example_meaning_cn": "请涨工资（给与）。", "example_meaning_en": "Please raise my salary."},
        "N2_535": {"example_sentence": "き（（器）き）よう（よう）ですね！", "example_reading": "きようですね！", "example_meaning_cn": "真手巧（或精明）呢！", "example_meaning_en": "You're very skillful/clever, aren't you?"},
        "N2_536": {"example_sentence": "き（（教）き）ょう（ょう）いく（いく）を（を）受け（うけ）て（て）ください。", "example_reading": "きょういくをうけてください。", "example_meaning_cn": "请接受教育。", "example_meaning_en": "Please receive an education."},
        "N2_537": {"example_sentence": "き（（教）き）ょう（ょう）し（し）になり（なり）たい（たい）です。", "example_reading": "きょうしになりたいです。", "example_meaning_cn": "想成为老师。", "example_meaning_en": "I want to become a teacher."},
        "N2_538": {"example_sentence": "き（（教）き）ょう（ょう）じ（じ）ゅ（ゅ）に（に）なり（なり）たい（たい）です。", "example_reading": "きょうじゅになりたいです。", "example_meaning_cn": "想成为教授。", "example_meaning_en": "I want to become a professor."},
        "N2_539": {"example_sentence": "き（（共）き）ょう（ょう）ふ（ふ）を（を）感じ（かんじ）ます。", "example_reading": "きょうふをかんじます。", "example_meaning_cn": "感到恐惧（恐怖）。", "example_meaning_en": "I feel fear/terror."},
        "N2_540": {"example_sentence": "き（（共）き）ょう（ょう）つ（つ）う（う）の（の）趣味（しゅみ）です。", "example_reading": "きょうつうのしゅみです。", "example_meaning_cn": "共同的嗜好。", "example_meaning_en": "It's a common hobby."},
        "N2_541": {"example_sentence": "き（（強）き）ょう（ょう）せい（せい）し（し）ないで（で）ください。", "example_reading": "きょうせいしないでください。", "example_meaning_cn": "请不要强制。", "example_meaning_en": "Please don't force it."},
        "N2_542": {"example_sentence": "き（（境）き）ょう（ょう）だ（だ）い（い）が（が）あり（あり）ますか。", "example_reading": "きょうだいがありますか。", "example_meaning_cn": "有兄弟姐妹吗？", "example_meaning_en": "Do you have siblings?"},
        "N2_543": {"example_sentence": "き（（強）き）ょう（ょう）だい（だい）な（な）力（ちから）です。", "example_reading": "きょうだいなちからです。", "example_meaning_cn": "强大的力量。", "example_meaning_en": "A powerful force."},
        "N2_544": {"example_sentence": "き（（強）き）ょう（ょう）ち（ち）を（を）開拓（かいたく）し（し）て（て）ください。", "example_reading": "きょうちをかいたくしてください。", "example_meaning_cn": "请开辟新境界。", "example_meaning_en": "Please open up a new realm."},
        "N2_545": {"example_sentence": "き（（協）き）ょう（ょう）て（て）い（い）を（を）結び（むすび）ましょう。", "example_reading": "きょうていをむすびましょう。", "example_meaning_cn": "签个协议（协定）吧。", "example_meaning_en": "Let's make an agreement."},
        "N2_546": {"example_sentence": "き（（郷）き）ょう（ょう）ど（ど）料理（りょうり）を（を）食べ（たべ）ましょう。", "example_reading": "きょうどりょうりをたべましょう。", "example_meaning_cn": "吃点乡土（地方）菜吧。", "example_meaning_en": "Let's eat some local cuisine."},
        "N2_547": {"example_sentence": "き（（強）き）ょう（ょう）れ（れ）つ（つ）な（な）印象（いんしょう）です。", "example_reading": "きょうれつないんしょうです。", "example_meaning_cn": "强烈的印象。", "example_meaning_en": "A strong/intense impression."},
        "N2_548": {"example_sentence": "き（（共）き）ょう（ょう）わ（わ）こ（こ）く（く）です。", "example_reading": "きょうわこくです。", "example_meaning_cn": "是共和国。", "example_meaning_en": "It's a republic."},
        "N2_549": {"example_sentence": "（（局）きょく）に（に）聞い（きい）て（て）ください。", "example_reading": "きょくにきいてください。", "example_meaning_cn": "请问那个局（部门）。", "example_meaning_en": "Please ask that bureau/office."},
        "N2_550": {"example_sentence": "きょく（（曲）きょく）を（を）作っ（つくっ）て（て）ください。", "example_reading": "きょくをつくってください。", "example_meaning_cn": "请作曲。", "example_meaning_en": "Please compose a song."}
    }

    for item in vocab:
        if item['id'] in enrichment:
            item.update(enrichment[item['id']])

    with open(data_file, 'w', encoding='utf-8') as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

    print(f"Updated items up to N2_550.")

if __name__ == "__main__":
    main()
