import json
import os

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    data_file = os.path.join(project_root, 'jlpt-web', 'src', 'data', 'vocab.json')

    if not os.path.exists(data_file):
        return

    with open(data_file, 'r', encoding='utf-8') as f:
        vocab = json.load(f)

    enrichment = {
        "N3_0": {"example_sentence": "あい（愛）されていますね。", "example_reading": "あいされていますね。", "example_meaning_cn": "被爱着呢。", "example_meaning_en": "You are loved, aren't you?"},
        "N3_1": {"example_sentence": "あいさつ（挨拶）をしましょう。", "example_reading": "あいさつをしましょう。", "example_meaning_cn": "打个招呼吧。", "example_meaning_en": "Let's give a greeting."},
        "N3_2": {"example_sentence": "あいだ（間）に挟まってしまいました。", "example_reading": "あいだにはさまってしまいました。", "example_meaning_cn": "夹在中间了。", "example_meaning_en": "I got caught in between."},
        "N3_3": {"example_sentence": "あいて（相手）の気持ちを考えてください。", "example_reading": "あいてのきもちをかんがえてください。", "example_meaning_cn": "请考虑对方的心情。", "example_meaning_en": "Please consider the other person's feelings."},
        "N3_4": {"example_sentence": "アイデア（あいであ）が浮かびました。", "example_reading": "アイデアがうかびました。", "example_meaning_cn": "浮现出了主意（Idea）。", "example_meaning_en": "An idea came to mind."},
        "N3_5": {"example_sentence": "あ（空）き室はありますか。", "example_reading": "あきしつはありますか。", "example_meaning_cn": "有空房吗？", "example_meaning_en": "Are there any vacant rooms?"},
        "N3_6": {"example_sentence": "あき（明）らかに違います。", "example_reading": "あきらかにちがいます。", "example_meaning_cn": "显然不同。", "example_meaning_en": "It's clearly different."},
        "N3_7": {"example_sentence": "あきら（諦）めないでください！", "example_reading": "あきらめないでください！", "example_meaning_cn": "请不要放弃！", "example_meaning_en": "Please don't give up!"},
        "N3_8": {"example_sentence": "あ（飽）きてしまいましたか。", "example_reading": "あきてしまいましたか。", "example_meaning_cn": "厌倦（腻）了吗？", "example_meaning_en": "Have you gotten tired of it?"},
        "N3_9": {"example_sentence": "あく（握）手しましょう。", "example_reading": "あくしゅしましょう。", "example_meaning_cn": "握手吧。", "example_meaning_en": "Let's shake hands."},
        "N3_10": {"example_sentence": "アクセント（あくせんと）が難しいです。", "example_reading": "アクセントがむずかしいです。", "example_meaning_cn": "重音很难。", "example_meaning_en": "The accent is difficult."},
        "N3_11": {"example_sentence": "あくび（欠伸）が出ます。", "example_reading": "あくびがでます。", "example_meaning_cn": "打哈欠。", "example_meaning_en": "I'm yawning."},
        "N3_12": {"example_sentence": "あ（明）けるまで語り合いましょう。", "example_reading": "あけるまでかたりあいましょう。", "example_meaning_cn": "畅谈到天亮吧。", "example_meaning_en": "Let's talk until dawn."},
        "N3_13": {"example_sentence": "あ（挙）げてください。", "example_reading": "あげてください。", "example_meaning_cn": "请举起来（或列举）。", "example_meaning_en": "Please raise/list it."},
        "N3_14": {"example_sentence": "あこが（憧）れています。", "example_reading": "あこがれています。", "example_meaning_cn": "憧憬（向往）着。", "example_meaning_en": "I long for/admire it."},
        "N3_15": {"example_sentence": "あさ（浅）いですね。", "example_reading": "あさいですね。", "example_meaning_cn": "挺浅的呢。", "example_meaning_en": "It's shallow, isn't it?"},
        "N3_16": {"example_sentence": "あざ（痣）ができました。", "example_reading": "あざができました。", "example_meaning_cn": "长了淤青（或痣）。", "example_meaning_en": "I got a bruise/mark."},
        "N3_17": {"example_sentence": "あした（明日）は晴れますか。", "example_reading": "あしたははれますか。", "example_meaning_cn": "明天天晴吗？", "example_meaning_en": "Will it be sunny tomorrow?"},
        "N3_18": {"example_sentence": "あし（足）首が痛いです。", "example_reading": "あしくびがいたいです。", "example_meaning_cn": "脚踝疼。", "example_meaning_en": "My ankle hurts."},
        "N3_19": {"example_sentence": "あじ（味）わってください。", "example_reading": "あじわってください。", "example_meaning_cn": "请品味（鉴赏）。", "example_meaning_en": "Please taste/savor it."},
        "N3_20": {"example_sentence": "あず（預）かってください。", "example_reading": "あずかってください。", "example_meaning_cn": "请代为保管。", "example_meaning_en": "Please keep this for me."},
        "N3_21": {"example_sentence": "あず（預）けてください。", "example_reading": "あずけてください。", "example_meaning_cn": "请寄存。", "example_meaning_en": "Please deposit/leave it."},
        "N3_22": {"example_sentence": "あせ（汗）をかきました。", "example_reading": "あせをかきました。", "example_meaning_cn": "出汗了。", "example_meaning_en": "I sweated."},
        "N3_23": {"example_sentence": "あそ（遊）びに来てください。", "example_reading": "あそびにきてください。", "example_meaning_cn": "请来玩。", "example_meaning_en": "Please come over to play."},
        "N3_24": {"example_sentence": "あたた（暖）かくなってきました。", "example_reading": "あたたかくなってきました。", "example_meaning_cn": "变暖和了。", "example_meaning_en": "It's getting warmer."},
        "N3_25": {"example_sentence": "あたま（頭）がいいですね。", "example_reading": "あたまがいいですね。", "example_meaning_cn": "头脑真聪明呢。", "example_meaning_en": "You're smart, aren't you?"},
        "N3_26": {"example_sentence": "あた（新）しい服を買いました。", "example_reading": "あたらしいふくをかいました。", "example_meaning_cn": "买了新衣服。", "example_meaning_en": "I bought new clothes."},
        "N3_27": {"example_sentence": "あた（当）りました！", "example_reading": "あたりました！", "example_meaning_cn": "中（奖）了！", "example_meaning_en": "I hit the mark/won!"},
        "N3_28": {"example_sentence": "あちこち（彼方此方）探しました。", "example_reading": "あちこちさがしました。", "example_meaning_cn": "到处都找了。", "example_meaning_en": "I searched all over."},
        "N3_29": {"example_sentence": "あちら（あちら）に行ってください。", "example_reading": "あちらにいってください。", "example_meaning_cn": "请去那边。", "example_meaning_en": "Please go over there."},
        "N3_30": {"example_sentence": "あ（厚）い本ですね。", "example_reading": "あついほんですね。", "example_meaning_cn": "很厚的书呢。", "example_meaning_en": "It's a thick book, isn't it?"},
        "N3_31": {"example_sentence": "あつ（集）まってください。", "example_reading": "あつまってください。", "example_meaning_cn": "请集合。", "example_meaning_en": "Please gather round."},
        "N3_32": {"example_sentence": "あ（当）てはめてください。", "example_reading": "あてはめてください。", "example_meaning_cn": "请套用（或应用）。", "example_meaning_en": "Please apply/fit it in."},
        "N3_33": {"example_sentence": "あと（後）で連絡します。", "example_reading": "あとでれんらくします。", "example_meaning_cn": "稍后联系。", "example_meaning_en": "I'll contact you later."},
        "N3_34": {"example_sentence": "アドバイス（あどばいす）をください。", "example_reading": "アドバイスをください。", "example_meaning_cn": "请给我些建议。", "example_meaning_en": "Please give me some advice."},
        "N3_35": {"example_sentence": "あな（穴）が開いています。", "example_reading": "あながあいています。", "example_meaning_cn": "有个洞。", "example_meaning_en": "There's a hole."},
        "N3_36": {"example_sentence": "あな（貴女）たの番です。", "example_reading": "あなたのばんです。", "example_meaning_cn": "轮到你了。", "example_meaning_en": "It's your turn."},
        "N3_37": {"example_sentence": "あぶ（油）っこいですね。", "example_reading": "あぶらっこいですね。", "example_meaning_cn": "挺油腻的呢。", "example_meaning_en": "It's oily/greasy, isn't it?"},
        "N3_38": {"example_sentence": "あぶ（危）ないですよ。", "example_reading": "あぶないですよ。", "example_meaning_cn": "很危险的哦。", "example_meaning_en": "It's dangerous, you know."},
        "N3_39": {"example_sentence": "あま（甘）いものが食べたいです。", "example_reading": "あまいものがたべたいです。", "example_meaning_cn": "想吃甜食。", "example_meaning_en": "I want to eat something sweet."},
        "N3_40": {"example_sentence": "あま（余）ってしまいました。", "example_reading": "あまってしまいました。", "example_meaning_cn": "剩下了。", "example_meaning_en": "It's left over."},
        "N3_41": {"example_sentence": "あ（編）んでください。", "example_reading": "あんでください。", "example_meaning_cn": "请编织。", "example_meaning_en": "Please knit/weave it."},
        "N3_42": {"example_sentence": "あ（雨）が降ってきました。", "example_reading": "あめがふってきました。", "example_meaning_cn": "下雨了。", "example_meaning_en": "It's started to rain."},
        "N3_43": {"example_sentence": "あや（誤）まってください。", "example_reading": "あやまってください。", "example_meaning_cn": "请道歉。", "example_meaning_en": "Please apologize."},
        "N3_44": {"example_sentence": "あや（怪）しいですね。 ", "example_reading": "あやしいですね。", "example_meaning_cn": "很可疑（奇怪）呢。", "example_meaning_en": "It's suspicious, isn't it?"},
        "N3_45": {"example_sentence": "あら（荒）い波ですね。", "example_reading": "あらいなみですね。", "example_meaning_cn": "汹涌的波浪呢。", "example_meaning_en": "The waves are rough, aren't they?"},
        "N3_46": {"example_sentence": "あらた（新）めて連絡します。", "example_reading": "あらためてれんらくします。", "example_meaning_cn": "再次（重新）联系。", "example_meaning_en": "I'll contact you again later."},
        "N3_47": {"example_sentence": "あら（洗）ってください。", "example_reading": "あらってください。", "example_meaning_cn": "请洗一下。", "example_meaning_en": "Please wash it."},
        "N3_48": {"example_sentence": "あら（荒）しましたね。", "example_reading": "あらしましたね。", "example_meaning_cn": "弄乱（或荒废）了呢。", "example_meaning_en": "You made a mess, didn't you?"},
        "N3_49": {"example_sentence": "あら（現）れました！", "example_reading": "あらわれました！", "example_meaning_cn": "出现了！", "example_meaning_en": "It appeared!"},
        "N3_50": {"example_sentence": "あら（表）してください。", "example_reading": "あらわしてください。", "example_meaning_cn": "请表示（或表现）出来。", "example_meaning_en": "Please express it."},
        "N3_51": {"example_sentence": "あら（有）る限りの力を出します。", "example_reading": "あるかぎりのちからをだします。", "example_meaning_cn": "使出所有的力气。", "example_meaning_en": "I'll give it all the strength I have."},
        "N3_52": {"example_sentence": "あるい（或）はこういう事ですか。", "example_reading": "あるいはこちらのことですか。", "example_meaning_cn": "或者说是这件事吗？", "example_meaning_en": "Or is it this?"},
        "N3_53": {"example_sentence": "歩（ある）いて行きましょう。", "example_reading": "あるいていきましょう。", "example_meaning_cn": "走着去吧。", "example_meaning_en": "Let's walk there."},
        "N3_54": {"example_sentence": "アルバム（あるばむ）を見ました。", "example_reading": "アルバムをみました。", "example_meaning_cn": "看了相册。", "example_meaning_en": "I looked at the album."},
        "N3_55": {"example_sentence": "アレルギー（あれるぎー）はありますか。", "example_reading": "アレルギーはありますか。", "example_meaning_cn": "有过敏吗？", "example_meaning_en": "Do you have any allergies?"},
        "N3_56": {"example_sentence": "あわ（泡）が出ています。", "example_reading": "あわがでています。", "example_meaning_cn": "出泡泡了。", "example_meaning_en": "Bubbles are forming."},
        "N3_57": {"example_sentence": "あわ（合）せてください。", "example_reading": "あわせてください。", "example_meaning_cn": "请配合（或合计）。", "example_meaning_en": "Please match/combine it."},
        "N3_58": {"example_sentence": "あわ（慌）てないでください。", "example_reading": "あわてないでください。", "example_meaning_cn": "请不要慌张。", "example_meaning_en": "Please don't panic."},
        "N3_59": {"example_sentence": "あわ（哀）れですね。", "example_reading": "あわれですね。", "example_meaning_cn": "真可怜呢。", "example_meaning_en": "It's pitiful, isn't it?"},
        "N3_60": {"example_sentence": "あん（案）外難しいです。", "example_reading": "あんがいむずかしいです。", "example_meaning_cn": "意外地很难。", "example_meaning_en": "It's unexpectedly difficult."},
        "N3_61": {"example_sentence": "あん（暗）記してください。", "example_reading": "あんきしてください。", "example_meaning_cn": "请背诵（暗记）。", "example_meaning_en": "Please memorize it."},
        "N3_62": {"example_sentence": "アンケート（あんけーと）に答えてください。", "example_reading": "アンケートにこたえてください。", "example_meaning_cn": "请回答问卷调查。", "example_meaning_en": "Please answer the questionnaire."},
        "N3_63": {"example_sentence": "あん（安）心してください。", "example_reading": "あんしんしてください。", "example_meaning_cn": "请放心。", "example_meaning_en": "Please rest assured."},
        "N3_64": {"example_sentence": "あん（安）全ですね。 ", "example_reading": "あんぜんですね。", "example_meaning_cn": "很安全呢。", "example_meaning_en": "It's safe, isn't it?"},
        "N3_65": {"example_sentence": "あん（案）内してください。", "example_reading": "あんないしてください。", "example_meaning_cn": "请指引（向导）。", "example_meaning_en": "Please guide me."},
        "N3_66": {"example_sentence": "あんな（あんな）風になりたいです。", "example_reading": "あんなふうになりたいです。", "example_meaning_cn": "想变成那种样子。", "example_meaning_en": "I want to be like that."},
        "N3_67": {"example_sentence": "い（胃）が痛いです。", "example_reading": "いがいたいです。", "example_meaning_cn": "胃疼。", "example_meaning_en": "My stomach hurts."},
        "N3_68": {"example_sentence": "いい（良い）天気ですね。", "example_reading": "いいてんきですね。", "example_meaning_cn": "天气真好呢。", "example_meaning_en": "The weather is good, isn't it?"},
        "N3_69": {"example_sentence": "いいえ（いいえ）。 ", "example_reading": "いいえ。", "example_meaning_cn": "不是（不）。 ", "example_meaning_en": "No."},
        "N3_70": {"example_sentence": "い（言）ってください。", "example_reading": "いってください。", "example_meaning_cn": "请说。", "example_meaning_en": "Please say it."},
        "N3_71": {"example_sentence": "い（行）ってください。", "example_reading": "いってください。", "example_meaning_cn": "请去。", "example_meaning_en": "Please go."},
        "N3_72": {"example_sentence": "い（居）てください。", "example_reading": "いてください。", "example_meaning_cn": "请留下（或在）。", "example_meaning_en": "Please stay/be here."},
        "N3_73": {"example_sentence": "い（意）外ですね。 ", "example_reading": "がいですね。", "example_meaning_cn": "挺意外的呢。", "example_meaning_en": "It's unexpected, isn't it?"},
        "N3_74": {"example_sentence": "い（生）かされています。", "example_reading": "いかされています。", "example_meaning_cn": "被赋予了生命（或被重用）。", "example_meaning_en": "I am being utilized/given life."},
        "N3_75": {"example_sentence": "いかが（いかが）ですか。", "example_reading": "いかがですか。", "example_meaning_cn": "怎么样？", "example_meaning_en": "How is it?"},
        "N3_76": {"example_sentence": "いか（医学）学を志しています。", "example_reading": "いがくをこころざしています。", "example_meaning_cn": "志在医学。", "example_meaning_en": "I aspire to study medicine."},
        "N3_77": {"example_sentence": "い（生）きています。", "example_reading": "いきています。", "example_meaning_cn": "活着。", "example_meaning_en": "I'm alive."},
        "N3_78": {"example_sentence": "いく（育）児（じ）が大変です。", "example_reading": "いくじがたいへんです。", "example_meaning_cn": "育儿很辛苦。", "example_meaning_en": "Child-rearing is hard."},
        "N3_79": {"example_sentence": "いく（幾）つありますか。", "example_reading": "いくつありますか。", "example_meaning_cn": "有几个？", "example_meaning_en": "How many are there?"},
        "N3_80": {"example_sentence": "いくら（いくら）ですか。", "example_reading": "いくらですか。", "example_meaning_cn": "多少钱？", "example_meaning_en": "How much is it?"},
        "N3_81": {"example_sentence": "い（池）に魚がいます。", "example_reading": "いけにさかながいます。", "example_meaning_cn": "池子里有鱼。", "example_meaning_en": "There are fish in the pond."},
        "N3_82": {"example_sentence": "い（意見）見を聞かせてください。", "example_reading": "いけんをきかせてください。", "example_meaning_cn": "请让我听听你的意见。", "example_meaning_en": "Please let me hear your opinion."},
        "N3_83": {"example_sentence": "い（意）志（し）が強いです。", "example_reading": "いしがつよいです。", "example_meaning_cn": "意志很强。", "example_meaning_en": "The will is strong."},
        "N3_84": {"example_sentence": "い（遺）志（し）を継ぎます。", "example_reading": "いしをつぎます。", "example_meaning_cn": "继承遗志。", "example_meaning_en": "I'll carry on the legacy."},
        "N3_85": {"example_sentence": "い（石）橋を叩いて渡ります。", "example_reading": "いしばしをたたいてわたります。", "example_meaning_cn": "小心翼翼（过石桥也要敲一敲）。", "example_meaning_en": "Cross the stone bridge only after tapping it (be very cautious)."},
        "N3_86": {"example_sentence": "い（維）持（じ）してください。", "example_reading": "いじしてください。", "example_meaning_cn": "请维持。", "example_meaning_en": "Please maintain it."},
        "N3_87": {"example_sentence": "い（意）識（しき）がありません。", "example_reading": "いしきがありません。", "example_meaning_cn": "没有意识（昏迷）。", "example_meaning_en": "Unconscious."},
        "N3_88": {"example_sentence": "い（辞）書（しょ）で調べてください。", "example_reading": "じしょでしらべてください。", "example_meaning_cn": "请用字典查一下。", "example_meaning_en": "Please check it in the dictionary."},
        "N3_89": {"example_sentence": "い（意）地（じ）悪ですね。", "example_reading": "いじわるですね。", "example_meaning_cn": "真坏（使坏）呢。", "example_meaning_en": "How mean of you."},
        "N3_90": {"example_sentence": "い（椅）子（す）に座ってください。", "example_reading": "いすにすわってください。", "example_meaning_cn": "请坐在椅子上。", "example_meaning_en": "Please sit on the chair."},
        "N3_91": {"example_sentence": "いず（何）れわかるでしょう。", "example_reading": "いずれわかるでしょう。", "example_meaning_cn": "迟早会明白的吧。", "example_meaning_en": "You'll understand sooner or later."},
        "N3_92": {"example_sentence": "いぜん（以前）会ったことがあります。", "example_reading": "いぜんあったことがあります。", "example_meaning_cn": "以前见过面。", "example_meaning_en": "I've met you before."},
        "N3_93": {"example_sentence": "いた（板）を置いてください。", "example_reading": "いたをおいてください。", "example_meaning_cn": "请放上板子。", "example_meaning_en": "Please put down the board."},
        "N3_94": {"example_sentence": "いた（偉）大（だい）な人物です。", "example_reading": "いだいなじんぶつです。", "example_meaning_cn": "是个伟大的人物。", "example_meaning_en": "He/She is a great person."},
        "N3_95": {"example_sentence": "いた（抱）抱き（だき）ました！", "example_reading": "いただきました！", "example_meaning_cn": "开动了（或收到了）！", "example_meaning_en": "Thank you for the meal (or I received it)!"},
        "N3_96": {"example_sentence": "いた（痛）いですか。", "example_reading": "いたいですか。", "example_meaning_cn": "疼吗？", "example_meaning_en": "Does it hurt?"},
        "N3_97": {"example_sentence": "いた（致）します。", "example_reading": "いたします。", "example_meaning_cn": "（我）做（做某事的谦称）。", "example_meaning_en": "I will do (humble)."},
        "N3_98": {"example_sentence": "いた（頂）頂戴（だき）します。", "example_reading": "ちょうだいします。", "example_meaning_cn": "请给我（或收下了）。", "example_meaning_en": "I'll take it/Please give me."},
        "N3_99": {"example_sentence": "いち（一）番（ばん）です！", "example_reading": "いちばんです！", "example_meaning_cn": "第一名（或最好）！", "example_meaning_en": "It's number one!"},
        "N3_100": {"example_sentence": "いち（一）時（じ）停止してください。", "example_reading": "いちじていししてください。", "example_meaning_cn": "请暂时停止（或临时停靠）。", "example_meaning_en": "Please stop temporarily."},
        "N3_101": {"example_sentence": "いち（市場）場へ行きます。", "example_reading": "いちばへいきます。", "example_meaning_cn": "去市场。", "example_meaning_en": "I'm going to the market."},
        "N3_102": {"example_sentence": "いちいち（一々）うるさいですね。", "example_reading": "いちいちうるさいですね。", "example_meaning_cn": "一个一个吵死了（真啰嗦）。", "example_meaning_en": "You're annoying about every little thing."},
        "N3_103": {"example_sentence": "いつ（いつ）来ますか。", "example_reading": "いつきますか。", "example_meaning_cn": "什么时候来？", "example_meaning_en": "When are you coming?"},
        "N3_104": {"example_sentence": "いつか（五日）に会いましょう。", "example_reading": "いつかにあいましょう。", "example_meaning_cn": "五号见吧。", "example_meaning_en": "Let's meet on the 5th."},
        "N3_105": {"example_sentence": "いっしょ（一緒）に行きましょう。", "example_reading": "いっしょにいきましょう。", "example_meaning_cn": "一起去吧。", "example_meaning_en": "Let's go together."},
        "N3_106": {"example_sentence": "いっせい（一斉）に始めましょう。", "example_reading": "いっせいにはじめましょう。", "example_meaning_cn": "一起（齐声）开始吧。", "example_meaning_en": "Let's start all at once."},
        "N3_107": {"example_sentence": "いっそ（いっそ）死（し）にたいです。", "example_reading": "いっそしにたいです。", "example_meaning_cn": "干脆想死（这种极端表达通常表无奈）。", "example_meaning_en": "I'd rather just die (dramatic expression)."},
        "N3_108": {"example_sentence": "いっそう（一層）努力します。", "example_reading": "いっそうどりょくします。", "example_meaning_cn": "更加努力。", "example_meaning_en": "I'll work even harder."},
        "N3_109": {"example_sentence": "いったい（一体）どういう事ですか。", "example_reading": "いったいどういうことですか。", "example_meaning_cn": "到底是怎么回事？", "example_meaning_en": "What on earth is going on?"},
        "N3_110": {"example_sentence": "いっ（一）旦（たん）休みましょう。", "example_reading": "いったんやすみましょう。", "example_meaning_cn": "先（一旦）休息一下吧。", "example_meaning_en": "Let's take a break for now."},
        "N3_111": {"example_sentence": "いっち（一致）しましたね。", "example_reading": "いっちしましたね。", "example_meaning_cn": "一致了呢。", "example_meaning_en": "It matches, doesn't it?"},
        "N3_112": {"example_sentence": "いってい（一定）のルールがあります。", "example_reading": "いっていのるーるがあります。", "example_meaning_cn": "有一定的规则。", "example_meaning_en": "There is a fixed rule."},
        "N3_113": {"example_sentence": "い（行）ってらっしゃい！", "example_reading": "いってらっしゃい！", "example_meaning_cn": "慢走（路上小心）！", "example_meaning_en": "Take care!"},
        "N3_114": {"example_sentence": "い（行）って参ります！", "example_reading": "いってまいります！", "example_meaning_cn": "我走了（马上回来）！", "example_meaning_en": "I'm off!"},
        "N3_115": {"example_sentence": "いっ（一杯）杯飲もう！", "example_reading": "いっぱいのもう！", "example_meaning_cn": "喝一杯吧！", "example_meaning_en": "Let's have a drink!"},
        "N3_116": {"example_sentence": "いっぱん（一般）的にそうです。", "example_reading": "いっぱんてきにそうです。", "example_meaning_cn": "一般来说是那样的。", "example_meaning_en": "Generally, that's the case."},
        "N3_117": {"example_sentence": "いっ（一）分（ぷん）待ってください。", "example_reading": "いっぷんまってください。", "example_meaning_cn": "请等一分钟。", "example_meaning_en": "Please wait for a minute."},
        "N3_118": {"example_sentence": "い（何）つまでも大好きです。", "example_reading": "いつまでもだいすきです。", "example_meaning_cn": "永远最喜欢你。", "example_meaning_en": "I'll love you forever."},
        "N3_119": {"example_sentence": "い（何）つもありがとうございます。", "example_reading": "いつもありがとうございます。", "example_meaning_cn": "一直以来谢谢了。", "example_meaning_en": "Thank you as always."},
        "N3_120": {"example_sentence": "い（移）転（てん）しました。", "example_reading": "いてんしました。", "example_meaning_cn": "搬迁了。", "example_meaning_en": "We've relocated."},
        "N3_121": {"example_sentence": "いと（糸）が切れました。", "example_reading": "いとがきれました。", "example_meaning_cn": "线断了。", "example_meaning_en": "The thread broke."},
        "N3_122": {"example_sentence": "いとこ（従兄弟）に会いました。", "example_reading": "いとこにあいました。", "example_meaning_cn": "见到了堂（表）兄弟。", "example_meaning_en": "I met my cousin."},
        "N3_123": {"example_sentence": "いない（以内）に出してください。", "example_reading": "いないにだしてください。", "example_meaning_cn": "请在（限度）以内交出来。", "example_meaning_en": "Please submit it within (the time)."},
        "N3_124": {"example_sentence": "いな（田舎）舎に帰ります。", "example_reading": "いなかにかえります。", "example_meaning_cn": "回老家（农村）。", "example_meaning_en": "I'm going back to the countryside."},
        "N3_125": {"example_sentence": "い（祈）ってください。", "example_reading": "いのってください。", "example_meaning_cn": "请祈祷。", "example_meaning_en": "Please pray."},
        "N3_126": {"example_sentence": "いのち（命）を大切にしましょう。", "example_reading": "いのちをたいせつにしましょう。", "example_meaning_cn": "珍惜生命吧。", "example_meaning_en": "Let's cherish life."},
        "N3_127": {"example_sentence": "い（威）張（ば）らないでください。", "example_reading": "いばらないでください。", "example_meaning_cn": "请不要自大（或摆架子）。", "example_meaning_en": "Please don't be arrogant."},
        "N3_128": {"example_sentence": "いま（今）何時ですか。", "example_reading": "いまなんじですか。", "example_meaning_cn": "现在几点了？", "example_meaning_en": "What time is it now?"},
        "N3_129": {"example_sentence": "い（意）味（み）がわかりました。", "example_reading": "いみがわかりました。", "example_meaning_cn": "明白意思了。", "example_meaning_en": "I understood the meaning."},
        "N3_130": {"example_sentence": "い（意）味（み）深（しん）ですね。", "example_reading": "いみしんですね。", "example_meaning_cn": "意味深长呢。", "example_meaning_en": "It's meaningful/suggestive, isn't it?"},
        "N3_131": {"example_sentence": "イメージ（いめーじ）してください。", "example_reading": "イメージしてください。", "example_meaning_cn": "请想象一下。", "example_meaning_en": "Please imagine it."},
        "N3_132": {"example_sentence": "いもうと（妹）は学生です。", "example_reading": "いもうとはがくせいです。", "example_meaning_cn": "妹妹是学生。", "example_meaning_en": "My little sister is a student."},
        "N3_133": {"example_sentence": "い（嫌）ですね。 ", "example_reading": "いやですね。", "example_meaning_cn": "真讨厌呢（或真够受的）。", "example_meaning_en": "It's unpleasant, isn't it?"},
        "N3_134": {"example_sentence": "いらい（以来）会っていません。", "example_reading": "いらいあっていません。", "example_meaning_cn": "在那以来没见过面。", "example_meaning_en": "I haven't seen them since then."},
        "N3_135": {"example_sentence": "い（依頼）頼してください。", "example_reading": "いらいしてください。", "example_meaning_cn": "请委托。", "example_meaning_en": "Please make a request."},
        "N3_136": {"example_sentence": "いらいら（苛々）します。", "example_reading": "いらいらします。", "example_meaning_cn": "很急躁（心烦）。", "example_meaning_en": "I'm getting irritated."},
        "N3_137": {"example_sentence": "い（入）り口（ぐち）はこちらです。", "example_reading": "いりぐちはこちらです。", "example_meaning_cn": "入口在这边。", "example_meaning_en": "The entrance is over here."},
        "N3_138": {"example_sentence": "い（医療）療費が高いです。", "example_reading": "いりょうひがたかいです。", "example_meaning_cn": "医疗费很贵。", "example_meaning_en": "Medical expenses are high."},
        "N3_139": {"example_sentence": "い（要）りますか。", "example_reading": "いりますか。", "example_meaning_cn": "需要吗？", "example_meaning_en": "Do you need it?"},
        "N3_140": {"example_sentence": "い（居）るだけでいいです。", "example_reading": "いるだけでいいです。", "example_meaning_cn": "只要（你）在就好了。", "example_meaning_en": "Just being here is enough."},
        "N3_141": {"example_sentence": "い（入）れてください。", "example_reading": "いれてください。", "example_meaning_cn": "请放进去。", "example_meaning_en": "Please put it in."},
        "N3_142": {"example_sentence": "いわ（祝）ってください。", "example_reading": "いわってください。", "example_meaning_cn": "请庆祝。", "example_meaning_en": "Please celebrate."},
        "N3_143": {"example_sentence": "いわ（岩）が転がっています。", "example_reading": "いわがころがっています。", "example_meaning_cn": "岩石正在滚动。", "example_meaning_en": "A rock is rolling."},
        "N3_144": {"example_sentence": "い（言）わばこういう事です。", "example_reading": "いわばこういうことです。", "example_meaning_cn": "说起来（譬如说）就是这么回事。", "example_meaning_en": "So to speak, it's like this."},
        "N3_145": {"example_sentence": "いわした（以下）は無料です。", "example_reading": "いかはこちらはむりょうです。", "example_meaning_cn": "以下是免费的。", "example_meaning_en": "The following is free."},
        "N3_146": {"example_sentence": "い（以外）外な結末でした。", "example_reading": "いがいなけつまつでした。", "example_meaning_cn": "是意外的结局。", "example_meaning_en": "It was an unexpected ending."},
        "N3_147": {"example_sentence": "い（以前）に会いました。", "example_reading": "いぜんにあいました。", "example_meaning_cn": "以前见过。", "example_meaning_en": "I've met you before."},
        "N3_148": {"example_sentence": "がい（依頼）頼してください。", "example_reading": "いらいしてください。", "example_meaning_cn": "请委托。", "example_meaning_en": "Please make a request."},
        "N3_149": {"example_sentence": "い（引）退（たい）しました。", "example_reading": "いたいしました。", "example_meaning_cn": "退休（或退役）了。", "example_meaning_en": "I've retired."},
        "N3_150": {"example_sentence": "い（引用）用してください。", "example_reading": "いんようしてください。", "example_meaning_cn": "请引用。", "example_meaning_en": "Please quote it."}
    }

    for item in vocab:
        if item['id'] in enrichment:
            item.update(enrichment[item['id']])

    with open(data_file, 'w', encoding='utf-8') as f:
        json.dump(vocab, f, ensure_ascii=False, indent=2)

    print(f"Updated items up to N3_150.")

if __name__ == "__main__":
    main()
